-- Seed All VITAL Skills
-- Source: .vital-command-center/skills-main
-- Generated by: parse_all_skills.py


-- Algorithmic Art
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Algorithmic Art',
    'Skill for Algorithmic Art',
    'workflow',
    'skills-main/algorithmic-art',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "algorithmic-art", "folder_path": "algorithmic-art"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Anthropic Brand Styling
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Anthropic Brand Styling',
    '## Overview',
    'prompt',
    'skills-main/brand-guidelines',
    'General Utilities',
    7,
    true,
    '{"source": "vital-command-center", "slug": "brand-guidelines", "folder_path": "brand-guidelines"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Canvas Design
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Canvas Design',
    'Skill for Canvas Design',
    'workflow',
    'skills-main/canvas-design',
    'General Utilities',
    7,
    true,
    '{"source": "vital-command-center", "slug": "canvas-design", "folder_path": "canvas-design"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- DOCX creation, editing, and analysis
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'DOCX creation, editing, and analysis',
    '## Overview',
    'workflow',
    'skills-main/document-skills/docx',
    'Document Processing',
    9,
    true,
    '{"source": "vital-command-center", "slug": "docx", "folder_path": "document-skills/docx"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- PDF Processing Guide
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'PDF Processing Guide',
    '## Overview',
    'tool',
    'skills-main/document-skills/pdf',
    'Document Processing',
    9,
    true,
    '{"source": "vital-command-center", "slug": "pdf", "folder_path": "document-skills/pdf"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- PPTX creation, editing, and analysis
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'PPTX creation, editing, and analysis',
    '## Overview',
    'workflow',
    'skills-main/document-skills/pptx',
    'Document Processing',
    9,
    true,
    '{"source": "vital-command-center", "slug": "pptx", "folder_path": "document-skills/pptx"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Requirements for Outputs
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Requirements for Outputs',
    '## All Excel files',
    'tool',
    'skills-main/document-skills/xlsx',
    'Document Processing',
    9,
    true,
    '{"source": "vital-command-center", "slug": "xlsx", "folder_path": "document-skills/xlsx"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Frontend Design
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Frontend Design',
    'Skill for Frontend Design',
    'prompt',
    'skills-main/frontend-design',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "frontend-design", "folder_path": "frontend-design"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Internal Comms
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Internal Comms',
    'Skill for Internal Comms',
    'prompt',
    'skills-main/internal-comms',
    'General Utilities',
    5,
    true,
    '{"source": "vital-command-center", "slug": "internal-comms", "folder_path": "internal-comms"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- MCP Server Development Guide
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'MCP Server Development Guide',
    '## Overview',
    'workflow',
    'skills-main/mcp-builder',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "mcp-builder", "folder_path": "mcp-builder"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Skill Creator
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Skill Creator',
    'This skill provides guidance for creating effective skills.',
    'workflow',
    'skills-main/skill-creator',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "skill-creator", "folder_path": "skill-creator"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Slack GIF Creator
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Slack GIF Creator',
    'A toolkit providing utilities and knowledge for creating animated GIFs optimized for Slack.',
    'tool',
    'skills-main/slack-gif-creator',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "slack-gif-creator", "folder_path": "slack-gif-creator"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Insert instructions below
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Insert instructions below',
    'Skill for Insert instructions below',
    'prompt',
    'skills-main/template-skill',
    'General Utilities',
    3,
    true,
    '{"source": "vital-command-center", "slug": "template-skill", "folder_path": "template-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Theme Factory Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Theme Factory Skill',
    'This skill provides a curated collection of professional font and color themes themes, each with carefully selected color palettes and font pairings. Once a theme is chosen, it can be applied to any artifact.',
    'prompt',
    'skills-main/theme-factory',
    'General Utilities',
    7,
    true,
    '{"source": "vital-command-center", "slug": "theme-factory", "folder_path": "theme-factory"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Web Artifacts Builder
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Web Artifacts Builder',
    'To build powerful frontend claude.ai artifacts, follow these steps:',
    'workflow',
    'skills-main/web-artifacts-builder',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "web-artifacts-builder", "folder_path": "web-artifacts-builder"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;

-- Web Application Testing
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Web Application Testing',
    'To test local web applications, write native Python Playwright scripts.',
    'tool',
    'skills-main/webapp-testing',
    'General Utilities',
    9,
    true,
    '{"source": "vital-command-center", "slug": "webapp-testing", "folder_path": "webapp-testing"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    category = EXCLUDED.category,
    complexity_level = EXCLUDED.complexity_level,
    metadata = EXCLUDED.metadata;
