-- Seed Awesome Claude Skills
-- Source: https://github.com/anthropics/awesome-claude-skills
-- Generated by: parse_awesome_claude_skills.py


-- Docx
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Docx',
    'Create, edit, analyze Word docs with tracked changes, comments, formatting.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/document-skills/docx',
    'Document Skills',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "docx", "github_url": "https://github.com/anthropics/skills/tree/main/document-skills/docx"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Pdf
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Pdf',
    'Extract text, tables, metadata, merge & annotate PDFs.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/document-skills/pdf',
    'Document Skills',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "pdf", "github_url": "https://github.com/anthropics/skills/tree/main/document-skills/pdf"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Pptx
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Pptx',
    'Read, generate, and adjust slides, layouts, templates.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/document-skills/pptx',
    'Document Skills',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "pptx", "github_url": "https://github.com/anthropics/skills/tree/main/document-skills/pptx"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Xlsx
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Xlsx',
    'Spreadsheet manipulation: formulas, charts, data transformations.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/document-skills/xlsx',
    'Document Skills',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "xlsx", "github_url": "https://github.com/anthropics/skills/tree/main/document-skills/xlsx"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Artifacts Builder
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Artifacts Builder',
    'Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui).',
    'tool',
    'https://github.com/anthropics/skills/tree/main/artifacts-builder',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "artifacts-builder", "github_url": "https://github.com/anthropics/skills/tree/main/artifacts-builder"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Test Driven Development
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Test Driven Development',
    'Use when implementing any feature or bugfix, before writing implementation code',
    'tool',
    'https://github.com/obra/superpowers/tree/main/skills/test-driven-development',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "test-driven-development", "github_url": "https://github.com/obra/superpowers/tree/main/skills/test-driven-development"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Using Git Worktrees
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Using Git Worktrees',
    'Creates isolated git worktrees with smart directory selection and safety verification.',
    'tool',
    'https://github.com/obra/superpowers/blob/main/skills/using-git-worktrees/',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "using-git-worktrees", "github_url": "https://github.com/obra/superpowers/blob/main/skills/using-git-worktrees/"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Finishing A Development Branch
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Finishing A Development Branch',
    'Guides completion of development work by presenting clear options and handling chosen workflow.',
    'tool',
    'https://github.com/obra/superpowers/tree/main/skills/finishing-a-development-branch',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "finishing-a-development-branch", "github_url": "https://github.com/obra/superpowers/tree/main/skills/finishing-a-development-branch"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Pypict Claude Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Pypict Claude Skill',
    'Design comprehensive test cases using PICT (Pairwise Independent Combinatorial Testing) for requirements or code, generating optimized test suites with pairwise coverage.',
    'tool',
    'https://github.com/omkamal/pypict-claude-skill',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "pypict-claude-skill", "github_url": "https://github.com/omkamal/pypict-claude-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Aws Skills
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Aws Skills',
    'AWS development with CDK best practices, cost optimization MCP servers, and serverless/event-driven architecture patterns.',
    'tool',
    'https://github.com/zxkane/aws-skills',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "aws-skills", "github_url": "https://github.com/zxkane/aws-skills"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Move Code Quality Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Move Code Quality Skill',
    'Analyzes Move language packages against the official Move Book Code Quality Checklist for Move 2024 Edition compliance and best practices.',
    'tool',
    'https://github.com/1NickPappas/move-code-quality-skill',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "move-code-quality-skill", "github_url": "https://github.com/1NickPappas/move-code-quality-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Claude Code Terminal Title
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Claude Code Terminal Title',
    'Gives each Claud Code terminal window a dynamic title that describes the work being done so you don''t lose track of what terminal window is doing what.',
    'tool',
    'https://github.com/bluzername/claude-code-terminal-title',
    'Development & Code Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "claude-code-terminal-title", "github_url": "https://github.com/bluzername/claude-code-terminal-title"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Root Cause Tracing
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Root Cause Tracing',
    'Use when errors occur deep in execution and you need to trace back to find the original trigger',
    'tool',
    'https://github.com/obra/superpowers/tree/main/skills/root-cause-tracing',
    'Data & Analysis',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "root-cause-tracing", "github_url": "https://github.com/obra/superpowers/tree/main/skills/root-cause-tracing"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Csv Data Summarizer Claude Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Csv Data Summarizer Claude Skill',
    'Automatically analyzes CSVs: columns, distributions, missing data, correlations.',
    'tool',
    'https://github.com/coffeefuelbump/csv-data-summarizer-claude-skill',
    'Data & Analysis',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "csv-data-summarizer-claude-skill", "github_url": "https://github.com/coffeefuelbump/csv-data-summarizer-claude-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Scientific Databases
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Scientific Databases',
    'Access to 26 scientific databases including PubMed, PubChem, UniProt, ChEMBL, and AlphaFold DB.',
    'tool',
    'https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-databases',
    'Scientific & Research Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "scientific-databases", "github_url": "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-databases"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Scientific Integrations
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Scientific Integrations',
    'Platform integrations for lab automation and workflow management (Benchling, DNAnexus, Opentrons, and more).',
    'tool',
    'https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-integrations',
    'Scientific & Research Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "scientific-integrations", "github_url": "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-integrations"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Scientific Packages
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Scientific Packages',
    '58 specialized Python packages for bioinformatics, cheminformatics, machine learning, and data analysis.',
    'tool',
    'https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-packages',
    'Scientific & Research Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "scientific-packages", "github_url": "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-packages"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Scientific Thinking
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Scientific Thinking',
    'Analysis tools and document processing for scientific writing, visualization, and methodology.',
    'tool',
    'https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-thinking',
    'Scientific & Research Tools',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "scientific-thinking", "github_url": "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/scientific-thinking"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Article Extractor
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Article Extractor',
    'Extract full article text and metadata from web pages.',
    'tool',
    'https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/article-extractor',
    '## ✍️ Writing & Research',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "article-extractor", "github_url": "https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/article-extractor"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Content Research Writer
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Content Research Writer',
    'Assists in writing high-quality content by conducting research, adding citations, improving hooks, iterating on outlines, and providing real-time feedback on each section',
    'tool',
    'https://github.com/ComposioHQ/awesome-claude-skills/tree/master/content-research-writer',
    '## ✍️ Writing & Research',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "content-research-writer", "github_url": "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/content-research-writer"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Internal Comms
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Internal Comms',
    'Create internal communications	(status reports, leadership updates, etc)',
    'tool',
    'https://github.com/anthropics/skills/tree/main/internal-comms',
    '## ✍️ Writing & Research',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "internal-comms", "github_url": "https://github.com/anthropics/skills/tree/main/internal-comms"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Brainstorming
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Brainstorming',
    'Transform rough ideas into fully-formed designs through structured questioning and alternative exploration.',
    'tool',
    'https://github.com/obra/superpowers/tree/main/skills/brainstorming',
    '## ✍️ Writing & Research',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "brainstorming", "github_url": "https://github.com/obra/superpowers/tree/main/skills/brainstorming"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Family History Research
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Family History Research',
    'Provides assistance with planning family history and genealogy research projects.',
    'tool',
    'https://github.com/emaynard/claude-family-history-research-skill',
    '## ✍️ Writing & Research',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "family-history-research", "github_url": "https://github.com/emaynard/claude-family-history-research-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Tapestry
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Tapestry',
    'Interlink and summarize related documents into knowledge networks.',
    'tool',
    'https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/tapestry',
    'Learning & Knowledge',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "tapestry", "github_url": "https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/tapestry"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Ship Learn Next
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Ship Learn Next',
    'Skill to help iterate on what to build or learn next, based on feedback loops.',
    'tool',
    'https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/ship-learn-next',
    'Learning & Knowledge',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "ship-learn-next", "github_url": "https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/ship-learn-next"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Youtube Transcript
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Youtube Transcript',
    'Fetch transcripts from YouTube videos and prepare summaries.',
    'tool',
    'https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/youtube-transcript',
    'Media & Content',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "youtube-transcript", "github_url": "https://github.com/michalparkola/tapestry-skills-for-claude-code/tree/main/youtube-transcript"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Video Downloader
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Video Downloader',
    'Downloads videos from YouTube and other platforms for offline viewing, editing, or archival.',
    'tool',
    'https://github.com/ComposioHQ/awesome-claude-skills/tree/master/video-downloader',
    'Media & Content',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "video-downloader", "github_url": "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/video-downloader"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Image Enhancer
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Image Enhancer',
    'Improves the quality of images, especially screenshots.',
    'tool',
    'https://github.com/ComposioHQ/awesome-claude-skills/tree/master/image-enhancer',
    'Media & Content',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "image-enhancer", "github_url": "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/image-enhancer"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Claude Epub Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Claude Epub Skill',
    'Parse and analyze EPUB ebook contents for querying or summarizing.',
    'tool',
    'https://github.com/smerchek/claude-epub-skill',
    'Media & Content',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "claude-epub-skill", "github_url": "https://github.com/smerchek/claude-epub-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Git Pushing
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Git Pushing',
    'Automate git operations and repository interactions.',
    'tool',
    'https://github.com/mhattingpete/claude-skills-marketplace/tree/main/engineering-workflow-plugin/skills/git-pushing',
    'Collaboration & Project Management',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "git-pushing", "github_url": "https://github.com/mhattingpete/claude-skills-marketplace/tree/main/engineering-workflow-plugin/skills/git-pushing"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Review Implementing
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Review Implementing',
    'Evaluate code implementation plans and align with specs.',
    'tool',
    'https://github.com/mhattingpete/claude-skills-marketplace/tree/main/engineering-workflow-plugin/skills/review-implementing',
    'Collaboration & Project Management',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "review-implementing", "github_url": "https://github.com/mhattingpete/claude-skills-marketplace/tree/main/engineering-workflow-plugin/skills/review-implementing"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Test Fixing
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Test Fixing',
    'Detect failing tests and propose patches or fixes.',
    'tool',
    'https://github.com/mhattingpete/claude-skills-marketplace/tree/main/engineering-workflow-plugin/skills/test-fixing',
    'Collaboration & Project Management',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "test-fixing", "github_url": "https://github.com/mhattingpete/claude-skills-marketplace/tree/main/engineering-workflow-plugin/skills/test-fixing"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Meeting Insights Analyzer
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Meeting Insights Analyzer',
    'Transforms your meeting transcripts into actionable insights about your communication patterns',
    'tool',
    'https://github.com/ComposioHQ/awesome-claude-skills/blob/master/meeting-insights-analyzer/',
    'Collaboration & Project Management',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "meeting-insights-analyzer", "github_url": "https://github.com/ComposioHQ/awesome-claude-skills/blob/master/meeting-insights-analyzer/"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Linear Cli Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Linear Cli Skill',
    'A skill teaching claude how to use linear-CLI (provided alongside the skill), meant to replace linear MCP.',
    'tool',
    'https://github.com/Valian/linear-cli-skill',
    'Collaboration & Project Management',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "linear-cli-skill", "github_url": "https://github.com/Valian/linear-cli-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Ffuf_Claude_Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Ffuf_Claude_Skill',
    'Integrate Claude with FFUF (fuzzing) and analyze results for vulnerabilities.',
    'tool',
    'https://github.com/jthack/ffuf_claude_skill',
    'Security & Web Testing',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "ffuf_claude_skill", "github_url": "https://github.com/jthack/ffuf_claude_skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Defense In Depth
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Defense In Depth',
    'Implement multi-layered testing and security best practices.',
    'tool',
    'https://github.com/obra/superpowers/blob/main/skills/defense-in-depth',
    'Security & Web Testing',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "defense-in-depth", "github_url": "https://github.com/obra/superpowers/blob/main/skills/defense-in-depth"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Webapp Testing
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Webapp Testing',
    'Toolkit for interacting with and testing local web applications using Playwright.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/webapp-testing',
    'Security & Web Testing',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "webapp-testing", "github_url": "https://github.com/anthropics/skills/tree/main/webapp-testing"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Systematic Debugging
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Systematic Debugging',
    'Use when encountering any bug, test failure, or unexpected behavior, before proposing fixes',
    'tool',
    'https://github.com/obra/superpowers/blob/main/skills/systematic-debugging',
    'Security & Web Testing',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "systematic-debugging", "github_url": "https://github.com/obra/superpowers/blob/main/skills/systematic-debugging"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- File Organizer
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'File Organizer',
    'Intelligently organizes your files and folders across your computer.',
    'tool',
    'https://github.com/ComposioHQ/awesome-claude-skills/tree/master/file-organizer',
    'Utility & Automation',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "file-organizer", "github_url": "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/file-organizer"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Invoice Organizer
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Invoice Organizer',
    'Automatically organizes invoices and receipts for tax preparation',
    'tool',
    'https://github.com/ComposioHQ/awesome-claude-skills/blob/master/invoice-organizer/SKILL.md',
    'Utility & Automation',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "invoice-organizer", "github_url": "https://github.com/ComposioHQ/awesome-claude-skills/blob/master/invoice-organizer/SKILL.md"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Skill Creator
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Skill Creator',
    'Template / helper to build new Claude skills.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/skill-creator',
    'Utility & Automation',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "skill-creator", "github_url": "https://github.com/anthropics/skills/tree/main/skill-creator"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;

-- Template Skill
INSERT INTO skills (
    name, 
    description, 
    implementation_type, 
    implementation_ref, 
    category,
    complexity_level,
    is_active,
    metadata
) VALUES (
    'Template Skill',
    'Minimal skeleton for a new skill project structure.',
    'tool',
    'https://github.com/anthropics/skills/tree/main/template-skill',
    'Utility & Automation',
    5,
    true,
    '{"source": "awesome-claude-skills", "slug": "template-skill", "github_url": "https://github.com/anthropics/skills/tree/main/template-skill"}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    implementation_ref = EXCLUDED.implementation_ref,
    metadata = EXCLUDED.metadata;
