# VITAL Path - Development Override
# Docker Compose configuration for local development

version: '3.8'

services:
  # Frontend - Development mode with hot reload
  frontend:
    build:
      target: development
    ports:
      - "3002:3000"
      - "3003:24678"  # Hot reload port
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - /app/node_modules
    command: npm run dev

  # Node.js Gateway - Development mode
  node-gateway:
    build:
      context: ./backend/node-gateway
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=vital-path:*
      - LOG_LEVEL=debug
    volumes:
      - ./backend/node-gateway/src:/app/src
      - ./backend/node-gateway/package.json:/app/package.json
      - ./backend/node-gateway/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    command: npm run dev

  # Python AI Services - Development mode
  python-ai-services:
    build:
      context: ./backend/python-ai-services
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=debug
      - RELOAD=true
    volumes:
      - ./backend/python-ai-services:/app
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  # Redis - Development configuration
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # PostgreSQL for local development (if not using Supabase)
  postgres-dev:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vital_path_dev
      - POSTGRES_USER=vital_path
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d
    networks:
      - vital-path-network

  # Supabase Local (Alternative to cloud Supabase)
  supabase-db:
    image: supabase/postgres:15.1.0.117
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=your-super-secret-and-long-postgres-password
      - POSTGRES_DB=postgres
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
    networks:
      - vital-path-network

  supabase-studio:
    image: supabase/studio:20240101-ce2b7d7
    ports:
      - "54323:3000"
    environment:
      - SUPABASE_URL=http://supabase-kong:8000
      - STUDIO_PG_META_URL=http://supabase-meta:8080
    depends_on:
      - supabase-db
    networks:
      - vital-path-network

  # Development tools
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-dev
    depends_on:
      - postgres-dev
    networks:
      - vital-path-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - vital-path-network

volumes:
  postgres-dev-data:
    driver: local
  supabase-db-data:
    driver: local