#!/bin/bash
# Railway Environment Variables Setup Script
# This script helps you populate Railway variables from the JSON file

echo "🔑 VITAL Path AI Engine - Railway Environment Variables Setup"
echo "================================================================"
echo ""
echo "📋 Available Configuration Sets:"
echo ""
echo "1. CRITICAL ONLY (5 variables)"
echo "   - Minimal setup for basic functionality"
echo ""
echo "2. STANDARD (Critical + High Priority - 12 variables)"
echo "   - Recommended for production"
echo "   - Includes web search and monitoring"
echo ""
echo "3. COMPLETE (All 40+ variables)"
echo "   - Maximum features"
echo "   - All integrations enabled"
echo ""
echo "================================================================"
echo ""
echo "📝 MANUAL SETUP INSTRUCTIONS:"
echo ""
echo "1. Open Railway dashboard in your browser:"
echo "   https://railway.app/project/YOUR_PROJECT/service/ai-engine"
echo ""
echo "2. Click on 'Variables' tab"
echo ""
echo "3. For each variable below, click 'New Variable' and copy-paste:"
echo ""
echo "================================================================"
echo "🔴 CRITICAL VARIABLES (Required - Add these first):"
echo "================================================================"
echo ""
echo "PORT=8080"
echo ""
echo "OPENAI_API_KEY=<from JSON file - line 21>"
echo ""
echo "SUPABASE_URL=<from JSON file - line 28>"
echo ""
echo "SUPABASE_SERVICE_ROLE_KEY=<from JSON file - line 35>"
echo ""
echo "SUPABASE_ANON_KEY=<from JSON file - line 42>"
echo ""
echo "================================================================"
echo "🟡 HIGH PRIORITY VARIABLES (Recommended):"
echo "================================================================"
echo ""
echo "TAVILY_API_KEY=<from JSON file - search for TAVILY>"
echo ""
echo "LANGCHAIN_API_KEY=<from JSON file - search for LANGCHAIN>"
echo "LANGCHAIN_PROJECT=vital-advisory-board"
echo "LANGCHAIN_TRACING_V2=true"
echo "LANGCHAIN_ENDPOINT=https://api.smith.langchain.com"
echo ""
echo "HUGGINGFACE_API_KEY=<from JSON file - search for HUGGINGFACE>"
echo ""
echo "GOOGLE_API_KEY=<from JSON file - search for GOOGLE>"
echo ""
echo "LOG_LEVEL=info"
echo "PYTHONUNBUFFERED=1"
echo "ENV=production"
echo ""
echo "================================================================"
echo "✅ After adding variables:"
echo "================================================================"
echo ""
echo "1. Railway will auto-redeploy (~2-3 minutes)"
echo "2. Watch deployment logs for startup messages"
echo "3. Verify with: curl https://your-railway-url.railway.app/health"
echo "4. Check that services show 'healthy' (not 'unavailable')"
echo ""
echo "================================================================"
echo "⚠️ SECURITY REMINDER:"
echo "================================================================"
echo ""
echo "After you've copied all values to Railway:"
echo ""
echo "1. DELETE railway-environment-variables.json:"
echo "   rm railway-environment-variables.json"
echo ""
echo "2. Make sure it's in .gitignore:"
echo "   echo 'railway-environment-variables.json' >> .gitignore"
echo ""
echo "3. Commit the safe files only:"
echo "   git add RAILWAY_ENVIRONMENT_VARIABLES_GUIDE.md"
echo "   git commit -m 'docs: add Railway environment variables guide'"
echo "   git push origin main"
echo ""
echo "================================================================"
echo ""

# Open the JSON file for easy copying
echo "📄 Opening railway-environment-variables.json for you to copy values..."
echo ""
echo "Press any key to continue..."
read -n 1

# Try to open with default editor
if command -v code &> /dev/null; then
    code railway-environment-variables.json
elif command -v nano &> /dev/null; then
    nano railway-environment-variables.json
else
    cat railway-environment-variables.json
fi

