#!/bin/bash
# Run JTBD migrations via Supabase REST API

APIKEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbWx0a2hpeGVhdHh1b3htb2xxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mjc4MzkxNSwiZXhwIjoyMDc4MzU5OTE1fQ.dhhJIMib1DMTuIvacv4VnDYjXAgVFRZ5Zrrl_LkpD6Q"
URL="https://bomltkhixeatxuoxmolq.supabase.co"
TENANT_ID="c6d221f8-1e8d-4dd9-86c5-d640ad6bf30b"

echo "=============================================="
echo "Running JTBD Migrations for 3 Functions"
echo "=============================================="

# Function to run a single JTBD insert
run_jtbd_insert() {
    local code="$1"
    local name="$2"
    local description="$3"
    local functional_area="$4"
    local job_category="$5"
    local complexity="$6"
    local frequency="$7"
    local validation_score="$8"
    local jtbd_type="$9"
    local work_pattern="${10}"
    local strategic_priority="${11}"
    local impact_level="${12}"
    local compliance_sensitivity="${13}"
    local service_layer="${14}"

    # Escape single quotes in description and name
    name=$(echo "$name" | sed "s/'/''/g")
    description=$(echo "$description" | sed "s/'/''/g")

    curl -s -X POST "${URL}/rest/v1/jtbd" \
      -H "apikey: ${APIKEY}" \
      -H "Authorization: Bearer ${APIKEY}" \
      -H "Content-Type: application/json" \
      -H "Prefer: resolution=merge-duplicates" \
      -d "{
        \"tenant_id\": \"${TENANT_ID}\",
        \"code\": \"${code}\",
        \"name\": \"${name}\",
        \"description\": \"${description}\",
        \"functional_area\": \"${functional_area}\",
        \"job_category\": \"${job_category}\",
        \"complexity\": \"${complexity}\",
        \"frequency\": \"${frequency}\",
        \"status\": \"active\",
        \"validation_score\": ${validation_score},
        \"jtbd_type\": \"${jtbd_type}\",
        \"work_pattern\": \"${work_pattern}\",
        \"strategic_priority\": \"${strategic_priority}\",
        \"impact_level\": \"${impact_level}\",
        \"compliance_sensitivity\": \"${compliance_sensitivity}\",
        \"recommended_service_layer\": \"${service_layer}\"
      }" > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo "  ✓ ${code}"
    else
        echo "  ✗ ${code} - FAILED"
    fi
}

echo ""
echo "=== MEDICAL AFFAIRS JTBDs (33) ==="

# Medical Leadership (5)
run_jtbd_insert "JTBD-MA-L001" "Develop Integrated Medical Strategy" "When aligning medical affairs activities with corporate objectives and product lifecycle needs, I want to develop a comprehensive medical strategy that integrates scientific evidence generation, medical education, and field medical activities, so I can maximize the medical contribution to commercial success while maintaining scientific integrity." "Medical Affairs" "strategic" "high" "annually" "0.90" "strategic" "mixed" "high" "high" "high" "L2_panel"
run_jtbd_insert "JTBD-MA-L002" "Establish Medical Governance Framework" "When ensuring compliance with regulations and ethical standards across all medical activities, I want to establish and maintain a robust medical governance framework with clear policies and oversight mechanisms, so I can protect the organization from regulatory and reputational risks while enabling efficient operations." "Medical Affairs" "strategic" "high" "quarterly" "0.88" "strategic" "structured" "high" "high" "critical" "L1_expert"
run_jtbd_insert "JTBD-MA-L003" "Optimize Medical Affairs Budget Allocation" "When allocating limited resources across competing medical priorities, I want to analyze ROI of medical activities and prioritize investments based on strategic impact, so I can maximize the value delivered by medical affairs while staying within budget constraints." "Medical Affairs" "operational" "high" "quarterly" "0.85" "operational" "structured" "medium" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-L004" "Coordinate Cross-Functional Medical Initiatives" "When medical insights need to inform commercial, regulatory, and R&D decisions, I want to establish effective cross-functional collaboration mechanisms and communication channels, so I can ensure medical perspectives are appropriately integrated into key business decisions." "Medical Affairs" "coordination" "high" "monthly" "0.87" "strategic" "mixed" "high" "high" "medium" "L2_panel"
run_jtbd_insert "JTBD-MA-L005" "Build High-Performing Medical Affairs Team" "When building organizational capability in medical affairs, I want to recruit, develop, and retain top medical talent with the right mix of scientific expertise and business acumen, so I can build a world-class medical affairs function that drives competitive advantage." "Medical Affairs" "management" "medium" "quarterly" "0.82" "operational" "mixed" "medium" "medium" "low" "L1_expert"

# Field Medical/MSL (7)
run_jtbd_insert "JTBD-MA-FM001" "Develop Strategic KOL Engagement Plan" "When building relationships with key opinion leaders in our therapeutic areas, I want to develop and execute a comprehensive KOL engagement strategy that identifies, prioritizes, and engages the right scientific leaders, so I can build trusted scientific partnerships that advance medical understanding and support appropriate product use." "Medical Affairs" "strategic" "high" "quarterly" "0.92" "strategic" "mixed" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-FM002" "Prepare for Scientific Exchange Meetings" "When preparing for HCP interactions, I want to thoroughly research the HCPs background, interests, and practice patterns, and prepare relevant scientific materials, so I can engage in meaningful scientific exchange that addresses their specific information needs." "Medical Affairs" "operational" "medium" "daily" "0.89" "operational" "reactive" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-FM003" "Capture and Synthesize Medical Insights" "When gathering intelligence from the field, I want to systematically capture, synthesize, and communicate medical insights from HCP interactions, so I can inform evidence strategy, identify emerging trends, and support data-driven decision making." "Medical Affairs" "analytical" "high" "weekly" "0.91" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-FM004" "Plan Territory Coverage Strategy" "When managing my MSL territory, I want to develop and execute an optimal territory plan that balances KOL priorities, geographic efficiency, and strategic imperatives, so I can maximize impact while managing time and travel effectively." "Medical Affairs" "operational" "medium" "monthly" "0.85" "operational" "recurring" "medium" "medium" "low" "L1_expert"
run_jtbd_insert "JTBD-MA-FM005" "Support Investigator-Initiated Trials" "When researchers want to conduct independent studies with our products, I want to facilitate IIT submissions, provide scientific guidance, and ensure compliance with internal processes, so I can support valuable research that generates evidence and strengthens KOL relationships." "Medical Affairs" "compliance" "high" "monthly" "0.87" "operational" "project" "high" "high" "critical" "L1_expert"
run_jtbd_insert "JTBD-MA-FM006" "Execute Congress Coverage" "When major medical congresses occur, I want to provide comprehensive coverage including abstract analysis, competitive intelligence, and KOL engagement, so I can keep the organization informed of scientific developments and maximize congress ROI." "Medical Affairs" "research" "high" "quarterly" "0.88" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-FM007" "Facilitate Advisory Board Meetings" "When seeking expert input on medical strategy, I want to plan and execute advisory board meetings that generate actionable insights from thought leaders, so I can inform evidence development, medical education, and product positioning strategies." "Medical Affairs" "events" "high" "quarterly" "0.86" "strategic" "project" "high" "high" "high" "L2_panel"

# Medical Information (5)
run_jtbd_insert "JTBD-MA-MI001" "Respond to Medical Inquiries" "When HCPs, patients, or internal stakeholders have questions about our products, I want to provide accurate, balanced, and timely responses that address their specific information needs, so I can support appropriate product use and maintain scientific credibility." "Medical Affairs" "operational" "medium" "daily" "0.93" "operational" "reactive" "high" "high" "critical" "L0_ask"
run_jtbd_insert "JTBD-MA-MI002" "Develop Standard Response Documents" "When recurring questions require consistent responses, I want to develop and maintain scientifically accurate standard response documents, so I can ensure consistency, accuracy, and efficiency in medical information services." "Medical Affairs" "documentation" "high" "monthly" "0.88" "operational" "project" "medium" "medium" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-MI003" "Handle Off-Label Information Requests" "When HCPs request information about unapproved uses, I want to provide balanced, evidence-based information through compliant channels, so I can meet legitimate information needs while ensuring full regulatory compliance." "Medical Affairs" "compliance" "high" "daily" "0.90" "operational" "reactive" "high" "high" "critical" "L1_expert"
run_jtbd_insert "JTBD-MA-MI004" "Maintain Medical Knowledge Base" "When scientific evidence evolves, I want to keep our medical knowledge base current with latest data, guidelines, and competitive information, so I can ensure our medical communications reflect the most current scientific understanding." "Medical Affairs" "documentation" "medium" "weekly" "0.85" "operational" "recurring" "medium" "medium" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-MI005" "Analyze Medical Inquiry Trends" "When patterns emerge in inquiry data, I want to analyze inquiry trends to identify emerging issues, information gaps, and opportunities, so I can proactively address stakeholder needs and inform medical strategy." "Medical Affairs" "analytical" "medium" "monthly" "0.84" "operational" "recurring" "medium" "medium" "low" "L1_expert"

# Medical Education (5)
run_jtbd_insert "JTBD-MA-ME001" "Develop Medical Education Strategy" "When planning educational initiatives, I want to develop a comprehensive medical education strategy aligned with treatment gaps and learning needs, so I can improve patient outcomes through enhanced HCP knowledge and skills." "Medical Affairs" "strategic" "high" "annually" "0.89" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-ME002" "Design CME/IME Programs" "When developing accredited education, I want to design CME/IME programs that address identified gaps, meet accreditation standards, and engage target audiences effectively, so I can deliver impactful education that improves clinical practice." "Medical Affairs" "content" "high" "quarterly" "0.87" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-ME003" "Train and Develop Speaker Bureau" "When building peer-to-peer education capabilities, I want to identify, train, and support qualified speakers who can effectively communicate scientific content, so I can extend our educational reach through credible peer influence." "Medical Affairs" "enablement" "high" "quarterly" "0.85" "operational" "project" "medium" "high" "high" "L2_panel"
run_jtbd_insert "JTBD-MA-ME004" "Create Digital Education Content" "When reaching broader audiences, I want to develop engaging digital education content including e-learning, webinars, and interactive tools, so I can provide flexible, accessible learning opportunities that scale efficiently." "Medical Affairs" "content" "medium" "monthly" "0.83" "operational" "project" "medium" "medium" "medium" "L2_panel"
run_jtbd_insert "JTBD-MA-ME005" "Manage Educational Grants" "When supporting independent medical education, I want to evaluate grant requests, manage grant programs, and track educational outcomes, so I can support high-quality education while ensuring compliance with grant guidelines." "Medical Affairs" "compliance" "medium" "monthly" "0.82" "operational" "recurring" "medium" "medium" "high" "L1_expert"

# Publications (5)
run_jtbd_insert "JTBD-MA-PB001" "Develop Publication Strategy" "When planning scientific communications, I want to develop a publication strategy aligned with evidence gaps and product lifecycle, so I can ensure timely dissemination of data that supports product value and medical understanding." "Medical Affairs" "strategic" "high" "annually" "0.91" "strategic" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-PB002" "Manage Manuscript Development" "When preparing manuscripts for publication, I want to coordinate author teams, manage timelines, and ensure quality and compliance throughout the development process, so I can achieve timely publication in appropriate journals." "Medical Affairs" "coordination" "high" "monthly" "0.88" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-PB003" "Prepare Congress Abstracts and Presentations" "When presenting at medical congresses, I want to develop compelling abstracts and presentations that effectively communicate key data, so I can maximize visibility and impact at scientific meetings." "Medical Affairs" "content" "high" "quarterly" "0.87" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-PB004" "Conduct Literature Surveillance" "When monitoring the scientific landscape, I want to systematically track and analyze published literature in our therapeutic areas, so I can identify emerging evidence, competitive developments, and opportunities for our evidence strategy." "Medical Affairs" "research" "medium" "weekly" "0.86" "operational" "recurring" "medium" "medium" "low" "L1_expert"
run_jtbd_insert "JTBD-MA-PB005" "Ensure Publication Compliance" "When publishing company-sponsored research, I want to ensure adherence to GPP guidelines, disclosure requirements, and internal policies, so I can maintain publication integrity and regulatory compliance." "Medical Affairs" "compliance" "high" "monthly" "0.89" "operational" "recurring" "high" "high" "critical" "L1_expert"

# Medical Strategy (3)
run_jtbd_insert "JTBD-MA-MS001" "Analyze Competitive Medical Landscape" "When assessing competitive positioning, I want to comprehensively analyze competitor medical activities, evidence generation, and scientific communications, so I can identify opportunities and threats to inform our medical strategy." "Medical Affairs" "analytical" "high" "quarterly" "0.88" "strategic" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-MS002" "Identify Evidence Gaps" "When planning evidence generation, I want to systematically identify gaps in our evidence base relative to competitor data and stakeholder needs, so I can prioritize research investments that address the most critical evidence requirements." "Medical Affairs" "analytical" "high" "quarterly" "0.90" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-MS003" "Support Product Launch Planning" "When preparing for product launches, I want to ensure medical affairs is fully prepared with trained teams, developed content, and engaged KOLs, so I can contribute to successful launch execution." "Medical Affairs" "coordination" "high" "quarterly" "0.89" "strategic" "project" "critical" "critical" "high" "L1_expert"

echo ""
echo "Medical Affairs JTBDs: 33 total"
echo "✓ Section complete"

# === MARKET ACCESS JTBDs ===
echo ""
echo "=== MARKET ACCESS JTBDs (40) ==="

# HEOR (6)
run_jtbd_insert "JTBD-MA-HE001" "Develop Cost-Effectiveness Models" "When preparing for HTA submissions and payer negotiations, I want to develop robust cost-effectiveness models that accurately estimate the economic value of our treatment compared to alternatives, so I can demonstrate favorable incremental cost-effectiveness ratios (ICERs) that support favorable reimbursement decisions." "Market Access" "analytical" "high" "quarterly" "0.91" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-HE002" "Conduct Budget Impact Modeling" "When engaging with payers and health systems, I want to develop budget impact models that project the financial impact of adopting our therapy on their overall healthcare budget, so I can address affordability concerns and demonstrate manageable budget implications." "Market Access" "analytical" "high" "quarterly" "0.89" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-HE003" "Execute Systematic Literature Reviews" "When building the evidence base for HTA submissions, I want to conduct comprehensive systematic literature reviews and meta-analyses that synthesize all relevant clinical and economic evidence, so I can provide HTA bodies with the rigorous evidence synthesis they require for assessments." "Market Access" "research" "high" "monthly" "0.90" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-HE004" "Develop HEOR Publication Strategy" "When building external credibility for our value proposition, I want to develop and execute a strategic HEOR publication plan that disseminates our economic evidence to peer-reviewed journals and congresses, so I can establish our products value credentials in the scientific community." "Market Access" "strategic" "medium" "quarterly" "0.87" "strategic" "recurring" "medium" "medium" "medium" "L2_panel"
run_jtbd_insert "JTBD-MA-HE005" "Validate Economic Models" "When preparing models for HTA submission, I want to conduct thorough validation of our economic models including technical verification, face validity with clinical experts, and external validation against real-world data, so I can ensure our models withstand rigorous HTA scrutiny." "Market Access" "quality" "high" "quarterly" "0.88" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-HE006" "Design Comparative Effectiveness Studies" "When addressing evidence gaps for payer decision-making, I want to design and execute comparative effectiveness research studies that demonstrate our products clinical and economic advantages versus relevant comparators, so I can generate the head-to-head evidence that payers demand." "Market Access" "research" "high" "quarterly" "0.86" "strategic" "project" "high" "high" "high" "L1_expert"

# Pricing Strategy (5)
run_jtbd_insert "JTBD-MA-PR001" "Develop Global Pricing Strategy" "When launching a new product globally, I want to develop a comprehensive global pricing strategy that optimizes list prices across markets while accounting for international reference pricing and local market dynamics, so I can maximize global revenue while maintaining sustainable market access." "Market Access" "strategic" "high" "annually" "0.93" "strategic" "project" "critical" "critical" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-PR002" "Design Value-Based Pricing Frameworks" "When positioning our therapy in the market, I want to develop value-based pricing models that align our price with demonstrated clinical and economic value outcomes, so I can justify premium pricing through transparent value-price relationships that resonate with payers." "Market Access" "strategic" "high" "quarterly" "0.90" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-PR003" "Optimize Launch Pricing" "When preparing for product launch, I want to conduct comprehensive price optimization analyses including willingness-to-pay research, competitive pricing intelligence, and scenario modeling, so I can set an optimal launch price that balances access, revenue, and long-term market position." "Market Access" "analytical" "high" "quarterly" "0.91" "strategic" "project" "critical" "critical" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-PR004" "Manage International Reference Pricing" "When setting prices across multiple markets, I want to model and manage the impact of international reference pricing on our global price corridor, so I can optimize launch sequencing and minimize adverse reference pricing spillover effects." "Market Access" "analytical" "high" "monthly" "0.88" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-PR005" "Develop Innovative Contracting Models" "When negotiating with payers, I want to develop innovative contracting approaches including outcomes-based contracts, volume-based agreements, and risk-sharing arrangements, so I can address payer budget concerns while protecting our price integrity and market access." "Market Access" "strategic" "high" "quarterly" "0.87" "strategic" "project" "high" "high" "high" "L2_panel"

# Payer Relations (6)
run_jtbd_insert "JTBD-MA-PC001" "Develop Payer Engagement Strategy" "When launching products or expanding access, I want to develop comprehensive payer engagement strategies that identify key payer decision-makers, understand their priorities, and establish credible relationships, so I can effectively communicate our value proposition to influence formulary and coverage decisions." "Market Access" "strategic" "high" "quarterly" "0.90" "strategic" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-PC002" "Secure Optimal Formulary Positioning" "When seeking formulary inclusion, I want to develop compelling formulary dossiers and conduct effective P&T committee presentations that differentiate our therapy, so I can achieve optimal tier placement and minimal prior authorization barriers." "Market Access" "strategic" "high" "monthly" "0.89" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-PC003" "Execute Payer Contract Negotiations" "When establishing commercial agreements with payers, I want to negotiate contracts that balance favorable rebate/discount terms with access commitments, so I can secure broad patient access while protecting net revenue and avoiding adverse precedents." "Market Access" "negotiation" "high" "monthly" "0.91" "operational" "recurring" "critical" "critical" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-PC004" "Develop IDN/Health System Strategy" "When targeting integrated delivery networks and health systems, I want to develop tailored value propositions that address their specific clinical, operational, and financial priorities, so I can secure preferred product positioning within these increasingly influential healthcare organizations." "Market Access" "strategic" "high" "quarterly" "0.88" "strategic" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-PC005" "Manage Government Payer Relationships" "When engaging with Medicare, Medicaid, and other government payers, I want to navigate complex government pricing regulations and coverage determination processes, so I can secure favorable coverage while ensuring full compliance with government pricing requirements." "Market Access" "compliance" "high" "monthly" "0.92" "operational" "recurring" "high" "high" "critical" "L1_expert"
run_jtbd_insert "JTBD-MA-PC006" "Monitor Account Performance" "When managing payer account portfolios, I want to track and analyze account-level performance metrics including market share, access metrics, and contract compliance, so I can identify opportunities to improve access and optimize contract terms at renewal." "Market Access" "analytical" "medium" "monthly" "0.86" "operational" "recurring" "medium" "high" "medium" "L2_panel"

# Value & Evidence (5)
run_jtbd_insert "JTBD-MA-VE001" "Develop Compelling Value Propositions" "When positioning our product for payers and HTA bodies, I want to develop evidence-based value propositions that articulate our clinical, economic, and humanistic value in terms that resonate with each stakeholder, so I can create compelling narratives that differentiate our therapy and support access." "Market Access" "strategic" "high" "quarterly" "0.91" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-VE002" "Conduct Evidence Gap Analysis" "When planning our evidence generation strategy, I want to conduct systematic evidence gap analyses that identify deficiencies in our clinical, economic, and real-world evidence base relative to payer and HTA requirements, so I can prioritize evidence investments that address critical access barriers." "Market Access" "analytical" "high" "quarterly" "0.89" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-VE003" "Develop AMCP Format Dossiers" "When seeking formulary consideration, I want to develop comprehensive AMCP-format dossiers that present our clinical and economic evidence in a standardized, payer-friendly format, so I can facilitate efficient payer review and communicate our full value story." "Market Access" "documentation" "high" "quarterly" "0.88" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-VE004" "Create Value Communication Materials" "When arming our field teams for payer interactions, I want to develop compliant value communication materials including economic models, budget impact tools, and slide decks, so I can equip our team with compelling, legally-reviewed resources for customer engagements." "Market Access" "content" "medium" "monthly" "0.87" "operational" "recurring" "medium" "medium" "high" "L2_panel"
run_jtbd_insert "JTBD-MA-VE005" "Analyze Competitive Value Positioning" "When tracking our competitive positioning, I want to continuously monitor and analyze competitor value propositions, pricing, and market access status, so I can identify threats and opportunities and adjust our value strategy accordingly." "Market Access" "analytical" "medium" "monthly" "0.86" "operational" "recurring" "high" "medium" "medium" "L1_expert"

# Market Access Strategy (5)
run_jtbd_insert "JTBD-MA-AS001" "Develop Market Access Strategic Plans" "When preparing for product launches, I want to develop comprehensive market access strategic plans that define our target access profiles, evidence requirements, pricing corridors, and stakeholder engagement approach by market, so I can ensure coordinated execution toward optimal access outcomes." "Market Access" "strategic" "high" "annually" "0.92" "strategic" "project" "critical" "critical" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-AS002" "Optimize Global Launch Sequencing" "When planning multi-country launches, I want to develop optimal launch sequencing strategies that consider regulatory timelines, reference pricing implications, and commercial priorities, so I can maximize global value capture while protecting price integrity." "Market Access" "strategic" "high" "quarterly" "0.90" "strategic" "project" "critical" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-AS003" "Assess Market Access Barriers" "When evaluating market opportunities, I want to conduct systematic assessments of market access barriers including reimbursement hurdles, prior authorization requirements, and step therapy protocols, so I can develop mitigation strategies and realistic access forecasts." "Market Access" "analytical" "high" "quarterly" "0.88" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-AS004" "Monitor Healthcare Policy Landscape" "When navigating the evolving policy environment, I want to continuously monitor healthcare policy developments including drug pricing legislation, coverage policies, and reimbursement changes, so I can anticipate impacts on our products and proactively adapt our access strategies." "Market Access" "research" "medium" "weekly" "0.87" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-AS005" "Align Cross-Functional Access Strategy" "When coordinating market access activities, I want to ensure alignment between Market Access, Commercial, Medical Affairs, and Regulatory functions on access strategy, evidence planning, and customer engagement, so I can drive integrated execution that maximizes access success." "Market Access" "coordination" "high" "monthly" "0.89" "strategic" "recurring" "high" "high" "medium" "L2_panel"

# HTA (5)
run_jtbd_insert "JTBD-MA-HT001" "Prepare HTA Submissions" "When seeking reimbursement through HTA pathways, I want to develop comprehensive HTA submission dossiers that meet agency-specific requirements and present compelling clinical, economic, and budget impact evidence, so I can achieve positive HTA recommendations that enable reimbursement." "Market Access" "documentation" "high" "quarterly" "0.92" "strategic" "project" "critical" "critical" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-HT002" "Engage HTA Agencies" "When navigating HTA processes, I want to establish and maintain productive relationships with key HTA agencies through scientific advice meetings, public consultations, and post-submission dialogues, so I can understand agency expectations and address concerns proactively." "Market Access" "stakeholder" "high" "monthly" "0.90" "strategic" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-HT003" "Analyze Global HTA Landscape" "When planning global access strategy, I want to analyze HTA requirements, timelines, and decision patterns across key markets, so I can identify optimal submission strategies and anticipate likely outcomes based on precedent decisions." "Market Access" "analytical" "high" "quarterly" "0.88" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-HT004" "Manage HTA Appeals Process" "When receiving unfavorable HTA recommendations, I want to develop and execute effective appeal strategies that address agency concerns with additional evidence or refined analyses, so I can reverse negative decisions or improve recommended coverage restrictions." "Market Access" "strategic" "high" "quarterly" "0.86" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-HT005" "Align Evidence Generation with HTA Needs" "When planning clinical development, I want to ensure that trial designs and endpoints address HTA evidence requirements, so I can generate the comparative, quality of life, and economic evidence that HTA bodies need for favorable assessments." "Market Access" "strategic" "high" "quarterly" "0.89" "strategic" "project" "high" "high" "medium" "L2_panel"

# RWE (5)
run_jtbd_insert "JTBD-MA-RW001" "Develop Real-World Evidence Strategy" "When planning post-launch evidence generation, I want to develop comprehensive RWE strategies that identify priority research questions, data sources, and analytical approaches, so I can generate the real-world effectiveness and safety evidence that payers and regulators increasingly require." "Market Access" "strategic" "high" "annually" "0.90" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-RW002" "Execute Real-World Evidence Studies" "When generating post-launch evidence, I want to design and execute rigorous real-world studies using claims data, registries, or electronic health records, so I can demonstrate real-world effectiveness, safety, and economic outcomes in diverse patient populations." "Market Access" "research" "high" "quarterly" "0.88" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-RW003" "Manage Real-World Data Partnerships" "When accessing real-world data, I want to establish and manage strategic partnerships with data vendors, academic institutions, and health systems, so I can secure access to high-quality, representative data sources for our evidence generation programs." "Market Access" "stakeholder" "medium" "quarterly" "0.86" "operational" "recurring" "medium" "medium" "medium" "L2_panel"
run_jtbd_insert "JTBD-MA-RW004" "Support Outcomes-Based Contracts" "When implementing outcomes-based agreements, I want to design RWE measurement frameworks that accurately capture the contracted outcomes and enable fair performance assessment, so I can support successful OBC execution and demonstrate real-world value." "Market Access" "analytical" "high" "quarterly" "0.87" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-MA-RW005" "Support RWE Regulatory Submissions" "When seeking label expansions or post-marketing commitments, I want to generate regulatory-grade real-world evidence that meets FDA/EMA standards for decision-making, so I can support label updates and fulfill post-marketing evidence requirements." "Market Access" "compliance" "high" "quarterly" "0.89" "operational" "project" "high" "high" "critical" "L1_expert"

# Access Operations (3)
run_jtbd_insert "JTBD-MA-AO001" "Track Market Access Metrics" "When monitoring access performance, I want to track comprehensive market access metrics including formulary status, tier positioning, prior authorization rates, and lives covered, so I can identify access issues early and measure the effectiveness of our access strategies." "Market Access" "analytical" "medium" "weekly" "0.88" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-MA-AO002" "Manage Prior Authorization Requirements" "When addressing access barriers, I want to monitor and optimize our response to prior authorization and step therapy requirements, including criteria simplification efforts and PA support programs, so I can minimize patient access barriers and administrative burden on prescribers." "Market Access" "operational" "medium" "monthly" "0.86" "operational" "recurring" "medium" "high" "medium" "L2_panel"
run_jtbd_insert "JTBD-MA-AO003" "Enable Market Access Field Teams" "When equipping field-based market access teams, I want to provide them with current account intelligence, competitive insights, and compliant selling tools, so I can maximize their effectiveness in payer and health system customer engagements." "Market Access" "enablement" "medium" "monthly" "0.85" "operational" "recurring" "medium" "medium" "medium" "L2_panel"

echo ""
echo "Market Access JTBDs: 40 total"
echo "✓ Section complete"

# === COMMERCIAL ORGANIZATION JTBDs ===
echo ""
echo "=== COMMERCIAL ORGANIZATION JTBDs (40) ==="

# Sales Leadership (6)
run_jtbd_insert "JTBD-CO-SL001" "Develop National Sales Strategy" "When planning for the fiscal year, I want to develop a comprehensive national sales strategy that aligns sales targets, resource allocation, and go-to-market approach with corporate objectives, so I can position my organization to achieve and exceed revenue goals while maximizing market share." "Commercial" "strategic" "high" "annually" "0.92" "strategic" "project" "critical" "critical" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-SL002" "Optimize Sales Territory Design" "When balancing sales resources, I want to design and optimize sales territories that equalize opportunity, minimize travel burden, and align with customer concentration patterns, so I can ensure fair quota distribution and maximize field team productivity." "Commercial" "analytical" "high" "annually" "0.89" "operational" "project" "high" "high" "low" "L1_expert"
run_jtbd_insert "JTBD-CO-SL003" "Determine Optimal Sales Force Size" "When planning resource investments, I want to conduct rigorous sales force sizing analyses that model the relationship between call frequency, reach, and revenue, so I can optimize our sales investment and justify headcount decisions to leadership." "Commercial" "analytical" "high" "annually" "0.88" "strategic" "project" "high" "high" "low" "L1_expert"
run_jtbd_insert "JTBD-CO-SL004" "Execute Commercial Launch Readiness" "When preparing for product launches, I want to orchestrate comprehensive commercial launch readiness activities including field training, materials development, and customer targeting, so I can ensure maximum impact from day one of product availability." "Commercial" "coordination" "high" "quarterly" "0.91" "strategic" "project" "critical" "critical" "high" "L1_expert"
run_jtbd_insert "JTBD-CO-SL005" "Drive Sales Performance Management" "When managing team performance, I want to implement robust performance management systems that set clear expectations, track leading indicators, and enable timely coaching interventions, so I can develop high-performing sales teams that consistently hit targets." "Commercial" "management" "high" "weekly" "0.90" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-SL006" "Design Incentive Compensation Plans" "When motivating sales performance, I want to design incentive compensation plans that align rep behaviors with strategic priorities while remaining competitive for talent acquisition, so I can drive the right selling behaviors and retain top performers." "Commercial" "strategic" "high" "annually" "0.87" "operational" "project" "high" "high" "medium" "L2_panel"

# Field Sales (6)
run_jtbd_insert "JTBD-CO-FS001" "Plan Effective Customer Calls" "When preparing for customer interactions, I want to develop call plans that are tailored to each HCPs prescribing patterns, patient population, and previous interactions, so I can deliver relevant, personalized messages that advance my commercial objectives." "Commercial" "operational" "medium" "daily" "0.88" "operational" "recurring" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-CO-FS002" "Manage Territory Effectively" "When managing my assigned territory, I want to strategically prioritize accounts, plan efficient routing, and balance call frequency across customer segments, so I can maximize my reach and impact within available selling time." "Commercial" "operational" "medium" "weekly" "0.87" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-FS003" "Execute Effective HCP Engagements" "When interacting with healthcare professionals, I want to deliver compelling, compliant scientific discussions that address their clinical questions and patient needs, so I can build trusted relationships and drive appropriate product consideration." "Commercial" "stakeholder" "medium" "daily" "0.90" "operational" "recurring" "high" "high" "critical" "L1_expert"
run_jtbd_insert "JTBD-CO-FS004" "Respond to Competitive Activity" "When facing competitive pressures, I want to identify and respond to competitor moves in my territory with appropriate counter-messaging and intensified coverage, so I can protect and grow my market share position." "Commercial" "tactical" "medium" "weekly" "0.86" "operational" "recurring" "high" "medium" "high" "L1_expert"
run_jtbd_insert "JTBD-CO-FS005" "Execute Local Speaker Programs" "When leveraging peer influence, I want to plan and execute local speaker programs that feature credible KOLs presenting to relevant HCP audiences, so I can extend my reach and drive adoption through peer-to-peer education." "Commercial" "events" "medium" "monthly" "0.85" "operational" "project" "medium" "medium" "critical" "L2_panel"
run_jtbd_insert "JTBD-CO-FS006" "Manage Sample Distribution" "When providing product samples, I want to strategically distribute samples to appropriate HCPs while maintaining full compliance with sample accountability requirements, so I can facilitate trial while managing inventory and audit risk." "Commercial" "compliance" "low" "daily" "0.84" "operational" "recurring" "medium" "medium" "critical" "L0_ask"

# Key Account Management (5)
run_jtbd_insert "JTBD-CO-KA001" "Develop Strategic Account Plans" "When managing major accounts, I want to develop comprehensive strategic account plans that map decision-makers, understand organizational priorities, and identify value-creation opportunities, so I can build deep partnerships that drive preferred access and growth." "Commercial" "strategic" "high" "quarterly" "0.91" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-KA002" "Negotiate IDN/Health System Contracts" "When engaging integrated delivery networks, I want to negotiate value-based contracts that align our products with health system quality and cost objectives, so I can secure preferred formulary positioning and pull-through commitment." "Commercial" "negotiation" "high" "quarterly" "0.89" "operational" "project" "high" "critical" "high" "L1_expert"
run_jtbd_insert "JTBD-CO-KA003" "Manage GPO Relationships" "When working with group purchasing organizations, I want to maintain strong GPO relationships that secure favorable contract positioning and drive member awareness, so I can leverage GPO influence to expand institutional access." "Commercial" "stakeholder" "high" "monthly" "0.87" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-KA004" "Track Key Account Performance" "When monitoring account health, I want to track key account performance metrics including contract compliance, market share, and relationship scores, so I can identify issues early and demonstrate value delivered to account stakeholders." "Commercial" "analytical" "medium" "weekly" "0.86" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-KA005" "Coordinate Cross-Functional Account Teams" "When managing complex accounts, I want to orchestrate cross-functional account teams including Medical, Access, and Commercial colleagues, so I can deliver integrated solutions that address the full range of account needs." "Commercial" "coordination" "high" "monthly" "0.88" "operational" "recurring" "high" "high" "medium" "L2_panel"

# Sales Force Effectiveness (5)
run_jtbd_insert "JTBD-CO-SF001" "Design Sales Training Programs" "When developing sales capabilities, I want to design and deliver comprehensive training programs that build product knowledge, selling skills, and market understanding, so I can equip sales teams to execute effectively in the field." "Commercial" "enablement" "high" "quarterly" "0.89" "operational" "project" "high" "high" "high" "L1_expert"
run_jtbd_insert "JTBD-CO-SF002" "Implement Sales Coaching Programs" "When developing sales talent, I want to implement systematic coaching programs that provide managers with tools and skills to develop their teams through observation, feedback, and role-playing, so I can build a coaching culture that drives continuous improvement." "Commercial" "development" "high" "monthly" "0.87" "operational" "recurring" "high" "high" "medium" "L2_panel"
run_jtbd_insert "JTBD-CO-SF003" "Drive CRM Adoption and Optimization" "When leveraging sales technology, I want to maximize CRM adoption and usage through training, process integration, and continuous optimization, so I can ensure data quality and provide reps with actionable customer insights." "Commercial" "operational" "medium" "monthly" "0.85" "operational" "recurring" "medium" "medium" "low" "L2_panel"
run_jtbd_insert "JTBD-CO-SF004" "Manage Sales Content Library" "When enabling customer conversations, I want to curate and maintain a library of approved sales content including presentations, leave-behinds, and digital assets, so I can ensure reps have easy access to current, compliant materials." "Commercial" "content" "medium" "monthly" "0.84" "operational" "recurring" "medium" "medium" "high" "L2_panel"
run_jtbd_insert "JTBD-CO-SF005" "Execute Field Force Communications" "When informing the sales organization, I want to develop and deliver timely, relevant field communications that update teams on strategy changes, competitive intelligence, and operational matters, so I can keep the field informed and aligned." "Commercial" "communication" "medium" "weekly" "0.83" "operational" "recurring" "medium" "medium" "medium" "L0_ask"

# Business Development (5)
run_jtbd_insert "JTBD-CO-BD001" "Assess Partnership Opportunities" "When evaluating strategic opportunities, I want to conduct rigorous assessments of potential licensing, co-promotion, and distribution partnerships, so I can identify opportunities that strengthen our portfolio and provide attractive risk-adjusted returns." "Commercial" "analytical" "high" "monthly" "0.90" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-BD002" "Structure Business Development Deals" "When negotiating partnerships, I want to structure deal terms including economics, governance, and performance milestones that protect our interests while creating win-win arrangements, so I can close deals that deliver sustainable value." "Commercial" "negotiation" "high" "quarterly" "0.88" "strategic" "project" "high" "critical" "high" "L1_expert"
run_jtbd_insert "JTBD-CO-BD003" "Manage BD Pipeline" "When tracking business development activities, I want to maintain a robust pipeline of opportunities at various stages, so I can ensure consistent deal flow and provide accurate forecasting to leadership." "Commercial" "operational" "medium" "weekly" "0.86" "operational" "recurring" "high" "medium" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-BD004" "Scan Market for BD Opportunities" "When searching for growth opportunities, I want to systematically scan the market for assets, companies, and technologies that fit our strategic priorities, so I can identify attractive opportunities before competitors." "Commercial" "research" "medium" "weekly" "0.85" "strategic" "recurring" "high" "medium" "low" "L1_expert"
run_jtbd_insert "JTBD-CO-BD005" "Plan Deal Integration" "When closing business development transactions, I want to develop comprehensive integration plans that address commercial, operational, and organizational requirements, so I can ensure smooth transitions and rapid value realization." "Commercial" "coordination" "high" "quarterly" "0.87" "operational" "project" "high" "high" "medium" "L2_panel"

# Trade & Distribution (4)
run_jtbd_insert "JTBD-CO-TD001" "Optimize Distribution Network" "When managing product distribution, I want to design and optimize our distribution network including wholesaler relationships, specialty distribution, and direct-to-patient channels, so I can ensure product availability while managing inventory costs and channel conflict." "Commercial" "strategic" "high" "quarterly" "0.88" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-TD002" "Manage Wholesaler Relationships" "When working with trade partners, I want to maintain productive relationships with wholesalers and distributors through regular business reviews and collaborative problem-solving, so I can ensure reliable product flow and favorable trade terms." "Commercial" "stakeholder" "medium" "monthly" "0.86" "operational" "recurring" "medium" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-TD003" "Manage Channel Inventory" "When balancing product availability and working capital, I want to monitor and manage inventory levels across the distribution channel, so I can prevent stockouts while minimizing excess inventory and product expiration." "Commercial" "operational" "medium" "weekly" "0.85" "operational" "recurring" "high" "high" "low" "L1_expert"
run_jtbd_insert "JTBD-CO-TD004" "Manage Specialty Distribution Channels" "When distributing specialty products, I want to manage limited distribution networks and specialty pharmacies that can handle complex products and patient support requirements, so I can ensure appropriate handling and patient access support." "Commercial" "operational" "high" "monthly" "0.87" "operational" "recurring" "high" "high" "high" "L1_expert"

# Sales Analytics (5)
run_jtbd_insert "JTBD-CO-SA001" "Develop Sales Forecasts" "When projecting business performance, I want to develop accurate sales forecasts using statistical models, market intelligence, and field input, so I can provide leadership with reliable projections for financial planning and resource allocation." "Commercial" "analytical" "high" "monthly" "0.90" "operational" "recurring" "critical" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-SA002" "Analyze Sales Performance" "When evaluating sales effectiveness, I want to conduct deep-dive analyses of sales performance by geography, product, customer segment, and rep, so I can identify improvement opportunities and provide actionable insights to field leadership." "Commercial" "analytical" "high" "weekly" "0.89" "operational" "recurring" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-SA003" "Develop Customer Targeting & Segmentation" "When prioritizing sales effort, I want to develop data-driven customer segmentation and targeting models that identify high-potential HCPs and accounts, so I can optimize field resource allocation for maximum impact." "Commercial" "analytical" "high" "quarterly" "0.88" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-SA004" "Set Sales Quotas" "When establishing performance expectations, I want to set fair, motivating quotas that are grounded in market opportunity and aligned with strategic priorities, so I can drive the right behaviors while maintaining rep engagement." "Commercial" "analytical" "high" "annually" "0.87" "operational" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-SA005" "Gather and Analyze Competitive Intelligence" "When monitoring the competitive landscape, I want to systematically gather and analyze competitive intelligence on products, pricing, and market activities, so I can inform strategy and equip the field to compete effectively." "Commercial" "research" "medium" "weekly" "0.86" "operational" "recurring" "high" "medium" "medium" "L1_expert"

# Customer Engagement (4)
run_jtbd_insert "JTBD-CO-CE001" "Develop Omnichannel Engagement Strategy" "When orchestrating customer engagement, I want to develop integrated omnichannel strategies that coordinate personal, remote, and digital touchpoints based on customer preferences, so I can maximize engagement effectiveness across all channels." "Commercial" "strategic" "high" "quarterly" "0.89" "strategic" "project" "high" "high" "medium" "L1_expert"
run_jtbd_insert "JTBD-CO-CE002" "Execute Digital Customer Engagement" "When engaging customers digitally, I want to execute compelling digital campaigns through email, web, and social channels that deliver personalized content and drive meaningful interactions, so I can extend reach and complement field efforts." "Commercial" "digital" "medium" "weekly" "0.87" "operational" "recurring" "high" "medium" "high" "L2_panel"
run_jtbd_insert "JTBD-CO-CE003" "Build Virtual Engagement Capabilities" "When adapting to changing customer preferences, I want to develop robust virtual engagement capabilities including remote detailing and digital events, so I can maintain customer relationships regardless of access constraints." "Commercial" "enablement" "high" "quarterly" "0.86" "operational" "project" "high" "high" "medium" "L2_panel"
run_jtbd_insert "JTBD-CO-CE004" "Manage Customer Experience" "When optimizing customer relationships, I want to monitor and improve the end-to-end customer experience across all touchpoints, so I can build loyalty and differentiate through superior service." "Commercial" "quality" "medium" "monthly" "0.85" "operational" "recurring" "medium" "medium" "medium" "L2_panel"

echo ""
echo "Commercial Organization JTBDs: 40 total"
echo "✓ Section complete"

echo ""
echo "=============================================="
echo "JTBD Migration Summary"
echo "=============================================="
echo "Medical Affairs:        33 JTBDs"
echo "Market Access:          40 JTBDs"
echo "Commercial Organization: 40 JTBDs"
echo "----------------------------------------"
echo "TOTAL:                  113 JTBDs"
echo "=============================================="
