-- ============================================================================
-- AgentOS Complete Responsibilities Seeding - AUTO-GENERATED
-- File: 20251127-seed-all-responsibilities-AUTO.sql
-- ============================================================================
-- Generated from responsibility taxonomy markdown files
-- Total responsibilities: 278
-- Schema: unique_id, name, description, category, priority, complexity_level, is_active
-- ============================================================================

BEGIN;

INSERT INTO org_responsibilities (
    unique_id,
    name,
    description,
    category,
    priority,
    complexity_level,
    is_active
) VALUES

('RESP-MA-001', 'Enterprise Medical Strategy & Vision', 'Own and execute enterprise-wide medical strategy across all therapeutic areas, geographies, and stakeholders. Set medical vision, priorities, and resource allocation at highest level.', 'Leadership', 100, 'Critical', true),
('RESP-MA-002', 'Regional/Global Medical Portfolio Leadership', 'Lead medical affairs for regional/global portfolio including budget ownership, team leadership across multiple functions, and strategic objective delivery.', 'Leadership', 100, 'Critical', true),
('RESP-MA-003', 'Medical Function/TA Leadership', 'Direct leadership of medical affairs function or therapeutic area including team management, budget oversight, and delivery of strategic medical initiatives.', 'Leadership', 100, 'Critical', true),
('RESP-MA-004', 'Medical Governance Framework Ownership', 'Establish, maintain, and enforce medical governance frameworks, compliance programs, quality standards, and audit processes across medical affairs.', 'Compliance', 90, 'High', true),
('RESP-MA-005', 'KOL Relationship Portfolio Management', 'Build, maintain, and deepen relationships with assigned portfolio of key opinion leaders and thought leaders. Serve as primary scientific liaison.', 'Operations', 90, 'High', true),
('RESP-MA-006', 'Territory Scientific Coverage', 'Ensure comprehensive scientific coverage of assigned geographic territory or accounts. Execute territory plan with strategic HCP prioritization.', 'Operations', 80, 'High', true),
('RESP-MA-007', 'Clinical Insight Collection & Intelligence', 'Gather, analyze, and report high-quality clinical insights, competitive intelligence, and market trends from field interactions to inform medical and commercial strategy.', 'Operations', 90, 'High', true),
('RESP-MA-008', 'Clinical Trial Site Support & Recruitment', 'Support clinical trial site identification, feasibility assessment, and investigator engagement. Facilitate enrollment and serve as medical liaison to sites.', 'Operations', 80, 'High', true),
('RESP-MA-009', 'Congress & Scientific Meeting Coverage', 'Execute congress strategy including booth coverage, symposia support, KOL meetings, competitive intelligence, and abstract review at assigned congresses.', 'Operations', 90, 'High', true),
('RESP-MA-010', 'Field Medical Team Performance', 'Lead, coach, and develop field medical team to achieve performance objectives. Manage territory assignments, coaching, and capability development.', 'Operations', 90, 'High', true),
('RESP-MA-011', 'Regulatory Document Preparation', 'Write and review regulatory documents (CSRs, IBs, briefing documents, submissions) to regulatory standards with accuracy and timeliness.', 'Operations', 90, 'High', true),
('RESP-MA-012', 'Scientific Manuscript Development', 'Develop peer-reviewed manuscripts for journal publication including literature review, drafting, author coordination, and revision management.', 'Operations', 90, 'High', true),
('RESP-MA-013', 'Congress Materials Creation', 'Create congress abstracts, posters, and presentations to scientific standards. Manage submission process and presentation logistics.', 'Operations', 80, 'High', true),
('RESP-MA-014', 'Publication Plan Execution', 'Execute strategic publication plan including timeline management, vendor coordination, author engagement, and budget management.', 'Operations', 90, 'High', true),
('RESP-MA-015', 'Scientific Communications Content', 'Develop scientific communication materials (slide decks, platforms, messaging) for internal and external audiences aligned with medical strategy.', 'Communication', 90, 'High', true),
('RESP-MA-016', 'Medical Inquiry Response Quality', 'Respond to medical inquiries from HCPs and stakeholders with accurate, balanced, compliant information within SLA timelines.', 'Quality', 90, 'High', true),
('RESP-MA-017', 'Medical Information Content Management', 'Build, maintain, and update medical information reference library including standard responses, monographs, and FAQs.', 'Operations', 80, 'High', true),
('RESP-MA-018', 'Adverse Event Surveillance & Reporting', 'Identify, document, and report adverse events per regulatory requirements. Ensure pharmacovigilance compliance.', 'Communication', 80, 'High', true),
('RESP-MA-019', 'Medical Information Operations Management', 'Manage medical information operations including metrics, quality, vendor oversight, process optimization, and team performance.', 'Operations', 90, 'High', true),
('RESP-MA-020', 'Medical Education Strategy Development', 'Develop and execute medical education strategy including needs assessment, program portfolio, evaluation frameworks, and budget management.', 'Leadership', 90, 'High', true),
('RESP-MA-021', 'Internal Commercial Team Training', 'Design and deliver medical training programs for sales, marketing, and market access teams. Ensure disease/product knowledge and message accuracy.', 'Education', 90, 'High', true),
('RESP-MA-022', 'Digital Medical Content Development', 'Create digital medical education content including e-learning, webinars, virtual events, and mobile applications.', 'Operations', 90, 'High', true),
('RESP-MA-023', 'HCP Education Program Delivery', 'Plan and execute external HCP education programs including speaker programs, advisory boards, symposia, and grants.', 'Education', 90, 'High', true),
('RESP-MA-024', 'Health Economic Model Development', 'Build, validate, and maintain health economic models (CEA, BIA, CUA) to demonstrate product value for pricing and reimbursement.', 'Operations', 90, 'High', true),
('RESP-MA-025', 'Real-World Evidence Study Execution', 'Design and execute RWE studies including protocol development, data collection, analysis, and publication.', 'Operations', 90, 'High', true),
('RESP-MA-026', 'Outcomes Research & PRO Assessment', 'Measure patient-reported outcomes, quality of life, and treatment satisfaction in real-world settings. Analyze and report findings.', 'Operations', 90, 'High', true),
('RESP-MA-027', 'Value Evidence Communication', 'Generate and communicate value evidence to payers, HTA bodies, and formulary committees to support access decisions.', 'Communication', 90, 'High', true),
('RESP-MA-028', 'Clinical Site Relationship Management', 'Serve as primary liaison between medical affairs and clinical sites. Support site selection, training, and relationship management.', 'Operations', 90, 'High', true),
('RESP-MA-029', 'Clinical Data Analysis & Insights', 'Analyze clinical trial data, identify trends, and generate insights to support medical strategy and evidence generation.', 'Operations', 90, 'High', true),
('RESP-MA-030', 'Medical Compliance Monitoring', 'Monitor medical affairs activities for regulatory compliance, conduct audits, identify issues, and implement remediation.', 'Compliance', 90, 'High', true),
('RESP-MA-031', 'Promotional Material Review & MLR', 'Review promotional materials and medical communications for accuracy, balance, and compliance. Manage MLR process.', 'Operations', 90, 'High', true),
('RESP-MA-032', 'Quality Management System Maintenance', 'Maintain quality management system for medical affairs including SOPs, training, document control, and continuous improvement.', 'Quality', 90, 'High', true),
('RESP-MA-033', 'Scientific Thought Leadership', 'Establish and maintain scientific leadership in therapeutic area through KOL engagement, advisory boards, and strategic scientific initiatives.', 'Leadership', 90, 'High', true),
('RESP-MA-034', 'Cross-Functional Medical Input', 'Provide senior medical input to commercial, regulatory, market access, and R&D decisions. Ensure medical perspective in strategic discussions.', 'Operations', 100, 'Critical', true),
('RESP-MA-035', 'Medical Document Repository Management', 'Organize, maintain, and ensure accessibility of medical documents, literature, and reference materials per document management policies.', 'Operations', 70, 'Medium', true),
('RESP-MA-036', 'Literature Monitoring & Alerting', 'Conduct systematic literature monitoring for assigned therapeutic areas. Identify and alert medical team to relevant publications and safety signals.', 'Operations', 70, 'Medium', true),
('RESP-MA-037', 'CRM Data Quality Assurance', 'Enter, validate, and maintain medical affairs activity data in CRM. Ensure data quality, completeness, and accurate reporting.', 'Quality', 70, 'Medium', true),
('RESP-MA-038', 'Standard Report Production', 'Generate standard medical affairs reports (activity, metrics, KOLs) on scheduled basis. Ensure accuracy and timely delivery.', 'Operations', 70, 'Medium', true),
('RESP-MA-039', 'Meeting & Event Coordination', 'Coordinate logistics for medical meetings, advisory boards, and events including venue, materials, travel, expenses, and compliance documentation.', 'Operations', 70, 'Medium', true),
('RESP-MA-040', 'Strategic Planning & Roadmap Development', 'Develop strategic plans and roadmaps for medical affairs initiatives. Set priorities, define objectives, and allocate resources.', 'Strategic', 100, 'Critical', true),
('RESP-MA-041', 'Budget Ownership & Financial Performance', 'Own budget for assigned area including forecasting, tracking, and optimizing spend. Ensure financial targets met and ROI maximized.', 'Financial', 100, 'Critical', true),
('RESP-MA-042', 'Team Development & Talent Management', 'Develop team capabilities, manage performance, succession planning, and talent acquisition. Build high-performing teams.', 'Operations', 100, 'Critical', true),
('RESP-MA-043', 'Process Improvement & Innovation Leadership', 'Lead continuous improvement initiatives, drive innovation, and implement new processes/technologies to enhance medical affairs effectiveness.', 'Leadership', 100, 'Critical', true),
('RESP-MA-044', 'Executive Stakeholder Management', 'Manage relationships with C-suite and senior executives. Provide updates, seek guidance, and influence strategic decisions.', 'Operations', 100, 'Critical', true),
('RESP-MA-045', 'Cross-Functional Partnership Management', 'Build and maintain productive partnerships with commercial, regulatory, market access, and R&D functions. Ensure alignment and collaboration.', 'Operations', 90, 'High', true),
('RESP-MA-046', 'Internal Communication & Change Leadership', 'Communicate organizational changes, strategic direction, and important updates to team. Lead change initiatives with clear messaging.', 'Leadership', 100, 'Critical', true),
('RESP-MA-047', 'Documentation & Record Management', 'Ensure accurate documentation of medical affairs activities per compliance requirements. Maintain audit-ready records.', 'Operations', 90, 'High', true),
('RESP-MA-048', 'KPI Achievement & Performance Delivery', 'Achieve or exceed assigned key performance indicators. Monitor performance, identify issues, and implement corrective actions.', 'Operations', 100, 'Critical', true),
('RESP-MA-049', 'Quality Standards & Compliance Adherence', 'Maintain high quality standards in all work. Ensure compliance with regulations, SOPs, and company policies.', 'Compliance', 90, 'High', true),
('RESP-MA-050', 'Metrics Tracking & Reporting', 'Track relevant metrics for assigned activities and report to stakeholders. Provide insights and recommendations based on data.', 'Communication', 90, 'High', true),
('RESP-MA-051', 'Therapeutic Area Expertise Maintenance', 'Maintain deep, current knowledge of assigned therapeutic areas including disease, treatments, guidelines, and competitive landscape.', 'Operations', 90, 'High', true),
('RESP-MA-052', 'Regulatory & Compliance Knowledge Currency', 'Stay current on pharmaceutical regulations, industry codes, and compliance requirements. Apply knowledge to medical affairs activities.', 'Compliance', 90, 'High', true),
('RESP-MA-053', 'Continuous Learning & Professional Development', 'Engage in continuous learning, skill development, and professional growth. Stay current with industry trends and best practices.', 'Operations', 100, 'Critical', true),
('RESP-MA-054', 'SOP Adherence & Process Compliance', 'Follow all standard operating procedures and established processes. Identify process gaps and recommend improvements.', 'Compliance', 90, 'High', true),
('RESP-MA-055', 'System & Technology Utilization', 'Effectively use medical affairs systems and technology platforms. Maintain data quality and system hygiene.', 'Operations', 90, 'High', true),
('RESP-MA-056', 'Resource Optimization & Efficiency', 'Optimize use of time, budget, and resources. Identify efficiencies and eliminate waste. Maximize productivity.', 'Operations', 90, 'High', true),
('RESP-MA-057', 'Team Collaboration & Support', 'Actively collaborate with team members, share knowledge, and support team objectives. Contribute to positive team culture.', 'Operations', 90, 'High', true),
('RESP-MA-058', 'Knowledge Sharing & Best Practice Dissemination', 'Share knowledge, insights, and best practices with team and broader organization. Contribute to organizational learning.', 'Operations', 90, 'High', true),
('RESP-MA-059', 'Ethical Conduct & Professional Integrity', 'Maintain highest ethical standards in all interactions and decisions. Act with integrity, honesty, and transparency.', 'Operations', 80, 'High', true),
('RESP-MA-060', 'Patient Focus & Scientific Rigor', 'Maintain patient-centric perspective in all medical affairs activities. Ensure scientific rigor and evidence-based approach.', 'Operations', 80, 'High', true),
('RESP-RA-001', 'Global Regulatory Strategy Ownership', 'Own and execute comprehensive global regulatory strategy across all products, therapeutic areas, and markets with full accountability for approvals and compliance.', 'Leadership', 100, 'Critical', true),
('RESP-RA-002', 'Regional Regulatory Leadership & P&L', 'Lead regional regulatory function with P&L accountability, team management, and responsibility for achieving submission and approval milestones.', 'Leadership', 100, 'Critical', true),
('RESP-RA-003', 'Therapeutic Area Regulatory Leadership', 'Direct all regulatory activities for assigned therapeutic area including strategy, submissions, agency interactions, and team leadership.', 'Leadership', 90, 'High', true),
('RESP-RA-004', 'Regulatory Project Delivery', 'Deliver regulatory projects on time, on budget, with high quality including submissions, approvals, and lifecycle management.', 'Operations', 90, 'High', true),
('RESP-RA-005', 'IND/CTA Submission Excellence', 'Prepare and submit high-quality IND/CTA applications that enable clinical trial initiation without delays or deficiencies.', 'Operations', 90, 'High', true),
('RESP-RA-006', 'NDA/BLA Approval Achievement', 'Deliver approvable NDA/BLA submissions with comprehensive data packages that address all review issues and achieve first-cycle approval.', 'Operations', 90, 'High', true),
('RESP-RA-007', 'MAA/EU Approval Success', 'Achieve Marketing Authorization in EU via Centralised, Decentralised, or Mutual Recognition procedures with positive CHMP opinion.', 'Operations', 90, 'High', true),
('RESP-RA-008', 'Global Registration Execution', 'Execute global registration strategy across priority markets achieving approvals per commercial timelines and investment case.', 'Operations', 90, 'High', true),
('RESP-RA-009', 'Post-Approval Change Management', 'Manage all post-approval changes ensuring regulatory compliance, minimal business disruption, and maintenance of marketing authorizations.', 'Operations', 80, 'High', true),
('RESP-RA-010', 'Orphan & Pediatric Program Delivery', 'Secure orphan designations and complete pediatric programs per approved PIPs/PSPs achieving regulatory incentives and compliance.', 'Operations', 90, 'High', true),
('RESP-RA-011', 'Expedited Pathway Success', 'Successfully navigate expedited pathways achieving designation and approval via accelerated timelines while maintaining data quality.', 'Operations', 90, 'High', true),
('RESP-RA-012', 'CMC Regulatory Package Excellence', 'Deliver comprehensive, high-quality Module 3 (CMC) regulatory packages that support approval without manufacturing-related deficiencies.', 'Operations', 90, 'High', true),
('RESP-RA-013', 'Facility Registration & Inspection Readiness', 'Maintain all facility registrations, ensure inspection readiness, and achieve successful GMP inspections with zero critical observations.', 'Operations', 80, 'High', true),
('RESP-RA-014', 'Pharmaceutical Development Justification', 'Provide robust pharmaceutical development justification and specification rationale that withstands regulatory scrutiny.', 'Operations', 80, 'High', true),
('RESP-RA-015', 'CMC Lifecycle Compliance', 'Maintain CMC compliance throughout product lifecycle managing changes, comparability, and quality variations with regulatory approval.', 'Compliance', 80, 'High', true),
('RESP-RA-016', 'Biologics Regulatory Compliance', 'Ensure regulatory compliance for biologics, biosimilars, and advanced therapies meeting specialized requirements and maintaining approvals.', 'Compliance', 90, 'High', true),
('RESP-RA-017', 'Approved Labeling Achievement', 'Achieve approved product labeling that accurately reflects product benefits/risks and enables optimal commercial positioning.', 'Operations', 80, 'High', true),
('RESP-RA-018', 'Labeling Negotiation Success', 'Successfully negotiate product labeling with agencies defending proposed language and achieving favorable outcomes on key issues.', 'Operations', 90, 'High', true),
('RESP-RA-019', 'Global Label Harmonization', 'Maintain harmonized global labeling across markets while meeting regional requirements and ensuring consistent safety messaging.', 'Operations', 90, 'High', true),
('RESP-RA-020', 'Safety Label Update Compliance', 'Ensure timely and compliant implementation of safety labeling updates in response to new safety data across all markets.', 'Compliance', 80, 'High', true),
('RESP-RA-021', 'Pre-Submission Meeting Success', 'Achieve successful pre-submission meetings and scientific advice obtaining regulatory alignment on critical development and submission issues.', 'Operations', 90, 'High', true),
('RESP-RA-022', 'Agency Query Resolution Excellence', 'Resolve all agency queries, information requests, and deficiencies with high-quality responses that address reviewer concerns and support approval.', 'Operations', 90, 'High', true),
('RESP-RA-023', 'Advisory Committee Positive Outcome', 'Achieve positive Advisory Committee vote through comprehensive preparation, compelling presentation, and effective committee engagement.', 'Operations', 90, 'High', true),
('RESP-RA-024', 'Inspection & Audit Excellence', 'Achieve successful regulatory inspections with zero critical observations and timely resolution of any non-critical findings.', 'Compliance', 90, 'High', true),
('RESP-RA-025', 'Regulatory Intelligence Delivery', 'Deliver actionable regulatory intelligence that informs strategic decisions, anticipates regulatory changes, and provides competitive advantage.', 'Operations', 90, 'High', true),
('RESP-RA-026', 'Regulatory Compliance Assurance', 'Maintain 100% regulatory compliance across all products and markets including commitments, reporting, and ongoing obligations.', 'Compliance', 80, 'High', true),
('RESP-RA-027', 'Regulatory Policy Contribution', 'Actively contribute to regulatory policy development through industry associations, agency interactions, and policy advocacy.', 'Operations', 100, 'Critical', true),
('RESP-RA-028', 'Regulatory Training Excellence', 'Deliver comprehensive regulatory training ensuring team competency, compliance knowledge, and continuous learning.', 'Education', 90, 'High', true),
('RESP-RA-029', 'Product Lifecycle Optimization', 'Optimize product lifecycle through strategic regulatory planning including new indications, formulations, and lifecycle extensions.', 'Operations', 90, 'High', true),
('RESP-RA-030', 'Post-Approval Commitment Fulfillment', 'Complete all post-approval commitments and studies per agreed timelines maintaining compliance and avoiding penalties.', 'Operations', 80, 'High', true),
('RESP-RA-031', 'Regulatory Maintenance Excellence', 'Maintain all marketing authorizations through timely submissions, renewals, and ongoing compliance activities.', 'Operations', 80, 'High', true),
('RESP-RA-032', 'Risk Management Plan Implementation', 'Develop and implement comprehensive Risk Management Plans and REMS ensuring patient safety and regulatory compliance.', 'Operations', 90, 'High', true),
('RESP-RA-033', 'Safety Reporting Compliance', 'Ensure 100% compliance with all regulatory safety reporting requirements including expedited and aggregate reports.', 'Compliance', 80, 'High', true),
('RESP-RA-034', 'Benefit-Risk Documentation', 'Document comprehensive benefit-risk assessments that support regulatory decisions and demonstrate favorable benefit-risk profile.', 'Operations', 90, 'High', true),
('RESP-RA-035', 'Regulatory Crisis Resolution', 'Successfully resolve regulatory crises minimizing patient risk, business impact, and regulatory consequences through rapid, coordinated response.', 'Operations', 100, 'Critical', true),
('RESP-RA-036', 'Strategic Regulatory Decision-Making', 'Make strategic regulatory decisions that balance speed, risk, cost, and scientific integrity to achieve business objectives.', 'Strategic', 100, 'Critical', true),
('RESP-RA-037', 'Cross-Functional Regulatory Guidance', 'Provide expert regulatory guidance to cross-functional teams ensuring regulatory compliance and strategic alignment across development.', 'Operations', 100, 'Critical', true),
('RESP-RA-038', 'Regulatory Resource Optimization', 'Optimize regulatory resources including budget, staff, and external consultants to maximize efficiency and value.', 'Operations', 100, 'Critical', true),
('RESP-RA-039', 'Regulatory Expertise Maintenance', 'Maintain deep regulatory expertise through continuous learning, guideline monitoring, and professional development.', 'Operations', 90, 'High', true),
('RESP-RA-040', 'Regulatory Document Quality', 'Ensure all regulatory documents meet highest quality standards with scientific rigor, accuracy, and regulatory compliance.', 'Quality', 90, 'High', true),
('RESP-RA-041', 'Clinical-Regulatory Alignment', 'Ensure clinical development programs align with regulatory requirements and support approvable submissions.', 'Operations', 90, 'High', true),
('RESP-RA-042', 'Regulatory Data Integrity', 'Ensure integrity, accuracy, and traceability of all regulatory data and information in submissions and communications.', 'Operations', 90, 'High', true),
('RESP-RA-043', 'Agency Relationship Excellence', 'Build and maintain positive, professional relationships with health authorities based on transparency, trust, and mutual respect.', 'Operations', 90, 'High', true),
('RESP-RA-044', 'Regulatory Communication Impact', 'Deliver impactful regulatory communications to internal and external stakeholders that drive understanding and action.', 'Communication', 90, 'High', true),
('RESP-RA-045', 'Global Regulatory Collaboration', 'Foster effective collaboration across global regulatory teams ensuring knowledge sharing, alignment, and efficiency.', 'Operations', 90, 'High', true),
('RESP-RA-046', 'Regulatory Advisory Excellence', 'Provide expert regulatory advice that adds strategic value and enables informed decision-making across the organization.', 'Operations', 90, 'High', true),
('RESP-RA-047', 'Regulatory Systems Proficiency', 'Maintain proficiency in regulatory systems ensuring accurate, efficient use and contributing to system optimization.', 'Operations', 90, 'High', true),
('RESP-RA-048', 'Regulatory Quality Assurance', 'Execute rigorous quality assurance for all regulatory activities ensuring compliance with internal and external standards.', 'Quality', 90, 'High', true),
('RESP-RA-049', 'Regulatory Process Excellence', 'Execute regulatory processes with excellence identifying and implementing continuous improvements for efficiency and quality.', 'Operations', 90, 'High', true),
('RESP-RA-050', 'Regulatory Timeline Achievement', 'Achieve regulatory milestones and submission timelines through effective planning, coordination, and execution.', 'Operations', 90, 'High', true),
('RESP-CD-001', 'Clinical Development Strategy Execution', 'Own and execute clinical development strategy achieving development milestones, regulatory approvals, and budget targets.', 'Leadership', 100, 'Critical', true),
('RESP-CD-002', 'Clinical Program Delivery', 'Deliver clinical programs from Phase I through approval achieving quality, timeline, and budget objectives.', 'Operations', 100, 'Critical', true),
('RESP-CD-003', 'Functional Leadership & Team Management', 'Lead clinical functional area (operations, data, biostatistics) with team performance and budget accountability.', 'Leadership', 90, 'High', true),
('RESP-CD-004', 'Clinical Trial Success Delivery', 'Deliver successful clinical trials meeting enrollment, timeline, quality, and data objectives.', 'Operations', 90, 'High', true),
('RESP-CD-005', 'Protocol Quality & Regulatory Acceptability', 'Deliver high-quality protocols that meet scientific, regulatory, and operational standards.', 'Quality', 90, 'High', true),
('RESP-CD-006', 'Study Design Scientific Rigor', 'Ensure scientific rigor of study designs enabling definitive conclusions and regulatory approval.', 'Operations', 90, 'High', true),
('RESP-CD-007', 'Special Population Study Success', 'Successfully conduct special population studies meeting enrollment, safety, and data objectives.', 'Operations', 90, 'High', true),
('RESP-CD-008', 'Biomarker Strategy Implementation', 'Successfully implement biomarker strategies including patient selection, companion diagnostic development, and regulatory approval.', 'Leadership', 90, 'High', true),
('RESP-CD-009', 'Adaptive Trial Execution Excellence', 'Execute adaptive trials maintaining integrity while implementing protocol modifications based on interim data.', 'Operations', 90, 'High', true),
('RESP-CD-010', 'Trial Operational Excellence', 'Achieve operational excellence in trial execution including timeline, quality, budget, and site performance.', 'Operations', 90, 'High', true),
('RESP-CD-011', 'Site Network Performance', 'Build and maintain high-performing site network achieving enrollment, quality, and retention targets.', 'Operations', 80, 'High', true),
('RESP-CD-012', 'Site Start-Up Efficiency', 'Achieve efficient site start-up meeting activation timelines and minimizing enrollment delays.', 'Operations', 80, 'High', true),
('RESP-CD-013', 'Protocol Compliance & Data Quality', 'Ensure protocol compliance and data quality through effective monitoring and issue resolution.', 'Compliance', 80, 'High', true),
('RESP-CD-014', 'Enrollment Target Achievement', 'Achieve enrollment targets within timeline through effective recruitment strategies and site management.', 'Operations', 90, 'High', true),
('RESP-CD-015', 'Clinical Supply Availability', 'Ensure continuous clinical supply availability with zero patient disruptions due to stockouts.', 'Operations', 80, 'High', true),
('RESP-CD-016', 'Clinical Data Quality & Integrity', 'Ensure clinical data quality and integrity meeting regulatory standards and supporting approvable submissions.', 'Quality', 90, 'High', true),
('RESP-CD-017', 'EDC System Performance', 'Deliver EDC systems that support efficient data collection with minimal user issues and high data quality.', 'Operations', 80, 'High', true),
('RESP-CD-018', 'Data Cleaning Excellence', 'Achieve data cleaning excellence through efficient query management and timely resolution.', 'Operations', 80, 'High', true),
('RESP-CD-019', 'Database Lock Timeliness', 'Achieve database lock within target timelines enabling analysis and submission milestones.', 'Operations', 80, 'High', true),
('RESP-CD-020', 'Statistical Strategy Quality', 'Deliver statistical strategies that optimize development efficiency and enable definitive conclusions.', 'Leadership', 90, 'High', true),
('RESP-CD-021', 'SAP Quality & Completeness', 'Deliver comprehensive SAPs that enable complete analysis and address regulatory requirements.', 'Quality', 90, 'High', true),
('RESP-CD-022', 'Analysis Quality & Timeliness', 'Deliver high-quality statistical analyses within timeline supporting regulatory submissions and decisions.', 'Quality', 90, 'High', true),
('RESP-CD-023', 'DMC Support Excellence', 'Provide excellent DMC support with timely, accurate interim analyses and safety reports.', 'Operations', 90, 'High', true),
('RESP-CD-024', 'Clinical Quality System Management', 'Maintain effective clinical quality system ensuring GCP compliance and continuous improvement.', 'Quality', 90, 'High', true),
('RESP-CD-025', 'Audit Quality & Value', 'Conduct high-quality audits that identify risks, ensure compliance, and add value.', 'Compliance', 80, 'High', true),
('RESP-CD-026', 'GCP Compliance Assurance', 'Ensure 100% GCP compliance across all trials through monitoring, training, and oversight.', 'Compliance', 90, 'High', true),
('RESP-CD-027', 'Inspection Success', 'Achieve successful inspections with zero critical findings and timely resolution of observations.', 'Operations', 90, 'High', true),
('RESP-CD-028', 'Clinical Safety Management', 'Ensure patient safety through robust safety monitoring, signal detection, and risk mitigation.', 'Safety', 90, 'High', true),
('RESP-CD-029', 'Safety Committee Effectiveness', 'Ensure Safety Review Committee effectiveness with timely meetings, quality assessments, and implemented recommendations.', 'Safety', 90, 'High', true),
('RESP-CD-030', 'Safety Report Quality', 'Deliver high-quality safety reports meeting regulatory standards and supporting approval decisions.', 'Quality', 80, 'High', true),
('RESP-CD-031', 'CSR Quality & Regulatory Acceptance', 'Deliver CSRs meeting ICH E3 standards that support regulatory submissions and approvals.', 'Quality', 90, 'High', true),
('RESP-CD-032', 'Development Plan Documentation Quality', 'Deliver development plan documentation that communicates strategy and supports regulatory interactions.', 'Quality', 90, 'High', true),
('RESP-CD-033', 'IB Currency & Compliance', 'Maintain current investigator brochures meeting regulatory update requirements and supporting trial conduct.', 'Compliance', 80, 'High', true),
('RESP-CD-034', 'Medical Monitoring Quality', 'Provide high-quality medical monitoring ensuring patient safety and appropriate medical decisions.', 'Quality', 90, 'High', true),
('RESP-CD-035', 'PK/PD Analysis Quality', 'Deliver high-quality PK/PD analyses informing dose selection and development decisions.', 'Quality', 90, 'High', true),
('RESP-CD-036', 'Strategic Development Decision-Making', 'Strategic Development Decision-Making', 'Strategic', 80, 'High', true),
('RESP-CD-037', 'Cross-Functional Clinical Coordination', 'Cross-Functional Clinical Coordination', 'Operations', 80, 'High', true),
('RESP-CD-038', 'Clinical Budget Performance', 'Clinical Budget Performance', 'Financial', 80, 'High', true),
('RESP-CD-039', 'Clinical & TA Expertise Maintenance', 'Clinical & TA Expertise Maintenance', 'Operations', 80, 'High', true),
('RESP-CD-040', 'Regulatory & GCP Compliance', 'Regulatory & GCP Compliance', 'Compliance', 80, 'High', true),
('RESP-CD-041', 'Data Integrity & Quality', 'Data Integrity & Quality', 'Quality', 80, 'High', true),
('RESP-CD-042', 'Investigator & Site Relationship Excellence', 'Investigator & Site Relationship Excellence', 'Operations', 80, 'High', true),
('RESP-CD-043', 'Clinical Communication Impact', 'Clinical Communication Impact', 'Communication', 80, 'High', true),
('RESP-CD-044', 'Clinical Team Collaboration', 'Clinical Team Collaboration', 'Operations', 80, 'High', true),
('RESP-CD-045', 'Vendor & CRO Performance', 'Vendor & CRO Performance', 'Operations', 80, 'High', true),
('RESP-CD-046', 'Clinical Project Delivery', 'Clinical Project Delivery', 'Operations', 80, 'High', true),
('RESP-CD-047', 'Clinical Quality Excellence', 'Clinical Quality Excellence', 'Quality', 80, 'High', true),
('RESP-CD-048', 'Clinical Documentation Standards', 'Clinical Documentation Standards', 'Operations', 80, 'High', true),
('RESP-CD-049', 'Clinical Timeline Achievement', 'Clinical Timeline Achievement', 'Operations', 80, 'High', true),
('RESP-CD-050', 'Continuous Improvement & Innovation', 'Continuous Improvement & Innovation', 'Operations', 80, 'High', true),
('RESP-SV-001', 'Global PV Strategy Execution', 'Global PV Strategy Execution', 'Leadership', 80, 'High', true),
('RESP-SV-002', 'PV Operations Excellence', 'PV Operations Excellence', 'Operations', 80, 'High', true),
('RESP-SV-003', 'Medical Safety Leadership', 'Medical Safety Leadership', 'Leadership', 80, 'High', true),
('RESP-SV-004', 'Case Processing Quality & Timeliness', 'Case Processing Quality & Timeliness', 'Quality', 80, 'High', true),
('RESP-SV-005', 'SAE Assessment Accuracy', 'SAE Assessment Accuracy', 'Operations', 80, 'High', true),
('RESP-SV-006', 'Expedited Reporting Compliance', 'Expedited Reporting Compliance', 'Compliance', 80, 'High', true),
('RESP-SV-007', 'Safety Database Quality', 'Safety Database Quality', 'Quality', 80, 'High', true),
('RESP-SV-008', 'Signal Detection Effectiveness', 'Signal Detection Effectiveness', 'Operations', 80, 'High', true),
('RESP-SV-009', 'Signal Assessment Quality', 'Signal Assessment Quality', 'Quality', 80, 'High', true),
('RESP-SV-010', 'RMP/REMS Implementation Success', 'RMP/REMS Implementation Success', 'Operations', 80, 'High', true),
('RESP-SV-011', 'Benefit-Risk Balance Maintenance', 'Benefit-Risk Balance Maintenance', 'Operations', 80, 'High', true),
('RESP-SV-012', 'Safety Committee Effectiveness', 'Safety Committee Effectiveness', 'Safety', 80, 'High', true),
('RESP-SV-013', 'PSUR/PBRER Quality & Timeliness', 'PSUR/PBRER Quality & Timeliness', 'Quality', 80, 'High', true),
('RESP-SV-014', 'DSUR Regulatory Compliance', 'DSUR Regulatory Compliance', 'Compliance', 80, 'High', true),
('RESP-SV-015', 'Safety Data Analysis Rigor', 'Safety Data Analysis Rigor', 'Safety', 80, 'High', true),
('RESP-SV-016', 'Aggregate Report Quality', 'Aggregate Report Quality', 'Quality', 80, 'High', true),
('RESP-SV-017', 'PV Regulatory Compliance Achievement', 'PV Regulatory Compliance Achievement', 'Compliance', 80, 'High', true),
('RESP-SV-018', 'Safety Submission Quality', 'Safety Submission Quality', 'Quality', 80, 'High', true),
('RESP-SV-019', 'PSMF Currency & Compliance', 'PSMF Currency & Compliance', 'Compliance', 80, 'High', true),
('RESP-SV-020', 'Inspection Success Rate', 'Inspection Success Rate', 'Operations', 80, 'High', true),
('RESP-SV-021', 'Medical Safety Surveillance Quality', 'Medical Safety Surveillance Quality', 'Quality', 80, 'High', true),
('RESP-SV-022', 'Clinical Trial Safety Oversight', 'Clinical Trial Safety Oversight', 'Safety', 80, 'High', true),
('RESP-SV-023', 'Product Safety Profile Accuracy', 'Product Safety Profile Accuracy', 'Safety', 80, 'High', true),
('RESP-SV-024', 'Literature Surveillance Completeness', 'Literature Surveillance Completeness', 'Operations', 80, 'High', true),
('RESP-SV-025', 'Medication Error Management', 'Medication Error Management', 'Operations', 80, 'High', true),
('RESP-SV-026', 'PASS/PAES Delivery', 'PASS/PAES Delivery', 'Operations', 80, 'High', true),
('RESP-SV-027', 'Vendor Safety Quality Oversight', 'Vendor Safety Quality Oversight', 'Quality', 80, 'High', true),
('RESP-SV-028', 'Safety Training & Competency', 'Safety Training & Competency', 'Safety', 80, 'High', true),
('RESP-MA-001', 'Market Access Strategy Execution', 'Market Access Strategy Execution', 'Leadership', 80, 'High', true),
('RESP-MA-002', 'Payer Engagement Success', 'Payer Engagement Success', 'Operations', 80, 'High', true),
('RESP-MA-003', 'HEOR Evidence Generation', 'HEOR Evidence Generation', 'Operations', 80, 'High', true),
('RESP-MA-004', 'Account Management Excellence', 'Account Management Excellence', 'Operations', 80, 'High', true),
('RESP-MA-005', 'Contract Negotiation Success', 'Contract Negotiation Success', 'Operations', 80, 'High', true),
('RESP-MA-006', 'Formulary Access Achievement', 'Formulary Access Achievement', 'Operations', 80, 'High', true),
('RESP-MA-007', 'Reimbursement Strategy Success', 'Reimbursement Strategy Success', 'Leadership', 80, 'High', true),
('RESP-MA-008', 'Value-Based Contract Implementation', 'Value-Based Contract Implementation', 'Operations', 80, 'High', true),
('RESP-MA-009', 'Economic Model Quality', 'Economic Model Quality', 'Quality', 80, 'High', true),
('RESP-MA-010', 'CEA Regulatory Acceptance', 'CEA Regulatory Acceptance', 'Operations', 80, 'High', true),
('RESP-MA-011', 'BIA Payer Acceptance', 'BIA Payer Acceptance', 'Operations', 80, 'High', true),
('RESP-MA-012', 'Pharmacoeconomic Model Validity', 'Pharmacoeconomic Model Validity', 'Operations', 80, 'High', true),
('RESP-MA-013', 'HTA Submission Success', 'HTA Submission Success', 'Operations', 80, 'High', true),
('RESP-MA-014', 'Model Validation Quality', 'Model Validation Quality', 'Quality', 80, 'High', true),
('RESP-MA-015', 'RWE Strategy Execution', 'RWE Strategy Execution', 'Leadership', 80, 'High', true),
('RESP-MA-016', 'Observational Study Success', 'Observational Study Success', 'Operations', 80, 'High', true),
('RESP-MA-017', 'PRO Validation & Utility', 'PRO Validation & Utility', 'Operations', 80, 'High', true),
('RESP-MA-018', 'RWD Analysis Quality', 'RWD Analysis Quality', 'Quality', 80, 'High', true),
('RESP-MA-019', 'CER Credibility', 'CER Credibility', 'Operations', 80, 'High', true),
('RESP-MA-020', 'Global Pricing Strategy Success', 'Global Pricing Strategy Success', 'Leadership', 80, 'High', true),
('RESP-MA-021', 'Value Proposition Impact', 'Value Proposition Impact', 'Operations', 80, 'High', true),
('RESP-MA-022', 'Value Dossier Quality', 'Value Dossier Quality', 'Quality', 80, 'High', true),
('RESP-MA-023', 'HEOR Communication Effectiveness', 'HEOR Communication Effectiveness', 'Communication', 80, 'High', true),
('RESP-MA-024', 'Evidence Gap Closure', 'Evidence Gap Closure', 'Operations', 80, 'High', true),
('RESP-MA-025', 'Policy Influence Impact', 'Policy Influence Impact', 'Operations', 80, 'High', true),
('RESP-MA-026', 'Coverage Policy Success', 'Coverage Policy Success', 'Operations', 80, 'High', true),
('RESP-MA-027', 'Patient Access Program Enrollment', 'Patient Access Program Enrollment', 'Operations', 80, 'High', true),
('RESP-MA-028', 'Market Access Analytics Insights', 'Market Access Analytics Insights', 'Operations', 80, 'High', true),
('RESP-MA-029', 'Payer Intelligence Quality', 'Payer Intelligence Quality', 'Quality', 80, 'High', true),
('RESP-MA-030', 'Access Monitoring & Optimization', 'Access Monitoring & Optimization', 'Operations', 80, 'High', true),
('RESP-CM-001', 'Commercial P&L Ownership', 'Commercial P&L Ownership', 'Operations', 80, 'High', true),
('RESP-CM-002', 'Commercial Strategy Execution', 'Commercial Strategy Execution', 'Leadership', 80, 'High', true),
('RESP-CM-003', 'Brand Portfolio Performance', 'Brand Portfolio Performance', 'Operations', 80, 'High', true),
('RESP-CM-004', 'Sales Force Performance', 'Sales Force Performance', 'Operations', 80, 'High', true),
('RESP-CM-005', 'Brand Strategy Success', 'Brand Strategy Success', 'Leadership', 80, 'High', true),
('RESP-CM-006', 'Launch Excellence', 'Launch Excellence', 'Operations', 80, 'High', true),
('RESP-CM-007', 'Campaign ROI Achievement', 'Campaign ROI Achievement', 'Operations', 80, 'High', true),
('RESP-CM-008', 'Promotional Strategy Impact', 'Promotional Strategy Impact', 'Leadership', 80, 'High', true),
('RESP-CM-009', 'Brand Growth & Share', 'Brand Growth & Share', 'Operations', 80, 'High', true),
('RESP-CM-010', 'Lifecycle Value Maximization', 'Lifecycle Value Maximization', 'Operations', 80, 'High', true),
('RESP-CM-011', 'Sales Force Productivity', 'Sales Force Productivity', 'Operations', 80, 'High', true),
('RESP-CM-012', 'Territory Optimization', 'Territory Optimization', 'Operations', 80, 'High', true),
('RESP-CM-013', 'Sales Insights Actionability', 'Sales Insights Actionability', 'Operations', 80, 'High', true),
('RESP-CM-014', 'Sales Readiness', 'Sales Readiness', 'Operations', 80, 'High', true),
('RESP-CM-015', 'Incentive Plan Effectiveness', 'Incentive Plan Effectiveness', 'Operations', 80, 'High', true),
('RESP-CM-016', 'HCP Engagement Quality', 'HCP Engagement Quality', 'Quality', 80, 'High', true),
('RESP-CM-017', 'Key Account Growth', 'Key Account Growth', 'Operations', 80, 'High', true),
('RESP-CM-018', 'Specialty Sales Excellence', 'Specialty Sales Excellence', 'Operations', 80, 'High', true),
('RESP-CM-019', 'Territory Quota Achievement', 'Territory Quota Achievement', 'Operations', 80, 'High', true),
('RESP-CM-020', 'Customer Segmentation Precision', 'Customer Segmentation Precision', 'Operations', 80, 'High', true),
('RESP-CM-021', 'Omnichannel Strategy Success', 'Omnichannel Strategy Success', 'Leadership', 80, 'High', true),
('RESP-CM-022', 'Digital Marketing ROI', 'Digital Marketing ROI', 'Operations', 80, 'High', true),
('RESP-CM-023', 'Speaker Program Quality', 'Speaker Program Quality', 'Quality', 80, 'High', true),
('RESP-CM-024', 'Commercial Analytics Accuracy', 'Commercial Analytics Accuracy', 'Operations', 80, 'High', true),
('RESP-CM-025', 'Market Research Quality', 'Market Research Quality', 'Quality', 80, 'High', true),
('RESP-CM-026', 'Competitive Intelligence Impact', 'Competitive Intelligence Impact', 'Operations', 80, 'High', true),
('RESP-CM-027', 'Commercial Operations Excellence', 'Commercial Operations Excellence', 'Operations', 80, 'High', true),
('RESP-CM-028', 'CRM Data Quality', 'CRM Data Quality', 'Quality', 80, 'High', true),
('RESP-MF-001', 'Manufacturing Operations Excellence', 'Manufacturing Operations Excellence', 'Operations', 80, 'High', true),
('RESP-MF-002', 'CMC Development Strategy Success', 'CMC Development Strategy Success', 'Leadership', 80, 'High', true),
('RESP-MF-003', 'Site Operations Performance', 'Site Operations Performance', 'Operations', 80, 'High', true),
('RESP-MF-004', 'Process Development Excellence', 'Process Development Excellence', 'Operations', 80, 'High', true),
('RESP-MF-005', 'Chemical Synthesis Optimization', 'Chemical Synthesis Optimization', 'Operations', 80, 'High', true),
('RESP-MF-006', 'Biologics Process Performance', 'Biologics Process Performance', 'Operations', 80, 'High', true),
('RESP-MF-007', 'Formulation Success', 'Formulation Success', 'Operations', 80, 'High', true),
('RESP-MF-008', 'Process Robustness', 'Process Robustness', 'Operations', 80, 'High', true),
('RESP-MF-009', 'Continuous Manufacturing Implementation', 'Continuous Manufacturing Implementation', 'Operations', 80, 'High', true),
('RESP-MF-010', 'Analytical Method Validation', 'Analytical Method Validation', 'Operations', 80, 'High', true),
('RESP-MF-011', 'Method Transfer Success', 'Method Transfer Success', 'Operations', 80, 'High', true),
('RESP-MF-012', 'Stability Program Compliance', 'Stability Program Compliance', 'Compliance', 80, 'High', true),
('RESP-MF-013', 'Characterization Completeness', 'Characterization Completeness', 'Operations', 80, 'High', true),
('RESP-MF-014', 'Scale-Up Success Rate', 'Scale-Up Success Rate', 'Operations', 80, 'High', true),
('RESP-MF-015', 'Technology Transfer Excellence', 'Technology Transfer Excellence', 'Operations', 80, 'High', true),
('RESP-MF-016', 'Manufacturing Validation Success', 'Manufacturing Validation Success', 'Operations', 80, 'High', true),
('RESP-MF-017', 'Comparability Demonstration', 'Comparability Demonstration', 'Operations', 80, 'High', true),
('RESP-MF-018', 'GMP Compliance Achievement', 'GMP Compliance Achievement', 'Compliance', 80, 'High', true),
('RESP-MF-019', 'Batch Success Rate', 'Batch Success Rate', 'Operations', 80, 'High', true),
('RESP-MF-020', 'Equipment Performance', 'Equipment Performance', 'Operations', 80, 'High', true),
('RESP-MF-021', 'Batch Release Timeliness', 'Batch Release Timeliness', 'Operations', 80, 'High', true),
('RESP-MF-022', 'Manufacturing Issue Resolution', 'Manufacturing Issue Resolution', 'Operations', 80, 'High', true),
('RESP-MF-023', 'QC Testing Timeliness', 'QC Testing Timeliness', 'Operations', 80, 'High', true),
('RESP-MF-024', 'Quality System Effectiveness', 'Quality System Effectiveness', 'Quality', 80, 'High', true),
('RESP-MF-025', 'Inspection Readiness & Success', 'Inspection Readiness & Success', 'Operations', 80, 'High', true),
('RESP-MF-026', 'Quality Risk Management', 'Quality Risk Management', 'Quality', 80, 'High', true),
('RESP-MF-027', 'Manufacturing Planning Accuracy', 'Manufacturing Planning Accuracy', 'Operations', 80, 'High', true),
('RESP-MF-028', 'Supply Chain Reliability', 'Supply Chain Reliability', 'Operations', 80, 'High', true),
('RESP-MF-029', 'Inventory Optimization', 'Inventory Optimization', 'Operations', 80, 'High', true),
('RESP-MF-030', 'CMC Regulatory Approval', 'CMC Regulatory Approval', 'Operations', 80, 'High', true),
('RESP-MF-031', 'Facility Registration Compliance', 'Facility Registration Compliance', 'Compliance', 80, 'High', true),
('RESP-MF-032', 'Post-Approval Change Success', 'Post-Approval Change Success', 'Operations', 80, 'High', true);

COMMIT;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT
    '✅ RESPONSIBILITIES SEEDED!' as status,
    COUNT(*) as total_responsibilities,
    COUNT(DISTINCT category) as categories,
    COUNT(DISTINCT complexity_level) as complexity_levels
FROM org_responsibilities;

-- Breakdown by function (using ID prefix)
SELECT
    CASE
        WHEN unique_id LIKE 'RESP-MA-%' THEN 'Medical Affairs'
        WHEN unique_id LIKE 'RESP-RA-%' THEN 'Regulatory Affairs'
        WHEN unique_id LIKE 'RESP-CD-%' THEN 'Clinical Development'
        WHEN unique_id LIKE 'RESP-SV-%' THEN 'Safety & Pharmacovigilance'
        WHEN unique_id LIKE 'RESP-MA-ACC-%' THEN 'Market Access & HEOR'
        WHEN unique_id LIKE 'RESP-CM-%' THEN 'Commercial Excellence'
        WHEN unique_id LIKE 'RESP-MF-%' THEN 'Manufacturing & CMC'
        ELSE 'Other'
    END as function,
    category,
    complexity_level,
    COUNT(*) as count
FROM org_responsibilities
GROUP BY ROLLUP(function, category, complexity_level)
ORDER BY function, category, complexity_level;

COMMIT;

-- ============================================================================
-- END OF SCRIPT
-- ============================================================================
