-- ============================================================================
-- AgentOS Responsibilities Seeding - SCHEMA CORRECTED
-- ============================================================================
-- Total responsibilities: 278
-- Schema: name, description, category (matching deployed schema)
-- ============================================================================

BEGIN;

INSERT INTO org_responsibilities (name, description, category, is_active) VALUES

('Enterprise Medical Strategy & Vision', 'Own and execute enterprise-wide medical strategy across all therapeutic areas, geographies, and stakeholders. Set medical vision, priorities, and resource allocation at highest level.', 'Leadership', true),
('Regional/Global Medical Portfolio Leadership', 'Lead medical affairs for regional/global portfolio including budget ownership, team leadership across multiple functions, and strategic objective delivery.', 'Leadership', true),
('Medical Function/TA Leadership', 'Direct leadership of medical affairs function or therapeutic area including team management, budget oversight, and delivery of strategic medical initiatives.', 'Leadership', true),
('Medical Governance Framework Ownership', 'Establish, maintain, and enforce medical governance frameworks, compliance programs, quality standards, and audit processes across medical affairs.', 'Compliance', true),
('KOL Relationship Portfolio Management', 'Build, maintain, and deepen relationships with assigned portfolio of key opinion leaders and thought leaders. Serve as primary scientific liaison.', 'Operations', true),
('Territory Scientific Coverage', 'Ensure comprehensive scientific coverage of assigned geographic territory or accounts. Execute territory plan with strategic HCP prioritization.', 'Operations', true),
('Clinical Insight Collection & Intelligence', 'Gather, analyze, and report high-quality clinical insights, competitive intelligence, and market trends from field interactions to inform medical and commercial strategy.', 'Operations', true),
('Clinical Trial Site Support & Recruitment', 'Support clinical trial site identification, feasibility assessment, and investigator engagement. Facilitate enrollment and serve as medical liaison to sites.', 'Operations', true),
('Congress & Scientific Meeting Coverage', 'Execute congress strategy including booth coverage, symposia support, KOL meetings, competitive intelligence, and abstract review at assigned congresses.', 'Operations', true),
('Field Medical Team Performance', 'Lead, coach, and develop field medical team to achieve performance objectives. Manage territory assignments, coaching, and capability development.', 'Operations', true),
('Regulatory Document Preparation', 'Write and review regulatory documents (CSRs, IBs, briefing documents, submissions) to regulatory standards with accuracy and timeliness.', 'Operations', true),
('Scientific Manuscript Development', 'Develop peer-reviewed manuscripts for journal publication including literature review, drafting, author coordination, and revision management.', 'Operations', true),
('Congress Materials Creation', 'Create congress abstracts, posters, and presentations to scientific standards. Manage submission process and presentation logistics.', 'Operations', true),
('Publication Plan Execution', 'Execute strategic publication plan including timeline management, vendor coordination, author engagement, and budget management.', 'Operations', true),
('Scientific Communications Content', 'Develop scientific communication materials (slide decks, platforms, messaging) for internal and external audiences aligned with medical strategy.', 'Communication', true),
('Medical Inquiry Response Quality', 'Respond to medical inquiries from HCPs and stakeholders with accurate, balanced, compliant information within SLA timelines.', 'Quality', true),
('Medical Information Content Management', 'Build, maintain, and update medical information reference library including standard responses, monographs, and FAQs.', 'Operations', true),
('Adverse Event Surveillance & Reporting', 'Identify, document, and report adverse events per regulatory requirements. Ensure pharmacovigilance compliance.', 'Communication', true),
('Medical Information Operations Management', 'Manage medical information operations including metrics, quality, vendor oversight, process optimization, and team performance.', 'Operations', true),
('Medical Education Strategy Development', 'Develop and execute medical education strategy including needs assessment, program portfolio, evaluation frameworks, and budget management.', 'Leadership', true),
('Internal Commercial Team Training', 'Design and deliver medical training programs for sales, marketing, and market access teams. Ensure disease/product knowledge and message accuracy.', 'Education', true),
('Digital Medical Content Development', 'Create digital medical education content including e-learning, webinars, virtual events, and mobile applications.', 'Operations', true),
('HCP Education Program Delivery', 'Plan and execute external HCP education programs including speaker programs, advisory boards, symposia, and grants.', 'Education', true),
('Health Economic Model Development', 'Build, validate, and maintain health economic models (CEA, BIA, CUA) to demonstrate product value for pricing and reimbursement.', 'Operations', true),
('Real-World Evidence Study Execution', 'Design and execute RWE studies including protocol development, data collection, analysis, and publication.', 'Operations', true),
('Outcomes Research & PRO Assessment', 'Measure patient-reported outcomes, quality of life, and treatment satisfaction in real-world settings. Analyze and report findings.', 'Operations', true),
('Value Evidence Communication', 'Generate and communicate value evidence to payers, HTA bodies, and formulary committees to support access decisions.', 'Communication', true),
('Clinical Site Relationship Management', 'Serve as primary liaison between medical affairs and clinical sites. Support site selection, training, and relationship management.', 'Operations', true),
('Clinical Data Analysis & Insights', 'Analyze clinical trial data, identify trends, and generate insights to support medical strategy and evidence generation.', 'Operations', true),
('Medical Compliance Monitoring', 'Monitor medical affairs activities for regulatory compliance, conduct audits, identify issues, and implement remediation.', 'Compliance', true),
('Promotional Material Review & MLR', 'Review promotional materials and medical communications for accuracy, balance, and compliance. Manage MLR process.', 'Operations', true),
('Quality Management System Maintenance', 'Maintain quality management system for medical affairs including SOPs, training, document control, and continuous improvement.', 'Quality', true),
('Scientific Thought Leadership', 'Establish and maintain scientific leadership in therapeutic area through KOL engagement, advisory boards, and strategic scientific initiatives.', 'Leadership', true),
('Cross-Functional Medical Input', 'Provide senior medical input to commercial, regulatory, market access, and R&D decisions. Ensure medical perspective in strategic discussions.', 'Operations', true),
('Medical Document Repository Management', 'Organize, maintain, and ensure accessibility of medical documents, literature, and reference materials per document management policies.', 'Operations', true),
('Literature Monitoring & Alerting', 'Conduct systematic literature monitoring for assigned therapeutic areas. Identify and alert medical team to relevant publications and safety signals.', 'Operations', true),
('CRM Data Quality Assurance', 'Enter, validate, and maintain medical affairs activity data in CRM. Ensure data quality, completeness, and accurate reporting.', 'Quality', true),
('Standard Report Production', 'Generate standard medical affairs reports (activity, metrics, KOLs) on scheduled basis. Ensure accuracy and timely delivery.', 'Operations', true),
('Meeting & Event Coordination', 'Coordinate logistics for medical meetings, advisory boards, and events including venue, materials, travel, expenses, and compliance documentation.', 'Operations', true),
('Strategic Planning & Roadmap Development', 'Develop strategic plans and roadmaps for medical affairs initiatives. Set priorities, define objectives, and allocate resources.', 'Strategic', true),
('Budget Ownership & Financial Performance', 'Own budget for assigned area including forecasting, tracking, and optimizing spend. Ensure financial targets met and ROI maximized.', 'Financial', true),
('Team Development & Talent Management', 'Develop team capabilities, manage performance, succession planning, and talent acquisition. Build high-performing teams.', 'Operations', true),
('Process Improvement & Innovation Leadership', 'Lead continuous improvement initiatives, drive innovation, and implement new processes/technologies to enhance medical affairs effectiveness.', 'Leadership', true),
('Executive Stakeholder Management', 'Manage relationships with C-suite and senior executives. Provide updates, seek guidance, and influence strategic decisions.', 'Operations', true),
('Cross-Functional Partnership Management', 'Build and maintain productive partnerships with commercial, regulatory, market access, and R&D functions. Ensure alignment and collaboration.', 'Operations', true),
('Internal Communication & Change Leadership', 'Communicate organizational changes, strategic direction, and important updates to team. Lead change initiatives with clear messaging.', 'Leadership', true),
('Documentation & Record Management', 'Ensure accurate documentation of medical affairs activities per compliance requirements. Maintain audit-ready records.', 'Operations', true),
('KPI Achievement & Performance Delivery', 'Achieve or exceed assigned key performance indicators. Monitor performance, identify issues, and implement corrective actions.', 'Operations', true),
('Quality Standards & Compliance Adherence', 'Maintain high quality standards in all work. Ensure compliance with regulations, SOPs, and company policies.', 'Compliance', true),
('Metrics Tracking & Reporting', 'Track relevant metrics for assigned activities and report to stakeholders. Provide insights and recommendations based on data.', 'Communication', true),
('Therapeutic Area Expertise Maintenance', 'Maintain deep, current knowledge of assigned therapeutic areas including disease, treatments, guidelines, and competitive landscape.', 'Operations', true),
('Regulatory & Compliance Knowledge Currency', 'Stay current on pharmaceutical regulations, industry codes, and compliance requirements. Apply knowledge to medical affairs activities.', 'Compliance', true),
('Continuous Learning & Professional Development', 'Engage in continuous learning, skill development, and professional growth. Stay current with industry trends and best practices.', 'Operations', true),
('SOP Adherence & Process Compliance', 'Follow all standard operating procedures and established processes. Identify process gaps and recommend improvements.', 'Compliance', true),
('System & Technology Utilization', 'Effectively use medical affairs systems and technology platforms. Maintain data quality and system hygiene.', 'Operations', true),
('Resource Optimization & Efficiency', 'Optimize use of time, budget, and resources. Identify efficiencies and eliminate waste. Maximize productivity.', 'Operations', true),
('Team Collaboration & Support', 'Actively collaborate with team members, share knowledge, and support team objectives. Contribute to positive team culture.', 'Operations', true),
('Knowledge Sharing & Best Practice Dissemination', 'Share knowledge, insights, and best practices with team and broader organization. Contribute to organizational learning.', 'Operations', true),
('Ethical Conduct & Professional Integrity', 'Maintain highest ethical standards in all interactions and decisions. Act with integrity, honesty, and transparency.', 'Operations', true),
('Patient Focus & Scientific Rigor', 'Maintain patient-centric perspective in all medical affairs activities. Ensure scientific rigor and evidence-based approach.', 'Operations', true),
('Global Regulatory Strategy Ownership', 'Own and execute comprehensive global regulatory strategy across all products, therapeutic areas, and markets with full accountability for approvals and compliance.', 'Leadership', true),
('Regional Regulatory Leadership & P&L', 'Lead regional regulatory function with P&L accountability, team management, and responsibility for achieving submission and approval milestones.', 'Leadership', true),
('Therapeutic Area Regulatory Leadership', 'Direct all regulatory activities for assigned therapeutic area including strategy, submissions, agency interactions, and team leadership.', 'Leadership', true),
('Regulatory Project Delivery', 'Deliver regulatory projects on time, on budget, with high quality including submissions, approvals, and lifecycle management.', 'Operations', true),
('IND/CTA Submission Excellence', 'Prepare and submit high-quality IND/CTA applications that enable clinical trial initiation without delays or deficiencies.', 'Operations', true),
('NDA/BLA Approval Achievement', 'Deliver approvable NDA/BLA submissions with comprehensive data packages that address all review issues and achieve first-cycle approval.', 'Operations', true),
('MAA/EU Approval Success', 'Achieve Marketing Authorization in EU via Centralised, Decentralised, or Mutual Recognition procedures with positive CHMP opinion.', 'Operations', true),
('Global Registration Execution', 'Execute global registration strategy across priority markets achieving approvals per commercial timelines and investment case.', 'Operations', true),
('Post-Approval Change Management', 'Manage all post-approval changes ensuring regulatory compliance, minimal business disruption, and maintenance of marketing authorizations.', 'Operations', true),
('Orphan & Pediatric Program Delivery', 'Secure orphan designations and complete pediatric programs per approved PIPs/PSPs achieving regulatory incentives and compliance.', 'Operations', true),
('Expedited Pathway Success', 'Successfully navigate expedited pathways achieving designation and approval via accelerated timelines while maintaining data quality.', 'Operations', true),
('CMC Regulatory Package Excellence', 'Deliver comprehensive, high-quality Module 3 (CMC) regulatory packages that support approval without manufacturing-related deficiencies.', 'Operations', true),
('Facility Registration & Inspection Readiness', 'Maintain all facility registrations, ensure inspection readiness, and achieve successful GMP inspections with zero critical observations.', 'Operations', true),
('Pharmaceutical Development Justification', 'Provide robust pharmaceutical development justification and specification rationale that withstands regulatory scrutiny.', 'Operations', true),
('CMC Lifecycle Compliance', 'Maintain CMC compliance throughout product lifecycle managing changes, comparability, and quality variations with regulatory approval.', 'Compliance', true),
('Biologics Regulatory Compliance', 'Ensure regulatory compliance for biologics, biosimilars, and advanced therapies meeting specialized requirements and maintaining approvals.', 'Compliance', true),
('Approved Labeling Achievement', 'Achieve approved product labeling that accurately reflects product benefits/risks and enables optimal commercial positioning.', 'Operations', true),
('Labeling Negotiation Success', 'Successfully negotiate product labeling with agencies defending proposed language and achieving favorable outcomes on key issues.', 'Operations', true),
('Global Label Harmonization', 'Maintain harmonized global labeling across markets while meeting regional requirements and ensuring consistent safety messaging.', 'Operations', true),
('Safety Label Update Compliance', 'Ensure timely and compliant implementation of safety labeling updates in response to new safety data across all markets.', 'Compliance', true),
('Pre-Submission Meeting Success', 'Achieve successful pre-submission meetings and scientific advice obtaining regulatory alignment on critical development and submission issues.', 'Operations', true),
('Agency Query Resolution Excellence', 'Resolve all agency queries, information requests, and deficiencies with high-quality responses that address reviewer concerns and support approval.', 'Operations', true),
('Advisory Committee Positive Outcome', 'Achieve positive Advisory Committee vote through comprehensive preparation, compelling presentation, and effective committee engagement.', 'Operations', true),
('Inspection & Audit Excellence', 'Achieve successful regulatory inspections with zero critical observations and timely resolution of any non-critical findings.', 'Operations', true),
('Regulatory Intelligence Delivery', 'Deliver actionable regulatory intelligence that informs strategic decisions, anticipates regulatory changes, and provides competitive advantage.', 'Operations', true),
('Regulatory Compliance Assurance', 'Maintain 100% regulatory compliance across all products and markets including commitments, reporting, and ongoing obligations.', 'Compliance', true),
('Regulatory Policy Contribution', 'Actively contribute to regulatory policy development through industry associations, agency interactions, and policy advocacy.', 'Operations', true),
('Regulatory Training Excellence', 'Deliver comprehensive regulatory training ensuring team competency, compliance knowledge, and continuous learning.', 'Education', true),
('Product Lifecycle Optimization', 'Optimize product lifecycle through strategic regulatory planning including new indications, formulations, and lifecycle extensions.', 'Operations', true),
('Post-Approval Commitment Fulfillment', 'Complete all post-approval commitments and studies per agreed timelines maintaining compliance and avoiding penalties.', 'Operations', true),
('Regulatory Maintenance Excellence', 'Maintain all marketing authorizations through timely submissions, renewals, and ongoing compliance activities.', 'Operations', true),
('Risk Management Plan Implementation', 'Develop and implement comprehensive Risk Management Plans and REMS ensuring patient safety and regulatory compliance.', 'Operations', true),
('Safety Reporting Compliance', 'Ensure 100% compliance with all regulatory safety reporting requirements including expedited and aggregate reports.', 'Compliance', true),
('Benefit-Risk Documentation', 'Document comprehensive benefit-risk assessments that support regulatory decisions and demonstrate favorable benefit-risk profile.', 'Operations', true),
('Regulatory Crisis Resolution', 'Successfully resolve regulatory crises minimizing patient risk, business impact, and regulatory consequences through rapid, coordinated response.', 'Operations', true),
('Strategic Regulatory Decision-Making', 'Make strategic regulatory decisions that balance speed, risk, cost, and scientific integrity to achieve business objectives.', 'Strategic', true),
('Cross-Functional Regulatory Guidance', 'Provide expert regulatory guidance to cross-functional teams ensuring regulatory compliance and strategic alignment across development.', 'Operations', true),
('Regulatory Resource Optimization', 'Optimize regulatory resources including budget, staff, and external consultants to maximize efficiency and value.', 'Operations', true),
('Regulatory Expertise Maintenance', 'Maintain deep regulatory expertise through continuous learning, guideline monitoring, and professional development.', 'Operations', true),
('Regulatory Document Quality', 'Ensure all regulatory documents meet highest quality standards with scientific rigor, accuracy, and regulatory compliance.', 'Quality', true),
('Clinical-Regulatory Alignment', 'Ensure clinical development programs align with regulatory requirements and support approvable submissions.', 'Operations', true),
('Regulatory Data Integrity', 'Ensure integrity, accuracy, and traceability of all regulatory data and information in submissions and communications.', 'Operations', true),
('Agency Relationship Excellence', 'Build and maintain positive, professional relationships with health authorities based on transparency, trust, and mutual respect.', 'Operations', true),
('Regulatory Communication Impact', 'Deliver impactful regulatory communications to internal and external stakeholders that drive understanding and action.', 'Communication', true),
('Global Regulatory Collaboration', 'Foster effective collaboration across global regulatory teams ensuring knowledge sharing, alignment, and efficiency.', 'Operations', true),
('Regulatory Advisory Excellence', 'Provide expert regulatory advice that adds strategic value and enables informed decision-making across the organization.', 'Operations', true),
('Regulatory Systems Proficiency', 'Maintain proficiency in regulatory systems ensuring accurate, efficient use and contributing to system optimization.', 'Operations', true),
('Regulatory Quality Assurance', 'Execute rigorous quality assurance for all regulatory activities ensuring compliance with internal and external standards.', 'Quality', true),
('Regulatory Process Excellence', 'Execute regulatory processes with excellence identifying and implementing continuous improvements for efficiency and quality.', 'Operations', true),
('Regulatory Timeline Achievement', 'Achieve regulatory milestones and submission timelines through effective planning, coordination, and execution.', 'Operations', true),
('Clinical Development Strategy Execution', 'Own and execute clinical development strategy achieving development milestones, regulatory approvals, and budget targets.', 'Leadership', true),
('Clinical Program Delivery', 'Deliver clinical programs from Phase I through approval achieving quality, timeline, and budget objectives.', 'Operations', true),
('Functional Leadership & Team Management', 'Lead clinical functional area (operations, data, biostatistics) with team performance and budget accountability.', 'Leadership', true),
('Clinical Trial Success Delivery', 'Deliver successful clinical trials meeting enrollment, timeline, quality, and data objectives.', 'Operations', true),
('Protocol Quality & Regulatory Acceptability', 'Deliver high-quality protocols that meet scientific, regulatory, and operational standards.', 'Quality', true),
('Study Design Scientific Rigor', 'Ensure scientific rigor of study designs enabling definitive conclusions and regulatory approval.', 'Operations', true),
('Special Population Study Success', 'Successfully conduct special population studies meeting enrollment, safety, and data objectives.', 'Operations', true),
('Biomarker Strategy Implementation', 'Successfully implement biomarker strategies including patient selection, companion diagnostic development, and regulatory approval.', 'Leadership', true),
('Adaptive Trial Execution Excellence', 'Execute adaptive trials maintaining integrity while implementing protocol modifications based on interim data.', 'Operations', true),
('Trial Operational Excellence', 'Achieve operational excellence in trial execution including timeline, quality, budget, and site performance.', 'Operations', true),
('Site Network Performance', 'Build and maintain high-performing site network achieving enrollment, quality, and retention targets.', 'Operations', true),
('Site Start-Up Efficiency', 'Achieve efficient site start-up meeting activation timelines and minimizing enrollment delays.', 'Operations', true),
('Protocol Compliance & Data Quality', 'Ensure protocol compliance and data quality through effective monitoring and issue resolution.', 'Compliance', true),
('Enrollment Target Achievement', 'Achieve enrollment targets within timeline through effective recruitment strategies and site management.', 'Operations', true),
('Clinical Supply Availability', 'Ensure continuous clinical supply availability with zero patient disruptions due to stockouts.', 'Operations', true),
('Clinical Data Quality & Integrity', 'Ensure clinical data quality and integrity meeting regulatory standards and supporting approvable submissions.', 'Quality', true),
('EDC System Performance', 'Deliver EDC systems that support efficient data collection with minimal user issues and high data quality.', 'Operations', true),
('Data Cleaning Excellence', 'Achieve data cleaning excellence through efficient query management and timely resolution.', 'Operations', true),
('Database Lock Timeliness', 'Achieve database lock within target timelines enabling analysis and submission milestones.', 'Operations', true),
('Statistical Strategy Quality', 'Deliver statistical strategies that optimize development efficiency and enable definitive conclusions.', 'Leadership', true),
('SAP Quality & Completeness', 'Deliver comprehensive SAPs that enable complete analysis and address regulatory requirements.', 'Quality', true),
('Analysis Quality & Timeliness', 'Deliver high-quality statistical analyses within timeline supporting regulatory submissions and decisions.', 'Quality', true),
('DMC Support Excellence', 'Provide excellent DMC support with timely, accurate interim analyses and safety reports.', 'Operations', true),
('Clinical Quality System Management', 'Maintain effective clinical quality system ensuring GCP compliance and continuous improvement.', 'Quality', true),
('Audit Quality & Value', 'Conduct high-quality audits that identify risks, ensure compliance, and add value.', 'Quality', true),
('GCP Compliance Assurance', 'Ensure 100% GCP compliance across all trials through monitoring, training, and oversight.', 'Compliance', true),
('Inspection Success', 'Achieve successful inspections with zero critical findings and timely resolution of observations.', 'Operations', true),
('Clinical Safety Management', 'Ensure patient safety through robust safety monitoring, signal detection, and risk mitigation.', 'Safety', true),
('Safety Committee Effectiveness', 'Ensure Safety Review Committee effectiveness with timely meetings, quality assessments, and implemented recommendations.', 'Safety', true),
('Safety Report Quality', 'Deliver high-quality safety reports meeting regulatory standards and supporting approval decisions.', 'Quality', true),
('CSR Quality & Regulatory Acceptance', 'Deliver CSRs meeting ICH E3 standards that support regulatory submissions and approvals.', 'Quality', true),
('Development Plan Documentation Quality', 'Deliver development plan documentation that communicates strategy and supports regulatory interactions.', 'Quality', true),
('IB Currency & Compliance', 'Maintain current investigator brochures meeting regulatory update requirements and supporting trial conduct.', 'Compliance', true),
('Medical Monitoring Quality', 'Provide high-quality medical monitoring ensuring patient safety and appropriate medical decisions.', 'Quality', true),
('PK/PD Analysis Quality', 'Deliver high-quality PK/PD analyses informing dose selection and development decisions.', 'Quality', true),
('Strategic Development Decision-Making', 'Strategic Development Decision-Making', 'Strategic', true),
('Cross-Functional Clinical Coordination', 'Cross-Functional Clinical Coordination', 'Operations', true),
('Clinical Budget Performance', 'Clinical Budget Performance', 'Financial', true),
('Clinical & TA Expertise Maintenance', 'Clinical & TA Expertise Maintenance', 'Operations', true),
('Regulatory & GCP Compliance', 'Regulatory & GCP Compliance', 'Compliance', true),
('Data Integrity & Quality', 'Data Integrity & Quality', 'Quality', true),
('Investigator & Site Relationship Excellence', 'Investigator & Site Relationship Excellence', 'Operations', true),
('Clinical Communication Impact', 'Clinical Communication Impact', 'Communication', true),
('Clinical Team Collaboration', 'Clinical Team Collaboration', 'Operations', true),
('Vendor & CRO Performance', 'Vendor & CRO Performance', 'Operations', true),
('Clinical Project Delivery', 'Clinical Project Delivery', 'Operations', true),
('Clinical Quality Excellence', 'Clinical Quality Excellence', 'Quality', true),
('Clinical Documentation Standards', 'Clinical Documentation Standards', 'Operations', true),
('Clinical Timeline Achievement', 'Clinical Timeline Achievement', 'Operations', true),
('Continuous Improvement & Innovation', 'Continuous Improvement & Innovation', 'Operations', true),
('Global PV Strategy Execution', 'Global PV Strategy Execution', 'Leadership', true),
('PV Operations Excellence', 'PV Operations Excellence', 'Operations', true),
('Medical Safety Leadership', 'Medical Safety Leadership', 'Leadership', true),
('Case Processing Quality & Timeliness', 'Case Processing Quality & Timeliness', 'Quality', true),
('SAE Assessment Accuracy', 'SAE Assessment Accuracy', 'Operations', true),
('Expedited Reporting Compliance', 'Expedited Reporting Compliance', 'Compliance', true),
('Safety Database Quality', 'Safety Database Quality', 'Quality', true),
('Signal Detection Effectiveness', 'Signal Detection Effectiveness', 'Operations', true),
('Signal Assessment Quality', 'Signal Assessment Quality', 'Quality', true),
('RMP/REMS Implementation Success', 'RMP/REMS Implementation Success', 'Operations', true),
('Benefit-Risk Balance Maintenance', 'Benefit-Risk Balance Maintenance', 'Operations', true),
('Safety Committee Effectiveness', 'Safety Committee Effectiveness', 'Safety', true),
('PSUR/PBRER Quality & Timeliness', 'PSUR/PBRER Quality & Timeliness', 'Quality', true),
('DSUR Regulatory Compliance', 'DSUR Regulatory Compliance', 'Compliance', true),
('Safety Data Analysis Rigor', 'Safety Data Analysis Rigor', 'Safety', true),
('Aggregate Report Quality', 'Aggregate Report Quality', 'Quality', true),
('PV Regulatory Compliance Achievement', 'PV Regulatory Compliance Achievement', 'Compliance', true),
('Safety Submission Quality', 'Safety Submission Quality', 'Quality', true),
('PSMF Currency & Compliance', 'PSMF Currency & Compliance', 'Compliance', true),
('Inspection Success Rate', 'Inspection Success Rate', 'Operations', true),
('Medical Safety Surveillance Quality', 'Medical Safety Surveillance Quality', 'Quality', true),
('Clinical Trial Safety Oversight', 'Clinical Trial Safety Oversight', 'Safety', true),
('Product Safety Profile Accuracy', 'Product Safety Profile Accuracy', 'Safety', true),
('Literature Surveillance Completeness', 'Literature Surveillance Completeness', 'Operations', true),
('Medication Error Management', 'Medication Error Management', 'Operations', true),
('PASS/PAES Delivery', 'PASS/PAES Delivery', 'Operations', true),
('Vendor Safety Quality Oversight', 'Vendor Safety Quality Oversight', 'Quality', true),
('Safety Training & Competency', 'Safety Training & Competency', 'Safety', true),
('Market Access Strategy Execution', 'Market Access Strategy Execution', 'Leadership', true),
('Payer Engagement Success', 'Payer Engagement Success', 'Operations', true),
('HEOR Evidence Generation', 'HEOR Evidence Generation', 'Operations', true),
('Account Management Excellence', 'Account Management Excellence', 'Operations', true),
('Contract Negotiation Success', 'Contract Negotiation Success', 'Operations', true),
('Formulary Access Achievement', 'Formulary Access Achievement', 'Operations', true),
('Reimbursement Strategy Success', 'Reimbursement Strategy Success', 'Leadership', true),
('Value-Based Contract Implementation', 'Value-Based Contract Implementation', 'Operations', true),
('Economic Model Quality', 'Economic Model Quality', 'Quality', true),
('CEA Regulatory Acceptance', 'CEA Regulatory Acceptance', 'Operations', true),
('BIA Payer Acceptance', 'BIA Payer Acceptance', 'Operations', true),
('Pharmacoeconomic Model Validity', 'Pharmacoeconomic Model Validity', 'Operations', true),
('HTA Submission Success', 'HTA Submission Success', 'Operations', true),
('Model Validation Quality', 'Model Validation Quality', 'Quality', true),
('RWE Strategy Execution', 'RWE Strategy Execution', 'Leadership', true),
('Observational Study Success', 'Observational Study Success', 'Operations', true),
('PRO Validation & Utility', 'PRO Validation & Utility', 'Operations', true),
('RWD Analysis Quality', 'RWD Analysis Quality', 'Quality', true),
('CER Credibility', 'CER Credibility', 'Operations', true),
('Global Pricing Strategy Success', 'Global Pricing Strategy Success', 'Leadership', true),
('Value Proposition Impact', 'Value Proposition Impact', 'Operations', true),
('Value Dossier Quality', 'Value Dossier Quality', 'Quality', true),
('HEOR Communication Effectiveness', 'HEOR Communication Effectiveness', 'Communication', true),
('Evidence Gap Closure', 'Evidence Gap Closure', 'Operations', true),
('Policy Influence Impact', 'Policy Influence Impact', 'Operations', true),
('Coverage Policy Success', 'Coverage Policy Success', 'Operations', true),
('Patient Access Program Enrollment', 'Patient Access Program Enrollment', 'Operations', true),
('Market Access Analytics Insights', 'Market Access Analytics Insights', 'Operations', true),
('Payer Intelligence Quality', 'Payer Intelligence Quality', 'Quality', true),
('Access Monitoring & Optimization', 'Access Monitoring & Optimization', 'Operations', true),
('Commercial P&L Ownership', 'Commercial P&L Ownership', 'Operations', true),
('Commercial Strategy Execution', 'Commercial Strategy Execution', 'Leadership', true),
('Brand Portfolio Performance', 'Brand Portfolio Performance', 'Operations', true),
('Sales Force Performance', 'Sales Force Performance', 'Operations', true),
('Brand Strategy Success', 'Brand Strategy Success', 'Leadership', true),
('Launch Excellence', 'Launch Excellence', 'Operations', true),
('Campaign ROI Achievement', 'Campaign ROI Achievement', 'Operations', true),
('Promotional Strategy Impact', 'Promotional Strategy Impact', 'Leadership', true),
('Brand Growth & Share', 'Brand Growth & Share', 'Operations', true),
('Lifecycle Value Maximization', 'Lifecycle Value Maximization', 'Operations', true),
('Sales Force Productivity', 'Sales Force Productivity', 'Operations', true),
('Territory Optimization', 'Territory Optimization', 'Operations', true),
('Sales Insights Actionability', 'Sales Insights Actionability', 'Operations', true),
('Sales Readiness', 'Sales Readiness', 'Operations', true),
('Incentive Plan Effectiveness', 'Incentive Plan Effectiveness', 'Operations', true),
('HCP Engagement Quality', 'HCP Engagement Quality', 'Quality', true),
('Key Account Growth', 'Key Account Growth', 'Operations', true),
('Specialty Sales Excellence', 'Specialty Sales Excellence', 'Operations', true),
('Territory Quota Achievement', 'Territory Quota Achievement', 'Operations', true),
('Customer Segmentation Precision', 'Customer Segmentation Precision', 'Operations', true),
('Omnichannel Strategy Success', 'Omnichannel Strategy Success', 'Leadership', true),
('Digital Marketing ROI', 'Digital Marketing ROI', 'Operations', true),
('Speaker Program Quality', 'Speaker Program Quality', 'Quality', true),
('Commercial Analytics Accuracy', 'Commercial Analytics Accuracy', 'Operations', true),
('Market Research Quality', 'Market Research Quality', 'Quality', true),
('Competitive Intelligence Impact', 'Competitive Intelligence Impact', 'Operations', true),
('Commercial Operations Excellence', 'Commercial Operations Excellence', 'Operations', true),
('CRM Data Quality', 'CRM Data Quality', 'Quality', true),
('Manufacturing Operations Excellence', 'Manufacturing Operations Excellence', 'Operations', true),
('CMC Development Strategy Success', 'CMC Development Strategy Success', 'Leadership', true),
('Site Operations Performance', 'Site Operations Performance', 'Operations', true),
('Process Development Excellence', 'Process Development Excellence', 'Operations', true),
('Chemical Synthesis Optimization', 'Chemical Synthesis Optimization', 'Operations', true),
('Biologics Process Performance', 'Biologics Process Performance', 'Operations', true),
('Formulation Success', 'Formulation Success', 'Operations', true),
('Process Robustness', 'Process Robustness', 'Operations', true),
('Continuous Manufacturing Implementation', 'Continuous Manufacturing Implementation', 'Operations', true),
('Analytical Method Validation', 'Analytical Method Validation', 'Operations', true),
('Method Transfer Success', 'Method Transfer Success', 'Operations', true),
('Stability Program Compliance', 'Stability Program Compliance', 'Compliance', true),
('Characterization Completeness', 'Characterization Completeness', 'Operations', true),
('Scale-Up Success Rate', 'Scale-Up Success Rate', 'Operations', true),
('Technology Transfer Excellence', 'Technology Transfer Excellence', 'Operations', true),
('Manufacturing Validation Success', 'Manufacturing Validation Success', 'Operations', true),
('Comparability Demonstration', 'Comparability Demonstration', 'Operations', true),
('GMP Compliance Achievement', 'GMP Compliance Achievement', 'Compliance', true),
('Batch Success Rate', 'Batch Success Rate', 'Operations', true),
('Equipment Performance', 'Equipment Performance', 'Operations', true),
('Batch Release Timeliness', 'Batch Release Timeliness', 'Operations', true),
('Manufacturing Issue Resolution', 'Manufacturing Issue Resolution', 'Operations', true),
('QC Testing Timeliness', 'QC Testing Timeliness', 'Operations', true),
('Quality System Effectiveness', 'Quality System Effectiveness', 'Quality', true),
('Inspection Readiness & Success', 'Inspection Readiness & Success', 'Operations', true),
('Quality Risk Management', 'Quality Risk Management', 'Quality', true),
('Manufacturing Planning Accuracy', 'Manufacturing Planning Accuracy', 'Operations', true),
('Supply Chain Reliability', 'Supply Chain Reliability', 'Operations', true),
('Inventory Optimization', 'Inventory Optimization', 'Operations', true),
('CMC Regulatory Approval', 'CMC Regulatory Approval', 'Operations', true),
('Facility Registration Compliance', 'Facility Registration Compliance', 'Compliance', true),
('Post-Approval Change Success', 'Post-Approval Change Success', 'Operations', true);

COMMIT;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT
    '✅ RESPONSIBILITIES SEEDED!' as status,
    COUNT(*) as total,
    COUNT(DISTINCT category) as categories
FROM org_responsibilities;

SELECT category, COUNT(*) as count
FROM org_responsibilities
GROUP BY category
ORDER BY count DESC;