apiVersion: v1
kind: ServiceAccount
metadata:
  name: ask-expert
  namespace: vital-production
  labels:
    app: ask-expert
    component: ask-expert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ask-expert
  namespace: vital-production
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ask-expert
  namespace: vital-production
subjects:
- kind: ServiceAccount
  name: ask-expert
  namespace: vital-production
roleRef:
  kind: Role
  name: ask-expert
  apiGroup: rbac.authorization.k8s.io
