-- Import Capabilities (simplified - without UUID dependencies)
INSERT INTO capabilities (
  capability_key,
  name,
  description,
  category,
  domain,
  complexity_level,
  status,
  stage,
  vital_component,
  priority,
  maturity,
  is_new,
  panel_recommended,
  competencies,
  implementation_timeline
) VALUES
(
  'clinical-trial-design',
  'Clinical Trial Design',
  'Design and structure clinical trials for medical devices including protocol development, endpoint selection, and statistical planning',
  'clinical',
  'medical',
  'advanced',
  'active',
  'clinical_validation',
  'T_transformation_design',
  'critical_immediate',
  'level_4_leading',
  false,
  true,
  '{"methodology": {"approach": "evidence-based"}, "quality_metrics": {"accuracy_target": "95%", "compliance_requirements": ["ICH-GCP", "FDA 21 CFR Part 820", "ISO 14155"]}}'::jsonb,
  4
),
(
  'regulatory-submission',
  'Regulatory Submission Preparation',
  'Prepare comprehensive regulatory submissions including 510(k), PMA, CE-MDR technical documentation',
  'regulatory',
  'regulatory',
  'expert',
  'active',
  'regulatory_pathway',
  'A_acceleration_execution',
  'critical_immediate',
  'level_5_transformative',
  false,
  true,
  '{"methodology": {"approach": "systematic"}, "quality_metrics": {"accuracy_target": "98%", "compliance_requirements": ["FDA 21 CFR 807", "CE-MDR Annex II", "ISO 13485"]}}'::jsonb,
  8
),
(
  'health-economics',
  'Health Economic Analysis',
  'Conduct health economic evaluations, budget impact analyses, and cost-effectiveness studies for medical technologies',
  'commercial',
  'commercial',
  'advanced',
  'active',
  'reimbursement_strategy',
  'V_value_discovery',
  'near_term_90_days',
  'level_4_leading',
  false,
  true,
  '{"methodology": {"approach": "evidence-based"}, "quality_metrics": {"accuracy_target": "92%", "compliance_requirements": ["ISPOR Guidelines", "NICE Methods Guide", "ICER Framework"]}}'::jsonb,
  6
),
(
  'quality-systems',
  'Quality Management Systems',
  'Develop and implement quality management systems compliant with ISO 13485 and FDA QSR',
  'quality',
  'technical',
  'advanced',
  'active',
  'regulatory_pathway',
  'T_transformation_design',
  'critical_immediate',
  'level_5_transformative',
  false,
  true,
  '{"methodology": {"approach": "systematic"}, "quality_metrics": {"accuracy_target": "96%", "compliance_requirements": ["ISO 13485", "FDA 21 CFR 820", "ISO 9001"]}}'::jsonb,
  5
),
(
  'statistical-analysis',
  'Clinical Statistical Analysis',
  'Perform statistical analyses for clinical studies including descriptive statistics, hypothesis testing, and survival analysis',
  'clinical',
  'medical',
  'advanced',
  'active',
  'clinical_validation',
  'I_intelligence_gathering',
  'critical_immediate',
  'level_4_leading',
  false,
  true,
  '{"methodology": {"approach": "statistical"}, "quality_metrics": {"accuracy_target": "97%", "compliance_requirements": ["ICH E9", "FDA Statistical Guidance", "EMA Statistical Guidelines"]}}'::jsonb,
  4
);
