-- Insert Prompts Only
INSERT INTO prompts (
  name,
  display_name,
  description,
  category,
  domain,
  system_prompt,
  user_prompt_template,
  complexity_level,
  estimated_tokens,
  model_requirements,
  input_schema,
  output_schema,
  success_criteria,
  validation_rules,
  prerequisite_prompts,
  related_capabilities,
  validation_status
) VALUES
(
  'clinical-trial-protocol-generator',
  'Clinical Trial Protocol Generator',
  'Generate comprehensive clinical trial protocols for medical devices with regulatory compliance',
  'medical',
  'medical',
  'You are an expert Clinical Research Protocol Developer. Generate comprehensive, regulatory-compliant clinical trial protocols for medical devices. Ensure all protocols meet FDA, CE-MDR, and ICH-GCP requirements. Include detailed study objectives, methodology, statistical analysis plans, and safety monitoring procedures. Always provide evidence-based recommendations with proper citations to current guidelines.',
  'Generate a clinical trial protocol for: {device_type}\n\nDevice Details:\n- Classification: {device_class}\n- Indication: {indication}\n- Primary Endpoint: {primary_endpoint}\n- Target Population: {population}\n- Regulatory Pathway: {pathway}\n\nRequirements:\n- Study Design: {study_design}\n- Sample Size: {sample_size}\n- Duration: {study_duration}\n- Special Considerations: {special_requirements}',
  'advanced',
  3500,
  '{"model": "gpt-4", "temperature": 0.3, "max_tokens": 4000}'::jsonb,
  '{"device_type": "string", "device_class": "enum", "indication": "string", "primary_endpoint": "string", "population": "string", "pathway": "enum", "study_design": "enum", "sample_size": "integer", "study_duration": "string", "special_requirements": "string"}'::jsonb,
  '{"protocol_title": "string", "protocol_synopsis": "string", "objectives": "array", "study_design": "object", "patient_population": "object", "endpoints": "object", "statistical_plan": "object", "safety_monitoring": "object", "regulatory_considerations": "object"}'::jsonb,
  '{"description": "Protocol passes regulatory review checklist", "metrics": ["Completeness score >95%", "Regulatory compliance verified", "Medical review approved"]}'::jsonb,
  '{"input_requirements": ["Device classification must be valid", "Primary endpoint must be clinically meaningful", "Sample size must be statistically justified"], "output_validation": ["Protocol must include all ICH-GCP required sections", "Statistical plan must be mathematically sound", "Safety monitoring plan must be comprehensive"]}'::jsonb,
  ARRAY['device-classification', 'risk-assessment'],
  ARRAY['clinical-trial-design', 'regulatory-compliance', 'statistical-analysis'],
  'active'
),
(
  'regulatory-submission-writer',
  'Regulatory Submission Writer',
  'Create comprehensive regulatory submission documents for FDA 510(k), PMA, and CE-MDR pathways',
  'regulatory',
  'regulatory',
  'You are an expert Regulatory Affairs Specialist with extensive experience in medical device submissions. Create comprehensive, compliant regulatory documents for FDA 510(k), PMA, CE-MDR, and other global pathways. Ensure all content meets current regulatory requirements and follows established templates. Always include proper predicate analysis, substantial equivalence arguments, and risk-benefit assessments.',
  'Create a regulatory submission document for:\n\nDevice Information:\n- Device Name: {device_name}\n- Classification: {device_class}\n- Intended Use: {intended_use}\n- Regulatory Pathway: {pathway}\n- Predicate Device: {predicate_device}',
  'expert',
  4000,
  '{"model": "gpt-4", "temperature": 0.2, "max_tokens": 4500}'::jsonb,
  '{"device_name": "string", "device_class": "enum", "intended_use": "string", "pathway": "enum", "predicate_device": "string", "submission_type": "enum", "special_controls": "string", "clinical_data_available": "boolean", "risk_class": "enum"}'::jsonb,
  '{"executive_summary": "string", "device_description": "object", "predicate_comparison": "object", "substantial_equivalence": "object", "risk_analysis": "object", "clinical_summary": "object", "labeling": "object"}'::jsonb,
  '{"description": "Submission meets regulatory acceptance criteria", "metrics": ["Regulatory completeness >98%", "Technical accuracy verified", "Compliance confirmed"]}'::jsonb,
  '{"input_requirements": ["Device classification must be accurate", "Predicate device must be legally marketed", "Intended use must be clearly defined"], "output_validation": ["Substantial equivalence argument must be sound", "Risk analysis must be comprehensive", "Clinical evidence must support claims"]}'::jsonb,
  ARRAY['predicate-analysis', 'clinical-evidence-summary'],
  ARRAY['regulatory-submission', 'device-classification', 'risk-assessment'],
  'active'
),
(
  'health-economic-evaluator',
  'Health Economic Evaluation Generator',
  'Conduct comprehensive health economic analyses and budget impact assessments for medical technologies',
  'commercial',
  'commercial',
  'You are an expert Health Economist specializing in medical device and digital health evaluations. Conduct comprehensive health economic analyses including cost-effectiveness, budget impact, and value assessments. Follow ISPOR guidelines and international HTA standards. Provide clear methodology, transparent assumptions, and actionable recommendations for payers and providers.',
  'Conduct a health economic evaluation for:\n\nTechnology Details:\n- Technology: {technology_name}\n- Indication: {indication}\n- Target Population: {population}\n- Comparator: {comparator}\n- Time Horizon: {time_horizon}',
  'advanced',
  3800,
  '{"model": "gpt-4", "temperature": 0.4, "max_tokens": 4000}'::jsonb,
  '{"technology_name": "string", "indication": "string", "population": "string", "comparator": "string", "time_horizon": "string", "perspective": "enum", "analysis_type": "enum", "cost_categories": "array", "outcomes": "array", "budget_constraint": "number"}'::jsonb,
  '{"research_question": "string", "model_structure": "object", "cost_analysis": "object", "outcome_analysis": "object", "cost_effectiveness": "object", "sensitivity_analysis": "object", "budget_impact": "object", "value_proposition": "object"}'::jsonb,
  '{"description": "Analysis meets HTA methodological standards", "metrics": ["Methodological rigor >90%", "Data quality verified", "Payer relevance confirmed"]}'::jsonb,
  '{"input_requirements": ["Technology must be clearly defined", "Comparator must be current standard of care", "Population must be well-characterized"], "output_validation": ["Model structure must be appropriate", "Costs must be comprehensive and accurate", "Outcomes must be clinically meaningful"]}'::jsonb,
  ARRAY['clinical-evidence-synthesis', 'cost-data-collection'],
  ARRAY['health-economics', 'statistical-analysis', 'market-analysis'],
  'active'
),
(
  'quality-system-designer',
  'Quality Management System Designer',
  'Design comprehensive quality management systems compliant with ISO 13485 and FDA QSR',
  'technical',
  'technical',
  'You are an expert Quality Systems Professional with deep knowledge of medical device quality standards. Design comprehensive quality management systems that comply with ISO 13485, FDA QSR, and other international standards. Ensure all processes are risk-based, efficient, and support regulatory compliance. Provide detailed procedures, forms, and implementation guidance.',
  'Design a quality management system for:\n\nOrganization Details:\n- Company Type: {company_type}\n- Device Types: {device_types}\n- Regulatory Markets: {markets}\n- Organization Size: {size}\n- Current QMS Status: {current_status}',
  'advanced',
  3900,
  '{"model": "gpt-4", "temperature": 0.3, "max_tokens": 4200}'::jsonb,
  '{"company_type": "enum", "device_types": "array", "markets": "array", "size": "enum", "current_status": "enum", "standards": "array", "certifications": "array", "risk_level": "enum", "timeline": "string", "special_requirements": "string"}'::jsonb,
  '{"gap_analysis": "object", "quality_manual": "object", "process_documentation": "object", "design_controls": "object", "risk_management": "object", "document_control": "object", "training_framework": "object", "audit_program": "object", "management_review": "object"}'::jsonb,
  '{"description": "QMS design meets certification requirements", "metrics": ["Standards compliance >95%", "Process effectiveness verified", "Audit readiness confirmed"]}'::jsonb,
  '{"input_requirements": ["Device types must be properly classified", "Regulatory markets must be specified", "Standards requirements must be clear"], "output_validation": ["All required processes must be documented", "Risk-based approach must be evident", "Procedures must be implementable"]}'::jsonb,
  ARRAY['risk-assessment', 'process-mapping'],
  ARRAY['quality-systems', 'risk-management', 'document-control'],
  'active'
),
(
  'clinical-data-analyzer',
  'Clinical Data Analysis Generator',
  'Perform comprehensive statistical analyses of clinical trial data with regulatory-compliant reporting',
  'medical',
  'medical',
  'You are an expert Clinical Biostatistician with extensive experience in medical device clinical trials. Perform comprehensive statistical analyses following ICH guidelines and regulatory requirements. Generate clear, accurate statistical reports with appropriate tables, figures, and interpretations. Ensure all analyses support regulatory submissions and clinical decision-making.',
  'Perform clinical data analysis for:\n\nStudy Details:\n- Study Type: {study_type}\n- Primary Endpoint: {primary_endpoint}\n- Secondary Endpoints: {secondary_endpoints}\n- Study Population: {population}\n- Sample Size: {sample_size}',
  'advanced',
  3700,
  '{"model": "gpt-4", "temperature": 0.3, "max_tokens": 4000}'::jsonb,
  '{"study_type": "enum", "primary_endpoint": "string", "secondary_endpoints": "array", "population": "string", "sample_size": "integer", "analysis_sets": "array", "methods": "array", "alpha": "number", "missing_data": "enum", "subgroups": "array"}'::jsonb,
  '{"analysis_plan": "object", "data_quality": "object", "baseline_characteristics": "object", "primary_analysis": "object", "secondary_analyses": "object", "safety_analysis": "object", "subgroup_analyses": "object", "conclusions": "object"}'::jsonb,
  '{"description": "Analysis meets regulatory statistical standards", "metrics": ["Statistical validity >95%", "Regulatory compliance verified", "Clinical interpretability confirmed"]}'::jsonb,
  '{"input_requirements": ["Primary endpoint must be pre-specified", "Statistical methods must be appropriate", "Sample size must be adequate"], "output_validation": ["All analyses must be statistically sound", "Results must be clearly interpreted", "Limitations must be acknowledged"]}'::jsonb,
  ARRAY['study-design-review', 'data-validation'],
  ARRAY['statistical-analysis', 'clinical-data-management', 'regulatory-statistics'],
  'active'
);
