# generated by datamodel-codegen:
#   filename:  conversation.json
#   timestamp: 2025-12-05T20:56:13+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Role(StrEnum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'
    tool = 'tool'


class Type(StrEnum):
    document = 'document'
    web = 'web'
    database = 'database'
    expert = 'expert'


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    type: Type
    title: str
    url: AnyUrl | None = None
    snippet: str
    relevanceScore: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    metadata: dict[str, Any] | None = None


class Status(StrEnum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    arguments: dict[str, Any]
    result: Any | None = None
    error: str | None = None
    status: Status


class ThinkingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: int
    thought: str
    action: str | None = None


class TokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    promptTokens: int
    completionTokens: int
    totalTokens: int


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    role: Role
    content: str
    citations: list[Citation] | None = None
    toolCalls: list[ToolCall] | None = None
    thinking: list[ThinkingItem] | None = None
    tokenUsage: TokenUsage | None = None
    createdAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    metadata: dict[str, Any] | None = None


class Mode(StrEnum):
    mode_1_instant = 'mode_1_instant'
    mode_2_standard = 'mode_2_standard'
    mode_3_deep_research = 'mode_3_deep_research'
    mode_4_autonomous = 'mode_4_autonomous'


class Conversation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    title: Annotated[str | None, Field(max_length=200)] = None
    agentId: UUID
    messages: list[Message]
    mode: Mode
    isActive: bool = True
    totalTokens: int = 0
    totalCostUsd: float = 0
    tenantId: Annotated[
        UUID, Field(description='Tenant identifier for multi-tenancy isolation')
    ]
    userId: Annotated[UUID, Field(description='User identifier')]
    createdAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    updatedAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    metadata: dict[str, Any] | None = None


class Model(RootModel[Conversation]):
    root: Conversation
