# generated by datamodel-codegen:
#   filename:  edge.json
#   timestamp: 2025-12-05T20:56:10+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Style(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stroke: str | None = None
    strokeWidth: float | None = None
    strokeDasharray: str | None = None


class Edge1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    source: Annotated[str, Field(min_length=1)]
    target: Annotated[str, Field(min_length=1)]
    sourceHandle: str | None = None
    targetHandle: str | None = None
    type: Literal['default'] = 'default'
    animated: bool | None = None
    label: str | None = None
    style: Style | None = None
    selected: bool | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    condition: str
    priority: Annotated[int, Field(ge=0)] = 0


class Edge2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    source: Annotated[str, Field(min_length=1)]
    target: Annotated[str, Field(min_length=1)]
    sourceHandle: str | None = None
    targetHandle: str | None = None
    type: Literal['conditional']
    animated: bool | None = None
    label: str | None = None
    style: Style | None = None
    selected: bool | None = None
    data: Data


class Edge3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    source: Annotated[str, Field(min_length=1)]
    target: Annotated[str, Field(min_length=1)]
    sourceHandle: str | None = None
    targetHandle: str | None = None
    type: Literal['animated']
    animated: Literal[True]
    label: str | None = None
    style: Style | None = None
    selected: bool | None = None


class Model(RootModel[Edge1 | Edge2 | Edge3]):
    root: Edge1 | Edge2 | Edge3
