# generated by datamodel-codegen:
#   filename:  expert_sync_response.json
#   timestamp: 2025-12-05T20:56:12+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Role(StrEnum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'
    tool = 'tool'


class Type(StrEnum):
    document = 'document'
    web = 'web'
    database = 'database'
    expert = 'expert'


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    type: Type
    title: str
    url: AnyUrl | None = None
    snippet: str
    relevanceScore: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    metadata: dict[str, Any] | None = None


class Status(StrEnum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    arguments: dict[str, Any]
    result: Any | None = None
    error: str | None = None
    status: Status


class ThinkingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: int
    thought: str
    action: str | None = None


class TokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    promptTokens: int
    completionTokens: int
    totalTokens: int


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    role: Role
    content: str
    citations: list[Citation] | None = None
    toolCalls: list[ToolCall] | None = None
    thinking: list[ThinkingItem] | None = None
    tokenUsage: TokenUsage | None = None
    createdAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    metadata: dict[str, Any] | None = None


class TotalTokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    promptTokens: int
    completionTokens: int
    totalTokens: int
    estimatedCostUsd: float


class ExpertSyncResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conversationId: UUID
    message: Message
    totalTokenUsage: TotalTokenUsage
    processingTimeMs: int
    model: str


class Model(RootModel[ExpertSyncResponse]):
    root: ExpertSyncResponse
