# generated by datamodel-codegen:
#   filename:  expert_request.json
#   timestamp: 2025-12-05T20:56:11+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Mode(StrEnum):
    mode_1_instant = 'mode_1_instant'
    mode_2_standard = 'mode_2_standard'
    mode_3_deep_research = 'mode_3_deep_research'
    mode_4_autonomous = 'mode_4_autonomous'


class Role(StrEnum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'
    tool = 'tool'


class Type(StrEnum):
    document = 'document'
    web = 'web'
    database = 'database'
    expert = 'expert'


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    type: Type
    title: str
    url: AnyUrl | None = None
    snippet: str
    relevanceScore: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    metadata: dict[str, Any] | None = None


class Status(StrEnum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    arguments: dict[str, Any]
    result: Any | None = None
    error: str | None = None
    status: Status


class ThinkingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: int
    thought: str
    action: str | None = None


class TokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    promptTokens: int
    completionTokens: int
    totalTokens: int


class HistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    role: Role
    content: str
    citations: list[Citation] | None = None
    toolCalls: list[ToolCall] | None = None
    thinking: list[ThinkingItem] | None = None
    tokenUsage: TokenUsage | None = None
    createdAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    metadata: dict[str, Any] | None = None


class ExpertRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conversationId: UUID | None = None
    agentId: UUID
    mode: Mode
    message: Annotated[str, Field(max_length=100000, min_length=1)]
    history: list[HistoryItem] | None = None
    knowledgeDomainIds: list[UUID] | None = None
    systemPromptOverride: str | None = None
    temperature: Annotated[float | None, Field(ge=0.0, le=2.0)] = None
    maxTokens: Annotated[int | None, Field(ge=1, le=128000)] = None
    includeCitations: bool = True
    stream: bool = True
    metadata: dict[str, Any] | None = None
    tenantId: Annotated[
        UUID | None, Field(description='Tenant identifier for multi-tenancy isolation')
    ] = None
    userId: Annotated[UUID | None, Field(description='User identifier')] = None


class Model(RootModel[ExpertRequest]):
    root: ExpertRequest
