# generated by datamodel-codegen:
#   filename:  expert_async_response.json
#   timestamp: 2025-12-05T20:56:12+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, RootModel


class Status(StrEnum):
    queued = 'queued'
    running = 'running'


class ExpertAsyncResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jobId: UUID
    conversationId: UUID
    status: Status
    estimatedTimeSeconds: int | None = None
    pollUrl: str
    streamUrl: str | None = None


class Model(RootModel[ExpertAsyncResponse]):
    root: ExpertAsyncResponse
