# generated by datamodel-codegen:
#   filename:  job.json
#   timestamp: 2025-12-05T20:56:14+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Type(StrEnum):
    expert_mode_3 = 'expert_mode_3'
    expert_mode_4 = 'expert_mode_4'
    panel_execution = 'panel_execution'
    workflow_execution = 'workflow_execution'
    document_ingestion = 'document_ingestion'
    ontology_discovery = 'ontology_discovery'


class Status(StrEnum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    timeout = 'timeout'


class Progress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    currentStep: Annotated[int, Field(ge=0)]
    totalSteps: Annotated[int | None, Field(ge=0)] = None
    percentComplete: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    currentStepDescription: str | None = None
    tokensUsed: Annotated[int, Field(ge=0)] = 0
    tokensRemaining: Annotated[int | None, Field(ge=0)] = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    stackTrace: str | None = None
    isRetryable: bool = False
    retryCount: Annotated[int, Field(ge=0)] = 0
    details: dict[str, Any] | None = None


class Job(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    type: Type
    status: Status
    progress: Progress | None = None
    error: Error | None = None
    result: Any | None = None
    input: dict[str, Any]
    referenceId: UUID | None = None
    referenceType: str | None = None
    queuedAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    startedAt: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 datetime')
    ] = None
    completedAt: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 datetime')
    ] = None
    estimatedCompletionAt: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 datetime')
    ] = None
    tenantId: Annotated[
        UUID, Field(description='Tenant identifier for multi-tenancy isolation')
    ]
    userId: Annotated[UUID, Field(description='User identifier')]
    metadata: dict[str, Any] | None = None


class Model(RootModel[Job]):
    root: Job
