# generated by datamodel-codegen:
#   filename:  job_status_response.json
#   timestamp: 2025-12-05T20:56:14+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    timeout = 'timeout'


class Progress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    currentStep: Annotated[int, Field(ge=0)]
    totalSteps: Annotated[int | None, Field(ge=0)] = None
    percentComplete: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    currentStepDescription: str | None = None
    tokensUsed: Annotated[int, Field(ge=0)] = 0
    tokensRemaining: Annotated[int | None, Field(ge=0)] = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    stackTrace: str | None = None
    isRetryable: bool = False
    retryCount: Annotated[int, Field(ge=0)] = 0
    details: dict[str, Any] | None = None


class JobStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jobId: UUID
    status: Status
    progress: Progress | None = None
    error: Error | None = None
    isComplete: bool
    resultUrl: str | None = None
    elapsedMs: int | None = None
    estimatedRemainingMs: int | None = None


class Model(RootModel[JobStatusResponse]):
    root: JobStatusResponse
