# generated by datamodel-codegen:
#   filename:  node.json
#   timestamp: 2025-12-05T20:56:10+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Position(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    initialContext: dict[str, Any] | None = None


class Node1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['start']
    position: Position
    data: Data
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class OutputMode(StrEnum):
    return_ = 'return'
    store = 'store'
    webhook = 'webhook'


class Data1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outputMode: OutputMode = 'return'
    webhookUrl: AnyUrl | None = None


class Node2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['end']
    position: Position
    data: Data1
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Mode(StrEnum):
    mode_1_instant = 'mode_1_instant'
    mode_2_standard = 'mode_2_standard'
    mode_3_deep_research = 'mode_3_deep_research'
    mode_4_autonomous = 'mode_4_autonomous'


class Data2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentId: UUID
    mode: Mode
    systemPrompt: str | None = None
    temperature: Annotated[float, Field(ge=0.0, le=2.0)] = 0.7
    maxTokens: Annotated[int | None, Field(ge=1, le=128000)] = None
    streaming: bool = True
    enabledTools: list[str] | None = None


class Node3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['expert']
    position: Position
    data: Data2
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Agent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentId: UUID
    role: str
    weight: Annotated[float, Field(ge=0.0, le=1.0)] = 1


class ConsensusStrategy(StrEnum):
    majority_vote = 'majority_vote'
    weighted_average = 'weighted_average'
    moderator_decision = 'moderator_decision'
    unanimous = 'unanimous'


class Data3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    panelId: UUID | None = None
    agents: list[Agent] | None = None
    consensusStrategy: ConsensusStrategy = 'weighted_average'
    consensusThreshold: Annotated[float, Field(ge=0.0, le=1.0)] = 0.7
    maxRounds: Annotated[int, Field(ge=1, le=10)] = 3


class Node4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['panel']
    position: Position
    data: Data3
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    toolId: Annotated[str, Field(min_length=1)]
    config: dict[str, Any] | None = None
    inputMapping: dict[str, str] | None = None
    outputKey: str | None = None


class Node5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['tool']
    position: Position
    data: Data4
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domainId: UUID | None = None
    topK: Annotated[int, Field(ge=1, le=50)] = 10
    similarityThreshold: Annotated[float, Field(ge=0.0, le=1.0)] = 0.7
    rerank: bool = True
    filters: dict[str, Any] | None = None


class Node6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['rag_query']
    position: Position
    data: Data5
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Provider(StrEnum):
    tavily = 'tavily'
    serper = 'serper'
    brave = 'brave'


class SearchDepth(StrEnum):
    basic = 'basic'
    advanced = 'advanced'


class Data6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provider: Provider = 'tavily'
    maxResults: Annotated[int, Field(ge=1, le=20)] = 5
    searchDepth: SearchDepth = 'basic'
    includeDomains: list[str] | None = None
    excludeDomains: list[str] | None = None


class Node7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['web_search']
    position: Position
    data: Data6
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Condition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    expression: str
    targetNodeId: str


class EvaluationMode(StrEnum):
    first_match = 'first_match'
    all_matches = 'all_matches'


class Data7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conditions: list[Condition]
    defaultTargetNodeId: str
    evaluationMode: EvaluationMode = 'first_match'


class Node8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['router']
    position: Position
    data: Data7
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expression: str
    trueTargetNodeId: str
    falseTargetNodeId: str


class Node9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['condition']
    position: Position
    data: Data8
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Branch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    targetNodeId: str


class Data9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branches: list[Branch]
    waitForAll: bool = True
    timeout: Annotated[int | None, Field(ge=1)] = None


class Node10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['parallel']
    position: Position
    data: Data9
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Strategy(StrEnum):
    concat = 'concat'
    merge_objects = 'merge_objects'
    first = 'first'
    custom = 'custom'


class Data10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Strategy = 'merge_objects'
    customMergeExpression: str | None = None


class Node11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['merge']
    position: Position
    data: Data10
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class InputType(StrEnum):
    text = 'text'
    choice = 'choice'
    file = 'file'
    rating = 'rating'


class Choice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str
    label: str


class Data11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt: str
    inputType: InputType = 'text'
    choices: list[Choice] | None = None
    timeout: Annotated[int, Field(ge=0)] = 0
    required: bool = True


class Node12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['human_input']
    position: Position
    data: Data11
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvalPrompt: str
    contextKeys: list[str] | None = None
    approverIds: list[UUID] | None = None
    minApprovals: Annotated[int, Field(ge=1)] = 1
    timeout: Annotated[int, Field(ge=0)] = 0


class Node13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['approval']
    position: Position
    data: Data12
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expression: str
    inputKeys: list[str]
    outputKey: str


class Node14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['transform']
    position: Position
    data: Data13
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Aggregation(StrEnum):
    concat = 'concat'
    sum = 'sum'
    average = 'average'
    min = 'min'
    max = 'max'
    count = 'count'
    custom = 'custom'


class Data14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aggregation: Aggregation
    inputKeys: list[str]
    outputKey: str
    customExpression: str | None = None


class Node15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['aggregate']
    position: Position
    data: Data14
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delayMs: Annotated[int, Field(ge=0, le=300000)] = 1000


class Node16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['delay']
    position: Position
    data: Data15
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Level(StrEnum):
    debug = 'debug'
    info = 'info'
    warn = 'warn'
    error = 'error'


class Data16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Level = 'info'
    message: str
    includeKeys: list[str] | None = None


class Node17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['log']
    position: Position
    data: Data16
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Method(StrEnum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class Data17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    method: Method = 'POST'
    headers: dict[str, str] | None = None
    bodyTemplate: str | None = None
    waitForResponse: bool = True
    timeout: Annotated[int, Field(ge=1, le=60)] = 30


class Node18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['webhook']
    position: Position
    data: Data17
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Model(
    RootModel[
        Node1
        | Node2
        | Node3
        | Node4
        | Node5
        | Node6
        | Node7
        | Node8
        | Node9
        | Node10
        | Node11
        | Node12
        | Node13
        | Node14
        | Node15
        | Node16
        | Node17
        | Node18
    ]
):
    root: (
        Node1
        | Node2
        | Node3
        | Node4
        | Node5
        | Node6
        | Node7
        | Node8
        | Node9
        | Node10
        | Node11
        | Node12
        | Node13
        | Node14
        | Node15
        | Node16
        | Node17
        | Node18
    )
