# generated by datamodel-codegen:
#   filename:  workflow.json
#   timestamp: 2025-12-05T20:56:08+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    draft = 'draft'
    published = 'published'
    archived = 'archived'
    deprecated = 'deprecated'


class Position(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    initialContext: dict[str, Any] | None = None


class Nodes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['start']
    position: Position
    data: Data
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class OutputMode(StrEnum):
    return_ = 'return'
    store = 'store'
    webhook = 'webhook'


class Data1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outputMode: OutputMode = 'return'
    webhookUrl: AnyUrl | None = None


class Nodes1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['end']
    position: Position
    data: Data1
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Mode(StrEnum):
    mode_1_instant = 'mode_1_instant'
    mode_2_standard = 'mode_2_standard'
    mode_3_deep_research = 'mode_3_deep_research'
    mode_4_autonomous = 'mode_4_autonomous'


class Data2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentId: UUID
    mode: Mode
    systemPrompt: str | None = None
    temperature: Annotated[float, Field(ge=0.0, le=2.0)] = 0.7
    maxTokens: Annotated[int | None, Field(ge=1, le=128000)] = None
    streaming: bool = True
    enabledTools: list[str] | None = None


class Nodes2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['expert']
    position: Position
    data: Data2
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Agent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentId: UUID
    role: str
    weight: Annotated[float, Field(ge=0.0, le=1.0)] = 1


class ConsensusStrategy(StrEnum):
    majority_vote = 'majority_vote'
    weighted_average = 'weighted_average'
    moderator_decision = 'moderator_decision'
    unanimous = 'unanimous'


class Data3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    panelId: UUID | None = None
    agents: list[Agent] | None = None
    consensusStrategy: ConsensusStrategy = 'weighted_average'
    consensusThreshold: Annotated[float, Field(ge=0.0, le=1.0)] = 0.7
    maxRounds: Annotated[int, Field(ge=1, le=10)] = 3


class Nodes3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['panel']
    position: Position
    data: Data3
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    toolId: Annotated[str, Field(min_length=1)]
    config: dict[str, Any] | None = None
    inputMapping: dict[str, str] | None = None
    outputKey: str | None = None


class Nodes4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['tool']
    position: Position
    data: Data4
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domainId: UUID | None = None
    topK: Annotated[int, Field(ge=1, le=50)] = 10
    similarityThreshold: Annotated[float, Field(ge=0.0, le=1.0)] = 0.7
    rerank: bool = True
    filters: dict[str, Any] | None = None


class Nodes5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['rag_query']
    position: Position
    data: Data5
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Provider(StrEnum):
    tavily = 'tavily'
    serper = 'serper'
    brave = 'brave'


class SearchDepth(StrEnum):
    basic = 'basic'
    advanced = 'advanced'


class Data6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provider: Provider = 'tavily'
    maxResults: Annotated[int, Field(ge=1, le=20)] = 5
    searchDepth: SearchDepth = 'basic'
    includeDomains: list[str] | None = None
    excludeDomains: list[str] | None = None


class Nodes6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['web_search']
    position: Position
    data: Data6
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Condition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    expression: str
    targetNodeId: str


class EvaluationMode(StrEnum):
    first_match = 'first_match'
    all_matches = 'all_matches'


class Data7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conditions: list[Condition]
    defaultTargetNodeId: str
    evaluationMode: EvaluationMode = 'first_match'


class Nodes7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['router']
    position: Position
    data: Data7
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expression: str
    trueTargetNodeId: str
    falseTargetNodeId: str


class Nodes8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['condition']
    position: Position
    data: Data8
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Branch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    targetNodeId: str


class Data9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    branches: list[Branch]
    waitForAll: bool = True
    timeout: Annotated[int | None, Field(ge=1)] = None


class Nodes9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['parallel']
    position: Position
    data: Data9
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Strategy(StrEnum):
    concat = 'concat'
    merge_objects = 'merge_objects'
    first = 'first'
    custom = 'custom'


class Data10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Strategy = 'merge_objects'
    customMergeExpression: str | None = None


class Nodes10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['merge']
    position: Position
    data: Data10
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class InputType(StrEnum):
    text = 'text'
    choice = 'choice'
    file = 'file'
    rating = 'rating'


class Choice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str
    label: str


class Data11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt: str
    inputType: InputType = 'text'
    choices: list[Choice] | None = None
    timeout: Annotated[int, Field(ge=0)] = 0
    required: bool = True


class Nodes11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['human_input']
    position: Position
    data: Data11
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvalPrompt: str
    contextKeys: list[str] | None = None
    approverIds: list[UUID] | None = None
    minApprovals: Annotated[int, Field(ge=1)] = 1
    timeout: Annotated[int, Field(ge=0)] = 0


class Nodes12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['approval']
    position: Position
    data: Data12
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expression: str
    inputKeys: list[str]
    outputKey: str


class Nodes13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['transform']
    position: Position
    data: Data13
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Aggregation(StrEnum):
    concat = 'concat'
    sum = 'sum'
    average = 'average'
    min = 'min'
    max = 'max'
    count = 'count'
    custom = 'custom'


class Data14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aggregation: Aggregation
    inputKeys: list[str]
    outputKey: str
    customExpression: str | None = None


class Nodes14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['aggregate']
    position: Position
    data: Data14
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Data15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delayMs: Annotated[int, Field(ge=0, le=300000)] = 1000


class Nodes15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['delay']
    position: Position
    data: Data15
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Level(StrEnum):
    debug = 'debug'
    info = 'info'
    warn = 'warn'
    error = 'error'


class Data16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Level = 'info'
    message: str
    includeKeys: list[str] | None = None


class Nodes16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['log']
    position: Position
    data: Data16
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Method(StrEnum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class Data17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    method: Method = 'POST'
    headers: dict[str, str] | None = None
    bodyTemplate: str | None = None
    waitForResponse: bool = True
    timeout: Annotated[int, Field(ge=1, le=60)] = 30


class Nodes17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    type: Literal['webhook']
    position: Position
    data: Data17
    label: str | None = None
    selected: bool | None = None
    dragging: bool | None = None


class Style(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stroke: str | None = None
    strokeWidth: float | None = None
    strokeDasharray: str | None = None


class Edges(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    source: Annotated[str, Field(min_length=1)]
    target: Annotated[str, Field(min_length=1)]
    sourceHandle: str | None = None
    targetHandle: str | None = None
    type: Literal['default'] = 'default'
    animated: bool | None = None
    label: str | None = None
    style: Style | None = None
    selected: bool | None = None


class Data18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    condition: str
    priority: Annotated[int, Field(ge=0)] = 0


class Edges1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    source: Annotated[str, Field(min_length=1)]
    target: Annotated[str, Field(min_length=1)]
    sourceHandle: str | None = None
    targetHandle: str | None = None
    type: Literal['conditional']
    animated: bool | None = None
    label: str | None = None
    style: Style | None = None
    selected: bool | None = None
    data: Data18


class Edges2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    source: Annotated[str, Field(min_length=1)]
    target: Annotated[str, Field(min_length=1)]
    sourceHandle: str | None = None
    targetHandle: str | None = None
    type: Literal['animated']
    animated: Literal[True]
    label: str | None = None
    style: Style | None = None
    selected: bool | None = None


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float
    zoom: Annotated[float, Field(ge=0.1, le=4.0)] = 1


class ExecutionSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxExecutionTime: Annotated[int, Field(ge=1, le=3600)] = 300
    maxTokenBudget: Annotated[int, Field(ge=1)] = 100000
    enableStreaming: bool = True
    enableCheckpointing: bool = True
    checkpointInterval: Annotated[int, Field(ge=0)] = 1
    allowHumanInLoop: bool = True
    defaultRetryCount: Annotated[int, Field(ge=0, le=5)] = 2
    retryDelayMs: Annotated[int, Field(ge=0)] = 1000


class Workflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    name: Annotated[str, Field(max_length=200, min_length=1)]
    description: Annotated[str | None, Field(max_length=2000)] = None
    version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')] = '1.0.0'
    status: Status = 'draft'
    nodes: list[
        Nodes
        | Nodes1
        | Nodes2
        | Nodes3
        | Nodes4
        | Nodes5
        | Nodes6
        | Nodes7
        | Nodes8
        | Nodes9
        | Nodes10
        | Nodes11
        | Nodes12
        | Nodes13
        | Nodes14
        | Nodes15
        | Nodes16
        | Nodes17
    ]
    edges: list[Edges | Edges1 | Edges2]
    viewport: Viewport | None = None
    entryNodeId: Annotated[str, Field(min_length=1)]
    exitNodeIds: Annotated[list[str], Field(min_length=1)]
    executionSettings: ExecutionSettings | None = None
    globalVariables: dict[str, Any] | None = None
    tags: list[str] = []
    metadata: dict[str, Any] | None = None
    tenantId: Annotated[
        UUID, Field(description='Tenant identifier for multi-tenancy isolation')
    ]
    createdBy: Annotated[UUID, Field(description='User identifier')]
    updatedBy: Annotated[UUID | None, Field(description='User identifier')] = None
    createdAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    updatedAt: Annotated[AwareDatetime, Field(description='ISO 8601 datetime')]
    publishedAt: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 datetime')
    ] = None


class Model(RootModel[Workflow]):
    root: Workflow
