-- ============================================================================
-- Add 50 Regulatory Affairs Capabilities ONLY
-- ============================================================================

BEGIN;

INSERT INTO capabilities (
    name,
    slug,
    description,
    capability_type,
    maturity_level,
    tags,
    is_active
) VALUES
('Chief Regulatory Officer Leadership', 'chief-regulatory-officer-leadership', 'Executive regulatory leadership setting global regulatory strategy, policy, and ensuring enterprise-wide regulatory compliance.', 'leadership', 'expert', ARRAY['regulatory-affairs'], true),
('VP Regulatory Affairs Strategy', 'vp-regulatory-affairs-strategy', 'VP-level development and execution of multi-region regulatory strategy across portfolio.', 'leadership', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Affairs Directorate', 'regulatory-affairs-directorate', 'Leading regulatory affairs function or therapeutic area at director level with strategic oversight.', 'leadership', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Project Management', 'regulatory-project-management', 'Managing complex regulatory projects across multiple submissions and jurisdictions with cross-functional teams.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('IND/CTA Preparation & Management', 'indcta-preparation-management', 'Preparing and managing Investigational New Drug (IND) and Clinical Trial Application (CTA) submissions.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('NDA/BLA Preparation & Submission', 'ndabla-preparation-submission', 'End-to-end preparation and submission of New Drug Applications (NDA) and Biologics License Applications (BLA).', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('MAA/Centralised Procedure Preparation', 'maacentralised-procedure-preparation', 'Preparing Marketing Authorization Applications (MAA) for EMA centralised procedure.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Global Registration Strategy', 'global-registration-strategy', 'Developing and executing global registration strategies across multiple markets and regulatory pathways.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Supplements & Variation Management', 'supplements-variation-management', 'Managing post-approval changes through supplements, variations, and amendments.', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Orphan Drug Designation & Pediatric Plans', 'orphan-drug-designation-pediatric-plans', 'Obtaining orphan drug designations and developing pediatric investigation plans (PIP/PSP).', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Breakthrough & Expedited Pathways', 'breakthrough-expedited-pathways', 'Navigating expedited regulatory pathways including breakthrough, fast track, priority review, and accelerated approval.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('CMC Regulatory Strategy & Documentation', 'cmc-regulatory-strategy-documentation', 'Developing CMC regulatory strategy and authoring Module 3 (Quality) documentation.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Manufacturing & Facility Registration', 'manufacturing-facility-registration', 'Registering manufacturing facilities and preparing Drug Master Files (DMFs).', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Pharmaceutical Development & Specifications', 'pharmaceutical-development-specifications', 'Regulatory review and approval of pharmaceutical development strategies and product specifications.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Comparability & Lifecycle Management (CMC)', 'comparability-lifecycle-management-cmc', 'Managing CMC changes through comparability protocols and lifecycle management strategies.', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Biologics & Advanced Therapy Regulatory', 'biologics-advanced-therapy-regulatory', 'Specialized regulatory expertise in biologics, cell therapy, gene therapy, and advanced therapeutic medicinal products (ATMP).', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Core Labeling Development', 'core-labeling-development', 'Developing core product labeling including prescribing information, SmPC, and package leaflets.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Labeling Negotiation & Defense', 'labeling-negotiation-defense', 'Negotiating labeling with health authorities and defending proposed label claims.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Global Labeling Harmonization', 'global-labeling-harmonization', 'Harmonizing product labeling across multiple regions while meeting local requirements.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Safety Labeling Updates', 'safety-labeling-updates', 'Managing safety-related labeling updates including warnings, contraindications, and adverse reactions.', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Pre-Submission Meetings & Scientific Advice', 'pre-submission-meetings-scientific-advice', 'Preparing for and conducting pre-submission meetings, End-of-Phase meetings, and scientific advice procedures.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Agency Query Response & Negotiation', 'agency-query-response-negotiation', 'Responding to health authority information requests, deficiency letters, and conducting regulatory negotiations.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Advisory Committee Preparation', 'advisory-committee-preparation', 'Preparing for and presenting at FDA Advisory Committee (AdComm) meetings.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Inspection Management & Agency Audit Support', 'inspection-management-agency-audit-support', 'Managing regulatory inspections, audits, and providing facility support during agency visits.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Intelligence & Horizon Scanning', 'regulatory-intelligence-horizon-scanning', 'Monitoring global regulatory landscape, guideline updates, and emerging regulatory trends.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Compliance Monitoring', 'regulatory-compliance-monitoring', 'Monitoring regulatory compliance across operations, identifying gaps, and implementing corrective actions.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Policy & Advocacy', 'regulatory-policy-advocacy', 'Engaging in regulatory policy development, industry advocacy, and trade association activities.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Training & SOP Development', 'regulatory-training-sop-development', 'Developing regulatory training programs and standard operating procedures for regulatory operations.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Product Lifecycle Management (Regulatory)', 'product-lifecycle-management-regulatory', 'Strategic regulatory lifecycle management from development through commercialization to end-of-life.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Post-Approval Commitments & Studies', 'post-approval-commitments-studies', 'Managing post-marketing requirements (PMR), post-marketing commitments (PMC), and post-authorization safety studies (PASS).', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Regulatory Maintenance & Annual Reporting', 'regulatory-maintenance-annual-reporting', 'Maintaining regulatory approvals through annual reports, periodic safety updates, and renewal applications.', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Risk Management Planning (RMP/REMS)', 'risk-management-planning-rmprems', 'Developing and maintaining Risk Management Plans (RMP) and Risk Evaluation and Mitigation Strategies (REMS).', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Safety Reporting', 'regulatory-safety-reporting', 'Managing regulatory safety reporting requirements including PSURs, PBRERs, and expedited reports.', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Benefit-Risk Assessment (Regulatory)', 'benefit-risk-assessment-regulatory', 'Conducting and communicating benefit-risk assessments for regulatory submissions and lifecycle management.', 'interpersonal', 'expert', ARRAY['regulatory-affairs'], true),
('Crisis Management & Regulatory Issues', 'crisis-management-regulatory-issues', 'Managing regulatory crises, product recalls, safety alerts, and urgent regulatory issues.', 'interpersonal', 'expert', ARRAY['regulatory-affairs'], true),
('Strategic Regulatory Thinking', 'strategic-regulatory-thinking', 'High-level strategic thinking to align regulatory strategy with business objectives.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Cross-Functional Regulatory Leadership', 'cross-functional-regulatory-leadership', 'Leading and influencing cross-functional teams across R&D, medical, commercial, and manufacturing.', 'leadership', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Budget & Resource Management', 'regulatory-budget-resource-management', 'Managing regulatory budgets, vendor contracts, and resource allocation.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Science & Guidelines Expertise', 'regulatory-science-guidelines-expertise', 'Deep expertise in regulatory science, ICH guidelines, and regional regulatory requirements.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Document Writing & Review', 'regulatory-document-writing-review', 'Authoring and reviewing high-quality regulatory documents with scientific accuracy and regulatory compliance.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Clinical-Regulatory Integration', 'clinical-regulatory-integration', 'Integrating clinical development strategy with regulatory requirements and ensuring alignment.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Data Analysis & Regulatory Interpretation', 'data-analysis-regulatory-interpretation', 'Analyzing clinical and non-clinical data for regulatory interpretation and submission strategy.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Agency Communication & Relationship Management', 'agency-communication-relationship-management', 'Building and maintaining effective relationships with health authority personnel.', 'interpersonal', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Presentation & Advocacy', 'regulatory-presentation-advocacy', 'Presenting to health authorities, advisory panels, and internal stakeholders with scientific credibility.', 'technical', 'expert', ARRAY['regulatory-affairs'], true),
('Global Regulatory Coordination', 'global-regulatory-coordination', 'Coordinating regulatory activities across multiple regions and ensuring global alignment.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Consulting & Advisory Services', 'regulatory-consulting-advisory-services', 'Providing regulatory consulting and advisory services to internal teams or external clients.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Systems & Technology Proficiency', 'regulatory-systems-technology-proficiency', 'Proficiency in regulatory information management systems, eCTD publishing, and regulatory technology.', 'business', 'advanced', ARRAY['regulatory-affairs'], true),
('Regulatory Quality & Compliance Assurance', 'regulatory-quality-compliance-assurance', 'Ensuring regulatory quality standards and compliance with SOPs, regulations, and best practices.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Regulatory Process Optimization', 'regulatory-process-optimization', 'Optimizing regulatory processes, workflows, and operational efficiency.', 'business', 'expert', ARRAY['regulatory-affairs'], true),
('Timeline Management & Critical Path', 'timeline-management-critical-path', 'Managing regulatory timelines, critical path activities, and milestone tracking.', 'business', 'expert', ARRAY['regulatory-affairs'], true);

COMMIT;
