-- =====================================================
-- MIGRATION: 048 - Market Access Expanded Personas
-- Date: 2025-11-29
-- Description: 80 additional personas for Market Access roles
-- Covers: HEOR Directors/Managers, Pricing, Payer Relations,
--         Reimbursement, Value & Evidence specialists
-- =====================================================

-- This migration SUPPLEMENTS the original Market Access migration (041)
-- which covered core Market Access Director/Manager/Analyst roles.
-- This migration adds coverage for specialized HEOR, Pricing, Payer,
-- and Value functions within Market Access.

-- =====================================================
-- SECTION 1: HEOR LEADERSHIP ROLES
-- =====================================================

-- Role 1: Director of Health Economics
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('dir-health-econ-automator', 'Director of Health Economics - Economic Modeling Expert', E'## Director of Health Economics (Automator)\n\n### Professional Context\nData-driven health economics director who leverages AI for economic modeling, cost-effectiveness analysis, and budget impact assessments. Uses AI to accelerate evidence generation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for economic models, automates sensitivity analyses, optimizes model validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | HEOR leadership |\n| Pain | 5 | AI reduces modeling burden |\n| Actions | 8 | Drives HEOR strategy |\n| Needs | 8 | AI-powered modeling tools |\n| Emotions | 9 | Excited by AI economics |\n| Scenarios | 8 | Complex modeling scenarios |', TRUE),

  ('dir-health-econ-orchestrator', 'Director of Health Economics - Strategic Value Architect', E'## Director of Health Economics (Orchestrator)\n\n### Professional Context\nStrategic HEOR leader who orchestrates health economics research aligned with commercial and medical strategy. Coordinates modeling teams and external partnerships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 91%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs HEOR AI strategy, coordinates research portfolio, builds economics COE\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Strategic HEOR role |\n| Pain | 4 | AI handles complexity |\n| Actions | 9 | Shapes HEOR direction |\n| Needs | 9 | Integrated HEOR platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 9 | Enterprise value scenarios |', TRUE),

  ('dir-health-econ-learner', 'Director of Health Economics - Evidence Builder', E'## Director of Health Economics (Learner)\n\n### Professional Context\nEvidence-focused HEOR director building AI capabilities for health economics research. Explores AI for model development while maintaining methodological rigor.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 50%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for modeling, validates methodologies, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | HEOR leadership |\n| Pain | 7 | Growing evidence demands |\n| Actions | 7 | Measured approach |\n| Needs | 8 | Validated economic AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 8 | Methodology scenarios |', TRUE),

  ('dir-health-econ-skeptic', 'Director of Health Economics - Methodological Rigor Guardian', E'## Director of Health Economics (Skeptic)\n\n### Professional Context\nMethodologically rigorous HEOR director who questions AI in economic analysis. Emphasizes validated methodologies and transparent assumptions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI assumptions, requires validation, emphasizes transparency\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | HEOR leadership |\n| Pain | 9 | Concerned about AI methods |\n| Actions | 6 | Conservative approach |\n| Needs | 9 | Validated, explainable AI |\n| Emotions | 3 | Skeptical of AI in economics |\n| Scenarios | 9 | High-stakes HTA scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 2: Global HEOR Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-heor-dir-automator', 'Global HEOR Director - Global Evidence Champion', E'## Global HEOR Director (Automator)\n\n### Professional Context\nGlobal HEOR leader who leverages AI for multi-country evidence generation, global dossier development, and cross-regional economic modeling.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 83%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for global models, automates dossier generation, standardizes across regions\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global HEOR leadership |\n| Pain | 6 | AI reduces global coordination burden |\n| Actions | 8 | Drives global HEOR strategy |\n| Needs | 8 | Global AI modeling platform |\n| Emotions | 8 | Excited by global AI scale |\n| Scenarios | 8 | Multi-market scenarios |', TRUE),

  ('global-heor-dir-orchestrator', 'Global HEOR Director - Enterprise Evidence Strategist', E'## Global HEOR Director (Orchestrator)\n\n### Professional Context\nEnterprise HEOR strategist who orchestrates global evidence strategy using AI-enabled research and modeling platforms. Aligns regional HEOR with global value strategy.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 90%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs global HEOR AI strategy, coordinates regional teams, builds global evidence COE\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global strategic role |\n| Pain | 4 | AI handles global complexity |\n| Actions | 9 | Shapes global HEOR direction |\n| Needs | 9 | Integrated global platform |\n| Emotions | 9 | Energized by global transformation |\n| Scenarios | 9 | Complex global scenarios |', TRUE),

  ('global-heor-dir-learner', 'Global HEOR Director - Regional Capability Builder', E'## Global HEOR Director (Learner)\n\n### Professional Context\nGlobal HEOR director building AI capabilities across regions. Pilots AI in select markets, learns from results, and scales successful approaches.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 48%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI in regions, shares best practices, builds global capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global role |\n| Pain | 7 | Regional coordination challenges |\n| Actions | 7 | Measured global approach |\n| Needs | 8 | Proven regional AI success |\n| Emotions | 6 | Cautiously optimistic |\n| Scenarios | 8 | Multi-market complexity |', TRUE),

  ('global-heor-dir-skeptic', 'Global HEOR Director - HTA Compliance Focus', E'## Global HEOR Director (Skeptic)\n\n### Professional Context\nCompliance-focused global HEOR director who emphasizes HTA body requirements across markets. Skeptical of AI that doesn''t meet HTA standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 30%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Prioritizes HTA compliance, questions AI models, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global leadership |\n| Pain | 9 | HTA compliance concerns |\n| Actions | 5 | Conservative, compliance-first |\n| Needs | 9 | Validated, HTA-compliant AI |\n| Emotions | 3 | Skeptical of AI in HEOR |\n| Scenarios | 9 | HTA submission scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 3: Senior Health Economist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sr-health-economist-automator', 'Senior Health Economist - Model Automation Expert', E'## Senior Health Economist (Automator)\n\n### Professional Context\nTech-savvy health economist who leverages AI for economic model development, systematic reviews, and meta-analyses. Pioneers new modeling methodologies.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for modeling, automates systematic reviews, optimizes analysis workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Senior specialist |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Leads economic analyses |\n| Needs | 7 | AI modeling tools |\n| Emotions | 9 | Excited by AI economics |\n| Scenarios | 7 | Complex modeling scenarios |', TRUE),

  ('sr-health-economist-orchestrator', 'Senior Health Economist - Strategic Economic Advisor', E'## Senior Health Economist (Orchestrator)\n\n### Professional Context\nStrategic economist who orchestrates complex economic evidence programs using AI. Coordinates multi-country models and advises on value strategy.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates evidence programs, designs AI-enabled methodologies, mentors junior economists\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Experienced specialist |\n| Pain | 5 | Complex coordination |\n| Actions | 8 | Strategic economic decisions |\n| Needs | 8 | Integrated economics platform |\n| Emotions | 9 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic economic scenarios |', TRUE),

  ('sr-health-economist-learner', 'Senior Health Economist - Evidence Quality Focus', E'## Senior Health Economist (Learner)\n\n### Professional Context\nEvidence-focused economist building AI capabilities for health economics research. Explores AI for specific analyses while maintaining methodological quality.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for analysis, validates outputs, builds expertise\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Senior specialist |\n| Pain | 7 | Growing analysis demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated economic AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 7 | Analysis quality scenarios |', TRUE),

  ('sr-health-economist-skeptic', 'Senior Health Economist - Methodology Guardian', E'## Senior Health Economist (Skeptic)\n\n### Professional Context\nMethodology-focused economist who questions AI in economic modeling. Emphasizes validated approaches and transparent model assumptions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI methodology, requires validation, emphasizes transparency\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Senior role |\n| Pain | 9 | Concerned about AI methods |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, transparent AI |\n| Emotions | 3 | Skeptical of AI modeling |\n| Scenarios | 8 | Methodology validation scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 4: Global HEOR Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-heor-mgr-automator', 'Global HEOR Manager - Research Automation Lead', E'## Global HEOR Manager (Automator)\n\n### Professional Context\nEfficiency-focused HEOR manager who automates research workflows, literature surveillance, and evidence tracking across global teams.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Automates research workflows, uses AI for surveillance, optimizes evidence tracking\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global management role |\n| Pain | 5 | AI reduces coordination burden |\n| Actions | 7 | Drives HEOR operations |\n| Needs | 7 | AI-powered research tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 6 | Research management scenarios |', TRUE),

  ('global-heor-mgr-orchestrator', 'Global HEOR Manager - Strategic Program Coordinator', E'## Global HEOR Manager (Orchestrator)\n\n### Professional Context\nStrategic HEOR manager who orchestrates global research programs using AI-enabled project management and evidence synthesis platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates global programs, designs AI-enabled processes, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global coordination role |\n| Pain | 5 | Program coordination |\n| Actions | 7 | Shapes program direction |\n| Needs | 8 | Integrated program platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Global program scenarios |', TRUE),

  ('global-heor-mgr-learner', 'Global HEOR Manager - Team Developer', E'## Global HEOR Manager (Learner)\n\n### Professional Context\nDevelopment-focused HEOR manager building AI capabilities across the global team. Pilots AI tools, provides training, and measures adoption.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI with team, invests in training, measures adoption\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Management role |\n| Pain | 7 | Growing team demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Team development scenarios |', TRUE),

  ('global-heor-mgr-skeptic', 'Global HEOR Manager - Quality Control Focus', E'## Global HEOR Manager (Skeptic)\n\n### Professional Context\nQuality-focused HEOR manager who emphasizes research quality and compliance. Skeptical of AI that compromises methodological rigor.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes quality control, questions AI outputs, requires review\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Management role |\n| Pain | 8 | Concerned about AI quality |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Validated, quality AI |\n| Emotions | 4 | Skeptical of AI research |\n| Scenarios | 7 | Quality control scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 5: Outcomes Research Scientist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('outcomes-res-scientist-automator', 'Outcomes Research Scientist - RWE Automation Expert', E'## Outcomes Research Scientist (Automator)\n\n### Professional Context\nData-driven outcomes researcher who leverages AI for real-world evidence analysis, claims data mining, and outcomes study design.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 81%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for RWE analysis, automates data processing, optimizes study workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Research specialist |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 6 | Leads research studies |\n| Needs | 7 | AI RWE analysis tools |\n| Emotions | 8 | Excited by AI research |\n| Scenarios | 6 | RWE analysis scenarios |', TRUE),

  ('outcomes-res-scientist-orchestrator', 'Outcomes Research Scientist - Strategic Evidence Leader', E'## Outcomes Research Scientist (Orchestrator)\n\n### Professional Context\nStrategic outcomes researcher who orchestrates complex RWE programs using AI-enabled data platforms. Coordinates database studies and external partnerships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates RWE programs, designs AI-enabled studies, builds research networks\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Experienced researcher |\n| Pain | 5 | Complex study coordination |\n| Actions | 7 | Strategic research decisions |\n| Needs | 7 | Integrated RWE platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Complex RWE scenarios |', TRUE),

  ('outcomes-res-scientist-learner', 'Outcomes Research Scientist - Evidence Quality Focus', E'## Outcomes Research Scientist (Learner)\n\n### Professional Context\nQuality-focused outcomes researcher building AI capabilities for RWE studies. Explores AI for data analysis while maintaining research standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for analysis, validates methodologies, builds skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Research role |\n| Pain | 7 | Growing data complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated research AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Research quality scenarios |', TRUE),

  ('outcomes-res-scientist-skeptic', 'Outcomes Research Scientist - Methodology Rigor Focus', E'## Outcomes Research Scientist (Skeptic)\n\n### Professional Context\nMethodology-focused outcomes researcher who questions AI in RWE analysis. Emphasizes validated statistical methods and transparent assumptions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI methods, requires validation, emphasizes transparency\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Research role |\n| Pain | 8 | Concerned about AI methods |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Validated, transparent AI |\n| Emotions | 3 | Skeptical of AI in RWE |\n| Scenarios | 7 | Methodology scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 2: PRICING & REIMBURSEMENT ROLES
-- =====================================================

-- Role 6: Global Pricing Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-pricing-mgr-automator', 'Global Pricing Manager - Analytics Expert', E'## Global Pricing Manager (Automator)\n\n### Professional Context\nAnalytics-driven pricing manager who leverages AI for pricing strategy analysis, competitive benchmarking, and scenario modeling across global markets.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for pricing analysis, automates benchmarking, optimizes scenario models\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global pricing role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Drives pricing strategy |\n| Needs | 7 | AI pricing analytics |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Pricing strategy scenarios |', TRUE),

  ('global-pricing-mgr-orchestrator', 'Global Pricing Manager - Strategic Pricing Architect', E'## Global Pricing Manager (Orchestrator)\n\n### Professional Context\nStrategic pricing leader who orchestrates global pricing strategy using AI-enabled analytics and scenario planning platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs global pricing AI strategy, coordinates regional pricing, builds pricing excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic pricing role |\n| Pain | 5 | Global coordination |\n| Actions | 8 | Shapes pricing direction |\n| Needs | 8 | Integrated pricing platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic pricing scenarios |', TRUE),

  ('global-pricing-mgr-learner', 'Global Pricing Manager - Market Intelligence Builder', E'## Global Pricing Manager (Learner)\n\n### Professional Context\nMarket-focused pricing manager building AI capabilities for pricing intelligence. Pilots AI for specific markets while maintaining analytical rigor.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for markets, validates pricing models, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Pricing management |\n| Pain | 7 | Growing market complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated pricing AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Market analysis scenarios |', TRUE),

  ('global-pricing-mgr-skeptic', 'Global Pricing Manager - Compliance Focus', E'## Global Pricing Manager (Skeptic)\n\n### Professional Context\nCompliance-focused pricing manager who emphasizes regulatory requirements for pricing across markets. Skeptical of AI recommendations without validation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes compliance, questions AI pricing, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Pricing role |\n| Pain | 8 | Compliance concerns |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Validated, compliant AI |\n| Emotions | 4 | Skeptical of AI pricing |\n| Scenarios | 7 | Compliance scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 7: Global Reimbursement Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-reimb-mgr-automator', 'Global Reimbursement Manager - Coverage Analytics Expert', E'## Global Reimbursement Manager (Automator)\n\n### Professional Context\nAnalytics-focused reimbursement manager who leverages AI for coverage analysis, payer landscape mapping, and reimbursement strategy development.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for coverage analysis, automates payer mapping, optimizes strategy development\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global reimbursement role |\n| Pain | 6 | AI reduces analysis burden |\n| Actions | 7 | Drives reimbursement strategy |\n| Needs | 7 | AI coverage analytics |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Coverage strategy scenarios |', TRUE),

  ('global-reimb-mgr-orchestrator', 'Global Reimbursement Manager - Strategic Access Planner', E'## Global Reimbursement Manager (Orchestrator)\n\n### Professional Context\nStrategic reimbursement leader who orchestrates global coverage strategy using AI-enabled payer analytics and market access platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs global reimbursement AI strategy, coordinates regional coverage, builds access excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic role |\n| Pain | 5 | Global coordination |\n| Actions | 8 | Shapes access direction |\n| Needs | 8 | Integrated access platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic access scenarios |', TRUE),

  ('global-reimb-mgr-learner', 'Global Reimbursement Manager - Payer Intelligence Builder', E'## Global Reimbursement Manager (Learner)\n\n### Professional Context\nPayer-focused reimbursement manager building AI capabilities for payer intelligence. Pilots AI for specific markets while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for payer analysis, validates outputs, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Management role |\n| Pain | 7 | Growing payer complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated payer AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Payer analysis scenarios |', TRUE),

  ('global-reimb-mgr-skeptic', 'Global Reimbursement Manager - Policy Compliance Focus', E'## Global Reimbursement Manager (Skeptic)\n\n### Professional Context\nPolicy-focused reimbursement manager who emphasizes regulatory compliance and payer policy requirements. Skeptical of AI that oversimplifies complex payer dynamics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes policy compliance, questions AI analysis, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Reimbursement role |\n| Pain | 8 | Concerned about AI accuracy |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Validated, compliant AI |\n| Emotions | 4 | Skeptical of AI reimbursement |\n| Scenarios | 7 | Policy compliance scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 8: Value & Pricing Analyst
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('value-pricing-analyst-automator', 'Value & Pricing Analyst - Analytics Power User', E'## Value & Pricing Analyst (Automator)\n\n### Professional Context\nAnalytics-savvy analyst who leverages AI for value modeling, pricing analysis, and competitive benchmarking. Uses AI to accelerate insights generation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for modeling, automates benchmarking, optimizes analysis workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI analysis tools |\n| Emotions | 8 | Excited by AI analytics |\n| Scenarios | 5 | Analysis scenarios |', TRUE),

  ('value-pricing-analyst-orchestrator', 'Value & Pricing Analyst - Cross-Functional Analyst', E'## Value & Pricing Analyst (Orchestrator)\n\n### Professional Context\nStrategic analyst who coordinates value and pricing analyses across functions using AI-enabled analytics platforms. Synthesizes inputs from multiple stakeholders.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 83%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates cross-functional analysis, designs AI-enabled workflows, builds analytical excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Experienced analyst |\n| Pain | 5 | Cross-functional coordination |\n| Actions | 6 | Strategic analysis decisions |\n| Needs | 7 | Integrated analytics platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Cross-functional scenarios |', TRUE),

  ('value-pricing-analyst-learner', 'Value & Pricing Analyst - Skills Developer', E'## Value & Pricing Analyst (Learner)\n\n### Professional Context\nDevelopment-focused analyst building AI capabilities for value and pricing analysis. Explores AI tools while developing analytical expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI tools, validates outputs, builds analytical skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 7 | Growing analysis demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('value-pricing-analyst-skeptic', 'Value & Pricing Analyst - Data Quality Focus', E'## Value & Pricing Analyst (Skeptic)\n\n### Professional Context\nData quality-focused analyst who questions AI outputs and emphasizes data validation. Concerned about AI introducing errors in pricing recommendations.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 24%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI outputs, requires data validation, emphasizes accuracy\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 8 | Concerned about AI errors |\n| Actions | 4 | Conservative approach |\n| Needs | 7 | Validated, accurate AI |\n| Emotions | 3 | Skeptical of AI analysis |\n| Scenarios | 6 | Data quality scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 3: PAYER RELATIONS ROLES
-- =====================================================

-- Role 9: Global Payer Strategy Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-payer-strategy-automator', 'Global Payer Strategy Lead - Payer Intelligence Expert', E'## Global Payer Strategy Lead (Automator)\n\n### Professional Context\nIntelligence-driven payer strategist who leverages AI for payer landscape analysis, policy tracking, and strategic planning across global markets.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 81%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for payer analysis, automates policy tracking, optimizes strategy development\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Global payer strategy role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Drives payer strategy |\n| Needs | 8 | AI payer intelligence |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Payer strategy scenarios |', TRUE),

  ('global-payer-strategy-orchestrator', 'Global Payer Strategy Lead - Strategic Payer Architect', E'## Global Payer Strategy Lead (Orchestrator)\n\n### Professional Context\nStrategic payer leader who orchestrates global payer engagement strategy using AI-enabled intelligence and relationship management platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 89%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs global payer AI strategy, coordinates regional engagement, builds payer excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic payer role |\n| Pain | 4 | AI handles complexity |\n| Actions | 8 | Shapes payer direction |\n| Needs | 9 | Integrated payer platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 8 | Strategic payer scenarios |', TRUE),

  ('global-payer-strategy-learner', 'Global Payer Strategy Lead - Market Intelligence Builder', E'## Global Payer Strategy Lead (Learner)\n\n### Professional Context\nMarket-focused payer strategist building AI capabilities for payer intelligence. Pilots AI in select markets while developing strategic expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 47%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for markets, validates payer insights, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategy leadership |\n| Pain | 7 | Growing market complexity |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Validated payer AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 7 | Market intelligence scenarios |', TRUE),

  ('global-payer-strategy-skeptic', 'Global Payer Strategy Lead - Relationship Quality Focus', E'## Global Payer Strategy Lead (Skeptic)\n\n### Professional Context\nRelationship-focused payer strategist who emphasizes authentic payer relationships over AI metrics. Skeptical that AI can capture payer relationship nuances.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 29%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes relationship quality, questions AI metrics, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Payer strategy role |\n| Pain | 8 | Concerned AI diminishes relationships |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | AI that enhances relationships |\n| Emotions | 4 | Skeptical of payer AI |\n| Scenarios | 8 | Relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 10: Payer Relations Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('payer-relations-mgr-automator', 'Payer Relations Manager - Engagement Analytics Expert', E'## Payer Relations Manager (Automator)\n\n### Professional Context\nAnalytics-savvy payer relations manager who leverages AI for engagement tracking, meeting preparation, and relationship analytics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 76%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for engagement tracking, automates meeting prep, optimizes relationship analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Payer relations role |\n| Pain | 6 | AI reduces admin burden |\n| Actions | 6 | Manages payer relationships |\n| Needs | 7 | AI engagement tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 6 | Engagement scenarios |', TRUE),

  ('payer-relations-mgr-orchestrator', 'Payer Relations Manager - Strategic Account Coordinator', E'## Payer Relations Manager (Orchestrator)\n\n### Professional Context\nStrategic payer relations manager who orchestrates payer engagement programs using AI-enabled CRM and relationship management platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates payer programs, designs AI-enabled engagement, builds relationship excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Management role |\n| Pain | 5 | Program coordination |\n| Actions | 7 | Shapes engagement direction |\n| Needs | 8 | Integrated CRM platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic engagement scenarios |', TRUE),

  ('payer-relations-mgr-learner', 'Payer Relations Manager - Relationship Builder', E'## Payer Relations Manager (Learner)\n\n### Professional Context\nRelationship-focused payer relations manager building AI capabilities for payer engagement. Pilots AI for specific use cases while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 43%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for engagement, validates outputs, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Relations management |\n| Pain | 7 | Growing engagement demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Relationship building scenarios |', TRUE),

  ('payer-relations-mgr-skeptic', 'Payer Relations Manager - Authentic Engagement Focus', E'## Payer Relations Manager (Skeptic)\n\n### Professional Context\nAuthenticity-focused payer relations manager who prioritizes genuine payer relationships over AI efficiency. Skeptical of AI in relationship-critical contexts.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes authentic engagement, questions AI metrics, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Relations role |\n| Pain | 8 | Concerned AI diminishes authenticity |\n| Actions | 5 | Traditional approach |\n| Needs | 7 | AI that supports relationships |\n| Emotions | 3 | Skeptical of payer AI |\n| Scenarios | 7 | Relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 11: Payer Evidence Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('payer-evidence-lead-automator', 'Payer Evidence Lead - Evidence Generation Expert', E'## Payer Evidence Lead (Automator)\n\n### Professional Context\nEvidence-focused specialist who leverages AI for payer-relevant evidence generation, dossier development, and value story creation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for evidence synthesis, automates dossier generation, optimizes value stories\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Evidence leadership role |\n| Pain | 5 | AI reduces evidence burden |\n| Actions | 7 | Leads evidence generation |\n| Needs | 7 | AI evidence synthesis tools |\n| Emotions | 8 | Excited by AI capabilities |\n| Scenarios | 7 | Evidence generation scenarios |', TRUE),

  ('payer-evidence-lead-orchestrator', 'Payer Evidence Lead - Strategic Evidence Architect', E'## Payer Evidence Lead (Orchestrator)\n\n### Professional Context\nStrategic evidence leader who orchestrates payer evidence programs using AI-enabled research and dossier development platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs evidence AI strategy, coordinates programs, builds evidence excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic evidence role |\n| Pain | 5 | Program coordination |\n| Actions | 8 | Shapes evidence direction |\n| Needs | 8 | Integrated evidence platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic evidence scenarios |', TRUE),

  ('payer-evidence-lead-learner', 'Payer Evidence Lead - Quality Evidence Builder', E'## Payer Evidence Lead (Learner)\n\n### Professional Context\nQuality-focused evidence lead building AI capabilities for payer evidence. Pilots AI for specific evidence types while maintaining quality standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for evidence, validates quality, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Evidence leadership |\n| Pain | 7 | Growing evidence demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated evidence AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Evidence quality scenarios |', TRUE),

  ('payer-evidence-lead-skeptic', 'Payer Evidence Lead - Evidence Integrity Guardian', E'## Payer Evidence Lead (Skeptic)\n\n### Professional Context\nIntegrity-focused evidence lead who questions AI in payer evidence contexts. Emphasizes scientific accuracy and transparent evidence generation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI evidence, requires validation, emphasizes integrity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Evidence role |\n| Pain | 9 | Concerned about AI accuracy |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, transparent AI |\n| Emotions | 3 | Skeptical of AI evidence |\n| Scenarios | 8 | Integrity scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 4: VALUE & EVIDENCE ROLES
-- =====================================================

-- Role 12: Director of Value & Access
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('dir-value-access-automator', 'Director of Value & Access - Value Optimization Expert', E'## Director of Value & Access (Automator)\n\n### Professional Context\nValue-focused director who leverages AI for value proposition development, access strategy optimization, and stakeholder engagement analytics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for value optimization, automates access analytics, optimizes stakeholder engagement\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Director-level leadership |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 8 | Drives value & access strategy |\n| Needs | 8 | AI value optimization tools |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 8 | Value strategy scenarios |', TRUE),

  ('dir-value-access-orchestrator', 'Director of Value & Access - Strategic Value Architect', E'## Director of Value & Access (Orchestrator)\n\n### Professional Context\nStrategic director who orchestrates enterprise value and access strategy using AI-enabled platforms. Coordinates cross-functional value initiatives.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 90%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs enterprise value AI strategy, coordinates functions, builds value excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Strategic leadership role |\n| Pain | 4 | AI handles complexity |\n| Actions | 9 | Shapes value direction |\n| Needs | 9 | Integrated value platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 9 | Enterprise value scenarios |', TRUE),

  ('dir-value-access-learner', 'Director of Value & Access - Capability Builder', E'## Director of Value & Access (Learner)\n\n### Professional Context\nCapability-focused director building AI competencies across the value and access team. Pilots AI initiatives while developing organizational expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 49%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI initiatives, validates results, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Director-level role |\n| Pain | 7 | Growing strategic demands |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Proven AI value tools |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 8 | Capability building scenarios |', TRUE),

  ('dir-value-access-skeptic', 'Director of Value & Access - Value Integrity Guardian', E'## Director of Value & Access (Skeptic)\n\n### Professional Context\nIntegrity-focused director who questions AI in value communication contexts. Emphasizes authentic value propositions and transparent evidence.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 30%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI value claims, requires validation, emphasizes authenticity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Director-level role |\n| Pain | 9 | Concerned about AI integrity |\n| Actions | 6 | Conservative approach |\n| Needs | 9 | Validated, authentic AI |\n| Emotions | 4 | Skeptical of AI value claims |\n| Scenarios | 9 | Value integrity scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 13: Value Evidence Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('value-evidence-lead-automator', 'Value Evidence Lead - Evidence Automation Expert', E'## Value Evidence Lead (Automator)\n\n### Professional Context\nEfficiency-focused value evidence specialist who leverages AI for evidence synthesis, value dossier development, and outcome analysis.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for evidence synthesis, automates dossiers, optimizes analysis workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Evidence leadership role |\n| Pain | 5 | AI reduces evidence burden |\n| Actions | 7 | Leads evidence programs |\n| Needs | 7 | AI evidence tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 7 | Evidence synthesis scenarios |', TRUE),

  ('value-evidence-lead-orchestrator', 'Value Evidence Lead - Strategic Evidence Coordinator', E'## Value Evidence Lead (Orchestrator)\n\n### Professional Context\nStrategic evidence coordinator who orchestrates value evidence programs using AI-enabled research and synthesis platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates evidence programs, designs AI-enabled processes, builds evidence excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic evidence role |\n| Pain | 5 | Program coordination |\n| Actions | 7 | Shapes evidence direction |\n| Needs | 8 | Integrated evidence platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic evidence scenarios |', TRUE),

  ('value-evidence-lead-learner', 'Value Evidence Lead - Quality-Focused Builder', E'## Value Evidence Lead (Learner)\n\n### Professional Context\nQuality-focused evidence lead building AI capabilities for value evidence. Pilots AI for specific evidence types while maintaining quality standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for evidence, validates quality, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Evidence leadership |\n| Pain | 7 | Growing evidence demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated evidence AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Evidence quality scenarios |', TRUE),

  ('value-evidence-lead-skeptic', 'Value Evidence Lead - Scientific Integrity Focus', E'## Value Evidence Lead (Skeptic)\n\n### Professional Context\nIntegrity-focused evidence lead who questions AI in value evidence contexts. Emphasizes scientific accuracy and transparent evidence generation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 27%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI evidence, requires validation, emphasizes integrity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Evidence role |\n| Pain | 9 | Concerned about AI accuracy |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, transparent AI |\n| Emotions | 3 | Skeptical of AI evidence |\n| Scenarios | 8 | Integrity scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 14: Value Proposition Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('value-prop-lead-automator', 'Value Proposition Lead - Message Optimization Expert', E'## Value Proposition Lead (Automator)\n\n### Professional Context\nMessage-focused specialist who leverages AI for value message development, stakeholder targeting, and communication optimization.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for message development, automates targeting, optimizes communications\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Value messaging role |\n| Pain | 5 | AI reduces content burden |\n| Actions | 7 | Leads value messaging |\n| Needs | 7 | AI messaging tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 6 | Messaging scenarios |', TRUE),

  ('value-prop-lead-orchestrator', 'Value Proposition Lead - Strategic Messaging Architect', E'## Value Proposition Lead (Orchestrator)\n\n### Professional Context\nStrategic messaging leader who orchestrates value proposition development using AI-enabled content and stakeholder platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs value messaging AI strategy, coordinates stakeholders, builds messaging excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic messaging role |\n| Pain | 5 | Stakeholder coordination |\n| Actions | 7 | Shapes messaging direction |\n| Needs | 8 | Integrated messaging platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic messaging scenarios |', TRUE),

  ('value-prop-lead-learner', 'Value Proposition Lead - Audience-Focused Builder', E'## Value Proposition Lead (Learner)\n\n### Professional Context\nAudience-focused value proposition specialist building AI capabilities for targeted messaging. Pilots AI for specific audiences while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for messaging, validates effectiveness, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Messaging role |\n| Pain | 7 | Growing audience complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated messaging AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Audience targeting scenarios |', TRUE),

  ('value-prop-lead-skeptic', 'Value Proposition Lead - Message Authenticity Guardian', E'## Value Proposition Lead (Skeptic)\n\n### Professional Context\nAuthenticity-focused value proposition specialist who questions AI in value messaging. Emphasizes genuine value claims and transparent communications.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI messaging, requires validation, emphasizes authenticity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Messaging role |\n| Pain | 8 | Concerned about AI authenticity |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Authentic, validated AI |\n| Emotions | 4 | Skeptical of AI messaging |\n| Scenarios | 7 | Authenticity scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 15: RWE Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('rwe-lead-automator', 'RWE Lead - Real-World Analytics Expert', E'## RWE Lead (Automator)\n\n### Professional Context\nAnalytics-driven RWE specialist who leverages AI for real-world data analysis, claims processing, and outcomes research.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for RWD analysis, automates claims processing, optimizes outcomes research\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | RWE leadership role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Leads RWE programs |\n| Needs | 8 | AI RWD analytics platform |\n| Emotions | 9 | Excited by AI RWE potential |\n| Scenarios | 7 | RWD analysis scenarios |', TRUE),

  ('rwe-lead-orchestrator', 'RWE Lead - Strategic Evidence Architect', E'## RWE Lead (Orchestrator)\n\n### Professional Context\nStrategic RWE leader who orchestrates real-world evidence programs using AI-enabled data platforms and analytics systems.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 90%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs RWE AI strategy, coordinates data partnerships, builds RWE excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic RWE role |\n| Pain | 4 | AI handles data complexity |\n| Actions | 8 | Shapes RWE direction |\n| Needs | 9 | Integrated RWD platform |\n| Emotions | 9 | Energized by AI RWE |\n| Scenarios | 8 | Strategic RWE scenarios |', TRUE),

  ('rwe-lead-learner', 'RWE Lead - Methodology Builder', E'## RWE Lead (Learner)\n\n### Professional Context\nMethodology-focused RWE specialist building AI capabilities for real-world evidence. Explores AI for RWD analysis while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 48%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for RWD, validates methodologies, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | RWE leadership |\n| Pain | 7 | Growing data complexity |\n| Actions | 6 | Measured approach |\n| Needs | 8 | Validated RWE AI |\n| Emotions | 7 | Hopeful about AI potential |\n| Scenarios | 6 | Methodology development scenarios |', TRUE),

  ('rwe-lead-skeptic', 'RWE Lead - Data Quality Guardian', E'## RWE Lead (Skeptic)\n\n### Professional Context\nData quality-focused RWE specialist who questions AI in RWD analysis contexts. Emphasizes data validation and transparent analytical methods.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 29%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI data quality, requires validation, emphasizes transparency\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | RWE role |\n| Pain | 9 | Concerned about AI data quality |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, transparent AI |\n| Emotions | 3 | Skeptical of AI in RWE |\n| Scenarios | 8 | Data quality scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 16: Value & Access Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('value-access-mgr-automator', 'Value & Access Manager - Operations Efficiency Expert', E'## Value & Access Manager (Automator)\n\n### Professional Context\nEfficiency-focused value & access manager who leverages AI for workflow automation, stakeholder tracking, and program analytics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Automates V&A workflows, uses AI for tracking, optimizes program analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Management role |\n| Pain | 5 | AI reduces operational burden |\n| Actions | 6 | Manages V&A operations |\n| Needs | 7 | AI operational tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 5 | Operations scenarios |', TRUE),

  ('value-access-mgr-orchestrator', 'Value & Access Manager - Program Coordinator', E'## Value & Access Manager (Orchestrator)\n\n### Professional Context\nStrategic V&A manager who orchestrates value and access programs using AI-enabled project management and analytics platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates V&A programs, designs AI-enabled processes, builds operational excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Program management role |\n| Pain | 5 | Program coordination |\n| Actions | 7 | Shapes program direction |\n| Needs | 7 | Integrated program platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Program management scenarios |', TRUE),

  ('value-access-mgr-learner', 'Value & Access Manager - Capability Developer', E'## Value & Access Manager (Learner)\n\n### Professional Context\nCapability-focused V&A manager building AI skills for value and access operations. Pilots AI tools while developing team expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 43%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI tools, validates results, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Management role |\n| Pain | 7 | Growing operational demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Capability building scenarios |', TRUE),

  ('value-access-mgr-skeptic', 'Value & Access Manager - Process Control Focus', E'## Value & Access Manager (Skeptic)\n\n### Professional Context\nControl-focused V&A manager who emphasizes process governance and compliance. Skeptical of AI that reduces visibility or control.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes process control, questions AI automation, requires audit trails\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Management role |\n| Pain | 8 | Concerned about AI control |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Transparent, auditable AI |\n| Emotions | 4 | Skeptical of AI automation |\n| Scenarios | 6 | Control scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 17: Senior Value & Access Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sr-value-access-mgr-automator', 'Senior V&A Manager - Strategic Analytics Expert', E'## Senior Value & Access Manager (Automator)\n\n### Professional Context\nAnalytics-driven senior V&A manager who leverages AI for strategic analysis, market insights, and value optimization across portfolios.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for strategic analysis, automates market insights, optimizes portfolio value\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Senior management role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Leads V&A strategy |\n| Needs | 7 | AI strategic analytics |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Strategic analysis scenarios |', TRUE),

  ('sr-value-access-mgr-orchestrator', 'Senior V&A Manager - Portfolio Strategy Leader', E'## Senior Value & Access Manager (Orchestrator)\n\n### Professional Context\nStrategic senior V&A manager who orchestrates portfolio value and access strategy using AI-enabled analytics and planning platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs portfolio AI strategy, coordinates functions, builds strategic excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic leadership role |\n| Pain | 4 | AI handles complexity |\n| Actions | 8 | Shapes portfolio direction |\n| Needs | 8 | Integrated strategy platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Portfolio strategy scenarios |', TRUE),

  ('sr-value-access-mgr-learner', 'Senior V&A Manager - Strategic Capability Builder', E'## Senior Value & Access Manager (Learner)\n\n### Professional Context\nCapability-focused senior V&A manager building AI competencies for strategic analysis. Develops AI expertise while mentoring team members.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops AI expertise, validates strategic outputs, mentors team\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Senior management |\n| Pain | 7 | Growing strategic demands |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Validated strategic AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 7 | Capability development scenarios |', TRUE),

  ('sr-value-access-mgr-skeptic', 'Senior V&A Manager - Strategic Governance Focus', E'## Senior Value & Access Manager (Skeptic)\n\n### Professional Context\nGovernance-focused senior V&A manager who emphasizes strategic rigor and compliance. Skeptical of AI that oversimplifies complex strategic decisions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes strategic rigor, questions AI recommendations, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Senior role |\n| Pain | 9 | Concerned about AI oversimplification |\n| Actions | 5 | Conservative strategic approach |\n| Needs | 9 | Validated, rigorous AI |\n| Emotions | 3 | Skeptical of AI strategy |\n| Scenarios | 8 | Strategic governance scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 18: HEOR Analyst
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('heor-analyst-automator', 'HEOR Analyst - Analysis Automation Expert', E'## HEOR Analyst (Automator)\n\n### Professional Context\nAnalytics-savvy HEOR analyst who leverages AI for economic analysis, literature reviews, and model development support.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 76%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for analysis, automates literature reviews, supports model development\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI analysis tools |\n| Emotions | 8 | Excited by AI analytics |\n| Scenarios | 5 | Analysis scenarios |', TRUE),

  ('heor-analyst-orchestrator', 'HEOR Analyst - Cross-Project Coordinator', E'## HEOR Analyst (Orchestrator)\n\n### Professional Context\nExperienced HEOR analyst who coordinates across multiple projects using AI-enabled research and analysis platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 83%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates across projects, designs AI-enabled workflows, builds analytical excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Experienced analyst |\n| Pain | 5 | Multi-project coordination |\n| Actions | 6 | Strategic analysis decisions |\n| Needs | 7 | Integrated analysis platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Multi-project scenarios |', TRUE),

  ('heor-analyst-learner', 'HEOR Analyst - Analytical Skills Developer', E'## HEOR Analyst (Learner)\n\n### Professional Context\nDevelopment-focused HEOR analyst building AI capabilities for economic analysis. Explores AI tools while developing analytical expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 41%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI tools, validates outputs, builds analytical skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 7 | Growing analysis demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('heor-analyst-skeptic', 'HEOR Analyst - Methodology Quality Focus', E'## HEOR Analyst (Skeptic)\n\n### Professional Context\nMethodology-focused HEOR analyst who questions AI outputs and emphasizes validated analytical methods. Concerned about AI errors in economic analysis.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 23%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI methods, requires validation, emphasizes methodology\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 8 | Concerned about AI errors |\n| Actions | 4 | Conservative approach |\n| Needs | 7 | Validated, accurate AI |\n| Emotions | 3 | Skeptical of AI analysis |\n| Scenarios | 6 | Methodology scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 19: HEOR Specialist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('heor-specialist-automator', 'HEOR Specialist - Research Efficiency Expert', E'## HEOR Specialist (Automator)\n\n### Professional Context\nEfficiency-focused HEOR specialist who leverages AI for research support, data extraction, and evidence synthesis.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 75%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for research support, automates data extraction, optimizes evidence synthesis\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Specialist role |\n| Pain | 5 | AI reduces research burden |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI research tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 5 | Research support scenarios |', TRUE),

  ('heor-specialist-orchestrator', 'HEOR Specialist - Research Project Coordinator', E'## HEOR Specialist (Orchestrator)\n\n### Professional Context\nProject-oriented HEOR specialist who coordinates research activities using AI-enabled project management and research platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates research projects, designs AI-enabled processes, builds research excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Experienced specialist |\n| Pain | 5 | Project coordination |\n| Actions | 6 | Research coordination decisions |\n| Needs | 7 | Integrated research platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Project coordination scenarios |', TRUE),

  ('heor-specialist-learner', 'HEOR Specialist - Research Skills Developer', E'## HEOR Specialist (Learner)\n\n### Professional Context\nDevelopment-focused HEOR specialist building AI capabilities for research. Explores AI tools while developing research expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 40%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for research, validates outputs, builds skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Specialist role |\n| Pain | 7 | Growing research demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('heor-specialist-skeptic', 'HEOR Specialist - Research Quality Focus', E'## HEOR Specialist (Skeptic)\n\n### Professional Context\nQuality-focused HEOR specialist who questions AI in research contexts. Emphasizes validated methods and accurate evidence synthesis.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 22%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI research outputs, requires validation, emphasizes accuracy\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Specialist role |\n| Pain | 8 | Concerned about AI quality |\n| Actions | 4 | Conservative approach |\n| Needs | 7 | Validated, accurate AI |\n| Emotions | 3 | Skeptical of AI research |\n| Scenarios | 6 | Quality scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 20: Health Economist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('health-economist-automator', 'Health Economist - Modeling Automation Expert', E'## Health Economist (Automator)\n\n### Professional Context\nAnalytics-driven health economist who leverages AI for economic modeling, sensitivity analysis, and budget impact calculations.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for modeling, automates sensitivity analyses, optimizes calculations\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Economist role |\n| Pain | 5 | AI reduces modeling burden |\n| Actions | 6 | Economic modeling decisions |\n| Needs | 7 | AI modeling tools |\n| Emotions | 8 | Excited by AI modeling |\n| Scenarios | 6 | Modeling scenarios |', TRUE),

  ('health-economist-orchestrator', 'Health Economist - Strategic Economic Advisor', E'## Health Economist (Orchestrator)\n\n### Professional Context\nStrategic health economist who coordinates complex economic analyses using AI-enabled modeling and research platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates economic analyses, designs AI-enabled methodologies, builds modeling excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Senior economist |\n| Pain | 5 | Complex coordination |\n| Actions | 7 | Strategic economic decisions |\n| Needs | 8 | Integrated economics platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic economic scenarios |', TRUE),

  ('health-economist-learner', 'Health Economist - Methods Developer', E'## Health Economist (Learner)\n\n### Professional Context\nMethods-focused health economist building AI capabilities for economic modeling. Explores AI for specific analyses while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for modeling, validates methodologies, builds skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Economist role |\n| Pain | 7 | Growing modeling demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated economic AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 6 | Methods development scenarios |', TRUE),

  ('health-economist-skeptic', 'Health Economist - Methodological Rigor Guardian', E'## Health Economist (Skeptic)\n\n### Professional Context\nMethodology-focused health economist who questions AI in economic modeling. Emphasizes validated methods, transparent assumptions, and rigorous analysis.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI models, requires validation, emphasizes rigor\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Economist role |\n| Pain | 9 | Concerned about AI methods |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, rigorous AI |\n| Emotions | 3 | Skeptical of AI modeling |\n| Scenarios | 8 | Methodology rigor scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- VERIFICATION QUERY
-- =====================================================
-- Run this after migration to verify:
-- SELECT persona_key, display_name, is_active
-- FROM personas
-- WHERE persona_key LIKE 'dir-health-econ-%'
--    OR persona_key LIKE 'global-heor-%'
--    OR persona_key LIKE 'sr-health-economist-%'
--    OR persona_key LIKE 'global-pricing-%'
--    OR persona_key LIKE 'global-reimb-%'
--    OR persona_key LIKE 'value-pricing-%'
--    OR persona_key LIKE 'global-payer-%'
--    OR persona_key LIKE 'payer-%'
--    OR persona_key LIKE 'dir-value-%'
--    OR persona_key LIKE 'value-evidence-%'
--    OR persona_key LIKE 'value-prop-%'
--    OR persona_key LIKE 'rwe-%'
--    OR persona_key LIKE 'value-access-%'
--    OR persona_key LIKE 'sr-value-access-%'
--    OR persona_key LIKE 'heor-analyst-%'
--    OR persona_key LIKE 'heor-specialist-%'
--    OR persona_key LIKE 'health-economist-%'
--    OR persona_key LIKE 'outcomes-res-%'
-- ORDER BY persona_key;

-- Expected: 80 rows (20 roles × 4 archetypes)
