'use client';

/**
 * V0 Node Generator Modal
 * 
 * Modal for generating custom workflow nodes using v0 AI.
 * Integrates with @vital/ai-ui shared components for consistency.
 */

import React, { useState, useCallback } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Sparkles, Plus, ExternalLink, Code, Copy, Check } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

// Import shared v0 components from @vital/ai-ui package
// TODO: Configure @vital/ai-ui path alias for production
import {
  VitalV0GeneratorPanel,
  VitalV0PreviewFrame,
  type V0GenerationResponse,
  type V0WorkflowContext,
} from '../../../../../../../packages/vital-ai-ui/src/v0';

import type { NodeTypeDefinition } from '../../constants/node-types';

interface V0NodeGeneratorModalProps {
  /** Whether the modal is open */
  open: boolean;
  /** Callback when modal open state changes */
  onOpenChange: (open: boolean) => void;
  /** Current workflow context */
  workflowContext: V0WorkflowContext;
  /** Callback when a node is successfully generated and added */
  onNodeGenerated: (nodeDefinition: Partial<NodeTypeDefinition>, previewUrl: string, chatId: string) => void;
  /** Callback for logging messages */
  onLog?: (message: string, level: 'info' | 'success' | 'error') => void;
}

/**
 * Medical Affairs KOL Engagement workflow examples for POC
 */
const KOL_WORKFLOW_EXAMPLES = [
  {
    label: 'KOL Influence Scorer',
    prompt: `Create a KOL Influence Scorer workflow node that displays:
- H-index with trend indicator (up/down arrow)
- Publication count with activity badge
- Citation impact score (0-100)
- Conference presentations count
- Editorial board memberships
- Overall influence percentile (gradient bar)
Use a card layout with collapsible sections for details. 
Purple/blue healthcare color scheme.`,
    category: 'Medical Affairs',
  },
  {
    label: 'Compliance Gateway',
    prompt: `Create a Compliance Gateway workflow node that shows:
- Pre-engagement checklist items (SOPs followed, approvals obtained, budget verified)
- Overall compliance score percentage
- Required approvals status with approver names
- Proceed/Hold decision button
- Compliance history log expandable section
Use traffic light colors (green/yellow/red) for status indicators.`,
    category: 'Medical Affairs',
  },
  {
    label: 'Engagement Tracker',
    prompt: `Create an Engagement Tracker workflow node that displays:
- Meeting history timeline (vertical)
- Sentiment analysis indicator (positive/neutral/negative)
- Follow-up tasks with due dates and owners
- Relationship strength meter (1-10)
- Next recommended actions list
- Export functionality button
Clean healthcare-appropriate design with blue accents.`,
    category: 'Medical Affairs',
  },
  {
    label: 'Publication Analyzer',
    prompt: `Create a Publication Analyzer workflow node showing:
- Recent publications list with titles and journals
- Impact factor badges
- Co-author network mini-graph
- Citation count trend sparkline
- Therapeutic area tags
- "View Full Profile" expandable section
Academic/professional styling.`,
    category: 'Medical Affairs',
  },
];

export function V0NodeGeneratorModal({
  open,
  onOpenChange,
  workflowContext,
  onNodeGenerated,
  onLog,
}: V0NodeGeneratorModalProps) {
  const [generatedResult, setGeneratedResult] = useState<V0GenerationResponse | null>(null);
  const [activeTab, setActiveTab] = useState<'generate' | 'preview' | 'code'>('generate');
  const [copied, setCopied] = useState(false);

  const handleGenerationComplete = useCallback((result: V0GenerationResponse) => {
    setGeneratedResult(result);
    setActiveTab('preview');
    onLog?.(`Generated ${result.generationType} preview`, 'success');
  }, [onLog]);

  const handleAddToWorkflow = useCallback(() => {
    if (!generatedResult) return;

    // Create a custom node definition based on v0 generation
    const customNodeDef: Partial<NodeTypeDefinition> = {
      type: `v0-custom-${Date.now()}` as any,
      label: 'v0 Generated Node',
      description: 'Custom node generated by v0 AI',
      color: '#7c3aed',
      bgColor: '#f3e8ff',
      borderColor: '#c4b5fd',
      category: 'tool',
      defaultConfig: {
        v0ChatId: generatedResult.chatId,
        v0PreviewUrl: generatedResult.previewUrl,
        generationType: generatedResult.generationType,
        generatedAt: generatedResult.timestamp,
      },
    };

    onNodeGenerated(customNodeDef, generatedResult.previewUrl, generatedResult.chatId);
    onLog?.('Custom node added to workflow palette', 'success');
    
    // Reset and close
    setGeneratedResult(null);
    setActiveTab('generate');
    onOpenChange(false);
  }, [generatedResult, onNodeGenerated, onLog, onOpenChange]);

  const handleCopyUrl = useCallback(async () => {
    if (generatedResult?.previewUrl) {
      await navigator.clipboard.writeText(generatedResult.previewUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [generatedResult]);

  const handleClose = useCallback(() => {
    setGeneratedResult(null);
    setActiveTab('generate');
    onOpenChange(false);
  }, [onOpenChange]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl max-h-[90vh] flex flex-col p-0">
        <DialogHeader className="px-6 pt-6 pb-4 border-b">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-gradient-to-br from-violet-500 to-purple-600 shadow-md">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <DialogTitle className="text-xl">
                Generate Custom Node with v0 AI
              </DialogTitle>
              <DialogDescription>
                Describe the workflow node you need and v0 will generate a custom React component
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as any)} className="flex-1 flex flex-col overflow-hidden">
          <TabsList className="mx-6 mt-4">
            <TabsTrigger value="generate" className="gap-2">
              <Sparkles className="h-4 w-4" />
              Generate
            </TabsTrigger>
            <TabsTrigger value="preview" className="gap-2" disabled={!generatedResult}>
              <ExternalLink className="h-4 w-4" />
              Preview
              {generatedResult && (
                <Badge variant="secondary" className="ml-1 text-[10px]">Ready</Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="code" className="gap-2" disabled={!generatedResult}>
              <Code className="h-4 w-4" />
              Code
            </TabsTrigger>
          </TabsList>

          <div className="flex-1 overflow-hidden p-6">
            <TabsContent value="generate" className="h-full m-0">
              <VitalV0GeneratorPanel
                defaultType="workflow-node"
                workflowContext={workflowContext}
                onGenerationComplete={handleGenerationComplete}
                className="h-full"
              />
            </TabsContent>

            <TabsContent value="preview" className="h-full m-0">
              {generatedResult && (
                <div className="h-full flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Badge variant="default" className="bg-green-600 gap-1">
                        <Check className="h-3 w-3" />
                        Generated
                      </Badge>
                      <span className="text-sm text-muted-foreground">
                        {new Date(generatedResult.timestamp).toLocaleString()}
                      </span>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" onClick={handleCopyUrl}>
                        {copied ? (
                          <Check className="h-4 w-4 mr-1" />
                        ) : (
                          <Copy className="h-4 w-4 mr-1" />
                        )}
                        {copied ? 'Copied!' : 'Copy URL'}
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => window.open(generatedResult.previewUrl, '_blank')}
                      >
                        <ExternalLink className="h-4 w-4 mr-1" />
                        Open in v0
                      </Button>
                    </div>
                  </div>

                  <VitalV0PreviewFrame
                    previewUrl={generatedResult.previewUrl}
                    chatId={generatedResult.chatId}
                    title="Generated Workflow Node"
                    className="flex-1"
                  />
                </div>
              )}
            </TabsContent>

            <TabsContent value="code" className="h-full m-0">
              {generatedResult && (
                <div className="h-full flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <p className="text-sm text-muted-foreground">
                      View the generated code in v0.dev to copy and customize
                    </p>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => window.open(generatedResult.previewUrl, '_blank')}
                    >
                      <Code className="h-4 w-4 mr-1" />
                      View Code in v0
                    </Button>
                  </div>
                  
                  <div className="flex-1 rounded-lg border bg-muted/30 p-6 flex items-center justify-center">
                    <div className="text-center space-y-4 max-w-md">
                      <Code className="h-12 w-12 text-muted-foreground mx-auto" />
                      <div>
                        <h3 className="font-semibold mb-2">Code Available in v0</h3>
                        <p className="text-sm text-muted-foreground">
                          Click "View Code in v0" to see the generated React component code.
                          You can copy and customize it directly in the v0 editor.
                        </p>
                      </div>
                      <Button onClick={() => window.open(generatedResult.previewUrl, '_blank')}>
                        <ExternalLink className="h-4 w-4 mr-2" />
                        Open v0 Editor
                      </Button>
                    </div>
                  </div>
                </div>
              )}
            </TabsContent>
          </div>
        </Tabs>

        <DialogFooter className="px-6 py-4 border-t bg-muted/30">
          <div className="flex items-center justify-between w-full">
            <div>
              {generatedResult && (
                <Badge variant="outline" className="gap-1">
                  <ExternalLink className="h-3 w-3" />
                  Preview ready - Review before adding
                </Badge>
              )}
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleClose}>
                Cancel
              </Button>
              <Button
                onClick={handleAddToWorkflow}
                disabled={!generatedResult}
                className="bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700"
              >
                <Plus className="h-4 w-4 mr-2" />
                Add to Workflow
              </Button>
            </div>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default V0NodeGeneratorModal;











