-- ============================================================================
-- Seed canonical knowledge domains (global, enterprise, user scopes)
-- Source: database/sql/seeds/knowledge_domains_full.json
-- ============================================================================

WITH payload AS (
  SELECT
    jsonb_build_object(
      'domains', jsonb '[
        {
          "domain_id": "regulatory_affairs",
          "parent_domain_id": null,
          "function_id": "regulatory_compliance",
          "function_name": "Regulatory & Compliance",
          "domain_name": "Regulatory Affairs",
          "domain_description_llm": "Covers regulatory strategy, submissions, approvals, labeling, lifecycle variations and interactions with authorities for medicinal products and digital health solutions. Use this domain for questions about approval pathways, dossier content, clinical evidence requirements for approval, and post-approval obligations.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Digital Health Startup"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "High",
          "pii_sensitivity": "Low",
          "lifecycle_stage": ["Pre-Launch", "Launch", "Post-Launch"],
          "governance_owner": "Regulatory Affairs Function",
          "last_review_owner_role": "Head of Regulatory Affairs",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.95,
          "access_policy": "public"
        },
        {
          "domain_id": "safety_pharmacovigilance",
          "parent_domain_id": null,
          "function_id": "regulatory_compliance",
          "function_name": "Regulatory & Compliance",
          "domain_name": "Pharmacovigilance & Safety Reporting",
          "domain_description_llm": "Covers safety surveillance, adverse event collection, signal detection, risk management plans, and benefit-risk monitoring for products in market and in clinical development. Use this domain for questions about safety obligations, safety signal escalation, and post-marketing safety commitments.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Healthcare Provider"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "High",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Clinical Development", "Post-Launch"],
          "governance_owner": "Drug Safety / PV Function",
          "last_review_owner_role": "Safety Officer",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.90,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "data_privacy_ethics",
          "parent_domain_id": null,
          "function_id": "regulatory_compliance",
          "function_name": "Regulatory & Compliance",
          "domain_name": "Data Privacy, Consent & Ethics",
          "domain_description_llm": "Covers patient consent, lawful basis for processing health data, secondary use of data, de-identification, ethical review, and data sharing governance. Use this domain for questions about whether certain patient/claims/EHR data can be collected, linked, analyzed, or shared legally and ethically.",
          "tenants_primary": ["Healthcare Provider", "Payer"],
          "tenants_secondary": ["Pharmaceutical", "Digital Health Startup"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "High",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Clinical Development", "Post-Launch", "Real-World Evidence"],
          "governance_owner": "Privacy / Compliance Office",
          "last_review_owner_role": "Data Protection Officer",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.95,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "samd_dtx_regulation",
          "parent_domain_id": null,
          "function_id": "regulatory_compliance",
          "function_name": "Regulatory & Compliance",
          "domain_name": "Software as a Medical Device / Digital Therapeutics Regulation",
          "domain_description_llm": "Covers classification, regulatory pathways, cybersecurity obligations, clinical validation expectations, and post-market surveillance for software-based medical products and digital therapeutics. Use for questions about how a digital solution is regulated, which approval pathway applies, and what evidence is required.",
          "tenants_primary": ["Digital Health Startup"],
          "tenants_secondary": ["Pharmaceutical", "Payer"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Specialized",
          "regulatory_exposure": "High",
          "pii_sensitivity": "Medium",
          "lifecycle_stage": ["Pre-Launch", "Launch", "Post-Launch"],
          "governance_owner": "Regulatory / Digital Health Compliance",
          "last_review_owner_role": "Digital Regulatory Lead",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.92,
          "access_policy": "public"
        },
        {
          "domain_id": "clinical_development_trial_design",
          "parent_domain_id": null,
          "function_id": "research_clinical_development",
          "function_name": "Research & Clinical Development",
          "domain_name": "Clinical Development & Trial Design",
          "domain_description_llm": "Covers clinical development strategy, trial phase design, endpoints, comparator selection, adaptive trials, and protocol justification for efficacy/safety. Use this domain for questions about how to design, justify, or run a clinical trial.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Digital Health Startup", "Healthcare Provider"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "High",
          "pii_sensitivity": "Medium",
          "lifecycle_stage": ["Clinical Development", "Pre-Launch"],
          "governance_owner": "Clinical Development Function",
          "last_review_owner_role": "Head of Clinical Development",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.95,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "rwe_real_world_evidence",
          "parent_domain_id": null,
          "function_id": "digital_data_ai",
          "function_name": "Digital, Data & AI",
          "domain_name": "Real-World Data & Real-World Evidence (RWE)",
          "domain_description_llm": "Covers use of observational data, claims data, registry data, EHR data, and patient-reported outcomes to generate evidence of effectiveness, safety, burden-of-disease, unmet need, and value. Use this domain for questions about leveraging real-world data for regulatory, market access, clinical, or policy decisions.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Payer", "Healthcare Provider"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "High",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Post-Launch", "In-Market Optimization"],
          "governance_owner": "RWE / Evidence Generation",
          "last_review_owner_role": "RWE Lead",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.95,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "heor_health_economics",
          "parent_domain_id": null,
          "function_id": "market_access_heor",
          "function_name": "Market Access & Health Economics",
          "domain_name": "Health Economics & Outcomes Research (HEOR)",
          "domain_description_llm": "Covers cost-effectiveness models, budget impact models, QALY analyses, burden-of-disease, and comparative effectiveness. Use this domain for questions about economic value, payer evidence expectations, and how to demonstrate value for money.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Payer"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "Low",
          "lifecycle_stage": ["Launch", "Post-Launch", "Reimbursement Negotiation"],
          "governance_owner": "HEOR / Market Access Function",
          "last_review_owner_role": "HEOR Lead",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.95,
          "access_policy": "public"
        },
        {
          "domain_id": "hta_reimbursement_assessment",
          "parent_domain_id": null,
          "function_id": "market_access_heor",
          "function_name": "Market Access & Health Economics",
          "domain_name": "HTA & Reimbursement Assessment",
          "domain_description_llm": "Covers health technology assessment, reimbursement decision frameworks, coverage criteria, willingness-to-pay thresholds, and payer evidence standards. Use this domain for questions about whether a therapy or digital intervention will be reimbursed and under what conditions.",
          "tenants_primary": ["Payer"],
          "tenants_secondary": ["Pharmaceutical"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "Low",
          "lifecycle_stage": ["Launch", "Post-Launch"],
          "governance_owner": "Payer / Reimbursement Function",
          "last_review_owner_role": "Reimbursement Policy Lead",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.93,
          "access_policy": "public"
        },
        {
          "domain_id": "clinical_practice_guidelines",
          "parent_domain_id": null,
          "function_id": "care_delivery_clinical_practice",
          "function_name": "Care Delivery & Clinical Practice",
          "domain_name": "Clinical Practice Guidelines & Standard of Care",
          "domain_description_llm": "Covers evidence-based clinical guidelines, diagnostic and treatment pathways, dosing protocols, escalation criteria, and monitoring standards in routine care. Use this domain for questions about how clinicians should diagnose, treat, and monitor a given condition today in practice.",
          "tenants_primary": ["Healthcare Provider"],
          "tenants_secondary": ["Pharmaceutical"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority",
          "maturity_level": "Established",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "Low",
          "lifecycle_stage": ["Clinical Practice", "Post-Launch"],
          "governance_owner": "Clinical Governance / Medical Leadership",
          "last_review_owner_role": "Chief Medical Officer",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.94,
          "access_policy": "public"
        },
        {
          "domain_id": "strategic_governance_esg",
          "parent_domain_id": null,
          "function_id": "corporate_governance_esg",
          "function_name": "Corporate, Governance & ESG",
          "domain_name": "Risk Management, Governance & ESG",
          "domain_description_llm": "Covers corporate governance, compliance risk, responsible innovation, sustainability expectations, and alignment of decisions with environmental/social/governance principles. Use this domain for questions about acceptable conduct, exposure to compliance risk, and long-term sustainability posture.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Payer", "Healthcare Provider", "Digital Health Startup"],
          "is_cross_tenant": true,
          "domain_scope": "global",
          "enterprise_id": null,
          "owner_user_id": null,
          "tier": 3,
          "tier_label": "Emerging / Fast-Evolving",
          "maturity_level": "Emerging",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "Low",
          "lifecycle_stage": ["Corporate Strategy", "Operational Transformation"],
          "governance_owner": "Corporate Governance / ESG Office",
          "last_review_owner_role": "ESG / Risk Lead",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.75,
          "access_policy": "public"
        },
        {
          "domain_id": "hta_reimbursement_assessment.enterprise_x",
          "parent_domain_id": "hta_reimbursement_assessment",
          "function_id": "market_access_heor",
          "function_name": "Market Access & Health Economics",
          "domain_name": "HTA & Reimbursement Assessment (Enterprise X)",
          "domain_description_llm": "Enterprise X–specific payer assessment logic, internal negotiation playbooks, known payer objections, escalation procedures, and local willingness-to-pay patterns. Use this domain for questions about how Enterprise X prepares and defends value for coverage decisions in its key markets.",
          "tenants_primary": ["Payer"],
          "tenants_secondary": ["Pharmaceutical"],
          "is_cross_tenant": false,
          "domain_scope": "enterprise",
          "enterprise_id": "enterprise_x",
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority (Local)",
          "maturity_level": "Established",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "Medium",
          "lifecycle_stage": ["Launch", "Post-Launch"],
          "governance_owner": "Market Access / Reimbursement Team - Enterprise X",
          "last_review_owner_role": "Local Reimbursement Lead - Enterprise X",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.97,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "rwe_real_world_evidence.enterprise_x",
          "parent_domain_id": "rwe_real_world_evidence",
          "function_id": "digital_data_ai",
          "function_name": "Digital, Data & AI",
          "domain_name": "Real-World Evidence (Enterprise X Registry & Claims Data)",
          "domain_description_llm": "Enterprise X’s internal RWE methods, local registry structures, claims data pipelines, linkage rules, and evidence packages already delivered to stakeholders. Use this for questions about how Enterprise X actually collects, cleans, links, and interprets its real-world data.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Payer", "Healthcare Provider"],
          "is_cross_tenant": false,
          "domain_scope": "enterprise",
          "enterprise_id": "enterprise_x",
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority (Local)",
          "maturity_level": "Specialized",
          "regulatory_exposure": "High",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Post-Launch", "In-Market Optimization"],
          "governance_owner": "Evidence & RWE Analytics - Enterprise X",
          "last_review_owner_role": "RWE Data Steward - Enterprise X",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.98,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "clinical_practice_guidelines.enterprise_x",
          "parent_domain_id": "clinical_practice_guidelines",
          "function_id": "care_delivery_clinical_practice",
          "function_name": "Care Delivery & Clinical Practice",
          "domain_name": "Clinical Practice Guidelines (Enterprise X Care Network)",
          "domain_description_llm": "Locally approved clinical pathways, dosing protocols, referral criteria, escalation/step-up rules, digital triage tools, and quality KPIs enforced across Enterprise X’s network. Use this domain for questions about how clinicians inside Enterprise X are expected to behave in day-to-day care.",
          "tenants_primary": ["Healthcare Provider"],
          "tenants_secondary": ["Payer"],
          "is_cross_tenant": false,
          "domain_scope": "enterprise",
          "enterprise_id": "enterprise_x",
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority (Local)",
          "maturity_level": "Established",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "Medium",
          "lifecycle_stage": ["Clinical Practice", "Post-Launch"],
          "governance_owner": "Clinical Governance - Enterprise X",
          "last_review_owner_role": "Chief Medical Officer - Enterprise X",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.99,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "pricing_and_contracting_strategy.enterprise_x",
          "parent_domain_id": "heor_health_economics",
          "function_id": "market_access_heor",
          "function_name": "Market Access & Health Economics",
          "domain_name": "Pricing & Contracting Playbook (Enterprise X)",
          "domain_description_llm": "Enterprise X’s internal pricing corridors, negotiation playbooks, discount guardrails, preferred contract structures, escalation thresholds, and historical payer objection handling. Use for questions about what we actually offer and accept during price negotiations.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Payer"],
          "is_cross_tenant": false,
          "domain_scope": "enterprise",
          "enterprise_id": "enterprise_x",
          "owner_user_id": null,
          "tier": 1,
          "tier_label": "Core / High Authority (Local)",
          "maturity_level": "Established",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Launch", "Post-Launch", "Reimbursement Negotiation"],
          "governance_owner": "Market Access / Pricing - Enterprise X",
          "last_review_owner_role": "Pricing Lead - Enterprise X",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.98,
          "access_policy": "enterprise_confidential"
        },
        {
          "domain_id": "hta_negotiation_notes_q4.user_a",
          "parent_domain_id": "hta_reimbursement_assessment.enterprise_x",
          "function_id": "market_access_heor",
          "function_name": "Market Access & Health Economics",
          "domain_name": "HTA Objection / Negotiation Notes Q4 (User A)",
          "domain_description_llm": "Running notes from active reimbursement negotiations, including payer objections, informal arguments that worked, and escalation points. Use this only if the question explicitly asks for current deal status, payer pushback, or in-progress negotiation tactics.",
          "tenants_primary": ["Payer"],
          "tenants_secondary": ["Pharmaceutical"],
          "is_cross_tenant": false,
          "domain_scope": "user",
          "enterprise_id": "enterprise_x",
          "owner_user_id": "user_a",
          "tier": 2,
          "tier_label": "Specialized / Working Material",
          "maturity_level": "Draft",
          "regulatory_exposure": "Medium",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Post-Launch", "Reimbursement Negotiation"],
          "governance_owner": "User A",
          "last_review_owner_role": "User A",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.40,
          "access_policy": "personal_draft"
        },
        {
          "domain_id": "rwe_local_signal_log.user_a",
          "parent_domain_id": "rwe_real_world_evidence.enterprise_x",
          "function_id": "digital_data_ai",
          "function_name": "Digital, Data & AI",
          "domain_name": "RWE Signal Log – Emerging Safety / Outcomes Flags (User A)",
          "domain_description_llm": "Early, unvalidated RWE observations captured by User A: unexpected outcomes, adherence drop-offs, site complaints, clinician feedback. Use ONLY if the question is about potential safety signals, operational red flags, or hypotheses to investigate — not for final evidence.",
          "tenants_primary": ["Pharmaceutical"],
          "tenants_secondary": ["Healthcare Provider"],
          "is_cross_tenant": false,
          "domain_scope": "user",
          "enterprise_id": "enterprise_x",
          "owner_user_id": "user_a",
          "tier": 3,
          "tier_label": "Emerging / Unvalidated Notes",
          "maturity_level": "Draft",
          "regulatory_exposure": "High",
          "pii_sensitivity": "High",
          "lifecycle_stage": ["Post-Launch", "In-Market Optimization"],
          "governance_owner": "User A",
          "last_review_owner_role": "User A",
          "embedding_model": "text-embedding-3-large",
          "rag_priority_weight": 0.30,
          "access_policy": "personal_draft"
        }
      ]'
    ) AS payload
)
INSERT INTO knowledge_domains (
  domain_id,
  parent_domain_id,
  function_id,
  function_name,
  domain_name,
  domain_description_llm,
  tenants_primary,
  tenants_secondary,
  is_cross_tenant,
  domain_scope,
  enterprise_id,
  owner_user_id,
  tier,
  tier_label,
  maturity_level,
  regulatory_exposure,
  pii_sensitivity,
  lifecycle_stage,
  governance_owner,
  last_review_owner_role,
  embedding_model,
  rag_priority_weight,
  access_policy
)
SELECT
  (d->>'domain_id'),
  NULLIF(d->>'parent_domain_id', '') AS parent_domain_id,
  d->>'function_id',
  d->>'function_name',
  d->>'domain_name',
  d->>'domain_description_llm',
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(d->'tenants_primary')), ARRAY[]::TEXT[]),
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(d->'tenants_secondary')), ARRAY[]::TEXT[]),
  COALESCE((d->>'is_cross_tenant')::BOOLEAN, FALSE),
  d->>'domain_scope',
  NULLIF(d->>'enterprise_id', ''),
  NULLIF(d->>'owner_user_id', ''),
  COALESCE((d->>'tier')::INTEGER, 3),
  d->>'tier_label',
  COALESCE(d->>'maturity_level', 'Draft'),
  COALESCE(d->>'regulatory_exposure', 'Medium'),
  COALESCE(d->>'pii_sensitivity', 'Low'),
  COALESCE(ARRAY(SELECT jsonb_array_elements_text(d->'lifecycle_stage')), ARRAY[]::TEXT[]),
  d->>'governance_owner',
  d->>'last_review_owner_role',
  d->>'embedding_model',
  COALESCE((d->>'rag_priority_weight')::NUMERIC, 0.5),
  COALESCE(d->>'access_policy', 'public')
FROM payload,
     jsonb_array_elements(payload.payload->'domains') AS d
ON CONFLICT (domain_id) DO UPDATE
SET
  parent_domain_id = EXCLUDED.parent_domain_id,
  function_id = EXCLUDED.function_id,
  function_name = EXCLUDED.function_name,
  domain_name = EXCLUDED.domain_name,
  domain_description_llm = EXCLUDED.domain_description_llm,
  tenants_primary = EXCLUDED.tenants_primary,
  tenants_secondary = EXCLUDED.tenants_secondary,
  is_cross_tenant = EXCLUDED.is_cross_tenant,
  domain_scope = EXCLUDED.domain_scope,
  enterprise_id = EXCLUDED.enterprise_id,
  owner_user_id = EXCLUDED.owner_user_id,
  tier = EXCLUDED.tier,
  tier_label = EXCLUDED.tier_label,
  maturity_level = EXCLUDED.maturity_level,
  regulatory_exposure = EXCLUDED.regulatory_exposure,
  pii_sensitivity = EXCLUDED.pii_sensitivity,
  lifecycle_stage = EXCLUDED.lifecycle_stage,
  governance_owner = EXCLUDED.governance_owner,
  last_review_owner_role = EXCLUDED.last_review_owner_role,
  embedding_model = EXCLUDED.embedding_model,
  rag_priority_weight = EXCLUDED.rag_priority_weight,
  access_policy = EXCLUDED.access_policy,
  updated_at = now();
