#!/bin/bash
# Registry 250 - Quick Execution Script
# Use this to quickly copy SQL files to clipboard for execution

echo "========================================================================"
echo "🚀 REGISTRY 250 - SQL FILES QUICK ACCESS"
echo "========================================================================"
echo ""
echo "📁 All SQL files are ready in: scripts/"
echo ""
echo "Individual batch files (READY TO EXECUTE):"
echo "  - exec_batch_04.sql  →  Agents 76-100   (33KB)"
echo "  - exec_batch_05.sql  →  Agents 101-125  (34KB)"
echo "  - exec_batch_06.sql  →  Agents 126-150  (33KB)"
echo "  - exec_batch_07.sql  →  Agents 151-175  (34KB)"
echo "  - exec_batch_08.sql  →  Agents 176-200  (34KB)"
echo "  - exec_batch_09.sql  →  Agents 201-225  (32KB)"
echo "  - exec_batch_10.sql  →  Agents 226-250  (33KB)"
echo ""
echo "========================================================================"
echo "📋 TO EXECUTE:"
echo "========================================================================"
echo ""
echo "Option 1 - Copy to clipboard (Mac):"
echo "  cat scripts/exec_batch_04.sql | pbcopy"
echo "  Then paste into Supabase SQL Editor"
echo ""
echo "Option 2 - View file:"
echo "  cat scripts/exec_batch_04.sql"
echo ""
echo "Option 3 - Execute all via psql:"
echo "  for i in {04..10}; do"
echo "    psql \$DATABASE_URL -f scripts/exec_batch_\${i}.sql"
echo "  done"
echo ""
echo "========================================================================"
echo "✅ All files verified and ready!"
echo "========================================================================"

