#!/bin/bash
echo "═══════════════════════════════════════════════════════════"
echo "  AgentOS 3.0 - Supabase Migration Instructions"
echo "═══════════════════════════════════════════════════════════"
echo ""
SUPABASE_URL=$(grep "SUPABASE_URL" .env.local 2>/dev/null | cut -d '=' -f2 | tr -d '"' | tr -d "'" | xargs)
if [ ! -z "$SUPABASE_URL" ]; then
    SUPABASE_PROJECT_ID=$(echo $SUPABASE_URL | sed -n 's/.*https:\/\/\([^.]*\)\.supabase\.co.*/\1/p')
    echo "📋 Your Supabase Project: $SUPABASE_PROJECT_ID"
    echo "🔗 SQL Editor: https://supabase.com/dashboard/project/$SUPABASE_PROJECT_ID/sql/new"
else
    echo "⚠️  Could not find SUPABASE_URL in .env.local"
    echo "🔗 Go to: https://supabase.com/dashboard"
fi
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  INSTRUCTIONS:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Open Supabase SQL Editor (link above)"
echo ""
echo "2. Run Migration (Infrastructure):"
echo "   - Open: database/migrations/20251126_system_prompt_infrastructure.sql"
echo "   - Copy entire file"
echo "   - Paste in SQL Editor and click 'Run'"
echo ""
echo "3. Run Seed Data:"
echo "   - Open: database/seeds/20251126_system_prompt_seed_data.sql"
echo "   - Copy entire file"
echo "   - Paste in SQL Editor and click 'Run'"
echo ""
echo "4. Verify with this query:"
echo ""
echo "   SELECT 'system_prompt_templates' as table_name, count(*) as rows"
echo "   FROM system_prompt_templates"
echo "   UNION ALL"
echo "   SELECT 'worker_pool_config', count(*) FROM worker_pool_config"
echo "   UNION ALL"
echo "   SELECT 'tool_registry', count(*) FROM tool_registry;"
echo ""
echo "═══════════════════════════════════════════════════════════"
