-- =====================================================
-- CORPORATE SUPPORT FUNCTIONS PERSONAS SEED DATA
-- Migration: 20251129_046_corporate_support_personas_seed.sql
-- Description: Seeds 80 personas for 20 Corporate Support role types
-- Functions: Pharmacovigilance, Manufacturing/Quality, Supply Chain, Finance, HR, Legal
-- MECE Framework: 4 archetypes per role (AUTOMATOR, ORCHESTRATOR, LEARNER, SKEPTIC)
-- =====================================================

-- SECTION 1: PHARMACOVIGILANCE / DRUG SAFETY (4 roles, 16 personas)
-- 1. VP of Patient Safety
-- 2. Director of Patient Safety
-- 3. Senior Safety Scientist
-- 4. Drug Safety Officer

-- SECTION 2: MANUFACTURING & QUALITY (5 roles, 20 personas)
-- 5. VP of Quality
-- 6. Director of Quality Assurance
-- 7. Director of Quality Engineering
-- 8. Senior Quality Manager
-- 9. Quality Assurance Specialist

-- SECTION 3: SUPPLY CHAIN (3 roles, 12 personas)
-- 10. VP of Supply Chain
-- 11. Supply Chain Director
-- 12. Supply Planner

-- SECTION 4: FINANCE (4 roles, 16 personas)
-- 13. VP of Finance
-- 14. Director of Finance
-- 15. Finance Business Partner
-- 16. Financial Analyst

-- SECTION 5: HR (3 roles, 12 personas)
-- 17. VP of Human Resources
-- 18. Senior HR Business Partner
-- 19. HR Business Partner

-- SECTION 6: LEGAL (1 role, 4 personas)
-- 20. VP of Legal

-- =====================================================
-- SECTION 1: PHARMACOVIGILANCE / DRUG SAFETY
-- =====================================================

-- 1. VP OF PATIENT SAFETY
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('vp_patient_safety_automator', 'Dr. Victoria Chen - VP Patient Safety Automator', E'**Role:** VP of Patient Safety\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 82/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nDr. Chen has transformed pharmacovigilance through AI-powered signal detection, automated case processing, and predictive safety analytics. She champions AI to enhance patient safety while maintaining regulatory compliance.\n\n## VPANES Scores\n- **Visibility:** 10/10 - Board-level patient safety accountability\n- **Pain:** 7/10 - Managing global safety data volumes\n- **Actions:** 9/10 - AI-automated safety monitoring\n- **Needs:** 9/10 - Predictive safety signal detection\n- **Emotions:** 8/10 - Confident in AI patient safety benefits\n- **Scenarios:** Enterprise pharmacovigilance transformation\n\n## Goals\n- Reduce signal detection time by 50% through AI\n- Build predictive safety analytics capabilities\n- Transform case processing with automation\n\n## Frustrations\n- Legacy safety database limitations\n- Regulatory uncertainty on AI in PV\n- Data quality across global safety networks', true, NOW(), NOW()),
('vp_patient_safety_orchestrator', 'Dr. Margaret Sullivan - VP Patient Safety Orchestrator', E'**Role:** VP of Patient Safety\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 88/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nDr. Sullivan orchestrates an integrated AI safety ecosystem connecting case management, signal detection, risk management, and regulatory reporting into unified pharmacovigilance platforms.\n\n## VPANES Scores\n- **Visibility:** 10/10 - Industry thought leader on PV AI\n- **Pain:** 8/10 - Coordinating global safety AI transformation\n- **Actions:** 10/10 - Multi-system safety AI orchestration\n- **Needs:** 10/10 - Unified global safety platform vision\n- **Emotions:** 9/10 - Visionary confidence in PV transformation\n- **Scenarios:** Industry-wide pharmacovigilance modernization\n\n## Goals\n- Lead industry adoption of AI-powered pharmacovigilance\n- Create integrated global safety intelligence ecosystem\n- Transform safety operations into competitive advantage\n\n## Frustrations\n- Fragmented safety systems across acquisitions\n- Varying AI readiness across global safety teams\n- Regulatory agencies with inconsistent AI guidance', true, NOW(), NOW()),
('vp_patient_safety_learner', 'Dr. Patricia Adams - VP Patient Safety Learner', E'**Role:** VP of Patient Safety\n**Archetype:** LEARNER\n**AI Maturity Score:** 48/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nDr. Adams recognizes AI potential for pharmacovigilance but approaches adoption methodically. She prioritizes understanding AI capabilities and regulatory implications before implementation.\n\n## VPANES Scores\n- **Visibility:** 10/10 - Executive safety accountability\n- **Pain:** 8/10 - Balancing innovation with safety compliance\n- **Actions:** 6/10 - Piloting AI in low-risk safety workflows\n- **Needs:** 7/10 - Evidence-based AI implementation roadmap\n- **Emotions:** 6/10 - Cautiously optimistic about safety AI\n- **Scenarios:** Conservative AI adoption with validation focus\n\n## Goals\n- Develop AI literacy across safety leadership\n- Identify high-value, low-risk AI pilot opportunities\n- Build internal expertise before vendor dependency\n\n## Frustrations\n- AI vendors overpromising PV transformation\n- Unclear regulatory guidance on AI in safety\n- Limited case studies of AI in regulated PV environments', true, NOW(), NOW()),
('vp_patient_safety_skeptic', 'Dr. Eleanor Richardson - VP Patient Safety Skeptic', E'**Role:** VP of Patient Safety\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nDr. Richardson maintains healthy skepticism about AI in pharmacovigilance, emphasizing patient safety and regulatory compliance above all. She requires extensive validation before any AI adoption.\n\n## VPANES Scores\n- **Visibility:** 10/10 - Ultimate patient safety accountability\n- **Pain:** 9/10 - Managing AI pressure while protecting safety integrity\n- **Actions:** 4/10 - Minimal AI adoption, maximum validation\n- **Needs:** 8/10 - Regulatory guidance on AI in PV\n- **Emotions:** 5/10 - Protective of patient safety reputation\n- **Scenarios:** Rigorous validation before any AI implementation\n\n## Goals\n- Ensure zero patient safety risk from AI implementation\n- Maintain regulatory relationships built on compliance\n- Protect company from AI-related safety failures\n\n## Frustrations\n- Executives pushing AI without understanding PV implications\n- Unclear regulatory positions on AI in pharmacovigilance\n- Vendors unable to demonstrate GVP-grade validation', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- 2. DIRECTOR OF PATIENT SAFETY
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('director_patient_safety_automator', 'Dr. Karen Mitchell - Director Patient Safety Automator', E'**Role:** Director of Patient Safety\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 79/100\n**Work Complexity:** Tactical/Strategic\n\n## AI Profile\nDr. Mitchell has automated case processing, signal detection, and aggregate reporting using AI. Her team leverages AI for real-time safety monitoring across global data.\n\n## VPANES Scores\n- **Visibility:** 8/10 - Portfolio-level safety updates\n- **Pain:** 7/10 - Managing complex global safety operations\n- **Actions:** 9/10 - AI-automated safety workflows\n- **Needs:** 8/10 - Integrated safety operations platform\n- **Emotions:** 8/10 - Enthusiastic about safety automation\n- **Scenarios:** Portfolio safety automation initiatives\n\n## Goals\n- Reduce case processing time by 40% through AI\n- Build predictive signal detection capabilities\n- Enable team focus on high-value safety analysis\n\n## Frustrations\n- Legacy safety database limitations\n- Data quality issues across sources\n- Budget constraints for safety AI tools', true, NOW(), NOW()),
('director_patient_safety_orchestrator', 'Dr. Susan Taylor - Director Patient Safety Orchestrator', E'**Role:** Director of Patient Safety\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 84/100\n**Work Complexity:** Tactical/Strategic\n\n## AI Profile\nDr. Taylor orchestrates AI integration across safety operations, connecting case management, signal detection, and regulatory reporting into unified safety platforms.\n\n## VPANES Scores\n- **Visibility:** 8/10 - Cross-functional safety coordination\n- **Pain:** 8/10 - Integrating diverse safety systems\n- **Actions:** 9/10 - Multi-system safety AI orchestration\n- **Needs:** 9/10 - Unified safety data architecture\n- **Emotions:** 8/10 - Energized by safety integration challenges\n- **Scenarios:** Enterprise safety AI integration programs\n\n## Goals\n- Create seamless safety data flow across systems\n- Build AI-native safety operations model\n- Lead safety digitalization initiatives\n\n## Frustrations\n- Siloed safety data across systems\n- Vendor lock-in limiting integration\n- Varying safety data quality globally', true, NOW(), NOW()),
('director_patient_safety_learner', 'Dr. Angela Davis - Director Patient Safety Learner', E'**Role:** Director of Patient Safety\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n**Work Complexity:** Tactical/Strategic\n\n## AI Profile\nDr. Davis is building AI capabilities for safety operations through structured pilots. She focuses on understanding AI while maintaining GVP compliance.\n\n## VPANES Scores\n- **Visibility:** 8/10 - Safety program accountability\n- **Pain:** 7/10 - Keeping pace with safety AI advancement\n- **Actions:** 5/10 - Structured safety AI pilots\n- **Needs:** 7/10 - Clear safety AI implementation guidance\n- **Emotions:** 6/10 - Curious but cautious about safety AI\n- **Scenarios:** Methodical safety AI capability building\n\n## Goals\n- Develop safety AI literacy across team\n- Identify high-value safety AI applications\n- Build hybrid human-AI safety workflows\n\n## Frustrations\n- AI tools lacking PV domain understanding\n- Difficulty quantifying AI value in GVP environment\n- Team members at varying AI readiness', true, NOW(), NOW()),
('director_patient_safety_skeptic', 'Dr. Janet Robinson - Director Patient Safety Skeptic', E'**Role:** Director of Patient Safety\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n**Work Complexity:** Tactical/Strategic\n\n## AI Profile\nDr. Robinson prioritizes GVP compliance and patient safety over AI innovation. She requires extensive proof before endorsing any AI adoption.\n\n## VPANES Scores\n- **Visibility:** 8/10 - Accountable for safety quality\n- **Pain:** 8/10 - Pressure to adopt unproven safety AI\n- **Actions:** 4/10 - Minimal AI engagement\n- **Needs:** 8/10 - Validated AI solutions with safety track record\n- **Emotions:** 5/10 - Protective of safety quality and GVP compliance\n- **Scenarios:** Defending traditional safety approaches\n\n## Goals\n- Maintain flawless GVP compliance record\n- Protect team from disruptive experiments\n- Require rigorous validation for any AI\n\n## Frustrations\n- AI enthusiasm without understanding safety stakes\n- Vendors with no GVP experience\n- Pressure to innovate rather than comply', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- 3. SENIOR SAFETY SCIENTIST
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('senior_safety_scientist_pv_automator', 'Dr. Christine Anderson - Senior Safety Scientist Automator', E'**Role:** Senior Safety Scientist\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 76/100\n**Work Complexity:** Analytical\n\n## AI Profile\nDr. Anderson has automated signal detection, literature monitoring, and aggregate report preparation using AI.\n\n## VPANES Scores\n- **Visibility:** 7/10\n- **Pain:** 7/10\n- **Actions:** 8/10\n- **Needs:** 8/10\n- **Emotions:** 8/10\n\n## Goals\n- Enhance signal detection through AI\n- Reduce aggregate report time by 35%\n- Build AI safety analytics capabilities', true, NOW(), NOW()),
('senior_safety_scientist_pv_orchestrator', 'Dr. Melissa Brown - Senior Safety Scientist Orchestrator', E'**Role:** Senior Safety Scientist\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 80/100\n**Work Complexity:** Analytical\n\n## AI Profile\nDr. Brown orchestrates AI across safety science workflows, connecting data analysis, literature, and reporting.\n\n## VPANES Scores\n- **Visibility:** 7/10\n- **Pain:** 7/10\n- **Actions:** 9/10\n- **Needs:** 8/10\n- **Emotions:** 8/10\n\n## Goals\n- Create seamless safety data flows\n- Build integrated safety intelligence\n- Lead safety science AI adoption', true, NOW(), NOW()),
('senior_safety_scientist_pv_learner', 'Dr. Kimberly White - Senior Safety Scientist Learner', E'**Role:** Senior Safety Scientist\n**Archetype:** LEARNER\n**AI Maturity Score:** 48/100\n**Work Complexity:** Analytical\n\n## AI Profile\nDr. White is exploring AI for safety science through careful pilots.\n\n## VPANES Scores\n- **Visibility:** 7/10\n- **Pain:** 6/10\n- **Actions:** 5/10\n- **Needs:** 7/10\n- **Emotions:** 6/10\n\n## Goals\n- Evaluate AI for safety analytics\n- Build team AI competency\n- Maintain scientific rigor', true, NOW(), NOW()),
('senior_safety_scientist_pv_skeptic', 'Dr. Laura Garcia - Senior Safety Scientist Skeptic', E'**Role:** Senior Safety Scientist\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n**Work Complexity:** Analytical\n\n## AI Profile\nDr. Garcia believes safety science requires expert judgment that AI cannot replace.\n\n## VPANES Scores\n- **Visibility:** 7/10\n- **Pain:** 8/10\n- **Actions:** 3/10\n- **Needs:** 8/10\n- **Emotions:** 4/10\n\n## Goals\n- Maintain safety excellence through expertise\n- Protect against AI safety errors\n- Require extensive validation', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- 4. DRUG SAFETY OFFICER
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('drug_safety_officer_automator', 'Jennifer Martinez - Drug Safety Officer Automator', E'**Role:** Drug Safety Officer\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 74/100\n**Work Complexity:** Operational\n\n## AI Profile\nJennifer has automated case processing, data entry, and routine safety reporting using AI tools.\n\n## VPANES Scores\n- **Visibility:** 6/10\n- **Pain:** 6/10\n- **Actions:** 8/10\n- **Needs:** 7/10\n- **Emotions:** 7/10\n\n## Goals\n- Reduce case processing time by 40%\n- Automate routine safety tasks\n- Enable focus on case quality', true, NOW(), NOW()),
('drug_safety_officer_orchestrator', 'Catherine Wong - Drug Safety Officer Orchestrator', E'**Role:** Drug Safety Officer\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 78/100\n**Work Complexity:** Operational\n\n## AI Profile\nCatherine integrates AI across safety workflows, connecting case intake, processing, and reporting systems.\n\n## VPANES Scores\n- **Visibility:** 6/10\n- **Pain:** 7/10\n- **Actions:** 8/10\n- **Needs:** 7/10\n- **Emotions:** 8/10\n\n## Goals\n- Create seamless case workflows\n- Build integrated safety tools\n- Lead DSO AI adoption', true, NOW(), NOW()),
('drug_safety_officer_learner', 'Rebecca Harris - Drug Safety Officer Learner', E'**Role:** Drug Safety Officer\n**Archetype:** LEARNER\n**AI Maturity Score:** 45/100\n**Work Complexity:** Operational\n\n## AI Profile\nRebecca is learning AI tools for safety processing through training and pilots.\n\n## VPANES Scores\n- **Visibility:** 6/10\n- **Pain:** 6/10\n- **Actions:** 5/10\n- **Needs:** 6/10\n- **Emotions:** 6/10\n\n## Goals\n- Build AI case processing skills\n- Find best AI use cases\n- Maintain case quality', true, NOW(), NOW()),
('drug_safety_officer_skeptic', 'Sharon Williams - Drug Safety Officer Skeptic', E'**Role:** Drug Safety Officer\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n**Work Complexity:** Operational\n\n## AI Profile\nSharon believes case processing requires human judgment that AI cannot replace.\n\n## VPANES Scores\n- **Visibility:** 6/10\n- **Pain:** 6/10\n- **Actions:** 3/10\n- **Needs:** 6/10\n- **Emotions:** 5/10\n\n## Goals\n- Maintain case quality through expertise\n- Protect against AI processing errors\n- Require proof for adoption', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- =====================================================
-- SECTION 2: MANUFACTURING & QUALITY
-- =====================================================

-- 5. VP OF QUALITY
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('vp_quality_automator', 'Sarah Chen - VP Quality Automator', E'**Role:** VP of Quality\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 80/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nSarah has transformed quality operations through AI-powered deviation detection, CAPA automation, and predictive quality analytics.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 7/10\n- **Actions:** 9/10\n- **Needs:** 9/10\n- **Emotions:** 8/10\n\n## Goals\n- Reduce deviation resolution time by 40% through AI\n- Build predictive quality capabilities\n- Transform quality operations with automation\n\n## Frustrations\n- Legacy QMS limitations\n- Regulatory uncertainty on AI in GxP\n- Data quality across manufacturing sites', true, NOW(), NOW()),
('vp_quality_orchestrator', 'Margaret Sullivan - VP Quality Orchestrator', E'**Role:** VP of Quality\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 86/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nMargaret orchestrates an integrated AI quality ecosystem connecting QMS, deviation management, CAPA, and supplier quality.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 8/10\n- **Actions:** 10/10\n- **Needs:** 10/10\n- **Emotions:** 9/10\n\n## Goals\n- Lead industry adoption of AI-powered quality\n- Create integrated global quality intelligence\n- Transform quality into competitive advantage\n\n## Frustrations\n- Fragmented quality systems across sites\n- Varying AI readiness across global teams\n- Regulatory agencies with inconsistent guidance', true, NOW(), NOW()),
('vp_quality_learner', 'Patricia Adams - VP Quality Learner', E'**Role:** VP of Quality\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nPatricia approaches quality AI adoption methodically, prioritizing understanding and GxP compliance.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 8/10\n- **Actions:** 6/10\n- **Needs:** 7/10\n- **Emotions:** 6/10\n\n## Goals\n- Develop AI literacy across quality leadership\n- Identify high-value, low-risk AI pilots\n- Build internal expertise before vendor dependency\n\n## Frustrations\n- AI vendors overpromising quality transformation\n- Unclear regulatory guidance on AI in GxP\n- Limited case studies in regulated quality environments', true, NOW(), NOW()),
('vp_quality_skeptic', 'Eleanor Richardson - VP Quality Skeptic', E'**Role:** VP of Quality\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nEleanor maintains healthy skepticism about AI in quality, emphasizing GxP compliance and product quality.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 9/10\n- **Actions:** 4/10\n- **Needs:** 8/10\n- **Emotions:** 5/10\n\n## Goals\n- Ensure zero quality risk from AI implementation\n- Maintain regulatory relationships built on compliance\n- Protect company from AI-related quality failures\n\n## Frustrations\n- Executives pushing AI without understanding GxP\n- Unclear regulatory positions on AI in quality\n- Vendors unable to demonstrate GxP-grade validation', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- 6-9. Director of Quality Assurance, Director of Quality Engineering, Senior Quality Manager, Quality Assurance Specialist
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('director_qa_automator', 'Karen Mitchell - Director Quality Assurance Automator', E'**Role:** Director of Quality Assurance\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 78/100\n\n## AI Profile\nKaren has automated deviation tracking, audit preparation, and compliance monitoring using AI.\n\n## Goals\n- Reduce audit prep time by 40%\n- Automate routine QA checks\n- Build predictive compliance capabilities', true, NOW(), NOW()),
('director_qa_orchestrator', 'Susan Taylor - Director Quality Assurance Orchestrator', E'**Role:** Director of Quality Assurance\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 82/100\n\n## AI Profile\nSusan orchestrates AI across QA operations, connecting audits, deviations, and supplier quality.\n\n## Goals\n- Create seamless QA data flows\n- Build integrated quality intelligence\n- Lead QA digitalization', true, NOW(), NOW()),
('director_qa_learner', 'Angela Davis - Director Quality Assurance Learner', E'**Role:** Director of Quality Assurance\n**Archetype:** LEARNER\n**AI Maturity Score:** 45/100\n\n## AI Profile\nAngela is building QA AI capabilities through structured pilots while maintaining GxP compliance.\n\n## Goals\n- Evaluate AI for QA applications\n- Build team AI competency\n- Maintain compliance rigor', true, NOW(), NOW()),
('director_qa_skeptic', 'Janet Robinson - Director Quality Assurance Skeptic', E'**Role:** Director of Quality Assurance\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n\n## AI Profile\nJanet prioritizes GxP compliance over AI innovation, requiring extensive proof before adoption.\n\n## Goals\n- Maintain flawless compliance record\n- Protect team from disruptive experiments\n- Require rigorous AI validation', true, NOW(), NOW()),
('director_qe_automator', 'Christine Anderson - Director Quality Engineering Automator', E'**Role:** Director of Quality Engineering\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 79/100\n\n## AI Profile\nChristine has automated process validation, change control, and equipment qualification using AI.\n\n## Goals\n- Reduce validation time by 35%\n- Automate change assessments\n- Build predictive maintenance capabilities', true, NOW(), NOW()),
('director_qe_orchestrator', 'Melissa Brown - Director Quality Engineering Orchestrator', E'**Role:** Director of Quality Engineering\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 83/100\n\n## AI Profile\nMelissa orchestrates AI across QE workflows, connecting validation, process monitoring, and equipment data.\n\n## Goals\n- Create seamless QE data flows\n- Build integrated engineering intelligence\n- Lead QE digitalization', true, NOW(), NOW()),
('director_qe_learner', 'Kimberly White - Director Quality Engineering Learner', E'**Role:** Director of Quality Engineering\n**Archetype:** LEARNER\n**AI Maturity Score:** 48/100\n\n## AI Profile\nKimberly is exploring AI for QE through careful pilots while maintaining validation rigor.\n\n## Goals\n- Evaluate AI for QE applications\n- Build team AI competency\n- Maintain engineering standards', true, NOW(), NOW()),
('director_qe_skeptic', 'Laura Garcia - Director Quality Engineering Skeptic', E'**Role:** Director of Quality Engineering\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n\n## AI Profile\nLaura is skeptical of AI in QE, emphasizing engineering judgment and validation requirements.\n\n## Goals\n- Maintain engineering quality through expertise\n- Protect against AI validation failures\n- Require extensive AI validation', true, NOW(), NOW()),
('senior_quality_manager_automator', 'Jennifer Clark - Senior Quality Manager Automator', E'**Role:** Senior Quality Manager\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 75/100\n\n## AI Profile\nJennifer has automated batch record review, deviation investigation, and CAPA tracking using AI.\n\n## Goals\n- Reduce batch release time by 30%\n- Automate routine quality tasks\n- Enable focus on quality improvement', true, NOW(), NOW()),
('senior_quality_manager_orchestrator', 'Michelle Lee - Senior Quality Manager Orchestrator', E'**Role:** Senior Quality Manager\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 79/100\n\n## AI Profile\nMichelle orchestrates AI across quality management workflows, connecting batch records, deviations, and CAPAs.\n\n## Goals\n- Create seamless quality workflows\n- Build integrated quality intelligence\n- Lead team AI adoption', true, NOW(), NOW()),
('senior_quality_manager_learner', 'Amanda White - Senior Quality Manager Learner', E'**Role:** Senior Quality Manager\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n\n## AI Profile\nAmanda is learning quality AI capabilities through training and pilot projects.\n\n## Goals\n- Develop quality AI competency\n- Identify best AI applications\n- Build team AI readiness', true, NOW(), NOW()),
('senior_quality_manager_skeptic', 'Laura Johnson - Senior Quality Manager Skeptic', E'**Role:** Senior Quality Manager\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n\n## AI Profile\nLaura prefers proven quality processes over AI experimentation.\n\n## Goals\n- Maintain quality excellence through proven processes\n- Protect team from disruptive experiments\n- Require proof before AI adoption', true, NOW(), NOW()),
('qa_specialist_automator', 'Stephanie Brown - Quality Assurance Specialist Automator', E'**Role:** Quality Assurance Specialist\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 72/100\n\n## AI Profile\nStephanie uses AI for documentation review, inspection preparation, and compliance tracking.\n\n## Goals\n- Reduce documentation review time\n- Automate routine QA tasks\n- Build QA AI skills', true, NOW(), NOW()),
('qa_specialist_orchestrator', 'Katherine Davis - Quality Assurance Specialist Orchestrator', E'**Role:** Quality Assurance Specialist\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 76/100\n\n## AI Profile\nKatherine integrates AI tools across QA workflows for efficient quality operations.\n\n## Goals\n- Create seamless QA workflows\n- Build integrated QA tools\n- Lead specialist AI adoption', true, NOW(), NOW()),
('qa_specialist_learner', 'Rachel Wilson - Quality Assurance Specialist Learner', E'**Role:** Quality Assurance Specialist\n**Archetype:** LEARNER\n**AI Maturity Score:** 44/100\n\n## AI Profile\nRachel is learning AI tools for QA through training and hands-on practice.\n\n## Goals\n- Build QA AI skills\n- Find best AI use cases\n- Maintain quality standards', true, NOW(), NOW()),
('qa_specialist_skeptic', 'Nancy Thompson - Quality Assurance Specialist Skeptic', E'**Role:** Quality Assurance Specialist\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n\n## AI Profile\nNancy prefers manual QA processes she can verify directly.\n\n## Goals\n- Maintain quality through proven methods\n- Protect against AI errors\n- Require proof for adoption', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- =====================================================
-- SECTION 3: SUPPLY CHAIN
-- =====================================================

-- 10. VP OF SUPPLY CHAIN (adding industry-standard role)
INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('vp_supply_chain_automator', 'David Chen - VP Supply Chain Automator', E'**Role:** VP of Supply Chain\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 82/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nDavid has transformed supply chain operations through AI-powered demand forecasting, inventory optimization, and supplier risk monitoring.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 7/10\n- **Actions:** 9/10\n- **Needs:** 9/10\n- **Emotions:** 8/10\n\n## Goals\n- Reduce inventory costs by 20% through AI optimization\n- Build predictive demand forecasting\n- Transform supply chain with AI visibility', true, NOW(), NOW()),
('vp_supply_chain_orchestrator', 'Michael Sullivan - VP Supply Chain Orchestrator', E'**Role:** VP of Supply Chain\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 87/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nMichael orchestrates an integrated AI supply chain ecosystem connecting planning, procurement, manufacturing, and distribution.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 8/10\n- **Actions:** 10/10\n- **Needs:** 10/10\n- **Emotions:** 9/10\n\n## Goals\n- Lead industry adoption of AI supply chain\n- Create end-to-end supply chain intelligence\n- Transform supply chain into competitive advantage', true, NOW(), NOW()),
('vp_supply_chain_learner', 'Robert Adams - VP Supply Chain Learner', E'**Role:** VP of Supply Chain\n**Archetype:** LEARNER\n**AI Maturity Score:** 48/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nRobert approaches supply chain AI methodically, piloting solutions before enterprise rollout.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 8/10\n- **Actions:** 6/10\n- **Needs:** 7/10\n- **Emotions:** 6/10\n\n## Goals\n- Develop AI literacy across supply chain leadership\n- Identify high-value AI pilot opportunities\n- Build internal expertise before vendor dependency', true, NOW(), NOW()),
('vp_supply_chain_skeptic', 'James Richardson - VP Supply Chain Skeptic', E'**Role:** VP of Supply Chain\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 30/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nJames maintains skepticism about AI in supply chain, emphasizing operational reliability and proven processes.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 9/10\n- **Actions:** 4/10\n- **Needs:** 8/10\n- **Emotions:** 5/10\n\n## Goals\n- Ensure supply chain reliability over AI experimentation\n- Maintain supplier relationships built on trust\n- Protect company from AI-related supply disruptions', true, NOW(), NOW()),
('supply_chain_director_automator', 'Karen Mitchell - Supply Chain Director Automator', E'**Role:** Supply Chain Director\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 78/100\n\n## AI Profile\nKaren has automated demand planning, inventory management, and supplier performance tracking.\n\n## Goals\n- Reduce planning cycle time by 40%\n- Automate routine supply chain tasks\n- Build predictive capabilities', true, NOW(), NOW()),
('supply_chain_director_orchestrator', 'Susan Taylor - Supply Chain Director Orchestrator', E'**Role:** Supply Chain Director\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 82/100\n\n## AI Profile\nSusan orchestrates AI across supply chain operations, connecting planning, procurement, and logistics.\n\n## Goals\n- Create seamless supply chain workflows\n- Build integrated supply intelligence\n- Lead supply chain digitalization', true, NOW(), NOW()),
('supply_chain_director_learner', 'Angela Davis - Supply Chain Director Learner', E'**Role:** Supply Chain Director\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n\n## AI Profile\nAngela is building supply chain AI capabilities through structured pilots.\n\n## Goals\n- Evaluate AI for supply chain applications\n- Build team AI competency\n- Maintain operational excellence', true, NOW(), NOW()),
('supply_chain_director_skeptic', 'Janet Robinson - Supply Chain Director Skeptic', E'**Role:** Supply Chain Director\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n\n## AI Profile\nJanet prioritizes supply chain reliability over AI innovation.\n\n## Goals\n- Maintain operational reliability\n- Protect against supply disruptions\n- Require proof before AI adoption', true, NOW(), NOW()),
('supply_planner_automator', 'Emily Roberts - Supply Planner Automator', E'**Role:** Supply Planner\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 74/100\n\n## AI Profile\nEmily uses AI for demand forecasting, inventory optimization, and order planning.\n\n## Goals\n- Improve forecast accuracy by 25%\n- Automate routine planning tasks\n- Enable focus on exception management', true, NOW(), NOW()),
('supply_planner_orchestrator', 'Hannah Kim - Supply Planner Orchestrator', E'**Role:** Supply Planner\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 78/100\n\n## AI Profile\nHannah integrates AI tools across planning workflows for efficient supply operations.\n\n## Goals\n- Create seamless planning workflows\n- Build integrated planning tools\n- Lead planner AI adoption', true, NOW(), NOW()),
('supply_planner_learner', 'Sarah Miller - Supply Planner Learner', E'**Role:** Supply Planner\n**Archetype:** LEARNER\n**AI Maturity Score:** 45/100\n\n## AI Profile\nSarah is learning AI tools for supply planning through training.\n\n## Goals\n- Build AI planning skills\n- Find best AI use cases\n- Maintain planning accuracy', true, NOW(), NOW()),
('supply_planner_skeptic', 'Diana Wright - Supply Planner Skeptic', E'**Role:** Supply Planner\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n\n## AI Profile\nDiana prefers proven planning methods over AI experimentation.\n\n## Goals\n- Maintain planning accuracy\n- Protect against forecast errors\n- Require proof for adoption', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- =====================================================
-- SECTION 4: FINANCE
-- =====================================================

INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('vp_finance_automator', 'Richard Chen - VP Finance Automator', E'**Role:** VP of Finance\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 81/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nRichard has transformed finance operations through AI-powered forecasting, automated reporting, and predictive analytics.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 7/10\n- **Actions:** 9/10\n- **Needs:** 9/10\n- **Emotions:** 8/10\n\n## Goals\n- Reduce close cycle by 40% through automation\n- Build predictive financial analytics\n- Transform finance with AI insights', true, NOW(), NOW()),
('vp_finance_orchestrator', 'William Sullivan - VP Finance Orchestrator', E'**Role:** VP of Finance\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 86/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nWilliam orchestrates an integrated AI finance ecosystem connecting FP&A, treasury, accounting, and business intelligence.\n\n## Goals\n- Create end-to-end finance intelligence\n- Lead finance AI transformation\n- Transform finance into strategic partner', true, NOW(), NOW()),
('vp_finance_learner', 'Thomas Adams - VP Finance Learner', E'**Role:** VP of Finance\n**Archetype:** LEARNER\n**AI Maturity Score:** 48/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nThomas approaches finance AI methodically, piloting solutions before enterprise rollout.\n\n## Goals\n- Develop AI literacy across finance leadership\n- Identify high-value AI pilots\n- Build internal expertise', true, NOW(), NOW()),
('vp_finance_skeptic', 'Charles Richardson - VP Finance Skeptic', E'**Role:** VP of Finance\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 30/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nCharles maintains skepticism about AI in finance, emphasizing accuracy and audit trail integrity.\n\n## Goals\n- Ensure financial accuracy over AI speed\n- Maintain audit trail integrity\n- Protect against AI-related financial errors', true, NOW(), NOW()),
('director_finance_automator', 'Karen Mitchell - Director Finance Automator', E'**Role:** Director of Finance\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 78/100\n\n## AI Profile\nKaren has automated budgeting, reporting, and variance analysis using AI.\n\n## Goals\n- Reduce reporting time by 35%\n- Automate routine finance tasks\n- Build predictive budgeting', true, NOW(), NOW()),
('director_finance_orchestrator', 'Susan Taylor - Director Finance Orchestrator', E'**Role:** Director of Finance\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 82/100\n\n## AI Profile\nSusan orchestrates AI across finance operations, connecting budgeting, reporting, and analysis.\n\n## Goals\n- Create seamless finance workflows\n- Build integrated finance intelligence\n- Lead finance digitalization', true, NOW(), NOW()),
('director_finance_learner', 'Angela Davis - Director Finance Learner', E'**Role:** Director of Finance\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n\n## AI Profile\nAngela is building finance AI capabilities through structured pilots.\n\n## Goals\n- Evaluate AI for finance applications\n- Build team AI competency\n- Maintain financial accuracy', true, NOW(), NOW()),
('director_finance_skeptic', 'Janet Robinson - Director Finance Skeptic', E'**Role:** Director of Finance\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n\n## AI Profile\nJanet prioritizes financial accuracy over AI innovation.\n\n## Goals\n- Maintain financial integrity\n- Protect against AI errors\n- Require proof before adoption', true, NOW(), NOW()),
('finance_bp_automator', 'Emily Roberts - Finance Business Partner Automator', E'**Role:** Finance Business Partner\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 75/100\n\n## AI Profile\nEmily uses AI for business analysis, forecasting support, and performance reporting.\n\n## Goals\n- Reduce analysis time by 30%\n- Automate routine reporting\n- Enable strategic partnership', true, NOW(), NOW()),
('finance_bp_orchestrator', 'Hannah Kim - Finance Business Partner Orchestrator', E'**Role:** Finance Business Partner\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 79/100\n\n## AI Profile\nHannah integrates AI tools across FBP workflows for efficient business support.\n\n## Goals\n- Create seamless analysis workflows\n- Build integrated business intelligence\n- Lead FBP AI adoption', true, NOW(), NOW()),
('finance_bp_learner', 'Sarah Miller - Finance Business Partner Learner', E'**Role:** Finance Business Partner\n**Archetype:** LEARNER\n**AI Maturity Score:** 45/100\n\n## AI Profile\nSarah is learning AI tools for business partnering.\n\n## Goals\n- Build AI analysis skills\n- Find best AI use cases\n- Maintain analytical rigor', true, NOW(), NOW()),
('finance_bp_skeptic', 'Diana Wright - Finance Business Partner Skeptic', E'**Role:** Finance Business Partner\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n\n## AI Profile\nDiana prefers proven analysis methods.\n\n## Goals\n- Maintain analytical quality\n- Protect against AI errors\n- Require proof for adoption', true, NOW(), NOW()),
('financial_analyst_automator', 'Jennifer Martinez - Financial Analyst Automator', E'**Role:** Financial Analyst\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 74/100\n\n## AI Profile\nJennifer uses AI for data analysis, report generation, and variance identification.\n\n## Goals\n- Reduce analysis time by 40%\n- Automate routine tasks\n- Build AI analytical skills', true, NOW(), NOW()),
('financial_analyst_orchestrator', 'Michelle Kim - Financial Analyst Orchestrator', E'**Role:** Financial Analyst\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 78/100\n\n## AI Profile\nMichelle integrates AI across analytical workflows.\n\n## Goals\n- Create seamless analysis workflows\n- Build integrated tools\n- Lead analyst AI adoption', true, NOW(), NOW()),
('financial_analyst_learner', 'Sarah Wilson - Financial Analyst Learner', E'**Role:** Financial Analyst\n**Archetype:** LEARNER\n**AI Maturity Score:** 45/100\n\n## AI Profile\nSarah is learning AI tools for financial analysis.\n\n## Goals\n- Build AI analysis skills\n- Find best use cases\n- Maintain accuracy', true, NOW(), NOW()),
('financial_analyst_skeptic', 'Nancy Davis - Financial Analyst Skeptic', E'**Role:** Financial Analyst\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n\n## AI Profile\nNancy prefers manual analysis methods.\n\n## Goals\n- Maintain analytical quality\n- Protect against errors\n- Require proof for adoption', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- =====================================================
-- SECTION 5: HR
-- =====================================================

INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('vp_hr_automator', 'Jessica Chen - VP Human Resources Automator', E'**Role:** VP of Human Resources\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 79/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nJessica has transformed HR operations through AI-powered talent analytics, automated recruiting, and predictive workforce planning.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 7/10\n- **Actions:** 9/10\n- **Needs:** 8/10\n- **Emotions:** 8/10\n\n## Goals\n- Reduce time-to-hire by 35% through AI\n- Build predictive workforce analytics\n- Transform HR with AI-powered insights', true, NOW(), NOW()),
('vp_hr_orchestrator', 'Margaret Sullivan - VP Human Resources Orchestrator', E'**Role:** VP of Human Resources\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 84/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nMargaret orchestrates an integrated AI HR ecosystem connecting talent acquisition, development, compensation, and analytics.\n\n## Goals\n- Create end-to-end people intelligence\n- Lead HR AI transformation\n- Transform HR into strategic partner', true, NOW(), NOW()),
('vp_hr_learner', 'Patricia Adams - VP Human Resources Learner', E'**Role:** VP of Human Resources\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nPatricia approaches HR AI methodically, balancing innovation with employee experience.\n\n## Goals\n- Develop AI literacy across HR leadership\n- Identify high-value AI pilots\n- Build internal expertise', true, NOW(), NOW()),
('vp_hr_skeptic', 'Eleanor Richardson - VP Human Resources Skeptic', E'**Role:** VP of Human Resources\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nEleanor maintains skepticism about AI in HR, emphasizing human judgment and employee experience.\n\n## Goals\n- Protect employee experience from AI depersonalization\n- Maintain ethical HR practices\n- Require extensive validation for AI in people decisions', true, NOW(), NOW()),
('senior_hrbp_automator', 'Karen Mitchell - Senior HRBP Automator', E'**Role:** Senior HR Business Partner\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 76/100\n\n## AI Profile\nKaren uses AI for workforce analytics, retention prediction, and engagement insights.\n\n## Goals\n- Reduce HR reporting time by 30%\n- Build predictive people analytics\n- Enable strategic HR partnership', true, NOW(), NOW()),
('senior_hrbp_orchestrator', 'Susan Taylor - Senior HRBP Orchestrator', E'**Role:** Senior HR Business Partner\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 80/100\n\n## AI Profile\nSusan orchestrates AI across HRBP workflows, connecting talent data, engagement, and business outcomes.\n\n## Goals\n- Create seamless HR workflows\n- Build integrated people intelligence\n- Lead HRBP AI adoption', true, NOW(), NOW()),
('senior_hrbp_learner', 'Angela Davis - Senior HRBP Learner', E'**Role:** Senior HR Business Partner\n**Archetype:** LEARNER\n**AI Maturity Score:** 45/100\n\n## AI Profile\nAngela is building HR AI capabilities through structured pilots.\n\n## Goals\n- Evaluate AI for HR applications\n- Build team AI competency\n- Maintain employee focus', true, NOW(), NOW()),
('senior_hrbp_skeptic', 'Janet Robinson - Senior HRBP Skeptic', E'**Role:** Senior HR Business Partner\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 26/100\n\n## AI Profile\nJanet prioritizes human judgment in HR over AI automation.\n\n## Goals\n- Maintain human-centric HR\n- Protect against AI bias\n- Require proof before adoption', true, NOW(), NOW()),
('hrbp_automator', 'Emily Roberts - HR Business Partner Automator', E'**Role:** HR Business Partner\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 74/100\n\n## AI Profile\nEmily uses AI for data analysis, reporting, and workforce insights.\n\n## Goals\n- Reduce analysis time\n- Automate routine HR tasks\n- Build AI skills', true, NOW(), NOW()),
('hrbp_orchestrator', 'Hannah Kim - HR Business Partner Orchestrator', E'**Role:** HR Business Partner\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 78/100\n\n## AI Profile\nHannah integrates AI tools across HRBP workflows.\n\n## Goals\n- Create seamless workflows\n- Build integrated tools\n- Lead HRBP AI adoption', true, NOW(), NOW()),
('hrbp_learner', 'Sarah Miller - HR Business Partner Learner', E'**Role:** HR Business Partner\n**Archetype:** LEARNER\n**AI Maturity Score:** 44/100\n\n## AI Profile\nSarah is learning AI tools for HR business partnering.\n\n## Goals\n- Build AI skills\n- Find best use cases\n- Maintain employee focus', true, NOW(), NOW()),
('hrbp_skeptic', 'Diana Wright - HR Business Partner Skeptic', E'**Role:** HR Business Partner\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 24/100\n\n## AI Profile\nDiana prefers human judgment in HR.\n\n## Goals\n- Maintain human-centric approach\n- Protect against bias\n- Require proof for adoption', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- =====================================================
-- SECTION 6: LEGAL
-- =====================================================

INSERT INTO personas (persona_key, display_name, description, is_active, created_at, updated_at)
VALUES
('vp_legal_automator', 'David Chen - VP Legal Automator', E'**Role:** VP of Legal\n**Archetype:** AUTOMATOR\n**AI Maturity Score:** 78/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nDavid has transformed legal operations through AI-powered contract analysis, document review, and compliance monitoring.\n\n## VPANES Scores\n- **Visibility:** 10/10\n- **Pain:** 7/10\n- **Actions:** 8/10\n- **Needs:** 8/10\n- **Emotions:** 8/10\n\n## Goals\n- Reduce contract review time by 50% through AI\n- Build predictive legal analytics\n- Transform legal with AI-powered insights', true, NOW(), NOW()),
('vp_legal_orchestrator', 'Michael Sullivan - VP Legal Orchestrator', E'**Role:** VP of Legal\n**Archetype:** ORCHESTRATOR\n**AI Maturity Score:** 83/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nMichael orchestrates an integrated AI legal ecosystem connecting contract management, compliance, litigation, and IP.\n\n## Goals\n- Create end-to-end legal intelligence\n- Lead legal AI transformation\n- Transform legal into strategic partner', true, NOW(), NOW()),
('vp_legal_learner', 'Robert Adams - VP Legal Learner', E'**Role:** VP of Legal\n**Archetype:** LEARNER\n**AI Maturity Score:** 46/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nRobert approaches legal AI methodically, balancing innovation with legal risk management.\n\n## Goals\n- Develop AI literacy across legal team\n- Identify high-value AI pilots\n- Build internal expertise', true, NOW(), NOW()),
('vp_legal_skeptic', 'James Richardson - VP Legal Skeptic', E'**Role:** VP of Legal\n**Archetype:** SKEPTIC\n**AI Maturity Score:** 28/100\n**Work Complexity:** Strategic/Enterprise\n\n## AI Profile\nJames maintains skepticism about AI in legal, emphasizing professional judgment and risk management.\n\n## Goals\n- Protect against AI legal errors\n- Maintain professional standards\n- Require extensive validation for AI in legal decisions', true, NOW(), NOW())
ON CONFLICT (persona_key) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, updated_at = NOW();

-- =====================================================
-- SUMMARY
-- =====================================================
-- Total Corporate Support Personas: 80
--
-- SECTION 1: Pharmacovigilance/Drug Safety (4 roles, 16 personas)
--   - VP of Patient Safety
--   - Director of Patient Safety
--   - Senior Safety Scientist
--   - Drug Safety Officer
--
-- SECTION 2: Manufacturing & Quality (5 roles, 20 personas)
--   - VP of Quality
--   - Director of Quality Assurance
--   - Director of Quality Engineering
--   - Senior Quality Manager
--   - Quality Assurance Specialist
--
-- SECTION 3: Supply Chain (3 roles, 12 personas)
--   - VP of Supply Chain
--   - Supply Chain Director
--   - Supply Planner
--
-- SECTION 4: Finance (4 roles, 16 personas)
--   - VP of Finance
--   - Director of Finance
--   - Finance Business Partner
--   - Financial Analyst
--
-- SECTION 5: HR (3 roles, 12 personas)
--   - VP of Human Resources
--   - Senior HR Business Partner
--   - HR Business Partner
--
-- SECTION 6: Legal (1 role, 4 personas)
--   - VP of Legal
-- =====================================================
