-- =====================================================
-- MIGRATION: 047 - Comprehensive Medical Affairs Personas
-- Date: 2025-11-29
-- Description: 80 personas for 20 Medical Affairs roles
-- Covers: CMO, VP Medical Affairs, MSL, Medical Directors,
--         Medical Education, Medical Information, Medical Writing
-- =====================================================

-- MECE PERSONA FRAMEWORK:
-- Each role gets 4 personas based on AI Maturity × Work Complexity:
--   AUTOMATOR (High AI/Low Complexity): AI maturity 70-90%, routine task automation
--   ORCHESTRATOR (High AI/High Complexity): AI maturity 85-95%, strategic AI leadership
--   LEARNER (Low AI/Low Complexity): AI maturity 30-55%, building foundational skills
--   SKEPTIC (Low AI/High Complexity): AI maturity 18-35%, governance & validation focus

-- =====================================================
-- SECTION 1: C-SUITE / EXECUTIVE ROLES
-- =====================================================

-- Role 1: Chief Medical Officer (CMO)
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('cmo-automator', 'CMO - Digital Pioneer', E'## Chief Medical Officer (Automator)\n\n### Professional Context\nVision-driven CMO who has embedded AI throughout the medical organization. Champions algorithmic approaches to clinical evidence synthesis, safety signal detection, and medical strategy development.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Mandates AI-first approaches, tracks AI ROI metrics, sponsors enterprise AI initiatives\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 10 | Highest visibility role in medical function |\n| Pain | 6 | AI alleviates data synthesis burden |\n| Actions | 9 | Makes organization-wide decisions |\n| Needs | 8 | Needs real-time medical intelligence |\n| Emotions | 7 | Confident in AI-augmented decisions |\n| Scenarios | 9 | Complex regulatory/clinical scenarios |', TRUE),

  ('cmo-orchestrator', 'CMO - Strategic Architect', E'## Chief Medical Officer (Orchestrator)\n\n### Professional Context\nStrategic CMO who orchestrates AI transformation across medical affairs, clinical development, and safety. Builds cross-functional AI governance and ensures regulatory compliance of AI systems.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 92%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs AI governance frameworks, coordinates multi-stakeholder AI initiatives, ensures FDA compliance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 10 | Sets medical strategy for entire organization |\n| Pain | 7 | Complex coordination across functions |\n| Actions | 10 | Enterprise-level decision authority |\n| Needs | 9 | Integrated medical intelligence platform |\n| Emotions | 8 | Excitement about AI-driven transformation |\n| Scenarios | 10 | Manages most complex medical scenarios |', TRUE),

  ('cmo-learner', 'CMO - Evidence Seeker', E'## Chief Medical Officer (Learner)\n\n### Professional Context\nExperienced CMO building AI capabilities methodically. Seeks evidence-based approaches to AI adoption, piloting initiatives before scaling. Values training and competency development.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 48%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Requests AI education for medical teams, pilots before scaling, seeks peer benchmarks\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 10 | Highest visibility role |\n| Pain | 8 | Data overload without AI support |\n| Actions | 8 | Cautious but decisive |\n| Needs | 9 | Proof of AI value before commitment |\n| Emotions | 6 | Curious but cautious about AI |\n| Scenarios | 9 | Complex decisions require careful approach |', TRUE),

  ('cmo-skeptic', 'CMO - Medical Guardian', E'## Chief Medical Officer (Skeptic)\n\n### Professional Context\nRisk-conscious CMO who prioritizes patient safety and scientific rigor over AI efficiency. Demands extensive validation of AI systems before deployment in medical contexts.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Requires extensive AI validation, emphasizes human oversight, questions AI in clinical contexts\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 10 | Most visible medical role |\n| Pain | 9 | Frustrated by AI hype without evidence |\n| Actions | 7 | Slow, deliberate decisions |\n| Needs | 10 | Rigorous validation before AI adoption |\n| Emotions | 4 | Skeptical of AI in medicine |\n| Scenarios | 10 | Patient safety scenarios paramount |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 2: VP Medical Affairs
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('vp-med-affairs-automator', 'VP Medical Affairs - Efficiency Champion', E'## VP Medical Affairs (Automator)\n\n### Professional Context\nEfficiency-focused VP who has automated medical information workflows, MSL territory planning, and publication tracking. Drives productivity gains through systematic AI adoption.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Implements AI for medical inquiries, automates MSL reporting, uses predictive analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 9 | Senior executive visibility |\n| Pain | 6 | AI reduces operational burden |\n| Actions | 8 | Drives function-wide initiatives |\n| Needs | 8 | Scalable medical operations |\n| Emotions | 8 | Enthusiastic about AI efficiency |\n| Scenarios | 8 | Manages diverse medical scenarios |', TRUE),

  ('vp-med-affairs-orchestrator', 'VP Medical Affairs - Transformation Leader', E'## VP Medical Affairs (Orchestrator)\n\n### Professional Context\nTransformational VP orchestrating AI integration across medical affairs, MSL teams, medical information, and publications. Builds AI strategy aligned with business objectives.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 90%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs AI-enabled medical strategy, coordinates cross-functional AI, builds AI governance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 9 | High executive visibility |\n| Pain | 5 | Strategic challenges vs operational |\n| Actions | 9 | Shapes medical affairs direction |\n| Needs | 9 | Integrated AI platform across medical |\n| Emotions | 9 | Excited by transformation potential |\n| Scenarios | 9 | Complex multi-stakeholder scenarios |', TRUE),

  ('vp-med-affairs-learner', 'VP Medical Affairs - Methodical Adopter', E'## VP Medical Affairs (Learner)\n\n### Professional Context\nMethodical VP building AI literacy across the medical affairs organization. Invests in training, seeks best practices, and pilots AI in contained use cases before scaling.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 52%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Sponsors AI training programs, pilots before scaling, benchmarks with peers\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 9 | High visibility role |\n| Pain | 7 | Growing demands without AI support |\n| Actions | 7 | Deliberate decision-making |\n| Needs | 8 | Proof-of-concept before commitment |\n| Emotions | 6 | Cautiously optimistic |\n| Scenarios | 8 | Varied complexity scenarios |', TRUE),

  ('vp-med-affairs-skeptic', 'VP Medical Affairs - Quality Guardian', E'## VP Medical Affairs (Skeptic)\n\n### Professional Context\nQuality-focused VP who prioritizes scientific accuracy and compliance over AI efficiency. Demands validation that AI outputs meet medical standards before adoption.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 32%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy in medical content, requires human review, emphasizes compliance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 9 | Senior visibility |\n| Pain | 8 | Quality concerns with AI content |\n| Actions | 6 | Conservative decision-making |\n| Needs | 9 | Validated, compliant AI tools |\n| Emotions | 4 | Skeptical of AI in medical context |\n| Scenarios | 8 | High-stakes medical scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 3: Global Medical Affairs Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-med-affairs-dir-automator', 'Global Medical Affairs Director - AI Integrator', E'## Global Medical Affairs Director (Automator)\n\n### Professional Context\nGlobal director who has integrated AI across medical affairs operations in multiple regions. Uses AI for medical inquiry management, content generation, and cross-border medical intelligence.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Deploys AI for global medical operations, standardizes AI tools across regions\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global leadership visibility |\n| Pain | 6 | AI reduces coordination burden |\n| Actions | 8 | Drives global medical initiatives |\n| Needs | 8 | Harmonized global AI tools |\n| Emotions | 8 | Confident in AI capabilities |\n| Scenarios | 8 | Multi-region medical scenarios |', TRUE),

  ('global-med-affairs-dir-orchestrator', 'Global Medical Affairs Director - Global Strategist', E'## Global Medical Affairs Director (Orchestrator)\n\n### Professional Context\nStrategic director orchestrating AI-enabled medical affairs transformation across global markets. Aligns regional AI initiatives with global medical strategy and regulatory requirements.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs global AI strategy, coordinates regional AI adoption, ensures compliance across markets\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global strategic visibility |\n| Pain | 5 | Strategic vs operational challenges |\n| Actions | 9 | Shapes global medical direction |\n| Needs | 9 | Integrated global AI platform |\n| Emotions | 9 | Energized by global transformation |\n| Scenarios | 9 | Complex global regulatory scenarios |', TRUE),

  ('global-med-affairs-dir-learner', 'Global Medical Affairs Director - Regional Builder', E'## Global Medical Affairs Director (Learner)\n\n### Professional Context\nGlobal director building AI capabilities methodically across regions. Learns from early adopter markets, shares best practices, and scales proven solutions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI in select markets, learns from regional successes, builds capabilities gradually\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global role visibility |\n| Pain | 7 | Regional coordination without AI |\n| Actions | 7 | Measured decision-making |\n| Needs | 8 | Regional AI success stories |\n| Emotions | 6 | Cautiously optimistic |\n| Scenarios | 8 | Multi-market complexity |', TRUE),

  ('global-med-affairs-dir-skeptic', 'Global Medical Affairs Director - Compliance Focus', E'## Global Medical Affairs Director (Skeptic)\n\n### Professional Context\nCompliance-focused director who emphasizes regulatory requirements across markets. Skeptical of AI that doesn''t meet global regulatory standards or creates compliance risks.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 30%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Prioritizes regulatory compliance, questions AI in multi-market contexts, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Global leadership role |\n| Pain | 8 | Compliance burden across markets |\n| Actions | 6 | Conservative, compliance-first |\n| Needs | 9 | Validated, compliant AI solutions |\n| Emotions | 4 | Skeptical of AI in global medical |\n| Scenarios | 9 | Complex regulatory scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 4: Head of Publications
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('head-publications-automator', 'Head of Publications - AI-Powered Publisher', E'## Head of Publications (Automator)\n\n### Professional Context\nInnovative publications head who leverages AI for manuscript drafting, literature reviews, and publication planning. Drives efficiency while maintaining scientific rigor.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 76%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for draft generation, automates literature surveillance, optimizes submission workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Publications leadership visibility |\n| Pain | 6 | AI reduces content creation burden |\n| Actions | 7 | Drives publications strategy |\n| Needs | 7 | AI tools for scientific writing |\n| Emotions | 8 | Excited by AI writing capabilities |\n| Scenarios | 7 | Publication planning scenarios |', TRUE),

  ('head-publications-orchestrator', 'Head of Publications - Strategic Publications Architect', E'## Head of Publications (Orchestrator)\n\n### Professional Context\nStrategic leader who orchestrates AI-enabled publication strategy aligned with medical and commercial objectives. Coordinates internal and external stakeholders for integrated publication planning.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs AI-enabled publication strategy, coordinates medical-commercial alignment, builds publication COE\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic publications role |\n| Pain | 5 | Strategic challenges vs tactical |\n| Actions | 8 | Shapes publication direction |\n| Needs | 8 | Integrated publication platform |\n| Emotions | 8 | Enthusiastic about AI potential |\n| Scenarios | 8 | Complex publication strategy |', TRUE),

  ('head-publications-learner', 'Head of Publications - Quality-Focused Adopter', E'## Head of Publications (Learner)\n\n### Professional Context\nQuality-conscious publications head building AI capabilities carefully. Explores AI for specific use cases while maintaining rigorous review processes.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for literature reviews, maintains human review, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Department leadership |\n| Pain | 7 | Growing publication demands |\n| Actions | 6 | Careful, quality-first decisions |\n| Needs | 7 | Validated AI writing tools |\n| Emotions | 6 | Hopeful but cautious |\n| Scenarios | 7 | Publication quality scenarios |', TRUE),

  ('head-publications-skeptic', 'Head of Publications - Scientific Integrity Guardian', E'## Head of Publications (Skeptic)\n\n### Professional Context\nScientific integrity-focused leader who questions AI in publication contexts. Concerned about AI-generated content accuracy, plagiarism, and journal policies on AI.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy, emphasizes human authorship, monitors journal AI policies\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Publications leadership |\n| Pain | 9 | Concerns about AI in publications |\n| Actions | 5 | Very conservative approach |\n| Needs | 9 | Validated, transparent AI tools |\n| Emotions | 3 | Skeptical of AI in scientific writing |\n| Scenarios | 8 | Integrity-focused scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 2: DIRECTOR LEVEL ROLES
-- =====================================================

-- Role 5: Regional MSL Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('regional-msl-dir-automator', 'Regional MSL Director - Field Excellence Leader', E'## Regional MSL Director (Automator)\n\n### Professional Context\nForward-thinking MSL director who has automated territory analytics, call planning, and KOL mapping. Drives MSL productivity through AI-enabled field tools.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Implements AI for territory optimization, automates MSL reporting, uses predictive KOL analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional field leadership |\n| Pain | 6 | AI reduces field coordination burden |\n| Actions | 7 | Drives regional MSL strategy |\n| Needs | 7 | AI-powered field tools |\n| Emotions | 8 | Excited by field AI capabilities |\n| Scenarios | 7 | Field engagement scenarios |', TRUE),

  ('regional-msl-dir-orchestrator', 'Regional MSL Director - Strategic Field Leader', E'## Regional MSL Director (Orchestrator)\n\n### Professional Context\nStrategic director who orchestrates AI-enabled MSL excellence across the region. Coordinates KOL strategy, medical education, and field medical initiatives using integrated AI platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs regional MSL AI strategy, coordinates field-HQ integration, builds MSL capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional strategic role |\n| Pain | 5 | Strategic coordination challenges |\n| Actions | 8 | Shapes regional field strategy |\n| Needs | 8 | Integrated MSL platform |\n| Emotions | 9 | Energized by field transformation |\n| Scenarios | 8 | Complex KOL engagement scenarios |', TRUE),

  ('regional-msl-dir-learner', 'Regional MSL Director - Field Capability Builder', E'## Regional MSL Director (Learner)\n\n### Professional Context\nCapability-focused director building AI skills across the MSL team. Pilots AI tools in select territories, learns from results, and scales successful approaches.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 48%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI with select MSLs, invests in training, benchmarks with peer regions\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional leadership |\n| Pain | 7 | Growing field demands |\n| Actions | 6 | Measured approach to AI |\n| Needs | 7 | Proven AI tools for MSLs |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 7 | Field complexity scenarios |', TRUE),

  ('regional-msl-dir-skeptic', 'Regional MSL Director - Scientific Relationship Focus', E'## Regional MSL Director (Skeptic)\n\n### Professional Context\nRelationship-focused director who prioritizes authentic KOL relationships over AI efficiency. Skeptical that AI can support nuanced scientific discussions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes human relationships, questions AI in scientific dialogue, requires MSL judgment\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional field role |\n| Pain | 8 | Concerned AI diminishes relationships |\n| Actions | 5 | Conservative approach to AI |\n| Needs | 8 | AI that enhances, not replaces |\n| Emotions | 4 | Skeptical of AI in field medical |\n| Scenarios | 8 | Relationship-focused scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 6: Medical Affairs Operations Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-affairs-ops-dir-automator', 'Medical Affairs Ops Director - Process Optimizer', E'## Medical Affairs Operations Director (Automator)\n\n### Professional Context\nOperations expert who has automated medical affairs workflows, vendor management, and budget tracking. Drives operational efficiency through systematic process automation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Automates operational workflows, implements AI for resource planning, optimizes vendor coordination\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Operations leadership |\n| Pain | 5 | AI reduces operational burden |\n| Actions | 7 | Drives operational excellence |\n| Needs | 7 | Integrated ops automation |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 7 | Operational complexity |', TRUE),

  ('med-affairs-ops-dir-orchestrator', 'Medical Affairs Ops Director - Strategic Operations Lead', E'## Medical Affairs Operations Director (Orchestrator)\n\n### Professional Context\nStrategic operations leader who orchestrates AI transformation across medical affairs operations. Coordinates budget, resources, and vendors using integrated AI systems.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs ops AI strategy, coordinates cross-functional operations, builds operational COE\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic ops role |\n| Pain | 4 | AI handles operational complexity |\n| Actions | 8 | Shapes operations direction |\n| Needs | 8 | Integrated operations platform |\n| Emotions | 9 | Excited by ops transformation |\n| Scenarios | 8 | Complex operations scenarios |', TRUE),

  ('med-affairs-ops-dir-learner', 'Medical Affairs Ops Director - Process Improver', E'## Medical Affairs Operations Director (Learner)\n\n### Professional Context\nProcess-focused director building AI capabilities in operations. Pilots AI for specific workflows, measures results, and scales proven solutions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI workflows, measures efficiency gains, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Operations leadership |\n| Pain | 7 | Growing operational demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Proven ops AI tools |\n| Emotions | 6 | Hopeful about efficiency |\n| Scenarios | 7 | Process improvement scenarios |', TRUE),

  ('med-affairs-ops-dir-skeptic', 'Medical Affairs Ops Director - Control-Focused', E'## Medical Affairs Operations Director (Skeptic)\n\n### Professional Context\nControl-focused operations director who emphasizes process governance and compliance. Skeptical of AI that reduces visibility or control over operations.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 30%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes process control, questions AI black boxes, requires audit trails\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Operations role |\n| Pain | 8 | Concerned about AI control |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Transparent, auditable AI |\n| Emotions | 4 | Skeptical of AI automation |\n| Scenarios | 7 | Control and governance scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 7: Medical Strategy Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-strategy-dir-automator', 'Medical Strategy Director - Data-Driven Strategist', E'## Medical Strategy Director (Automator)\n\n### Professional Context\nData-driven strategist who leverages AI for competitive intelligence, medical landscape analysis, and strategy development. Uses AI to synthesize vast medical literature.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for landscape analysis, automates competitive intelligence, leverages predictive analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Strategic leadership role |\n| Pain | 6 | AI reduces analysis burden |\n| Actions | 8 | Drives medical strategy |\n| Needs | 8 | AI-powered intelligence tools |\n| Emotions | 8 | Excited by AI insights |\n| Scenarios | 8 | Strategic planning scenarios |', TRUE),

  ('med-strategy-dir-orchestrator', 'Medical Strategy Director - Enterprise Strategist', E'## Medical Strategy Director (Orchestrator)\n\n### Professional Context\nEnterprise strategist who orchestrates AI-enabled medical strategy across therapeutic areas and regions. Aligns medical, commercial, and regulatory strategies using integrated AI insights.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 91%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs enterprise medical AI strategy, coordinates cross-functional alignment, builds strategy COE\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Enterprise strategy role |\n| Pain | 4 | Strategic vs tactical challenges |\n| Actions | 9 | Shapes enterprise direction |\n| Needs | 9 | Integrated strategy platform |\n| Emotions | 9 | Energized by strategic AI |\n| Scenarios | 9 | Complex enterprise scenarios |', TRUE),

  ('med-strategy-dir-learner', 'Medical Strategy Director - Analytical Builder', E'## Medical Strategy Director (Learner)\n\n### Professional Context\nAnalytical strategist building AI capabilities for strategy development. Explores AI for specific analysis needs, validates outputs, and builds team capabilities.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 50%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for analysis, validates AI insights, builds analytical skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Strategy leadership |\n| Pain | 7 | Growing complexity without AI |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Validated AI analysis tools |\n| Emotions | 6 | Curious about AI potential |\n| Scenarios | 8 | Strategy development scenarios |', TRUE),

  ('med-strategy-dir-skeptic', 'Medical Strategy Director - Evidence-Based Traditionalist', E'## Medical Strategy Director (Skeptic)\n\n### Professional Context\nEvidence-based strategist who questions AI-generated insights. Emphasizes human judgment in strategy development and requires rigorous validation of AI outputs.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy, emphasizes human judgment, requires extensive validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Strategic role |\n| Pain | 9 | Concerned about AI quality |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, explainable AI |\n| Emotions | 3 | Skeptical of AI insights |\n| Scenarios | 9 | High-stakes strategy scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 8: Medical Director TA Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-dir-ta-automator', 'Medical Director TA Lead - TA Excellence Champion', E'## Medical Director TA Lead (Automator)\n\n### Professional Context\nTherapeutic area lead who leverages AI for disease area intelligence, clinical evidence synthesis, and KOL mapping. Drives TA strategy with data-driven insights.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for TA landscape, automates evidence synthesis, leverages KOL analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | TA leadership visibility |\n| Pain | 6 | AI reduces TA analysis burden |\n| Actions | 8 | Drives TA medical strategy |\n| Needs | 8 | TA-specific AI tools |\n| Emotions | 8 | Excited by TA AI capabilities |\n| Scenarios | 8 | TA-specific scenarios |', TRUE),

  ('med-dir-ta-orchestrator', 'Medical Director TA Lead - TA Strategy Architect', E'## Medical Director TA Lead (Orchestrator)\n\n### Professional Context\nStrategic TA leader who orchestrates AI-enabled medical strategy across the therapeutic area. Coordinates clinical, commercial, and medical initiatives using integrated AI insights.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 89%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs TA AI strategy, coordinates cross-functional TA teams, builds TA excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | TA strategic leadership |\n| Pain | 5 | Strategic TA challenges |\n| Actions | 9 | Shapes TA direction |\n| Needs | 9 | Integrated TA platform |\n| Emotions | 9 | Energized by TA transformation |\n| Scenarios | 9 | Complex TA scenarios |', TRUE),

  ('med-dir-ta-learner', 'Medical Director TA Lead - Clinical Evidence Builder', E'## Medical Director TA Lead (Learner)\n\n### Professional Context\nEvidence-focused TA lead building AI capabilities for clinical evidence synthesis. Pilots AI for literature reviews, validates clinical accuracy, and builds team expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for evidence synthesis, validates clinical accuracy, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | TA leadership role |\n| Pain | 7 | Growing evidence burden |\n| Actions | 6 | Measured approach |\n| Needs | 8 | Validated clinical AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 8 | Evidence synthesis scenarios |', TRUE),

  ('med-dir-ta-skeptic', 'Medical Director TA Lead - Clinical Rigor Guardian', E'## Medical Director TA Lead (Skeptic)\n\n### Professional Context\nClinically rigorous TA lead who questions AI in clinical evidence contexts. Emphasizes scientific accuracy and requires extensive validation of AI-generated clinical content.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 29%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI clinical accuracy, requires human review, emphasizes scientific rigor\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | TA leadership |\n| Pain | 9 | Concerned about AI accuracy |\n| Actions | 5 | Conservative clinical approach |\n| Needs | 9 | Validated clinical AI |\n| Emotions | 3 | Skeptical of AI in clinical |\n| Scenarios | 9 | High-stakes clinical scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 3: SENIOR MANAGER ROLES
-- =====================================================

-- Role 9: MSL Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('msl-manager-automator', 'MSL Manager - Field Tech Leader', E'## MSL Manager (Automator)\n\n### Professional Context\nTech-savvy MSL manager who has equipped the team with AI-powered field tools. Uses AI for territory analytics, call reporting, and KOL insights to drive MSL productivity.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 75%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Implements AI field tools, automates call reporting, uses KOL analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | MSL team leadership |\n| Pain | 6 | AI reduces management burden |\n| Actions | 7 | Drives MSL team performance |\n| Needs | 7 | AI-powered MSL tools |\n| Emotions | 8 | Excited by field AI |\n| Scenarios | 6 | Team management scenarios |', TRUE),

  ('msl-manager-orchestrator', 'MSL Manager - Strategic Field Coordinator', E'## MSL Manager (Orchestrator)\n\n### Professional Context\nStrategic MSL manager who orchestrates AI-enabled field excellence. Coordinates MSL activities with medical strategy, tracks KOL engagement metrics, and drives continuous improvement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Aligns MSL activities with strategy, coordinates KOL initiatives, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Field management role |\n| Pain | 5 | Strategic vs tactical balance |\n| Actions | 7 | Shapes team direction |\n| Needs | 7 | Integrated MSL platform |\n| Emotions | 8 | Enthusiastic about AI potential |\n| Scenarios | 7 | Strategic field scenarios |', TRUE),

  ('msl-manager-learner', 'MSL Manager - Team Developer', E'## MSL Manager (Learner)\n\n### Professional Context\nDevelopment-focused MSL manager building AI skills across the team. Pilots AI tools with select MSLs, provides training, and scales successful approaches.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI with team, invests in training, measures adoption\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Team management role |\n| Pain | 7 | Growing team demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Team development scenarios |', TRUE),

  ('msl-manager-skeptic', 'MSL Manager - Relationship Protector', E'## MSL Manager (Skeptic)\n\n### Professional Context\nRelationship-focused MSL manager who prioritizes authentic KOL engagement over AI metrics. Skeptical that AI can capture the nuance of scientific relationships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 24%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes relationship quality, questions AI metrics, requires MSL judgment\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Team leadership |\n| Pain | 8 | Concerned AI diminishes relationships |\n| Actions | 5 | Conservative approach |\n| Needs | 7 | AI that enhances relationships |\n| Emotions | 4 | Skeptical of field AI |\n| Scenarios | 7 | Relationship-focused scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 10: Senior Medical Science Liaison
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('senior-msl-automator', 'Senior MSL - Digital Field Expert', E'## Senior Medical Science Liaison (Automator)\n\n### Professional Context\nTech-savvy senior MSL who leverages AI for scientific preparation, territory insights, and KOL mapping. Champions digital tools among peer MSLs.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for scientific prep, automates call planning, shares AI best practices\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Senior field role |\n| Pain | 6 | AI reduces prep burden |\n| Actions | 6 | Independent field professional |\n| Needs | 7 | AI-powered field tools |\n| Emotions | 8 | Excited by AI capabilities |\n| Scenarios | 6 | Scientific engagement scenarios |', TRUE),

  ('senior-msl-orchestrator', 'Senior MSL - Strategic KOL Expert', E'## Senior Medical Science Liaison (Orchestrator)\n\n### Professional Context\nStrategic senior MSL who orchestrates complex KOL engagement plans. Uses AI to synthesize scientific intelligence and coordinate with cross-functional partners.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates KOL strategy, synthesizes scientific intelligence, mentors junior MSLs\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Experienced field role |\n| Pain | 5 | Complex KOL coordination |\n| Actions | 7 | Strategic field decisions |\n| Needs | 7 | Integrated KOL platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Complex KOL scenarios |', TRUE),

  ('senior-msl-learner', 'Senior MSL - Scientific Excellence Focus', E'## Senior Medical Science Liaison (Learner)\n\n### Professional Context\nScience-focused senior MSL building AI capabilities for scientific engagement. Explores AI for literature synthesis while maintaining scientific excellence.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for science, validates AI content, maintains scientific rigor\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Senior field role |\n| Pain | 7 | Growing scientific demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated scientific AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Scientific engagement scenarios |', TRUE),

  ('senior-msl-skeptic', 'Senior MSL - Traditional Relationship Builder', E'## Senior Medical Science Liaison (Skeptic)\n\n### Professional Context\nRelationship-focused senior MSL who prioritizes authentic scientific dialogue over AI efficiency. Values deep KOL relationships built through personal engagement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 22%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes personal engagement, questions AI in scientific dialogue, values relationship depth\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Field role |\n| Pain | 8 | Concerned AI diminishes relationships |\n| Actions | 5 | Traditional approach |\n| Needs | 6 | AI that supports relationships |\n| Emotions | 3 | Skeptical of AI in field |\n| Scenarios | 7 | Relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 11: Global Medical Education Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-med-ed-mgr-automator', 'Global Medical Education Manager - Digital Learning Expert', E'## Global Medical Education Manager (Automator)\n\n### Professional Context\nDigital-savvy education manager who leverages AI for content development, learning personalization, and program effectiveness tracking.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for content generation, automates learning paths, tracks engagement analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global education role |\n| Pain | 6 | AI reduces content burden |\n| Actions | 7 | Drives education programs |\n| Needs | 7 | AI content development tools |\n| Emotions | 8 | Excited by AI in education |\n| Scenarios | 6 | Educational content scenarios |', TRUE),

  ('global-med-ed-mgr-orchestrator', 'Global Medical Education Manager - Strategic Learning Architect', E'## Global Medical Education Manager (Orchestrator)\n\n### Professional Context\nStrategic education manager who orchestrates global medical education strategy using AI-enabled learning platforms and content systems.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs global education AI strategy, coordinates regional programs, builds education COE\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global strategic role |\n| Pain | 5 | Strategic education challenges |\n| Actions | 7 | Shapes education direction |\n| Needs | 8 | Integrated education platform |\n| Emotions | 8 | Enthusiastic about learning AI |\n| Scenarios | 7 | Global education scenarios |', TRUE),

  ('global-med-ed-mgr-learner', 'Global Medical Education Manager - Quality-Focused Educator', E'## Global Medical Education Manager (Learner)\n\n### Professional Context\nQuality-focused education manager building AI capabilities for medical education. Pilots AI content tools while maintaining educational quality standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI content tools, validates educational quality, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Education management role |\n| Pain | 7 | Growing content demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated education AI |\n| Emotions | 6 | Hopeful about AI efficiency |\n| Scenarios | 6 | Content quality scenarios |', TRUE),

  ('global-med-ed-mgr-skeptic', 'Global Medical Education Manager - Educational Quality Guardian', E'## Global Medical Education Manager (Skeptic)\n\n### Professional Context\nQuality guardian who questions AI in medical education contexts. Concerned about scientific accuracy of AI-generated content and learner engagement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI content accuracy, requires expert review, emphasizes learner engagement\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Education role |\n| Pain | 8 | Concerned about AI quality |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Validated educational AI |\n| Emotions | 4 | Skeptical of AI content |\n| Scenarios | 7 | Quality assurance scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 12: Medical Information Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-info-mgr-automator', 'Medical Information Manager - Response Automation Expert', E'## Medical Information Manager (Automator)\n\n### Professional Context\nEfficiency-focused MI manager who has automated medical inquiry response, letter generation, and knowledge base management.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 83%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Automates inquiry responses, uses AI for letter generation, optimizes knowledge base\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | MI department leadership |\n| Pain | 5 | AI reduces response burden |\n| Actions | 7 | Drives MI operations |\n| Needs | 7 | AI-powered MI tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 6 | MI response scenarios |', TRUE),

  ('med-info-mgr-orchestrator', 'Medical Information Manager - Strategic MI Leader', E'## Medical Information Manager (Orchestrator)\n\n### Professional Context\nStrategic MI manager who orchestrates AI-enabled medical information services. Coordinates inquiry management, content development, and cross-functional medical support.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs MI AI strategy, coordinates content systems, builds MI excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic MI role |\n| Pain | 4 | AI handles operational load |\n| Actions | 7 | Shapes MI direction |\n| Needs | 8 | Integrated MI platform |\n| Emotions | 8 | Enthusiastic about MI AI |\n| Scenarios | 7 | Strategic MI scenarios |', TRUE),

  ('med-info-mgr-learner', 'Medical Information Manager - Quality-Focused Builder', E'## Medical Information Manager (Learner)\n\n### Professional Context\nQuality-focused MI manager building AI capabilities for medical information services. Pilots AI for specific inquiry types while maintaining accuracy standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for inquiries, validates response accuracy, builds team skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | MI leadership role |\n| Pain | 7 | Growing inquiry volume |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated MI AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | MI quality scenarios |', TRUE),

  ('med-info-mgr-skeptic', 'Medical Information Manager - Accuracy Guardian', E'## Medical Information Manager (Skeptic)\n\n### Professional Context\nAccuracy-focused MI manager who questions AI in medical response contexts. Emphasizes scientific accuracy and compliance in all medical communications.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy, requires human review, emphasizes compliance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | MI role |\n| Pain | 9 | Concerned about AI inaccuracy |\n| Actions | 5 | Conservative approach |\n| Needs | 9 | Validated, compliant AI |\n| Emotions | 3 | Skeptical of AI responses |\n| Scenarios | 8 | Accuracy-critical scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 13: Global Medical Info Scientist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-med-info-sci-automator', 'Global Medical Info Scientist - AI-Powered Analyst', E'## Global Medical Info Scientist (Automator)\n\n### Professional Context\nAnalytically-driven scientist who leverages AI for literature analysis, evidence synthesis, and response development. Champions AI tools across the MI team.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 81%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for literature synthesis, automates evidence analysis, optimizes response workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Scientific specialist role |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 6 | Scientific analysis decisions |\n| Needs | 7 | AI analysis tools |\n| Emotions | 8 | Excited by AI capabilities |\n| Scenarios | 6 | Analysis scenarios |', TRUE),

  ('global-med-info-sci-orchestrator', 'Global Medical Info Scientist - Strategic Scientific Leader', E'## Global Medical Info Scientist (Orchestrator)\n\n### Professional Context\nStrategic scientist who orchestrates complex scientific projects using AI-enabled research and analysis tools. Coordinates global evidence synthesis efforts.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates global projects, designs AI-enabled research, mentors junior scientists\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Senior scientist role |\n| Pain | 5 | Complex coordination |\n| Actions | 7 | Strategic scientific decisions |\n| Needs | 7 | Integrated research platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Complex scientific scenarios |', TRUE),

  ('global-med-info-sci-learner', 'Global Medical Info Scientist - Evidence-Focused Scientist', E'## Global Medical Info Scientist (Learner)\n\n### Professional Context\nEvidence-focused scientist building AI capabilities for scientific analysis. Explores AI for literature reviews while maintaining scientific rigor.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 48%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for research, validates scientific outputs, builds analytical skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Scientist role |\n| Pain | 7 | Growing research demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated research AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Research scenarios |', TRUE),

  ('global-med-info-sci-skeptic', 'Global Medical Info Scientist - Scientific Rigor Guardian', E'## Global Medical Info Scientist (Skeptic)\n\n### Professional Context\nScientifically rigorous scientist who questions AI in research contexts. Emphasizes peer-reviewed evidence and validation of all AI-generated scientific content.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 24%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI research quality, requires validation, emphasizes peer review\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Scientist role |\n| Pain | 8 | Concerned about AI quality |\n| Actions | 5 | Conservative scientific approach |\n| Needs | 8 | Validated scientific AI |\n| Emotions | 3 | Skeptical of AI in research |\n| Scenarios | 7 | Scientific validation scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 14: Global Publications Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-pubs-mgr-automator', 'Global Publications Manager - AI-Enabled Publisher', E'## Global Publications Manager (Automator)\n\n### Professional Context\nEfficiency-focused publications manager who leverages AI for manuscript tracking, literature surveillance, and publication planning optimization.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for manuscript tracking, automates literature monitoring, optimizes publication workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Publications management role |\n| Pain | 6 | AI reduces tracking burden |\n| Actions | 7 | Drives publications operations |\n| Needs | 7 | AI publication tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 6 | Publication management scenarios |', TRUE),

  ('global-pubs-mgr-orchestrator', 'Global Publications Manager - Strategic Publications Coordinator', E'## Global Publications Manager (Orchestrator)\n\n### Professional Context\nStrategic publications manager who orchestrates global publication planning using AI-enabled workflow systems. Coordinates authors, reviewers, and vendors.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates global publications, designs AI-enabled workflows, builds publication excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Global coordination role |\n| Pain | 5 | Complex coordination |\n| Actions | 7 | Shapes publication direction |\n| Needs | 8 | Integrated publication platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Complex publication scenarios |', TRUE),

  ('global-pubs-mgr-learner', 'Global Publications Manager - Quality-Focused Coordinator', E'## Global Publications Manager (Learner)\n\n### Professional Context\nQuality-focused publications manager building AI capabilities for publication management. Pilots AI for specific workflows while maintaining quality standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 43%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI workflows, validates quality, builds team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Management role |\n| Pain | 7 | Growing publication volume |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Proven AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Quality management scenarios |', TRUE),

  ('global-pubs-mgr-skeptic', 'Global Publications Manager - Publication Integrity Focus', E'## Global Publications Manager (Skeptic)\n\n### Professional Context\nIntegrity-focused publications manager who questions AI in publication contexts. Concerned about AI impact on scientific authorship and journal policies.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI in authorship, monitors journal policies, emphasizes integrity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Publications role |\n| Pain | 8 | Concerned about AI integrity |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Transparent, ethical AI |\n| Emotions | 4 | Skeptical of AI in publishing |\n| Scenarios | 7 | Integrity scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 15: Medical Affairs Program Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-affairs-pm-automator', 'Medical Affairs PM - Project Automation Expert', E'## Medical Affairs Program Manager (Automator)\n\n### Professional Context\nEfficiency-focused PM who has automated project tracking, resource planning, and stakeholder communications using AI-enabled project management tools.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Automates project tracking, uses AI for resource planning, optimizes communications\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Program management role |\n| Pain | 5 | AI reduces PM burden |\n| Actions | 7 | Drives program execution |\n| Needs | 7 | AI-powered PM tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 6 | PM scenarios |', TRUE),

  ('med-affairs-pm-orchestrator', 'Medical Affairs PM - Strategic Program Leader', E'## Medical Affairs Program Manager (Orchestrator)\n\n### Professional Context\nStrategic PM who orchestrates complex medical affairs programs using AI-enabled portfolio management. Coordinates cross-functional initiatives and resource allocation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates program portfolio, designs AI-enabled PM systems, builds PM excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic PM role |\n| Pain | 4 | AI handles complexity |\n| Actions | 7 | Shapes program direction |\n| Needs | 8 | Integrated PM platform |\n| Emotions | 8 | Enthusiastic about AI PM |\n| Scenarios | 7 | Complex program scenarios |', TRUE),

  ('med-affairs-pm-learner', 'Medical Affairs PM - Capability Builder', E'## Medical Affairs Program Manager (Learner)\n\n### Professional Context\nCapability-focused PM building AI skills for program management. Pilots AI tools for specific project types while developing team expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI PM tools, builds team capabilities, measures adoption\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | PM role |\n| Pain | 7 | Growing project complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Easy-to-use AI PM tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Capability building scenarios |', TRUE),

  ('med-affairs-pm-skeptic', 'Medical Affairs PM - Control-Focused PM', E'## Medical Affairs Program Manager (Skeptic)\n\n### Professional Context\nControl-focused PM who emphasizes project governance and visibility. Skeptical of AI that reduces project control or creates black boxes.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes project control, questions AI predictions, requires audit trails\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | PM role |\n| Pain | 8 | Concerned about AI control |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Transparent, auditable AI |\n| Emotions | 4 | Skeptical of AI PM tools |\n| Scenarios | 7 | Governance scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 16: Medical Education Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-ed-mgr-automator', 'Medical Education Manager - Digital Learning Champion', E'## Medical Education Manager (Automator)\n\n### Professional Context\nDigital-first education manager who leverages AI for content creation, learner personalization, and program analytics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 76%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for content creation, automates learning paths, tracks engagement\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Education management role |\n| Pain | 6 | AI reduces content burden |\n| Actions | 6 | Drives education programs |\n| Needs | 7 | AI content tools |\n| Emotions | 8 | Excited by AI in education |\n| Scenarios | 5 | Educational scenarios |', TRUE),

  ('med-ed-mgr-orchestrator', 'Medical Education Manager - Strategic Learning Designer', E'## Medical Education Manager (Orchestrator)\n\n### Professional Context\nStrategic education manager who orchestrates comprehensive learning programs using AI-enabled platforms. Coordinates content, delivery, and outcomes measurement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs AI-enabled programs, coordinates learning ecosystems, builds education excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Strategic education role |\n| Pain | 5 | Program coordination |\n| Actions | 6 | Shapes education direction |\n| Needs | 7 | Integrated learning platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Program design scenarios |', TRUE),

  ('med-ed-mgr-learner', 'Medical Education Manager - Quality Educator', E'## Medical Education Manager (Learner)\n\n### Professional Context\nQuality-focused education manager building AI capabilities for content development. Pilots AI for specific content types while maintaining educational standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI content tools, validates educational quality, develops capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Education role |\n| Pain | 7 | Content demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated education AI |\n| Emotions | 6 | Hopeful about AI |\n| Scenarios | 5 | Content development scenarios |', TRUE),

  ('med-ed-mgr-skeptic', 'Medical Education Manager - Learning Quality Guardian', E'## Medical Education Manager (Skeptic)\n\n### Professional Context\nQuality guardian who questions AI in educational contexts. Concerned about content accuracy and authentic learning engagement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI content, requires expert review, emphasizes engagement\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Education role |\n| Pain | 8 | Concerned about AI quality |\n| Actions | 5 | Conservative approach |\n| Needs | 8 | Validated educational AI |\n| Emotions | 4 | Skeptical of AI content |\n| Scenarios | 6 | Quality scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 4: MID-LEVEL / SPECIALIST ROLES
-- =====================================================

-- Role 17: Medical Science Liaison (MSL)
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('msl-automator', 'MSL - Digital Field Expert', E'## Medical Science Liaison (Automator)\n\n### Professional Context\nTech-savvy MSL who leverages AI for scientific preparation, territory planning, and call documentation. Early adopter of digital field tools.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 74%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for scientific prep, automates call planning, documents interactions efficiently\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field professional |\n| Pain | 6 | AI reduces prep time |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI field tools |\n| Emotions | 8 | Excited by AI capabilities |\n| Scenarios | 5 | Field engagement scenarios |', TRUE),

  ('msl-orchestrator', 'MSL - Strategic KOL Partner', E'## Medical Science Liaison (Orchestrator)\n\n### Professional Context\nStrategic MSL who coordinates complex KOL engagement using AI-enabled insights. Synthesizes scientific intelligence to drive meaningful scientific partnerships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates KOL strategy, synthesizes scientific insights, builds strategic relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field role |\n| Pain | 5 | Complex KOL coordination |\n| Actions | 6 | Strategic field decisions |\n| Needs | 7 | Integrated KOL insights |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Strategic KOL scenarios |', TRUE),

  ('msl-learner', 'MSL - Scientific Excellence Focus', E'## Medical Science Liaison (Learner)\n\n### Professional Context\nScience-focused MSL building AI capabilities for field engagement. Explores AI for scientific preparation while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 40%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for preparation, learns from results, builds scientific skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field professional |\n| Pain | 7 | Scientific prep demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Curious about AI |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('msl-skeptic', 'MSL - Relationship-First Professional', E'## Medical Science Liaison (Skeptic)\n\n### Professional Context\nRelationship-focused MSL who prioritizes authentic scientific dialogue over AI efficiency. Values deep KOL relationships built through personal engagement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 20%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes personal engagement, questions AI in dialogue, values relationship depth\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field role |\n| Pain | 8 | Concerned AI diminishes relationships |\n| Actions | 4 | Traditional approach |\n| Needs | 5 | AI that supports relationships |\n| Emotions | 3 | Skeptical of field AI |\n| Scenarios | 6 | Relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 18: Medical Writer
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-writer-automator', 'Medical Writer - AI-Augmented Writer', E'## Medical Writer (Automator)\n\n### Professional Context\nTech-savvy medical writer who leverages AI for draft generation, literature research, and document formatting. Uses AI to enhance productivity while maintaining scientific accuracy.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for drafting, automates literature searches, optimizes document workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Writing specialist |\n| Pain | 5 | AI reduces drafting burden |\n| Actions | 5 | Individual contributor |\n| Needs | 7 | AI writing tools |\n| Emotions | 8 | Excited by AI writing capabilities |\n| Scenarios | 5 | Writing scenarios |', TRUE),

  ('med-writer-orchestrator', 'Medical Writer - Strategic Scientific Communicator', E'## Medical Writer (Orchestrator)\n\n### Professional Context\nStrategic medical writer who orchestrates complex documentation projects using AI-enabled writing and research tools. Coordinates multiple documents and stakeholders.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates writing projects, designs AI-enabled workflows, builds writing excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Experienced writer |\n| Pain | 5 | Project coordination |\n| Actions | 6 | Strategic writing decisions |\n| Needs | 7 | Integrated writing platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Complex writing scenarios |', TRUE),

  ('med-writer-learner', 'Medical Writer - Quality-Focused Writer', E'## Medical Writer (Learner)\n\n### Professional Context\nQuality-focused medical writer building AI capabilities for scientific writing. Explores AI for specific document types while maintaining scientific accuracy.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for writing, validates accuracy, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Writer role |\n| Pain | 7 | Growing writing demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Validated writing AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Quality writing scenarios |', TRUE),

  ('med-writer-skeptic', 'Medical Writer - Scientific Accuracy Guardian', E'## Medical Writer (Skeptic)\n\n### Professional Context\nAccuracy-focused medical writer who questions AI in scientific writing contexts. Concerned about AI-generated content accuracy and scientific integrity.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 22%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy, requires extensive review, emphasizes scientific integrity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Writer role |\n| Pain | 9 | Concerned about AI inaccuracy |\n| Actions | 4 | Conservative approach |\n| Needs | 8 | Validated, accurate AI |\n| Emotions | 3 | Skeptical of AI writing |\n| Scenarios | 7 | Accuracy scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 19: Medical Information Specialist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('med-info-spec-automator', 'Medical Info Specialist - Response Efficiency Expert', E'## Medical Information Specialist (Automator)\n\n### Professional Context\nEfficiency-focused MI specialist who leverages AI for inquiry response, literature search, and letter generation. Uses AI to handle high inquiry volumes.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for responses, automates literature searches, optimizes response workflows\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | MI specialist |\n| Pain | 5 | AI reduces response burden |\n| Actions | 5 | Individual contributor |\n| Needs | 7 | AI response tools |\n| Emotions | 8 | Satisfied with AI efficiency |\n| Scenarios | 5 | Response scenarios |', TRUE),

  ('med-info-spec-orchestrator', 'Medical Info Specialist - Complex Inquiry Expert', E'## Medical Information Specialist (Orchestrator)\n\n### Professional Context\nExpert MI specialist who handles complex medical inquiries using AI-enabled research and response systems. Coordinates challenging cases requiring multi-source evidence.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Handles complex inquiries, coordinates evidence synthesis, builds MI expertise\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Expert specialist |\n| Pain | 5 | Complex inquiry coordination |\n| Actions | 6 | Expert decisions |\n| Needs | 7 | Integrated MI platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Complex inquiry scenarios |', TRUE),

  ('med-info-spec-learner', 'Medical Info Specialist - Accuracy-Focused Specialist', E'## Medical Information Specialist (Learner)\n\n### Professional Context\nAccuracy-focused MI specialist building AI capabilities for inquiry response. Explores AI for specific inquiry types while maintaining accuracy standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for responses, validates accuracy, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | MI specialist |\n| Pain | 7 | Growing inquiry volume |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Validated MI AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('med-info-spec-skeptic', 'Medical Info Specialist - Response Accuracy Guardian', E'## Medical Information Specialist (Skeptic)\n\n### Professional Context\nAccuracy-focused MI specialist who questions AI in medical response contexts. Emphasizes scientific accuracy and compliance in all medical communications.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 24%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy, requires review, emphasizes compliance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | MI role |\n| Pain | 9 | Concerned about AI inaccuracy |\n| Actions | 4 | Conservative approach |\n| Needs | 8 | Validated, compliant AI |\n| Emotions | 3 | Skeptical of AI responses |\n| Scenarios | 7 | Accuracy scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 20: Global Medical Communications Specialist
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('global-med-comms-spec-automator', 'Global Med Comms Specialist - Content Automation Expert', E'## Global Medical Communications Specialist (Automator)\n\n### Professional Context\nEfficiency-focused communications specialist who leverages AI for content development, message adaptation, and multi-channel distribution.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for content creation, automates channel adaptation, optimizes distribution\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Communications specialist |\n| Pain | 5 | AI reduces content burden |\n| Actions | 5 | Individual contributor |\n| Needs | 7 | AI content tools |\n| Emotions | 8 | Excited by AI capabilities |\n| Scenarios | 5 | Content scenarios |', TRUE),

  ('global-med-comms-spec-orchestrator', 'Global Med Comms Specialist - Strategic Communicator', E'## Global Medical Communications Specialist (Orchestrator)\n\n### Professional Context\nStrategic communications specialist who orchestrates global medical communications using AI-enabled content management and distribution systems.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates global communications, designs AI-enabled content systems, builds communications excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Strategic specialist |\n| Pain | 5 | Global coordination |\n| Actions | 6 | Strategic communications decisions |\n| Needs | 7 | Integrated communications platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Global communications scenarios |', TRUE),

  ('global-med-comms-spec-learner', 'Global Med Comms Specialist - Quality Content Developer', E'## Global Medical Communications Specialist (Learner)\n\n### Professional Context\nQuality-focused communications specialist building AI capabilities for content development. Explores AI for specific content types while maintaining quality standards.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 43%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for content, validates quality, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Communications role |\n| Pain | 7 | Growing content demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Validated content AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Content development scenarios |', TRUE),

  ('global-med-comms-spec-skeptic', 'Global Med Comms Specialist - Messaging Accuracy Guardian', E'## Global Medical Communications Specialist (Skeptic)\n\n### Professional Context\nAccuracy-focused communications specialist who questions AI in medical messaging contexts. Concerned about message accuracy and regulatory compliance.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI accuracy, requires review, emphasizes compliance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Communications role |\n| Pain | 8 | Concerned about AI accuracy |\n| Actions | 4 | Conservative approach |\n| Needs | 8 | Validated, compliant AI |\n| Emotions | 4 | Skeptical of AI content |\n| Scenarios | 6 | Accuracy scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- VERIFICATION QUERY
-- =====================================================
-- Run this after migration to verify:
-- SELECT persona_key, display_name, is_active
-- FROM personas
-- WHERE persona_key LIKE 'cmo-%'
--    OR persona_key LIKE 'vp-med-%'
--    OR persona_key LIKE 'global-med-%'
--    OR persona_key LIKE 'head-publications-%'
--    OR persona_key LIKE 'regional-msl-%'
--    OR persona_key LIKE 'med-affairs-%'
--    OR persona_key LIKE 'med-strategy-%'
--    OR persona_key LIKE 'med-dir-%'
--    OR persona_key LIKE 'msl-manager-%'
--    OR persona_key LIKE 'senior-msl-%'
--    OR persona_key LIKE 'global-med-ed-%'
--    OR persona_key LIKE 'med-info-%'
--    OR persona_key LIKE 'global-pubs-%'
--    OR persona_key LIKE 'med-ed-%'
--    OR persona_key LIKE 'msl-%'
--    OR persona_key LIKE 'med-writer-%'
--    OR persona_key LIKE 'global-med-comms-%'
-- ORDER BY persona_key;

-- Expected: 80 rows (20 roles × 4 archetypes)
