-- =====================================================
-- MIGRATION: 049 - Commercial Expanded Personas
-- Date: 2025-11-29
-- Description: 80 additional personas for Commercial roles
-- Covers: Sales leadership, Regional Sales Managers, Account
--         Managers, Business Development, Trade/Distribution
-- =====================================================

-- This migration SUPPLEMENTS the original Commercial migration (042)
-- which covered core Marketing/Brand and executive Commercial roles.
-- This migration adds coverage for Sales, Account Management,
-- Business Development, and Trade/Distribution functions.

-- =====================================================
-- SECTION 1: SALES LEADERSHIP ROLES
-- =====================================================

-- Role 1: National Sales Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('nat-sales-dir-automator', 'National Sales Director - Data-Driven Sales Leader', E'## National Sales Director (Automator)\n\n### Professional Context\nData-driven sales leader who leverages AI for territory analytics, sales forecasting, and performance optimization across the national sales force.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for sales analytics, automates forecasting, optimizes territory planning\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | National sales leadership |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 8 | Drives national sales strategy |\n| Needs | 8 | AI-powered sales analytics |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 8 | National sales scenarios |', TRUE),

  ('nat-sales-dir-orchestrator', 'National Sales Director - Strategic Sales Architect', E'## National Sales Director (Orchestrator)\n\n### Professional Context\nStrategic sales leader who orchestrates national sales transformation using AI-enabled CRM and sales intelligence platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 90%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs national sales AI strategy, coordinates regional teams, builds sales excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | Strategic sales leadership |\n| Pain | 4 | AI handles complexity |\n| Actions | 9 | Shapes national sales direction |\n| Needs | 9 | Integrated sales platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 9 | Enterprise sales scenarios |', TRUE),

  ('nat-sales-dir-learner', 'National Sales Director - Sales Capability Builder', E'## National Sales Director (Learner)\n\n### Professional Context\nCapability-focused sales director building AI skills across the national sales organization. Pilots AI in select regions while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 48%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI in regions, validates results, builds sales team capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | National leadership |\n| Pain | 7 | Growing sales complexity |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Proven sales AI tools |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 8 | Capability building scenarios |', TRUE),

  ('nat-sales-dir-skeptic', 'National Sales Director - Relationship-First Leader', E'## National Sales Director (Skeptic)\n\n### Professional Context\nRelationship-focused sales director who prioritizes customer relationships over AI metrics. Skeptical that AI can capture sales relationship nuances.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 30%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes customer relationships, questions AI metrics, requires validation\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 8 | National leadership |\n| Pain | 9 | Concerned AI diminishes relationships |\n| Actions | 6 | Conservative approach |\n| Needs | 8 | AI that enhances relationships |\n| Emotions | 4 | Skeptical of sales AI |\n| Scenarios | 8 | Customer relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 2: Regional Sales Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('regional-sales-mgr-automator', 'Regional Sales Manager - Territory Analytics Expert', E'## Regional Sales Manager (Automator)\n\n### Professional Context\nAnalytics-savvy regional manager who leverages AI for territory optimization, rep performance tracking, and sales forecasting.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for territory analytics, automates performance tracking, optimizes forecasting\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional sales leadership |\n| Pain | 6 | AI reduces management burden |\n| Actions | 7 | Drives regional performance |\n| Needs | 7 | AI-powered territory tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 7 | Regional management scenarios |', TRUE),

  ('regional-sales-mgr-orchestrator', 'Regional Sales Manager - Strategic Regional Leader', E'## Regional Sales Manager (Orchestrator)\n\n### Professional Context\nStrategic regional manager who orchestrates sales performance using AI-enabled CRM and coaching platforms. Coordinates district managers and key accounts.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs regional AI strategy, coordinates districts, builds sales culture\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional strategic role |\n| Pain | 5 | Coordination challenges |\n| Actions | 8 | Shapes regional direction |\n| Needs | 8 | Integrated regional platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic regional scenarios |', TRUE),

  ('regional-sales-mgr-learner', 'Regional Sales Manager - Team Developer', E'## Regional Sales Manager (Learner)\n\n### Professional Context\nDevelopment-focused regional manager building AI capabilities across the sales team. Pilots AI tools with select reps while providing coaching.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI with team, provides coaching, measures adoption\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional management |\n| Pain | 7 | Growing team demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Team development scenarios |', TRUE),

  ('regional-sales-mgr-skeptic', 'Regional Sales Manager - Customer Focus Guardian', E'## Regional Sales Manager (Skeptic)\n\n### Professional Context\nCustomer-focused regional manager who prioritizes authentic customer relationships over AI-driven efficiency. Values field time over screen time.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes customer face time, questions AI metrics, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Regional role |\n| Pain | 8 | Concerned AI reduces field time |\n| Actions | 5 | Traditional sales approach |\n| Needs | 7 | AI that supports field work |\n| Emotions | 4 | Skeptical of sales AI |\n| Scenarios | 7 | Customer relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 3: District Sales Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('district-sales-mgr-automator', 'District Sales Manager - Performance Analytics Expert', E'## District Sales Manager (Automator)\n\n### Professional Context\nAnalytics-driven district manager who leverages AI for rep coaching, call planning, and performance tracking.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 76%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for performance analytics, automates call planning, optimizes coaching\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | District leadership |\n| Pain | 6 | AI reduces admin burden |\n| Actions | 6 | Drives district performance |\n| Needs | 7 | AI coaching tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 6 | District management scenarios |', TRUE),

  ('district-sales-mgr-orchestrator', 'District Sales Manager - Strategic Field Leader', E'## District Sales Manager (Orchestrator)\n\n### Professional Context\nStrategic district manager who orchestrates field excellence using AI-enabled sales tools. Coordinates rep activities and key account coverage.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates field activities, designs AI-enabled processes, builds team excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | District leadership |\n| Pain | 5 | Coordination challenges |\n| Actions | 7 | Shapes district direction |\n| Needs | 7 | Integrated field platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic field scenarios |', TRUE),

  ('district-sales-mgr-learner', 'District Sales Manager - Rep Developer', E'## District Sales Manager (Learner)\n\n### Professional Context\nDevelopment-focused district manager building AI capabilities with the sales team. Pilots AI tools while coaching reps on adoption.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI with reps, coaches on adoption, measures results\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | District management |\n| Pain | 7 | Growing team demands |\n| Actions | 6 | Measured approach |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Rep development scenarios |', TRUE),

  ('district-sales-mgr-skeptic', 'District Sales Manager - Field Relationship Focus', E'## District Sales Manager (Skeptic)\n\n### Professional Context\nRelationship-focused district manager who prioritizes field presence and customer relationships over AI efficiency.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 24%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes field presence, questions AI metrics, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | District role |\n| Pain | 8 | Concerned AI reduces field time |\n| Actions | 5 | Traditional approach |\n| Needs | 6 | AI that supports field work |\n| Emotions | 3 | Skeptical of sales AI |\n| Scenarios | 7 | Field relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 4: Hospital Sales Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('hospital-sales-mgr-automator', 'Hospital Sales Manager - Account Analytics Expert', E'## Hospital Sales Manager (Automator)\n\n### Professional Context\nAnalytics-savvy hospital sales manager who leverages AI for account mapping, formulary tracking, and sales cycle optimization.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for account mapping, automates formulary tracking, optimizes sales cycles\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Hospital sales leadership |\n| Pain | 6 | AI reduces tracking burden |\n| Actions | 6 | Drives hospital sales |\n| Needs | 7 | AI account tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 6 | Hospital sales scenarios |', TRUE),

  ('hospital-sales-mgr-orchestrator', 'Hospital Sales Manager - Strategic Account Leader', E'## Hospital Sales Manager (Orchestrator)\n\n### Professional Context\nStrategic hospital sales manager who orchestrates complex account strategies using AI-enabled account intelligence and CRM platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs account AI strategy, coordinates stakeholders, builds account excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Hospital sales role |\n| Pain | 5 | Complex account coordination |\n| Actions | 7 | Shapes account direction |\n| Needs | 8 | Integrated account platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic account scenarios |', TRUE),

  ('hospital-sales-mgr-learner', 'Hospital Sales Manager - Account Capability Builder', E'## Hospital Sales Manager (Learner)\n\n### Professional Context\nCapability-focused hospital sales manager building AI skills for account management. Pilots AI for specific accounts while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 43%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Pilots AI for accounts, validates results, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Hospital sales |\n| Pain | 7 | Growing account complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated account AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Account development scenarios |', TRUE),

  ('hospital-sales-mgr-skeptic', 'Hospital Sales Manager - Clinical Relationship Focus', E'## Hospital Sales Manager (Skeptic)\n\n### Professional Context\nRelationship-focused hospital sales manager who prioritizes clinical stakeholder relationships over AI metrics. Values depth over breadth.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes clinical relationships, questions AI metrics, values depth\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Hospital sales role |\n| Pain | 8 | Concerned AI diminishes relationships |\n| Actions | 5 | Relationship-first approach |\n| Needs | 7 | AI that supports relationships |\n| Emotions | 4 | Skeptical of sales AI |\n| Scenarios | 7 | Clinical relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 5: Sales Training Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sales-training-mgr-automator', 'Sales Training Manager - Learning Tech Expert', E'## Sales Training Manager (Automator)\n\n### Professional Context\nTech-savvy training manager who leverages AI for content development, learning personalization, and training effectiveness measurement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 81%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for content creation, automates learning paths, measures effectiveness\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Training leadership |\n| Pain | 5 | AI reduces content burden |\n| Actions | 7 | Drives training programs |\n| Needs | 7 | AI learning tools |\n| Emotions | 9 | Excited by AI in training |\n| Scenarios | 6 | Training scenarios |', TRUE),

  ('sales-training-mgr-orchestrator', 'Sales Training Manager - Strategic Learning Architect', E'## Sales Training Manager (Orchestrator)\n\n### Professional Context\nStrategic training manager who orchestrates sales learning programs using AI-enabled LMS and content platforms. Coordinates training with field needs.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs training AI strategy, coordinates with field, builds learning excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic training role |\n| Pain | 5 | Program coordination |\n| Actions | 7 | Shapes training direction |\n| Needs | 8 | Integrated learning platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic training scenarios |', TRUE),

  ('sales-training-mgr-learner', 'Sales Training Manager - Instructional Developer', E'## Sales Training Manager (Learner)\n\n### Professional Context\nDevelopment-focused training manager building AI capabilities for sales training. Explores AI for specific content types while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for content, validates effectiveness, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Training role |\n| Pain | 7 | Growing training demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated training AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Content development scenarios |', TRUE),

  ('sales-training-mgr-skeptic', 'Sales Training Manager - Experiential Learning Focus', E'## Sales Training Manager (Skeptic)\n\n### Professional Context\nExperiential learning advocate who questions AI in sales training contexts. Emphasizes role-play, coaching, and field experience over digital content.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes experiential learning, questions AI content, values coaching\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Training role |\n| Pain | 8 | Concerned AI replaces coaching |\n| Actions | 5 | Traditional training approach |\n| Needs | 7 | AI that enhances coaching |\n| Emotions | 4 | Skeptical of AI training |\n| Scenarios | 7 | Coaching scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 2: FIELD SALES ROLES
-- =====================================================

-- Role 6: Sales Representative
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sales-rep-automator', 'Sales Representative - Digital Field Expert', E'## Sales Representative (Automator)\n\n### Professional Context\nTech-savvy sales rep who leverages AI for call preparation, territory planning, and customer insights. Early adopter of digital sales tools.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 74%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for call prep, automates planning, leverages customer insights\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field sales |\n| Pain | 6 | AI reduces prep time |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI field tools |\n| Emotions | 8 | Excited by AI capabilities |\n| Scenarios | 5 | Field sales scenarios |', TRUE),

  ('sales-rep-orchestrator', 'Sales Representative - Strategic Territory Expert', E'## Sales Representative (Orchestrator)\n\n### Professional Context\nStrategic sales rep who coordinates complex territory activities using AI-enabled CRM and intelligence tools. Synthesizes customer insights for targeted engagement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates territory strategy, synthesizes insights, builds customer relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field role |\n| Pain | 5 | Territory coordination |\n| Actions | 6 | Strategic field decisions |\n| Needs | 7 | Integrated territory tools |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Strategic territory scenarios |', TRUE),

  ('sales-rep-learner', 'Sales Representative - Skills Developer', E'## Sales Representative (Learner)\n\n### Professional Context\nDevelopment-focused sales rep building AI capabilities for field work. Explores AI tools while developing sales expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 40%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI tools, learns from results, builds field skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field role |\n| Pain | 7 | Growing field demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Curious about AI |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('sales-rep-skeptic', 'Sales Representative - Relationship-First Professional', E'## Sales Representative (Skeptic)\n\n### Professional Context\nRelationship-focused sales rep who prioritizes authentic customer connections over AI efficiency. Values face time and personal relationships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 20%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes customer relationships, questions AI metrics, values face time\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Field role |\n| Pain | 8 | Concerned AI reduces authenticity |\n| Actions | 4 | Traditional sales approach |\n| Needs | 5 | AI that supports relationships |\n| Emotions | 3 | Skeptical of sales AI |\n| Scenarios | 6 | Relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 7: Hospital Sales Representative
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('hospital-sales-rep-automator', 'Hospital Sales Rep - Clinical Intelligence Expert', E'## Hospital Sales Representative (Automator)\n\n### Professional Context\nTech-savvy hospital rep who leverages AI for clinical intelligence, formulary research, and stakeholder mapping.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 75%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for clinical intel, automates research, maps stakeholders\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Hospital field sales |\n| Pain | 6 | AI reduces research burden |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI hospital tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 5 | Hospital sales scenarios |', TRUE),

  ('hospital-sales-rep-orchestrator', 'Hospital Sales Rep - Strategic Account Expert', E'## Hospital Sales Representative (Orchestrator)\n\n### Professional Context\nStrategic hospital rep who coordinates complex account activities using AI-enabled account intelligence. Navigates hospital decision-making processes.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 83%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates account strategy, synthesizes intel, navigates committees\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Hospital field role |\n| Pain | 5 | Complex account navigation |\n| Actions | 6 | Strategic account decisions |\n| Needs | 7 | Integrated account platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Strategic account scenarios |', TRUE),

  ('hospital-sales-rep-learner', 'Hospital Sales Rep - Clinical Skills Developer', E'## Hospital Sales Representative (Learner)\n\n### Professional Context\nDevelopment-focused hospital rep building AI capabilities for clinical selling. Explores AI for specific use cases while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 41%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for accounts, validates results, builds skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Hospital field role |\n| Pain | 7 | Growing clinical complexity |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Validated clinical AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Clinical learning scenarios |', TRUE),

  ('hospital-sales-rep-skeptic', 'Hospital Sales Rep - Clinical Relationship Focus', E'## Hospital Sales Representative (Skeptic)\n\n### Professional Context\nRelationship-focused hospital rep who prioritizes clinical stakeholder relationships over AI efficiency. Values trust built through personal engagement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 21%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes clinical trust, questions AI in clinical contexts, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Hospital role |\n| Pain | 8 | Concerned AI diminishes trust |\n| Actions | 4 | Relationship-first approach |\n| Needs | 5 | AI that supports trust |\n| Emotions | 3 | Skeptical of AI in clinical |\n| Scenarios | 6 | Clinical relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 8: Specialty Sales Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('specialty-sales-lead-automator', 'Specialty Sales Lead - Therapeutic Intelligence Expert', E'## Specialty Sales Lead (Automator)\n\n### Professional Context\nSpecialty-focused sales lead who leverages AI for therapeutic area intelligence, specialty prescriber insights, and patient journey mapping.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for TA intelligence, automates prescriber analysis, maps patient journeys\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Specialty sales leadership |\n| Pain | 5 | AI reduces research burden |\n| Actions | 7 | Leads specialty sales |\n| Needs | 7 | AI specialty tools |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Specialty sales scenarios |', TRUE),

  ('specialty-sales-lead-orchestrator', 'Specialty Sales Lead - Strategic TA Leader', E'## Specialty Sales Lead (Orchestrator)\n\n### Professional Context\nStrategic specialty sales leader who orchestrates therapeutic area sales using AI-enabled intelligence and engagement platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs TA AI strategy, coordinates specialty teams, builds TA excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic TA role |\n| Pain | 5 | TA coordination |\n| Actions | 8 | Shapes TA direction |\n| Needs | 8 | Integrated TA platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic TA scenarios |', TRUE),

  ('specialty-sales-lead-learner', 'Specialty Sales Lead - TA Capability Builder', E'## Specialty Sales Lead (Learner)\n\n### Professional Context\nCapability-focused specialty sales lead building AI skills for therapeutic area selling. Develops expertise while coaching team.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops TA AI expertise, coaches team, validates results\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Specialty sales |\n| Pain | 7 | Growing TA complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated TA AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 6 | TA development scenarios |', TRUE),

  ('specialty-sales-lead-skeptic', 'Specialty Sales Lead - Scientific Relationship Focus', E'## Specialty Sales Lead (Skeptic)\n\n### Professional Context\nScientific relationship-focused specialty sales lead who prioritizes clinical credibility over AI metrics. Values deep therapeutic expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 27%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes clinical credibility, questions AI in specialty, values expertise\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Specialty role |\n| Pain | 8 | Concerned AI oversimplifies |\n| Actions | 5 | Expertise-first approach |\n| Needs | 7 | AI that supports expertise |\n| Emotions | 4 | Skeptical of specialty AI |\n| Scenarios | 7 | Scientific relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 3: ACCOUNT MANAGEMENT ROLES
-- =====================================================

-- Role 9: Key Account Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('key-account-mgr-automator', 'Key Account Manager - Account Intelligence Expert', E'## Key Account Manager (Automator)\n\n### Professional Context\nAnalytics-savvy KAM who leverages AI for account mapping, stakeholder analysis, and business review preparation.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for account mapping, automates analysis, prepares reviews efficiently\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Key account leadership |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Drives key account strategy |\n| Needs | 7 | AI account intelligence |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Key account scenarios |', TRUE),

  ('key-account-mgr-orchestrator', 'Key Account Manager - Strategic Partnership Architect', E'## Key Account Manager (Orchestrator)\n\n### Professional Context\nStrategic KAM who orchestrates complex account partnerships using AI-enabled CRM and account planning platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs account AI strategy, coordinates stakeholders, builds partnerships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic account role |\n| Pain | 4 | AI handles complexity |\n| Actions | 8 | Shapes account partnerships |\n| Needs | 8 | Integrated account platform |\n| Emotions | 9 | Energized by AI potential |\n| Scenarios | 8 | Strategic partnership scenarios |', TRUE),

  ('key-account-mgr-learner', 'Key Account Manager - Account Capability Builder', E'## Key Account Manager (Learner)\n\n### Professional Context\nCapability-focused KAM building AI skills for strategic account management. Develops expertise while managing key accounts.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops account AI skills, validates results, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Account management |\n| Pain | 7 | Growing account complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated account AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Account development scenarios |', TRUE),

  ('key-account-mgr-skeptic', 'Key Account Manager - Partnership Relationship Focus', E'## Key Account Manager (Skeptic)\n\n### Professional Context\nRelationship-focused KAM who prioritizes genuine partnerships over AI metrics. Values trust and long-term relationship building.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes genuine partnerships, questions AI metrics, values trust\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Account role |\n| Pain | 8 | Concerned AI diminishes trust |\n| Actions | 5 | Partnership-first approach |\n| Needs | 7 | AI that supports trust |\n| Emotions | 4 | Skeptical of account AI |\n| Scenarios | 8 | Partnership trust scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 10: Strategic Account Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('strategic-account-mgr-automator', 'Strategic Account Manager - Enterprise Analytics Expert', E'## Strategic Account Manager (Automator)\n\n### Professional Context\nAnalytics-driven SAM who leverages AI for enterprise account analysis, contract optimization, and strategic planning.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 81%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for enterprise analysis, automates contract analytics, optimizes planning\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic account leadership |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 7 | Drives strategic accounts |\n| Needs | 8 | AI enterprise analytics |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 8 | Strategic account scenarios |', TRUE),

  ('strategic-account-mgr-orchestrator', 'Strategic Account Manager - Enterprise Partnership Architect', E'## Strategic Account Manager (Orchestrator)\n\n### Professional Context\nEnterprise strategist who orchestrates complex strategic partnerships using AI-enabled account intelligence and planning platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 89%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs enterprise AI strategy, coordinates stakeholders, builds strategic partnerships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Enterprise strategic role |\n| Pain | 4 | AI handles enterprise complexity |\n| Actions | 9 | Shapes strategic partnerships |\n| Needs | 9 | Integrated enterprise platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 9 | Enterprise partnership scenarios |', TRUE),

  ('strategic-account-mgr-learner', 'Strategic Account Manager - Enterprise Capability Builder', E'## Strategic Account Manager (Learner)\n\n### Professional Context\nCapability-focused SAM building AI skills for enterprise account management. Develops strategic expertise while managing key partnerships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 47%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops enterprise AI skills, validates results, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic management |\n| Pain | 7 | Growing enterprise complexity |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Validated enterprise AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 7 | Capability development scenarios |', TRUE),

  ('strategic-account-mgr-skeptic', 'Strategic Account Manager - C-Suite Relationship Focus', E'## Strategic Account Manager (Skeptic)\n\n### Professional Context\nC-suite relationship-focused SAM who prioritizes executive partnerships over AI metrics. Values trust at the highest organizational levels.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 29%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes C-suite relationships, questions AI at executive level, values trust\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic role |\n| Pain | 9 | Concerned AI inappropriate for C-suite |\n| Actions | 5 | Executive relationship approach |\n| Needs | 8 | AI that supports executive trust |\n| Emotions | 3 | Skeptical of AI at strategic level |\n| Scenarios | 9 | C-suite relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 11: Account Manager - IDNs/GPOs
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('idn-gpo-acct-mgr-automator', 'IDN/GPO Account Manager - Contract Analytics Expert', E'## Account Manager - IDNs/GPOs (Automator)\n\n### Professional Context\nAnalytics-focused account manager who leverages AI for contract analysis, formulary tracking, and GPO decision mapping.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 78%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for contract analysis, automates formulary tracking, maps decisions\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | IDN/GPO account leadership |\n| Pain | 5 | AI reduces contract burden |\n| Actions | 7 | Drives IDN/GPO strategy |\n| Needs | 7 | AI contract analytics |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 7 | IDN/GPO scenarios |', TRUE),

  ('idn-gpo-acct-mgr-orchestrator', 'IDN/GPO Account Manager - Strategic Network Architect', E'## Account Manager - IDNs/GPOs (Orchestrator)\n\n### Professional Context\nStrategic account manager who orchestrates IDN/GPO relationships using AI-enabled contract and network intelligence platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs network AI strategy, coordinates stakeholders, builds network relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic network role |\n| Pain | 5 | Network coordination |\n| Actions | 8 | Shapes network strategy |\n| Needs | 8 | Integrated network platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic network scenarios |', TRUE),

  ('idn-gpo-acct-mgr-learner', 'IDN/GPO Account Manager - Network Capability Builder', E'## Account Manager - IDNs/GPOs (Learner)\n\n### Professional Context\nCapability-focused IDN/GPO manager building AI skills for network account management. Develops expertise across complex networks.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops network AI skills, validates results, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Network account management |\n| Pain | 7 | Growing network complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated network AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Network development scenarios |', TRUE),

  ('idn-gpo-acct-mgr-skeptic', 'IDN/GPO Account Manager - Committee Relationship Focus', E'## Account Manager - IDNs/GPOs (Skeptic)\n\n### Professional Context\nCommittee relationship-focused manager who prioritizes P&T and formulary committee relationships over AI metrics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes committee relationships, questions AI in committee contexts, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Network role |\n| Pain | 8 | Concerned AI inappropriate for committees |\n| Actions | 5 | Relationship-first approach |\n| Needs | 7 | AI that supports committee work |\n| Emotions | 4 | Skeptical of network AI |\n| Scenarios | 7 | Committee relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 12: Institutional Accounts Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('inst-acct-mgr-automator', 'Institutional Accounts Manager - Institution Analytics Expert', E'## Institutional Accounts Manager (Automator)\n\n### Professional Context\nAnalytics-driven institutional account manager who leverages AI for institutional analysis, contract optimization, and stakeholder mapping.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for institutional analysis, automates contracts, maps stakeholders\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Institutional leadership |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 6 | Drives institutional strategy |\n| Needs | 7 | AI institutional tools |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 6 | Institutional scenarios |', TRUE),

  ('inst-acct-mgr-orchestrator', 'Institutional Accounts Manager - Strategic Institution Leader', E'## Institutional Accounts Manager (Orchestrator)\n\n### Professional Context\nStrategic institutional manager who orchestrates complex institution relationships using AI-enabled account and contract platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs institutional AI strategy, coordinates stakeholders, builds institution relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic institutional role |\n| Pain | 5 | Institution coordination |\n| Actions | 7 | Shapes institutional strategy |\n| Needs | 8 | Integrated institutional platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic institutional scenarios |', TRUE),

  ('inst-acct-mgr-learner', 'Institutional Accounts Manager - Institution Builder', E'## Institutional Accounts Manager (Learner)\n\n### Professional Context\nCapability-focused institutional manager building AI skills for account management. Develops expertise across complex institutions.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 43%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops institutional AI skills, validates results, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Institutional management |\n| Pain | 7 | Growing institutional complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated institutional AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Institutional development scenarios |', TRUE),

  ('inst-acct-mgr-skeptic', 'Institutional Accounts Manager - Clinical Leadership Focus', E'## Institutional Accounts Manager (Skeptic)\n\n### Professional Context\nClinical leadership-focused manager who prioritizes relationships with institutional decision-makers over AI metrics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 25%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes clinical leadership, questions AI in clinical contexts, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Institutional role |\n| Pain | 8 | Concerned AI inappropriate for clinical |\n| Actions | 5 | Relationship-first approach |\n| Needs | 7 | AI that supports clinical relationships |\n| Emotions | 4 | Skeptical of institutional AI |\n| Scenarios | 7 | Clinical leadership scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- SECTION 4: BUSINESS DEVELOPMENT & TRADE
-- =====================================================

-- Role 13: Business Development Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('bd-mgr-automator', 'Business Development Manager - Deal Analytics Expert', E'## Business Development Manager (Automator)\n\n### Professional Context\nAnalytics-savvy BD manager who leverages AI for deal sourcing, market analysis, and partnership opportunity identification.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for deal sourcing, automates market analysis, identifies opportunities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | BD leadership |\n| Pain | 5 | AI reduces sourcing burden |\n| Actions | 7 | Drives BD initiatives |\n| Needs | 7 | AI deal intelligence |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Deal sourcing scenarios |', TRUE),

  ('bd-mgr-orchestrator', 'Business Development Manager - Strategic Partnership Architect', E'## Business Development Manager (Orchestrator)\n\n### Professional Context\nStrategic BD manager who orchestrates partnership development using AI-enabled market intelligence and deal management platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 87%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs BD AI strategy, coordinates partnerships, builds deal excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic BD role |\n| Pain | 5 | Partnership coordination |\n| Actions | 8 | Shapes partnership direction |\n| Needs | 8 | Integrated BD platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 8 | Strategic partnership scenarios |', TRUE),

  ('bd-mgr-learner', 'Business Development Manager - Market Intelligence Builder', E'## Business Development Manager (Learner)\n\n### Professional Context\nCapability-focused BD manager building AI skills for business development. Develops expertise in AI-enabled market intelligence.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops BD AI skills, validates market insights, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | BD management |\n| Pain | 7 | Growing market complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated BD AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 6 | Market intelligence scenarios |', TRUE),

  ('bd-mgr-skeptic', 'Business Development Manager - Relationship Deal Focus', E'## Business Development Manager (Skeptic)\n\n### Professional Context\nRelationship-focused BD manager who prioritizes genuine partner relationships over AI-driven deal metrics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 27%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes partner relationships, questions AI deal metrics, values relationships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | BD role |\n| Pain | 8 | Concerned AI reduces relationship depth |\n| Actions | 5 | Relationship-first approach |\n| Needs | 7 | AI that supports relationships |\n| Emotions | 4 | Skeptical of BD AI |\n| Scenarios | 7 | Partner relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 14: Senior Business Development Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sr-bd-mgr-automator', 'Senior BD Manager - Strategic Intelligence Expert', E'## Senior Business Development Manager (Automator)\n\n### Professional Context\nStrategically-minded senior BD manager who leverages AI for strategic deal analysis, market landscape mapping, and partnership optimization.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for strategic analysis, automates landscape mapping, optimizes partnerships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Senior BD leadership |\n| Pain | 5 | AI reduces strategic burden |\n| Actions | 8 | Drives strategic BD |\n| Needs | 8 | AI strategic intelligence |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 8 | Strategic BD scenarios |', TRUE),

  ('sr-bd-mgr-orchestrator', 'Senior BD Manager - Enterprise Deal Architect', E'## Senior Business Development Manager (Orchestrator)\n\n### Professional Context\nEnterprise BD strategist who orchestrates complex partnership portfolios using AI-enabled deal and market intelligence platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 89%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs enterprise BD AI strategy, coordinates portfolios, builds deal excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Enterprise BD role |\n| Pain | 4 | AI handles enterprise complexity |\n| Actions | 9 | Shapes enterprise partnerships |\n| Needs | 9 | Integrated enterprise BD platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 9 | Enterprise partnership scenarios |', TRUE),

  ('sr-bd-mgr-learner', 'Senior BD Manager - Strategic Capability Builder', E'## Senior Business Development Manager (Learner)\n\n### Professional Context\nCapability-focused senior BD manager building AI skills for strategic business development. Develops expertise while mentoring team.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 47%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops strategic BD AI skills, validates results, mentors team\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Senior BD management |\n| Pain | 7 | Growing strategic complexity |\n| Actions | 7 | Measured strategic approach |\n| Needs | 8 | Validated strategic BD AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 7 | Strategic development scenarios |', TRUE),

  ('sr-bd-mgr-skeptic', 'Senior BD Manager - Executive Partnership Focus', E'## Senior Business Development Manager (Skeptic)\n\n### Professional Context\nExecutive partnership-focused senior BD manager who prioritizes C-suite relationships over AI-driven deal metrics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 29%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes executive partnerships, questions AI at executive level, values trust\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Senior BD role |\n| Pain | 9 | Concerned AI inappropriate for executives |\n| Actions | 5 | Executive relationship approach |\n| Needs | 8 | AI that supports executive trust |\n| Emotions | 3 | Skeptical of AI at executive level |\n| Scenarios | 8 | Executive partnership scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 15: Trade Director
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('trade-dir-automator', 'Trade Director - Channel Analytics Expert', E'## Trade Director (Automator)\n\n### Professional Context\nAnalytics-driven trade director who leverages AI for channel analysis, inventory optimization, and distribution performance tracking.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 80%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for channel analysis, automates inventory optimization, tracks performance\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Trade leadership |\n| Pain | 5 | AI reduces analytics burden |\n| Actions | 7 | Drives trade strategy |\n| Needs | 8 | AI channel analytics |\n| Emotions | 8 | Satisfied with AI insights |\n| Scenarios | 7 | Trade strategy scenarios |', TRUE),

  ('trade-dir-orchestrator', 'Trade Director - Strategic Channel Architect', E'## Trade Director (Orchestrator)\n\n### Professional Context\nStrategic trade leader who orchestrates channel strategy using AI-enabled distribution and inventory management platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs trade AI strategy, coordinates channels, builds distribution excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Strategic trade role |\n| Pain | 4 | AI handles complexity |\n| Actions | 8 | Shapes channel direction |\n| Needs | 9 | Integrated trade platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 8 | Strategic channel scenarios |', TRUE),

  ('trade-dir-learner', 'Trade Director - Channel Capability Builder', E'## Trade Director (Learner)\n\n### Professional Context\nCapability-focused trade director building AI skills for channel management. Develops expertise while optimizing distribution.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 46%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops channel AI skills, validates results, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Trade leadership |\n| Pain | 7 | Growing channel complexity |\n| Actions | 7 | Measured approach |\n| Needs | 8 | Validated trade AI |\n| Emotions | 6 | Hopeful about AI potential |\n| Scenarios | 7 | Channel development scenarios |', TRUE),

  ('trade-dir-skeptic', 'Trade Director - Partner Relationship Focus', E'## Trade Director (Skeptic)\n\n### Professional Context\nPartner relationship-focused trade director who prioritizes channel partner relationships over AI metrics. Values long-term partnerships.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 28%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes partner relationships, questions AI metrics, values partnerships\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 7 | Trade role |\n| Pain | 8 | Concerned AI damages partnerships |\n| Actions | 5 | Partnership-first approach |\n| Needs | 8 | AI that supports partnerships |\n| Emotions | 4 | Skeptical of trade AI |\n| Scenarios | 8 | Partner relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 16: Distribution Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('dist-mgr-automator', 'Distribution Manager - Supply Analytics Expert', E'## Distribution Manager (Automator)\n\n### Professional Context\nAnalytics-focused distribution manager who leverages AI for inventory forecasting, logistics optimization, and supply chain visibility.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 79%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for forecasting, automates logistics, optimizes supply chain\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Distribution leadership |\n| Pain | 5 | AI reduces forecasting burden |\n| Actions | 7 | Drives distribution operations |\n| Needs | 7 | AI supply chain tools |\n| Emotions | 8 | Satisfied with AI accuracy |\n| Scenarios | 7 | Distribution scenarios |', TRUE),

  ('dist-mgr-orchestrator', 'Distribution Manager - Strategic Logistics Architect', E'## Distribution Manager (Orchestrator)\n\n### Professional Context\nStrategic distribution manager who orchestrates logistics using AI-enabled supply chain and inventory platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 86%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs distribution AI strategy, coordinates logistics, builds supply excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic distribution role |\n| Pain | 5 | Logistics coordination |\n| Actions | 7 | Shapes logistics direction |\n| Needs | 8 | Integrated supply platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic logistics scenarios |', TRUE),

  ('dist-mgr-learner', 'Distribution Manager - Supply Chain Builder', E'## Distribution Manager (Learner)\n\n### Professional Context\nCapability-focused distribution manager building AI skills for supply chain management. Develops expertise while optimizing operations.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 44%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Develops supply AI skills, validates forecasts, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Distribution management |\n| Pain | 7 | Growing supply complexity |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated supply AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Supply development scenarios |', TRUE),

  ('dist-mgr-skeptic', 'Distribution Manager - Operations Control Focus', E'## Distribution Manager (Skeptic)\n\n### Professional Context\nControl-focused distribution manager who emphasizes operational visibility and control over AI automation. Values process reliability.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 26%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes operational control, questions AI forecasts, values reliability\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Distribution role |\n| Pain | 8 | Concerned about AI reliability |\n| Actions | 5 | Control-first approach |\n| Needs | 8 | Reliable, auditable AI |\n| Emotions | 4 | Skeptical of supply AI |\n| Scenarios | 7 | Operations control scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 17: Sales Enablement Lead
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sales-enable-lead-automator', 'Sales Enablement Lead - Content Automation Expert', E'## Sales Enablement Lead (Automator)\n\n### Professional Context\nTech-savvy enablement lead who leverages AI for content development, sales tool optimization, and rep productivity enhancement.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 82%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for content creation, automates tool optimization, enhances productivity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Enablement leadership |\n| Pain | 5 | AI reduces content burden |\n| Actions | 7 | Drives enablement programs |\n| Needs | 8 | AI enablement platform |\n| Emotions | 9 | Excited by AI in enablement |\n| Scenarios | 7 | Enablement scenarios |', TRUE),

  ('sales-enable-lead-orchestrator', 'Sales Enablement Lead - Strategic Enablement Architect', E'## Sales Enablement Lead (Orchestrator)\n\n### Professional Context\nStrategic enablement leader who orchestrates sales effectiveness programs using AI-enabled content and training platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 88%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs enablement AI strategy, coordinates programs, builds sales excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic enablement role |\n| Pain | 4 | AI handles complexity |\n| Actions | 8 | Shapes enablement direction |\n| Needs | 9 | Integrated enablement platform |\n| Emotions | 9 | Energized by transformation |\n| Scenarios | 8 | Strategic enablement scenarios |', TRUE),

  ('sales-enable-lead-learner', 'Sales Enablement Lead - Capability Developer', E'## Sales Enablement Lead (Learner)\n\n### Professional Context\nDevelopment-focused enablement lead building AI capabilities for sales effectiveness. Explores AI while developing program expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 45%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for enablement, validates effectiveness, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Enablement leadership |\n| Pain | 7 | Growing enablement demands |\n| Actions | 6 | Measured approach |\n| Needs | 7 | Validated enablement AI |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 6 | Capability development scenarios |', TRUE),

  ('sales-enable-lead-skeptic', 'Sales Enablement Lead - Field Learning Focus', E'## Sales Enablement Lead (Skeptic)\n\n### Professional Context\nField learning advocate who questions AI in enablement contexts. Emphasizes experiential learning and field coaching over AI content.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 27%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes field learning, questions AI content, values coaching\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Enablement role |\n| Pain | 8 | Concerned AI replaces coaching |\n| Actions | 5 | Field learning approach |\n| Needs | 7 | AI that enhances coaching |\n| Emotions | 4 | Skeptical of AI enablement |\n| Scenarios | 7 | Field learning scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 18: Sales Analytics Manager
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('sales-analytics-mgr-automator', 'Sales Analytics Manager - Predictive Analytics Expert', E'## Sales Analytics Manager (Automator)\n\n### Professional Context\nAnalytics expert who leverages AI for predictive modeling, sales forecasting, and performance analytics.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 85%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for predictive models, automates forecasting, optimizes analytics\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Analytics leadership |\n| Pain | 4 | AI enhances analytics |\n| Actions | 7 | Drives analytics strategy |\n| Needs | 8 | Advanced AI analytics |\n| Emotions | 9 | Excited by AI analytics |\n| Scenarios | 7 | Analytics scenarios |', TRUE),

  ('sales-analytics-mgr-orchestrator', 'Sales Analytics Manager - Strategic Insights Architect', E'## Sales Analytics Manager (Orchestrator)\n\n### Professional Context\nStrategic analytics leader who orchestrates sales intelligence using AI-enabled BI and predictive platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 91%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Designs analytics AI strategy, coordinates insights, builds analytics excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Strategic analytics role |\n| Pain | 3 | AI is core capability |\n| Actions | 8 | Shapes insights direction |\n| Needs | 9 | Integrated analytics platform |\n| Emotions | 9 | Energized by AI analytics |\n| Scenarios | 8 | Strategic insights scenarios |', TRUE),

  ('sales-analytics-mgr-learner', 'Sales Analytics Manager - Model Builder', E'## Sales Analytics Manager (Learner)\n\n### Professional Context\nDevelopment-focused analytics manager building advanced AI capabilities for sales intelligence. Explores new models while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 52%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI models, validates predictions, builds capabilities\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Analytics management |\n| Pain | 6 | Growing data complexity |\n| Actions | 7 | Measured approach |\n| Needs | 8 | Validated AI models |\n| Emotions | 7 | Enthusiastic about AI |\n| Scenarios | 6 | Model development scenarios |', TRUE),

  ('sales-analytics-mgr-skeptic', 'Sales Analytics Manager - Model Validation Focus', E'## Sales Analytics Manager (Skeptic)\n\n### Professional Context\nValidation-focused analytics manager who questions AI model accuracy and emphasizes rigorous testing and explainability.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 32%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions model accuracy, requires validation, emphasizes explainability\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 6 | Analytics role |\n| Pain | 8 | Concerned about model bias |\n| Actions | 5 | Validation-first approach |\n| Needs | 9 | Validated, explainable AI |\n| Emotions | 4 | Skeptical of black box models |\n| Scenarios | 8 | Model validation scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 19: Account Executive
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('acct-exec-automator', 'Account Executive - Digital Sales Expert', E'## Account Executive (Automator)\n\n### Professional Context\nTech-savvy account executive who leverages AI for account research, proposal development, and sales cycle optimization.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 76%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for account research, automates proposals, optimizes sales cycles\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Account sales |\n| Pain | 6 | AI reduces research burden |\n| Actions | 6 | Drives account sales |\n| Needs | 7 | AI sales tools |\n| Emotions | 8 | Satisfied with AI support |\n| Scenarios | 6 | Account sales scenarios |', TRUE),

  ('acct-exec-orchestrator', 'Account Executive - Strategic Account Expert', E'## Account Executive (Orchestrator)\n\n### Professional Context\nStrategic account executive who coordinates complex sales cycles using AI-enabled CRM and proposal platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 84%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates account strategy, designs AI-enabled processes, builds sales excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Senior account sales |\n| Pain | 5 | Complex sales coordination |\n| Actions | 7 | Strategic sales decisions |\n| Needs | 7 | Integrated sales platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 7 | Strategic sales scenarios |', TRUE),

  ('acct-exec-learner', 'Account Executive - Sales Skills Developer', E'## Account Executive (Learner)\n\n### Professional Context\nDevelopment-focused account executive building AI capabilities for account sales. Explores AI tools while developing sales expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 42%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for sales, validates results, builds skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Account sales |\n| Pain | 7 | Growing sales demands |\n| Actions | 6 | Measured approach |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('acct-exec-skeptic', 'Account Executive - Customer Relationship Focus', E'## Account Executive (Skeptic)\n\n### Professional Context\nRelationship-focused account executive who prioritizes authentic customer connections over AI-driven efficiency.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 22%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Emphasizes customer relationships, questions AI metrics, values authenticity\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 5 | Account role |\n| Pain | 8 | Concerned AI reduces authenticity |\n| Actions | 4 | Relationship-first approach |\n| Needs | 6 | AI that supports relationships |\n| Emotions | 3 | Skeptical of sales AI |\n| Scenarios | 6 | Customer relationship scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- Role 20: Trade Operations Analyst
INSERT INTO personas (persona_key, display_name, description, is_active)
VALUES
  ('trade-ops-analyst-automator', 'Trade Operations Analyst - Supply Chain Analytics Expert', E'## Trade Operations Analyst (Automator)\n\n### Professional Context\nAnalytics-focused trade analyst who leverages AI for inventory analysis, distribution tracking, and supply chain reporting.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 77%\n- **Archetype:** AUTOMATOR\n- **Key Behaviors:** Uses AI for inventory analysis, automates tracking, optimizes reporting\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Trade operations |\n| Pain | 5 | AI reduces analysis burden |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | AI supply chain tools |\n| Emotions | 8 | Satisfied with AI accuracy |\n| Scenarios | 5 | Trade analysis scenarios |', TRUE),

  ('trade-ops-analyst-orchestrator', 'Trade Operations Analyst - Cross-Functional Coordinator', E'## Trade Operations Analyst (Orchestrator)\n\n### Professional Context\nCross-functional trade analyst who coordinates supply chain analytics using AI-enabled inventory and distribution platforms.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 83%\n- **Archetype:** ORCHESTRATOR\n- **Key Behaviors:** Coordinates cross-functional analytics, designs AI-enabled processes, builds operational excellence\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Senior analyst |\n| Pain | 5 | Cross-functional coordination |\n| Actions | 6 | Strategic analysis decisions |\n| Needs | 7 | Integrated analytics platform |\n| Emotions | 8 | Enthusiastic about AI |\n| Scenarios | 6 | Cross-functional scenarios |', TRUE),

  ('trade-ops-analyst-learner', 'Trade Operations Analyst - Analytics Skills Developer', E'## Trade Operations Analyst (Learner)\n\n### Professional Context\nDevelopment-focused trade analyst building AI capabilities for supply chain analysis. Explores AI tools while developing expertise.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 41%\n- **Archetype:** LEARNER\n- **Key Behaviors:** Explores AI for analysis, validates outputs, builds skills\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 7 | Growing analysis demands |\n| Actions | 5 | Individual contributor |\n| Needs | 6 | Easy-to-use AI tools |\n| Emotions | 6 | Hopeful about AI support |\n| Scenarios | 5 | Learning scenarios |', TRUE),

  ('trade-ops-analyst-skeptic', 'Trade Operations Analyst - Data Quality Focus', E'## Trade Operations Analyst (Skeptic)\n\n### Professional Context\nData quality-focused trade analyst who questions AI outputs and emphasizes data validation and accuracy.\n\n### AI Maturity Profile\n- **AI Readiness Score:** 23%\n- **Archetype:** SKEPTIC\n- **Key Behaviors:** Questions AI outputs, requires data validation, emphasizes accuracy\n\n### VPANES Scores\n| Dimension | Score | Rationale |\n|-----------|-------|----------|\n| Visibility | 4 | Analyst role |\n| Pain | 8 | Concerned about AI errors |\n| Actions | 4 | Conservative approach |\n| Needs | 7 | Validated, accurate AI |\n| Emotions | 3 | Skeptical of AI analysis |\n| Scenarios | 6 | Data quality scenarios |', TRUE)
ON CONFLICT (persona_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- =====================================================
-- VERIFICATION QUERY
-- =====================================================
-- Run this after migration to verify:
-- SELECT persona_key, display_name, is_active
-- FROM personas
-- WHERE persona_key LIKE 'nat-sales-%'
--    OR persona_key LIKE 'regional-sales-%'
--    OR persona_key LIKE 'district-sales-%'
--    OR persona_key LIKE 'hospital-sales-%'
--    OR persona_key LIKE 'sales-training-%'
--    OR persona_key LIKE 'sales-rep-%'
--    OR persona_key LIKE 'specialty-sales-%'
--    OR persona_key LIKE 'key-account-%'
--    OR persona_key LIKE 'strategic-account-%'
--    OR persona_key LIKE 'idn-gpo-%'
--    OR persona_key LIKE 'inst-acct-%'
--    OR persona_key LIKE 'bd-mgr-%'
--    OR persona_key LIKE 'sr-bd-%'
--    OR persona_key LIKE 'trade-dir-%'
--    OR persona_key LIKE 'dist-mgr-%'
--    OR persona_key LIKE 'sales-enable-%'
--    OR persona_key LIKE 'sales-analytics-%'
--    OR persona_key LIKE 'acct-exec-%'
--    OR persona_key LIKE 'trade-ops-%'
-- ORDER BY persona_key;

-- Expected: 80 rows (20 roles × 4 archetypes)
