#!/usr/bin/env python3
"""
VITAL Path - Pydantic Model Generator

Generates Pydantic models from Protocol Package JSON Schemas.
Uses datamodel-code-generator under the hood.

Usage:
    python scripts/codegen/generate_pydantic.py

Requirements:
    pip install datamodel-code-generator
"""

import subprocess
import sys
from pathlib import Path
from typing import Optional

# ============================================================================
# Configuration
# ============================================================================

# Paths (relative to monorepo root)
SCRIPT_DIR = Path(__file__).parent
ROOT_DIR = SCRIPT_DIR.parent.parent
PROTOCOL_JSON_SCHEMAS = ROOT_DIR / "packages" / "protocol" / "src" / "json-schemas"
OUTPUT_DIR = ROOT_DIR / "services" / "ai-engine" / "src" / "api" / "schemas" / "_generated"

# Schema files to process
SCHEMAS = [
    "workflow",
    "workflow_create",
    "node",
    "edge",
    "expert_request",
    "expert_sync_response",
    "expert_async_response",
    "conversation",
    "message",
    "job",
    "job_status_response",
    "job_result_response",
]

# ============================================================================
# Generator
# ============================================================================

def check_dependencies():
    """Check if required dependencies are installed."""
    try:
        import datamodel_code_generator
        return True
    except ImportError:
        print("❌ datamodel-code-generator is not installed")
        print("   Run: pip install datamodel-code-generator")
        return False


def generate_pydantic(schema_name: str) -> bool:
    """Generate Pydantic model from JSON Schema."""
    input_file = PROTOCOL_JSON_SCHEMAS / f"{schema_name}.json"
    output_file = OUTPUT_DIR / f"{schema_name}.py"
    
    if not input_file.exists():
        print(f"  ⚠️  Skipping {schema_name}: JSON Schema not found at {input_file}")
        return True  # Not a failure, just skip
    
    cmd = [
        sys.executable, "-m", "datamodel_code_generator",
        "--input", str(input_file),
        "--output", str(output_file),
        "--input-file-type", "jsonschema",
        "--output-model-type", "pydantic_v2.BaseModel",
        "--use-standard-collections",
        "--use-union-operator",
        "--field-constraints",
        "--strict-nullable",
        "--collapse-root-models",
        "--use-annotated",
        "--use-default-kwarg",
        "--target-python-version", "3.11",
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"  ❌ Failed to generate {schema_name}:")
        print(f"     {result.stderr}")
        return False
    
    print(f"  ✅ {schema_name}.py")
    return True


def generate_init_file():
    """Generate __init__.py with all exports."""
    init_content = '''"""
VITAL Protocol - Auto-generated Pydantic Models

⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️

These models are generated from the Protocol Package JSON Schemas.
To regenerate, run: make sync-types

Generated by: scripts/codegen/generate_pydantic.py
"""

# Re-export all generated models
'''
    
    for schema in SCHEMAS:
        module_name = schema.replace("-", "_")
        output_file = OUTPUT_DIR / f"{module_name}.py"
        if output_file.exists():
            init_content += f"from .{module_name} import *\n"
    
    init_file = OUTPUT_DIR / "__init__.py"
    init_file.write_text(init_content)
    print(f"  ✅ __init__.py")


def generate_extensions_stub():
    """Generate extensions.py stub for custom methods."""
    extensions_file = OUTPUT_DIR.parent / "extensions.py"
    
    if extensions_file.exists():
        print(f"  ℹ️  extensions.py already exists, skipping")
        return
    
    content = '''"""
VITAL Protocol - Pydantic Model Extensions

Add custom methods and behavior to generated models here.
Use inheritance to extend generated models without modifying them.

Example:
    from ._generated.workflow import Workflow as GeneratedWorkflow
    
    class Workflow(GeneratedWorkflow):
        def get_entry_node(self):
            return next(n for n in self.nodes if n.id == self.entry_node_id)
"""

# Add your model extensions here
'''
    
    extensions_file.write_text(content)
    print(f"  ✅ extensions.py (stub created)")


def main():
    """Main entry point."""
    print("🐍 Generating Pydantic models from JSON Schemas...")
    print(f"   Source: {PROTOCOL_JSON_SCHEMAS}")
    print(f"   Output: {OUTPUT_DIR}")
    print()
    
    # Check dependencies
    if not check_dependencies():
        sys.exit(1)
    
    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Check if JSON schemas exist
    if not PROTOCOL_JSON_SCHEMAS.exists():
        print(f"❌ JSON Schemas directory not found: {PROTOCOL_JSON_SCHEMAS}")
        print("   Run 'pnpm run generate:json-schemas' in packages/protocol first")
        sys.exit(1)
    
    # Generate models
    success_count = 0
    error_count = 0
    
    for schema in SCHEMAS:
        if generate_pydantic(schema):
            success_count += 1
        else:
            error_count += 1
    
    # Generate __init__.py
    print()
    print("📄 Generating index files...")
    generate_init_file()
    generate_extensions_stub()
    
    # Summary
    print()
    print("📋 Summary:")
    print(f"   ✅ Generated: {success_count}")
    print(f"   ❌ Failed: {error_count}")
    
    if error_count > 0:
        sys.exit(1)
    
    print()
    print("✨ Pydantic model generation complete!")


if __name__ == "__main__":
    main()


